// メニュー（じゅもん・どうぐ・さくせん・なまえ）を撮影: node tools/e2e-menu.mjs <出力dir>
import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const out = process.argv[2] || '/tmp/e2e-m'; fs.mkdirSync(out, { recursive: true });
const srv = http.createServer((q, s) => { const f = path.join(root, q.url.split('?')[0].replace(/\/$/, '/index.html')); fs.readFile(f, (e, d) => { if (e) { s.writeHead(404); s.end(); return; } s.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : 'text/html' }); s.end(d); }); }).listen(0);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto(`http://localhost:${srv.address().port}/index.html`);
await p.evaluate(() => localStorage.setItem('me-settings', JSON.stringify({ textSpeed: 'fast', sound: false, reduceMotion: true })));
await p.reload(); const wait = (ms) => p.waitForTimeout(ms);
const shot = (n) => p.screenshot({ path: path.join(out, n + '.png') });
const msgs = async () => { for (let i = 0; i < 60; i++) { if (await p.$('.choices')) return; const m = await p.$('.msgbox'); if (!m) return; await m.click(); await wait(60); } };
await p.locator('button', { hasText: 'はじめから' }).click(); await wait(200);
await p.locator('button', { hasText: 'けってい' }).click(); await wait(300);
await msgs();
await shot('01-name-ask');
await p.locator('.choices .item', { hasText: 'つける' }).click(); await wait(300);
await p.fill('input.name', 'ポン太'); await shot('02-name-input');
await p.locator('.panel-foot button', { hasText: 'けってい' }).click(); await wait(300);
await p.fill('input.name', 'コゲ'); await p.locator('.panel-foot button', { hasText: 'けってい' }).click(); await wait(300);
await msgs(); await p.waitForSelector('.pad-area');
await p.evaluate(() => { const g = window.app.game; g.state.monsters = g.state.monsters.map((m) => ({ ...m, hp: 4 })); });
await p.evaluate(() => window.app.dispatch('menu', true)); await wait(200);
await p.locator('.panel .item', { hasText: 'じゅもん' }).click(); await wait(200);
await shot('03-spells');
await p.locator('.panel').last().locator('button', { hasText: 'いやしのしずく' }).click(); await wait(200);
await shot('04-spell-target');
await p.locator('.choices .item').first().click(); await wait(300);
await shot('05-spell-result');
await msgs(); await p.locator('.panel').last().locator('button', { hasText: 'もどる' }).click(); await wait(200);
await p.locator('.panel .item', { hasText: 'どうぐ' }).click(); await wait(200);
await shot('06-items');
await p.locator('.panel').last().locator('button', { hasText: 'つかう' }).first().click(); await wait(200);
await shot('07-item-target');
await p.locator('.choices .item').nth(1).click(); await wait(300); await msgs();
await p.locator('.panel').last().locator('button', { hasText: 'もどる' }).click(); await wait(200);
await p.locator('.panel .item', { hasText: 'さくせん' }).click(); await wait(200);
await shot('08-tactics');
// 戦闘で 名前の見分け
await p.evaluate(() => { window.app.closeAllPanels(); const g = window.app.game; g.healAll(); g.startExpedition('forest'); window.app.show(new (window.app.screen.constructor)(window.app)); });
await p.evaluate(async () => { const m = await import('./game.js').catch(() => null); });
console.log(errors.join('\n') || 'no errors'); await b.close(); srv.close();
