// ステージ1：家の食卓（25 イベント）。登場人物・台詞はすべてオリジナル。
const done = id => ({ eventDone: id });
const notDone = id => ({ eventNotDone: id });

export default {
  id: 'S1', title: 'ちゃぶ台の夜', subtitle: '家の食卓', theme: '家',
  intro: '寒い冬の夜。家族そろって鍋をかこむ……はずが、みんな少しずつ不満そう。',
  timeLimitMs: 180000,
  world: { width: 2000, height: 1000, minZoom: 0.75, maxZoom: 3, bg: '#f6c98a', spawnCamera: { x: 1000, y: 640, zoom: 1.7 } },
  bgm: { tempo: 96, key: 0, mood: 'major' },
  clearEventId: 'S1-E25', timeoutEventId: 'S1-E24',
  routes: {
    'S1.route.family': '娘のダイエット', 'S1.route.cat': '猫のタマ', 'S1.route.heat': 'ストーブと部屋の温度',
    'S1.route.bug': '迷いこんだ虫', 'S1.route.soup': '鍋の味つけ', 'S1.route.misc': '家族のあれこれ', 'S1.route.end': '鍋のゆくえ',
  },
  scenery: [
    // 壁
    { t: 'rect', x: 0, y: 0, w: 2000, h: 560, fill: '#f6c98a' },
    { t: 'stripes', x: 0, y: 0, w: 2000, h: 470, dir: 'v', n: 40, c1: 'rgba(0,0,0,0)', c2: 'rgba(200,120,40,.07)' },
    { t: 'rect', x: 0, y: 0, w: 2000, h: 36, fill: '#9a6a3a' },
    { t: 'rect', x: 0, y: 470, w: 2000, h: 90, fill: '#e09a52' },
    { t: 'rect', x: 0, y: 548, w: 2000, h: 14, fill: '#8a5a32' },
    { t: 'prop', kind: 'fusuma', x: 1000, y: 548, s: 440, w: 620, n: 4, art: true },
    { t: 'prop', kind: 'wallclock', x: 1430, y: 250, s: 110 },
    { t: 'prop', kind: 'calendar', x: 620, y: 360, s: 150, text: '12月' },
    // 床（畳＋電気カーペット）
    { t: 'rect', x: 0, y: 560, w: 2000, h: 440, fill: '#e9894a' },
    { t: 'stripes', x: 0, y: 560, w: 2000, h: 440, dir: 'v', n: 10, c1: 'rgba(0,0,0,0)', c2: 'rgba(120,40,0,.07)' },
    { t: 'rect', x: 250, y: 680, w: 1500, h: 300, fill: '#c94a46', r: 24 },
    { t: 'rect', x: 270, y: 700, w: 1460, h: 260, fill: 'rgba(0,0,0,0)', stroke: 'rgba(255,220,180,.5)', lw: 5, r: 18 },
    { t: 'stripes', x: 270, y: 700, w: 1460, h: 260, dir: 'h', n: 12, c1: 'rgba(0,0,0,0)', c2: 'rgba(255,255,255,.05)' },
    // 家具・小物（飾り）
    { t: 'prop', kind: 'cabinet', x: 1880, y: 600, s: 260, w: 220, color: '#a8703c' },
    { t: 'prop', kind: 'pot', x: 110, y: 610, s: 150 },
    { t: 'prop', kind: 'cushion', x: 520, y: 880, s: 120, color: '#5a7ac8' },
    { t: 'prop', kind: 'cushion', x: 1460, y: 900, s: 110, color: '#5aa85a' },
    { t: 'emoji', e: '🧸', x: 1180, y: 980, s: 54 },
    { t: 'prop', kind: 'hanglamp', x: 1000, y: 130, s: 110 },
  ],
  actors: {
    father: {
      name: '父', x: 780, y: 645, wander: 0, facing: 'RIGHT',
      look: { hair: 'short', hairColor: '#2a2a2a', shirt: '#4a6a9a', pants: '#3a3a44', acc: ['glasses'], sit: true, h: 330 },
      idle: [
        { text: 'うーん、メガネが湯気でくもって何も見えん……', when: [notDone('S1-E01')] },
        'まだ煮えんのか？ 腹ぺこだぞ',
        { text: 'それにしても、この部屋あつくないか？', when: [done('S1-E17'), notDone('S1-E18'), notDone('S1-E19')] },
        { text: 'ふう、夜風が気持ちいいな', when: [done('S1-E18')] },
        { text: 'カーペットを切ったら、ちょうどいいな', when: [done('S1-E19')] },
      ],
    },
    mother: {
      name: '母', x: 500, y: 875, wander: 0, facing: 'RIGHT',
      look: { hair: 'bob', hairColor: '#5a3424', shirt: '#e8646a', pants: '#6a4a3a', acc: ['apron'], sit: true, h: 330 },
      idle: [
        { text: 'タマちゃんにも何か分けてあげたいわねえ', when: [notDone('S1-E03')] },
        '味つけ、これで足りてるかしら？',
        { text: 'さむいわね……鍋の火、弱すぎるのかしら', when: [done('S1-E03'), notDone('S1-E17')] },
        { text: 'みんなそろったことだし、いっそもっと強火に……？', when: [done('S1-E17'), done('S1-E07')] },
      ],
    },
    daughter: {
      name: '娘', x: 1310, y: 650, wander: 0, facing: 'LEFT',
      look: { hair: 'long', hairColor: '#7a3a1a', shirt: '#f2a8c8', pants: '#555', acc: ['ribbon'], sit: true, h: 320 },
      idle: [
        { text: 'あたしはいらない。ダイエット中だから', when: [notDone('S1-E07')] },
        { text: '……べつに、お腹すいてないし', when: [notDone('S1-E07')] },
        { text: 'みんな、あたしのことばっかり……', when: [{ countAtLeast: { id: 'S1-hotpot-hint', value: 2 } }, notDone('S1-E07')] },
        { text: 'ねえ、もっとグツグツさせようよ！', when: [done('S1-E07')] },
      ],
    },
    child: {
      name: '弟', x: 1460, y: 895, wander: 60, facing: 'LEFT',
      look: { hair: 'spiky', hairColor: '#1e1e1e', shirt: '#3ab0a0', pants: '#2a5ab0', kid: true, sit: true, h: 270 },
      idle: [
        '姉ちゃんってさ、いっつもダイエットって言うよね',
        'タマ〜、あそぼ〜',
        { text: 'あまいスープがいいなあ', when: [notDone('S1-E14')] },
        { text: '虫だ！ つかまえたい！', when: [done('S1-E18'), notDone('S1-E20'), notDone('S1-E22')] },
      ],
    },
    grandpa: {
      name: '祖父', x: 1050, y: 630, wander: 0,
      look: { hair: 'bald', hairColor: '#e8e8e8', shirt: '#8a7a5a', pants: '#4a4a3a', acc: ['beard'], old: true, sit: true, h: 320 },
      idle: [
        'ばあさんの写真、どこにしまったかのう',
        'わしの若いころはのう……',
        { text: '箸さばきなら、まだ負けんぞ', when: [done('S1-E18')] },
      ],
    },
    cat: { name: '猫のタマ', emoji: '🐈‍⬛', size: 120, x: 1680, y: 930, wander: 140, speed: 90, idle: ['にゃー', { text: 'フーッ……（窓の外をにらんでいる）', when: [notDone('S1-E12')] }] },
    straycat: { name: 'となりの猫', emoji: '🐈', size: 80, x: 380, y: 392, wander: 40, speed: 40, idle: ['ニャ〜オ'], layer: -1 },
    bug: { name: '虫', emoji: '🪲', size: 44, x: 330, y: 300, hidden: true, wander: 0, speed: 180, path: null },
  },
  objects: {
    table: { name: 'ちゃぶ台', prop: 'chabudai', propOpts: { w: 860 }, size: 190, w: 860, h: 150, x: 1000, y: 800, capturable: false },
    stove: { name: 'カセットコンロ', prop: 'stove', size: 110, w: 180, h: 40, x: 1000, y: 718, z: 801, capturable: false },
    hotpot: { name: '鍋', emoji: '🍲', size: 150, x: 1000, y: 690, z: 802 },
    knob: { name: 'ストーブのつまみ', emoji: '🔘', size: 30, x: 945, y: 712, z: 803, minZoom: 1.5 },
    tissue: { name: 'ティッシュ', emoji: '🧻', size: 64, x: 740, y: 712, z: 802 },
    soy: { name: '醤油', emoji: '🍶', size: 52, x: 1170, y: 700, z: 802 },
    sauce: { name: 'ソース', emoji: '🫙', size: 50, x: 1240, y: 716, z: 802 },
    sugar: { name: '砂糖', emoji: '🧂', size: 40, x: 830, y: 740, z: 803, minZoom: 1.3 },
    thermos: { name: '魔法瓶', emoji: '🫖', size: 100, x: 200, y: 900 },
    remote: { name: 'テレビのリモコン', emoji: '📱', size: 42, x: 1830, y: 950, minZoom: 1.3, rot: 1.2 },
    tv: { name: 'テレビ', prop: 'tvset', propOpts: { w: 330 }, size: 270, w: 330, h: 270, x: 1560, y: 600, capturable: false },
    trash: { name: 'ごみ箱', emoji: '🗑️', size: 90, x: 1880, y: 780 },
    photo: { name: 'おばあちゃんの写真', emoji: '🖼️', size: 70, x: 1880, y: 342 },
    window: { name: '窓', prop: 'roomwindow', propOpts: { w: 330 }, size: 250, w: 380, h: 290, x: 340, y: 410, layer: -2 },
    carpet: { name: '電気カーペット', sign: { text: 'ON', fill: '#e44', color: '#fff', s: 24 }, w: 80, h: 40, x: 1690, y: 965 },
  },
  reactions: [
    { s: 'hotpot', t: 'daughter', say: 'いらないってば。ダイエット中！', counter: 'S1-hotpot-hint', when: [notDone('S1-E07')], anim: 'react.angry' },
    { s: 'hotpot', t: 'father', say: 'まだ煮えとらんぞ', anim: 'react.shrug' },
    { s: 'knob', t: 'father', say: '火の番は母さんの係だ', anim: 'react.shrug' },
  ],
  exclusiveGroups: [
    { id: 'S1-SOUP-SEASONING', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E13', 'S1-E14', 'S1-E15', 'S1-E16'] },
    { id: 's1-window-or-carpet', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E18', 'S1-E19'] },
    { id: 's1-bug-kill', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E20', 'S1-E22'] },
    { id: 's1-ending', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E24', 'S1-E25'] },
  ],
  events: [
    { id: 'S1-E01', s: 'tissue', t: 'father', cat: 'PROGRESSION', title: '父のメガネがピカピカに', say: 'おお！ よく見える！ ……母さん、髪切った？', anim: 'react.sparkle', route: 'S1.route.misc',
      fx: [{ type: 'SET_FLAG', id: 'father.glassesClear', value: true }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'HAPPY' }],
      after: [{ actor: 'mother', text: 'あら、いまごろ気づいたの？' }] },
    { id: 'S1-E02', s: 'cat', t: 'child', cat: 'FLAVOR', title: '弟がタマを追いかけまわす', say: 'タマ、まてー！', anim: 'react.run', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'child', to: [300, 900], speed: 220 }, { type: 'ACTOR_MOVE', actorId: 'cat', to: [120, 940], speed: 260 }, { type: 'ACTOR_SPEECH', actorId: 'cat', text: 'ニャッ！？', delayMs: 300 }] },
    { id: 'S1-E03', s: 'cat', t: 'mother', cat: 'CHAIN', title: '母がタマにごはんを分ける', say: 'はい、タマちゃん。ささみよ', anim: 'react.happy', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1120, 900], speed: 200, wander: 0 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'cat.fed', value: true }],
      after: [{ actor: 'mother', text: 'それにしても冷えるわね。鍋の火、弱いのかしら……', delay: 3000 }] },
    { id: 'S1-E04', s: 'daughter', t: 'father', cat: 'FLAVOR', title: '父と娘の小さな言いあい', say: 'ちゃんと食べないと大きくなれんぞ！', anim: 'react.angry', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'もう大きいもん！', delayMs: 1500 }] },
    { id: 'S1-E05', s: 'daughter', t: 'mother', cat: 'FLAVOR', title: '母のダイエット講座', say: 'ダイエットはね、食べて動くのが一番なのよ', anim: 'react.think', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: '……ほんとに？', delayMs: 1600 }] },
    { id: 'S1-E06', s: 'daughter', t: 'child', cat: 'FLAVOR', title: '弟の暴露', say: '姉ちゃん、きのうアイス3個食べてたよ！', anim: 'react.laugh', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'ちょっと！ 言わないでよ！', delayMs: 1400 }, { type: 'ACTOR_SET_STATE', actorId: 'daughter', state: 'EMBARRASSED', delayMs: 1400 }] },
    { id: 'S1-E07', s: 'hotpot', t: 'daughter', cat: 'PROGRESSION', title: '娘、鍋の誘惑に負ける', say: '……やっぱり食べる！ 今日だけ！', anim: 'react.eat', route: 'S1.route.family',
      cond: [{ countAtLeast: { id: 'S1-hotpot-hint', value: 3 } }],
      fx: [{ type: 'ACTOR_SET_STATE', actorId: 'daughter', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'daughter.eating', value: true }],
      after: [{ actor: 'father', text: 'よしよし、それでこそ我が家だ' }] },
    { id: 'S1-E08', s: 'photo', t: 'grandpa', cat: 'FLAVOR', title: '祖父、思い出にひたる', say: 'ばあさんの鍋は、もっと甘かったのう……', anim: 'react.sad', route: 'S1.route.misc',
      fx: [{ type: 'ACTOR_SET_STATE', actorId: 'grandpa', state: 'SAD' }, { type: 'ACTOR_SPEECH', actorId: 'child', text: '甘い鍋！？ 食べたい！', delayMs: 2200 }] },
    { id: 'S1-E09', s: 'remote', t: 'cat', cat: 'FLAVOR', title: 'タマ、テレビをつける', say: 'ニャ？', anim: 'react.surprised', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1790, 940], speed: 200 }, { type: 'OBJECT_APPEARANCE', objectId: 'tv', look: { propOpts: { w: 330, on: true, text: '今夜は 冷えこみます' } }, delayMs: 1000 }, { type: 'PLAY_SOUND', soundId: 'tv', delayMs: 1000 }],
      after: [{ actor: 'mother', text: '冷えこむんですって。火、強めようかしら', delay: 3200 }] },
    { id: 'S1-E10', s: 'trash', t: 'cat', cat: 'FLAVOR', title: 'タマ、ごみ箱にすっぽり', say: 'ニャ〜', anim: 'react.happy', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1880, 790], speed: 220 }, { type: 'OBJECT_SET_STATE', objectId: 'trash', state: 'USED', delayMs: 1200 }, { type: 'OBJECT_APPEARANCE', objectId: 'trash', look: { emoji: '🐱' }, delayMs: 1200 }, { type: 'ACTOR_HIDE', actorId: 'cat', delayMs: 1200 }, { type: 'ACTOR_SHOW', actorId: 'cat', delayMs: 7000 }, { type: 'OBJECT_APPEARANCE', objectId: 'trash', look: { emoji: '🗑️' }, delayMs: 7000 }, { type: 'OBJECT_SET_STATE', objectId: 'trash', state: 'VISIBLE', delayMs: 7000 }] },
    { id: 'S1-E11', s: 'tissue', t: 'cat', cat: 'FLAVOR', title: 'ティッシュ大さんじ', say: 'ニャニャニャ！', anim: 'react.spin', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [760, 830], speed: 240 }, { type: 'FX', kind: 'paper', at: 'cat', delayMs: 900 }, { type: 'ACTOR_SPEECH', actorId: 'mother', text: 'ちょっとタマちゃん！ もう……', delayMs: 2200 }] },
    { id: 'S1-E12', s: 'straycat', t: 'cat', cat: 'FLAVOR', title: 'ライバル猫とにらみあい', say: 'フーーッ！！', anim: 'react.angry', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [420, 610], speed: 240 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'ANGRY' }, { type: 'ACTOR_SPEECH', actorId: 'straycat', text: 'シャーッ！', delayMs: 1600 }] },
    { id: 'S1-E13', s: 'thermos', t: 'mother', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', title: '母、スープをお湯でうすめる', say: 'ちょっとしょっぱいわね。お湯を足して……', anim: 'react.think', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'thin' }, { type: 'ACTOR_SPEECH', actorId: 'father', text: '……うすい', delayMs: 2400 }] },
    { id: 'S1-E14', s: 'sugar', t: 'child', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', decoy: true, title: '弟、鍋に砂糖をドバッ', say: 'あまくしちゃえ〜！', anim: 'react.laugh', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'sweet' }, { type: 'ACTOR_MOVE', actorId: 'child', to: [880, 860], speed: 200 }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'うわっ、あまっ！', delayMs: 2600 }, { type: 'ACTOR_SPEECH', actorId: 'grandpa', text: '……ばあさんの味じゃ', delayMs: 3800 }] },
    { id: 'S1-E15', s: 'soy', t: 'father', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', title: '父、醤油でキリッと仕上げる', say: 'ここはひとつ、醤油をひとたらし……うん、うまい！', anim: 'react.happy', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'good' }, { type: 'ACTOR_SPEECH', actorId: 'mother', text: 'あら、本当においしい', delayMs: 2600 }] },
    { id: 'S1-E16', s: 'sauce', t: 'father', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', decoy: true, title: '父、ソースで鍋を台なしに', say: '隠し味にソースだ！ ……ん？', anim: 'react.surprised', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'weird' }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'うぇ〜、なにこれ', delayMs: 2400 }] },
    { id: 'S1-E17', s: 'knob', t: 'mother', cat: 'PROGRESSION', requires: ['S1-E03'], title: '母、火を強める', say: '寒いし、ちょっと強火にしましょ', anim: 'react.think', route: 'S1.route.heat', focus: true,
      fx: [{ type: 'SET_FLAG', id: 'room.hot', value: true }, { type: 'OBJECT_APPEARANCE', objectId: 'knob', look: { size: 36 } }, { type: 'FX', kind: 'steam', at: 'hotpot', delayMs: 400 }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'BUSY', delayMs: 2500 }],
      after: [{ actor: 'father', text: 'あ、あつい……！ 窓か、カーペットか……', delay: 3400 }] },
    { id: 'S1-E18', s: 'window', t: 'father', cat: 'BRANCH', requires: ['S1-E17'], title: '父、窓を開ける', say: 'あつい！ 窓を開けるぞ！', anim: 'react.happy', route: 'S1.route.heat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'father', to: [420, 640], speed: 200 }, { type: 'OBJECT_APPEARANCE', objectId: 'window', look: { propOpts: { w: 330, open: true } }, delayMs: 1600 }, { type: 'SET_FLAG', id: 'window.open', value: true, delayMs: 1600 }, { type: 'ACTOR_SHOW', actorId: 'bug', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'bug', pathId: 'bugFly', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'father', to: [780, 645], speed: 160, delayMs: 3200 }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'IDLE', delayMs: 3200 }],
      after: [{ actor: 'child', text: 'あっ！ 虫が入ってきた！', delay: 3600 }] },
    { id: 'S1-E19', s: 'carpet', t: 'father', cat: 'BRANCH', requires: ['S1-E17'], title: '父、電気カーペットを切る', say: '下からもあっためてたのか！ 切っとこう', anim: 'react.think', route: 'S1.route.heat',
      fx: [{ type: 'OBJECT_APPEARANCE', objectId: 'carpet', look: { sign: { text: 'OFF', fill: '#555', color: '#ccc', s: 22 } }, delayMs: 1000 }, { type: 'SET_FLAG', id: 'carpet.off', value: true }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'HAPPY', delayMs: 1200 }] },
    { id: 'S1-E20', s: 'bug', t: 'father', cat: 'CHAIN', group: 's1-bug-kill', requires: ['S1-E18'], title: '父、新聞で虫退治', say: 'えいっ！ 新聞紙の一撃！', anim: 'react.hit', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_HIDE', actorId: 'bug', delayMs: 700 }, { type: 'ACTOR_SPEECH', actorId: 'child', text: 'あー！ つかまえたかったのに', delayMs: 2000 }] },
    { id: 'S1-E21', s: 'bug', t: 'child', cat: 'FLAVOR', requires: ['S1-E18'], blocksIfCompleted: ['S1-E20', 'S1-E22'], title: '弟、虫を追いかける', say: 'まてまて〜！', anim: 'react.run', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'child', to: [1650, 700], speed: 240 }, { type: 'ACTOR_MOVE', actorId: 'child', to: [1460, 895], speed: 200, delayMs: 2600 }] },
    { id: 'S1-E22', s: 'bug', t: 'grandpa', cat: 'CHAIN', group: 's1-bug-kill', requires: ['S1-E18'], title: '祖父、箸で虫をつまむ', say: 'ほいっ。……まだまだ現役じゃ', anim: 'react.sparkle', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_HIDE', actorId: 'bug', delayMs: 800 }, { type: 'ACTOR_SET_STATE', actorId: 'grandpa', state: 'HAPPY' }, { type: 'ACTOR_SPEECH', actorId: 'child', text: 'じいちゃん、すげー！', delayMs: 2000 }] },
    { id: 'S1-E23', s: 'bug', t: 'cat', cat: 'FLAVOR', requires: ['S1-E18'], blocksIfCompleted: ['S1-E20', 'S1-E22'], title: 'タマ、虫とたわむれる', say: 'ニャッ、ニャッ！', anim: 'react.surprised', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1300, 920], speed: 260 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'HAPPY' }] },
    { id: 'S1-E24', s: 'knob', t: 'mother', cat: 'TIMEOUT', title: 'ガス切れで鍋がひえひえ', say: 'あら……？ ガスが切れちゃったわ', anim: 'react.timeout', route: 'S1.route.end',
      fx: [{ type: 'FX', kind: 'smoke', at: 'hotpot' }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'つめたい鍋だ……', delayMs: 1800 }] },
    { id: 'S1-E25', s: 'knob', t: 'mother', cat: 'TERMINAL', title: '鍋、大噴火！', say: 'みんなそろったし、一気に強火で……あらあらあら！？', anim: 'react.terminal', route: 'S1.route.end',
      cond: [done('S1-E17'), done('S1-E07'), { anyEventDone: ['S1-E18', 'S1-E19'] }],
      fx: [{ type: 'FX', kind: 'eruption', at: 'hotpot', delayMs: 600 }, { type: 'PLAY_SOUND', soundId: 'boom', delayMs: 600 }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'うおお！ 天井まで湯気が！', delayMs: 1600 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'あははは！ でもおいしそう！', delayMs: 2400 }, { type: 'ACTOR_SPEECH', actorId: 'grandpa', text: 'これじゃ、これがうちの鍋じゃ', delayMs: 3200 }, { type: 'WAIT', durationMs: 3600 }] },
  ],
  paths: {
    bugFly: { points: [[420, 320], [700, 420], [1000, 360], [1300, 440], [1550, 380], [1200, 300], [760, 300], [420, 320]], speed: 140, loop: true },
  },
};
