// ステージ1：家の食卓（25 イベント）。登場人物・台詞はすべてオリジナル。
const done = id => ({ eventDone: id });
const notDone = id => ({ eventNotDone: id });

export default {
  id: 'S1', title: 'ちゃぶ台の夜', subtitle: '家の食卓', theme: '家',
  intro: '寒い冬の夜。家族そろって鍋をかこむ……はずが、みんな少しずつ不満そう。',
  timeLimitMs: 180000,
  world: { width: 2400, height: 1400, minZoom: 0.75, maxZoom: 4, bg: '#e9d9b6', spawnCamera: { x: 1150, y: 860, zoom: 1 } },
  bgm: { tempo: 96, key: 0, mood: 'major' },
  clearEventId: 'S1-E25', timeoutEventId: 'S1-E24',
  routes: {
    'S1.route.family': '娘のダイエット', 'S1.route.cat': '猫のタマ', 'S1.route.heat': 'ストーブと部屋の温度',
    'S1.route.bug': '迷いこんだ虫', 'S1.route.soup': '鍋の味つけ', 'S1.route.misc': '家族のあれこれ', 'S1.route.end': '鍋のゆくえ',
  },
  scenery: [
    // 壁・天井
    { t: 'rect', x: 0, y: 0, w: 2400, h: 700, fill: '#efe2c4' },
    { t: 'rect', x: 0, y: 0, w: 2400, h: 60, fill: '#8a6a44' },
    { t: 'rect', x: 0, y: 660, w: 2400, h: 40, fill: '#8a6a44' },
    { t: 'rect', x: 600, y: 60, w: 18, h: 600, fill: '#a58457' }, { t: 'rect', x: 1500, y: 60, w: 18, h: 600, fill: '#a58457' },
    // ふすま
    { t: 'rect', x: 640, y: 120, w: 380, h: 540, fill: '#f6efdc', stroke: '#b89a6a', lw: 6 },
    { t: 'rect', x: 1030, y: 120, w: 380, h: 540, fill: '#f6efdc', stroke: '#b89a6a', lw: 6 },
    { t: 'ellipse', x: 990, y: 400, rx: 10, ry: 22, fill: '#b89a6a' }, { t: 'ellipse', x: 1060, y: 400, rx: 10, ry: 22, fill: '#b89a6a' },
    { t: 'emoji', e: '🌸', x: 780, y: 330, s: 90 }, { t: 'emoji', e: '🏔️', x: 1220, y: 320, s: 110 },
    // 棚と時計
    { t: 'rect', x: 80, y: 480, w: 440, h: 22, fill: '#8a6a44' },
    { t: 'emoji', e: '🕰️', x: 380, y: 200, s: 90 }, { t: 'emoji', e: '📚', x: 140, y: 440, s: 60 }, { t: 'emoji', e: '🏺', x: 460, y: 435, s: 60 },
    { t: 'rect', x: 1560, y: 150, w: 120, h: 160, fill: '#fff', stroke: '#c33', lw: 3 },
    { t: 'text', text: '12月', x: 1620, y: 195, s: 30, fill: '#c33', bold: true },
    { t: 'text', text: '大掃除', x: 1620, y: 260, s: 24, fill: '#333' },
    // 台所
    { t: 'rect', x: 2080, y: 560, w: 320, h: 320, fill: '#c9b48c', stroke: '#8a6a44', lw: 6 },
    { t: 'rect', x: 2080, y: 540, w: 320, h: 30, fill: '#ddd' },
    { t: 'emoji', e: '🍳', x: 2330, y: 520, s: 50 }, { t: 'emoji', e: '🥢', x: 2370, y: 470, s: 36 },
    // 畳
    { t: 'rect', x: 0, y: 700, w: 2400, h: 700, fill: '#c8c27a' },
    { t: 'stripes', x: 0, y: 700, w: 2400, h: 700, dir: 'v', n: 8, c1: 'rgba(0,0,0,0)', c2: 'rgba(90,80,20,.18)' },
    // 電気カーペット
    { t: 'rect', x: 640, y: 1040, w: 1300, h: 300, fill: '#b5584a', r: 10 },
    { t: 'stripes', x: 640, y: 1040, w: 1300, h: 300, dir: 'h', n: 10, c1: 'rgba(0,0,0,0)', c2: 'rgba(255,255,255,.08)' },
    // ちゃぶ台
    { t: 'ellipse', x: 1250, y: 1000, rx: 430, ry: 120, fill: '#6b4426' },
    { t: 'ellipse', x: 1250, y: 975, rx: 430, ry: 115, fill: '#8a5a33' },
    { t: 'emoji', e: '🍚', x: 980, y: 1000, s: 40 }, { t: 'emoji', e: '🍚', x: 1500, y: 1010, s: 40 }, { t: 'emoji', e: '🍵', x: 1530, y: 950, s: 36 },
    { t: 'emoji', e: '🥢', x: 1080, y: 1040, s: 34 },
    // 座布団・小物
    { t: 'emoji', e: '🪴', x: 1990, y: 760, s: 90 }, { t: 'emoji', e: '🧸', x: 120, y: 1300, s: 60 }, { t: 'emoji', e: '👘', x: 2250, y: 1200, s: 80 },
    { t: 'emoji', e: '🪭', x: 600, y: 1350, s: 40 },
  ],
  actors: {
    father: {
      name: '父', x: 1560, y: 1000, wander: 0,
      look: { hair: 'short', hairColor: '#333', shirt: '#5b6f8a', pants: '#3a3a3a', acc: ['glasses'], sit: true, h: 165 },
      idle: [
        { text: 'うーん、メガネが湯気でくもって何も見えん……', when: [notDone('S1-E01')] },
        'まだ煮えんのか？ 腹ぺこだぞ',
        { text: 'それにしても、この部屋あつくないか？', when: [done('S1-E17'), notDone('S1-E18'), notDone('S1-E19')] },
        { text: 'ふう、夜風が気持ちいいな', when: [done('S1-E18')] },
        { text: 'カーペットを切ったら、ちょうどいいな', when: [done('S1-E19')] },
      ],
    },
    mother: {
      name: '母', x: 1150, y: 880, wander: 0,
      look: { hair: 'bun', hairColor: '#4a2e1e', shirt: '#d97a6a', pants: '#6a4a3a', acc: ['apron'], sit: true, h: 160 },
      idle: [
        { text: 'タマちゃんにも何か分けてあげたいわねえ', when: [notDone('S1-E03')] },
        '味つけ、これで足りてるかしら？',
        { text: 'さむいわね……鍋の火、弱すぎるのかしら', when: [done('S1-E03'), notDone('S1-E17')] },
        { text: 'みんなそろったことだし、いっそもっと強火に……？', when: [done('S1-E17'), done('S1-E07')] },
      ],
    },
    daughter: {
      name: '娘', x: 860, y: 1010, wander: 0,
      look: { hair: 'long', hairColor: '#6a3a1a', shirt: '#e7a5c8', pants: '#555', acc: ['ribbon'], sit: true, h: 160 },
      idle: [
        { text: 'あたしはいらない。ダイエット中だから', when: [notDone('S1-E07')] },
        { text: '……べつに、お腹すいてないし', when: [notDone('S1-E07')] },
        { text: 'みんな、あたしのことばっかり……', when: [{ countAtLeast: { id: 'S1-hotpot-hint', value: 2 } }, notDone('S1-E07')] },
        { text: 'ねえ、もっとグツグツさせようよ！', when: [done('S1-E07')] },
      ],
    },
    child: {
      name: '弟', x: 1080, y: 1210, wander: 70,
      look: { hair: 'spiky', hairColor: '#222', shirt: '#f2c14e', pants: '#3a6ab0', kid: true, h: 115 },
      idle: [
        '姉ちゃんってさ、いっつもダイエットって言うよね',
        'タマ〜、あそぼ〜',
        { text: 'あまいスープがいいなあ', when: [notDone('S1-E14')] },
        { text: '虫だ！ つかまえたい！', when: [done('S1-E18'), notDone('S1-E20'), notDone('S1-E22')] },
      ],
    },
    grandpa: {
      name: '祖父', x: 1820, y: 1180, wander: 30,
      look: { hair: 'bald', hairColor: '#ddd', shirt: '#7a8a6a', pants: '#4a4a3a', acc: ['beard'], old: true, h: 150 },
      idle: [
        'ばあさんの写真、どこにしまったかのう',
        'わしの若いころはのう……',
        { text: '箸さばきなら、まだ負けんぞ', when: [done('S1-E18')] },
      ],
    },
    cat: { name: '猫のタマ', emoji: '🐈', size: 72, x: 560, y: 1230, wander: 160, speed: 70, idle: ['にゃー', { text: 'フーッ……（窓の外をにらんでいる）', when: [notDone('S1-E12')] }] },
    straycat: { name: 'となりの猫', emoji: '🐈‍⬛', size: 56, x: 1900, y: 450, wander: 50, speed: 40, idle: ['ニャ〜オ'], layer: -1 },
    bug: { name: '虫', emoji: '🪲', size: 34, x: 1880, y: 420, hidden: true, wander: 0, speed: 160, path: null },
  },
  objects: {
    tissue: { name: 'ティッシュ', emoji: '🧻', size: 40, x: 1420, y: 940 },
    remote: { name: 'テレビのリモコン', emoji: '📱', size: 30, x: 470, y: 1080, minZoom: 1.2, rot: 1.2 },
    tv: { name: 'テレビ', sign: { text: '', fill: '#222', color: '#fff', s: 26 }, w: 260, h: 180, x: 300, y: 640, capturable: false },
    trash: { name: 'ごみ箱', emoji: '🗑️', size: 56, x: 340, y: 1180 },
    hotpot: { name: '鍋', emoji: '🍲', size: 84, x: 1250, y: 930 },
    photo: { name: 'おばあちゃんの写真', emoji: '🖼️', size: 52, x: 270, y: 445 },
    thermos: { name: '魔法瓶', emoji: '🫖', size: 48, x: 2150, y: 525 },
    sugar: { name: '砂糖', emoji: '🧂', size: 34, x: 2240, y: 530, minZoom: 1.1 },
    soy: { name: '醤油', emoji: '🍶', size: 34, x: 1010, y: 935 },
    sauce: { name: 'ソース', emoji: '🫙', size: 34, x: 1600, y: 930 },
    knob: { name: 'ストーブのつまみ', emoji: '🔥', size: 26, x: 1250, y: 985, minZoom: 1.3 },
    window: { name: '窓', sign: { text: '', fill: '#a9d4f5', color: '#fff' }, w: 300, h: 260, x: 1880, y: 530, layer: -2 },
    carpet: { name: '電気カーペット', sign: { text: 'ON', fill: '#e44', color: '#fff', s: 22 }, w: 70, h: 36, x: 1880, y: 1310 },
  },
  reactions: [
    { s: 'hotpot', t: 'daughter', say: 'いらないってば。ダイエット中！', counter: 'S1-hotpot-hint', when: [notDone('S1-E07')], anim: 'react.angry' },
    { s: 'hotpot', t: 'father', say: 'まだ煮えとらんぞ', anim: 'react.shrug' },
    { s: 'knob', t: 'father', say: '火の番は母さんの係だ', anim: 'react.shrug' },
  ],
  exclusiveGroups: [
    { id: 'S1-SOUP-SEASONING', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E13', 'S1-E14', 'S1-E15', 'S1-E16'] },
    { id: 's1-window-or-carpet', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E18', 'S1-E19'] },
    { id: 's1-bug-kill', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E20', 'S1-E22'] },
    { id: 's1-ending', policy: 'FIRST_TRIGGER_WINS', eventIds: ['S1-E24', 'S1-E25'] },
  ],
  events: [
    { id: 'S1-E01', s: 'tissue', t: 'father', cat: 'PROGRESSION', title: '父のメガネがピカピカに', say: 'おお！ よく見える！ ……母さん、髪切った？', anim: 'react.sparkle', route: 'S1.route.misc',
      fx: [{ type: 'SET_FLAG', id: 'father.glassesClear', value: true }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'HAPPY' }],
      after: [{ actor: 'mother', text: 'あら、いまごろ気づいたの？' }] },
    { id: 'S1-E02', s: 'cat', t: 'child', cat: 'FLAVOR', title: '弟がタマを追いかけまわす', say: 'タマ、まてー！', anim: 'react.run', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'child', to: [520, 1260], speed: 220 }, { type: 'ACTOR_MOVE', actorId: 'cat', to: [200, 1250], speed: 260 }, { type: 'ACTOR_SPEECH', actorId: 'cat', text: 'ニャッ！？', delayMs: 300 }] },
    { id: 'S1-E03', s: 'cat', t: 'mother', cat: 'CHAIN', title: '母がタマにごはんを分ける', say: 'はい、タマちゃん。ささみよ', anim: 'react.happy', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1300, 1080], speed: 200, wander: 0 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'cat.fed', value: true }],
      after: [{ actor: 'mother', text: 'それにしても冷えるわね。鍋の火、弱いのかしら……', delay: 3000 }] },
    { id: 'S1-E04', s: 'daughter', t: 'father', cat: 'FLAVOR', title: '父と娘の小さな言いあい', say: 'ちゃんと食べないと大きくなれんぞ！', anim: 'react.angry', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'もう大きいもん！', delayMs: 1500 }] },
    { id: 'S1-E05', s: 'daughter', t: 'mother', cat: 'FLAVOR', title: '母のダイエット講座', say: 'ダイエットはね、食べて動くのが一番なのよ', anim: 'react.think', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: '……ほんとに？', delayMs: 1600 }] },
    { id: 'S1-E06', s: 'daughter', t: 'child', cat: 'FLAVOR', title: '弟の暴露', say: '姉ちゃん、きのうアイス3個食べてたよ！', anim: 'react.laugh', route: 'S1.route.family', blocksIfCompleted: ['S1-E07'],
      fx: [{ type: 'INCREMENT_COUNTER', id: 'S1-hotpot-hint', amount: 1 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'ちょっと！ 言わないでよ！', delayMs: 1400 }, { type: 'ACTOR_SET_STATE', actorId: 'daughter', state: 'EMBARRASSED', delayMs: 1400 }] },
    { id: 'S1-E07', s: 'hotpot', t: 'daughter', cat: 'PROGRESSION', title: '娘、鍋の誘惑に負ける', say: '……やっぱり食べる！ 今日だけ！', anim: 'react.eat', route: 'S1.route.family',
      cond: [{ countAtLeast: { id: 'S1-hotpot-hint', value: 3 } }],
      fx: [{ type: 'ACTOR_SET_STATE', actorId: 'daughter', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'daughter.eating', value: true }],
      after: [{ actor: 'father', text: 'よしよし、それでこそ我が家だ' }] },
    { id: 'S1-E08', s: 'photo', t: 'grandpa', cat: 'FLAVOR', title: '祖父、思い出にひたる', say: 'ばあさんの鍋は、もっと甘かったのう……', anim: 'react.sad', route: 'S1.route.misc',
      fx: [{ type: 'ACTOR_SET_STATE', actorId: 'grandpa', state: 'SAD' }, { type: 'ACTOR_SPEECH', actorId: 'child', text: '甘い鍋！？ 食べたい！', delayMs: 2200 }] },
    { id: 'S1-E09', s: 'remote', t: 'cat', cat: 'FLAVOR', title: 'タマ、テレビをつける', say: 'ニャ？', anim: 'react.surprised', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [470, 1090], speed: 200 }, { type: 'OBJECT_APPEARANCE', objectId: 'tv', look: { sign: { text: '今夜は 冷えこみます', fill: '#2e6b8a', color: '#fff', s: 24 } }, delayMs: 1000 }, { type: 'PLAY_SOUND', soundId: 'tv', delayMs: 1000 }],
      after: [{ actor: 'mother', text: '冷えこむんですって。火、強めようかしら', delay: 3200 }] },
    { id: 'S1-E10', s: 'trash', t: 'cat', cat: 'FLAVOR', title: 'タマ、ごみ箱にすっぽり', say: 'ニャ〜', anim: 'react.happy', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [340, 1170], speed: 220 }, { type: 'OBJECT_SET_STATE', objectId: 'trash', state: 'USED', delayMs: 1200 }, { type: 'OBJECT_APPEARANCE', objectId: 'trash', look: { emoji: '🐈' }, delayMs: 1200 }, { type: 'ACTOR_HIDE', actorId: 'cat', delayMs: 1200 }, { type: 'ACTOR_SHOW', actorId: 'cat', delayMs: 7000 }, { type: 'OBJECT_APPEARANCE', objectId: 'trash', look: { emoji: '🗑️' }, delayMs: 7000 }, { type: 'OBJECT_SET_STATE', objectId: 'trash', state: 'VISIBLE', delayMs: 7000 }] },
    { id: 'S1-E11', s: 'tissue', t: 'cat', cat: 'FLAVOR', title: 'ティッシュ大さんじ', say: 'ニャニャニャ！', anim: 'react.spin', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1420, 1060], speed: 240 }, { type: 'FX', kind: 'paper', at: 'cat', delayMs: 900 }, { type: 'ACTOR_SPEECH', actorId: 'mother', text: 'ちょっとタマちゃん！ もう……', delayMs: 2200 }] },
    { id: 'S1-E12', s: 'straycat', t: 'cat', cat: 'FLAVOR', title: 'ライバル猫とにらみあい', say: 'フーーッ！！', anim: 'react.angry', route: 'S1.route.cat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1880, 760], speed: 240 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'ANGRY' }, { type: 'ACTOR_SPEECH', actorId: 'straycat', text: 'シャーッ！', delayMs: 1600 }] },
    { id: 'S1-E13', s: 'thermos', t: 'mother', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', title: '母、スープをお湯でうすめる', say: 'ちょっとしょっぱいわね。お湯を足して……', anim: 'react.think', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'thin' }, { type: 'ACTOR_SPEECH', actorId: 'father', text: '……うすい', delayMs: 2400 }] },
    { id: 'S1-E14', s: 'sugar', t: 'child', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', decoy: true, title: '弟、鍋に砂糖をドバッ', say: 'あまくしちゃえ〜！', anim: 'react.laugh', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'sweet' }, { type: 'ACTOR_MOVE', actorId: 'child', to: [1200, 1080], speed: 200 }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'うわっ、あまっ！', delayMs: 2600 }, { type: 'ACTOR_SPEECH', actorId: 'grandpa', text: '……ばあさんの味じゃ', delayMs: 3800 }] },
    { id: 'S1-E15', s: 'soy', t: 'father', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', title: '父、醤油でキリッと仕上げる', say: 'ここはひとつ、醤油をひとたらし……うん、うまい！', anim: 'react.happy', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'good' }, { type: 'ACTOR_SPEECH', actorId: 'mother', text: 'あら、本当においしい', delayMs: 2600 }] },
    { id: 'S1-E16', s: 'sauce', t: 'father', cat: 'BRANCH', group: 'S1-SOUP-SEASONING', decoy: true, title: '父、ソースで鍋を台なしに', say: '隠し味にソースだ！ ……ん？', anim: 'react.surprised', route: 'S1.route.soup',
      fx: [{ type: 'SET_FLAG', id: 'soup.taste', value: 'weird' }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'うぇ〜、なにこれ', delayMs: 2400 }] },
    { id: 'S1-E17', s: 'knob', t: 'mother', cat: 'PROGRESSION', requires: ['S1-E03'], title: '母、火を強める', say: '寒いし、ちょっと強火にしましょ', anim: 'react.think', route: 'S1.route.heat', focus: true,
      fx: [{ type: 'SET_FLAG', id: 'room.hot', value: true }, { type: 'OBJECT_APPEARANCE', objectId: 'knob', look: { size: 40 } }, { type: 'FX', kind: 'steam', at: 'hotpot', delayMs: 400 }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'BUSY', delayMs: 2500 }],
      after: [{ actor: 'father', text: 'あ、あつい……！ 窓か、カーペットか……', delay: 3400 }] },
    { id: 'S1-E18', s: 'window', t: 'father', cat: 'BRANCH', requires: ['S1-E17'], title: '父、窓を開ける', say: 'あつい！ 窓を開けるぞ！', anim: 'react.happy', route: 'S1.route.heat',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'father', to: [1880, 760], speed: 200 }, { type: 'OBJECT_APPEARANCE', objectId: 'window', look: { sign: { text: '', fill: '#1d2b4f', color: '#fff' } }, delayMs: 1600 }, { type: 'SET_FLAG', id: 'window.open', value: true, delayMs: 1600 }, { type: 'ACTOR_SHOW', actorId: 'bug', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'bug', pathId: 'bugFly', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'father', to: [1560, 1000], speed: 160, delayMs: 3200 }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'IDLE', delayMs: 3200 }],
      after: [{ actor: 'child', text: 'あっ！ 虫が入ってきた！', delay: 3600 }] },
    { id: 'S1-E19', s: 'carpet', t: 'father', cat: 'BRANCH', requires: ['S1-E17'], title: '父、電気カーペットを切る', say: '下からもあっためてたのか！ 切っとこう', anim: 'react.think', route: 'S1.route.heat',
      fx: [{ type: 'OBJECT_APPEARANCE', objectId: 'carpet', look: { sign: { text: 'OFF', fill: '#555', color: '#ccc', s: 22 } }, delayMs: 1000 }, { type: 'SET_FLAG', id: 'carpet.off', value: true }, { type: 'ACTOR_SET_STATE', actorId: 'father', state: 'HAPPY', delayMs: 1200 }] },
    { id: 'S1-E20', s: 'bug', t: 'father', cat: 'CHAIN', group: 's1-bug-kill', requires: ['S1-E18'], title: '父、新聞で虫退治', say: 'えいっ！ 新聞紙の一撃！', anim: 'react.hit', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_HIDE', actorId: 'bug', delayMs: 700 }, { type: 'ACTOR_SPEECH', actorId: 'child', text: 'あー！ つかまえたかったのに', delayMs: 2000 }] },
    { id: 'S1-E21', s: 'bug', t: 'child', cat: 'FLAVOR', requires: ['S1-E18'], blocksIfCompleted: ['S1-E20', 'S1-E22'], title: '弟、虫を追いかける', say: 'まてまて〜！', anim: 'react.run', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'child', to: [1700, 900], speed: 240 }, { type: 'ACTOR_MOVE', actorId: 'child', to: [1080, 1210], speed: 200, delayMs: 2600 }] },
    { id: 'S1-E22', s: 'bug', t: 'grandpa', cat: 'CHAIN', group: 's1-bug-kill', requires: ['S1-E18'], title: '祖父、箸で虫をつまむ', say: 'ほいっ。……まだまだ現役じゃ', anim: 'react.sparkle', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_HIDE', actorId: 'bug', delayMs: 800 }, { type: 'ACTOR_SET_STATE', actorId: 'grandpa', state: 'HAPPY' }, { type: 'ACTOR_SPEECH', actorId: 'child', text: 'じいちゃん、すげー！', delayMs: 2000 }] },
    { id: 'S1-E23', s: 'bug', t: 'cat', cat: 'FLAVOR', requires: ['S1-E18'], blocksIfCompleted: ['S1-E20', 'S1-E22'], title: 'タマ、虫とたわむれる', say: 'ニャッ、ニャッ！', anim: 'react.surprised', route: 'S1.route.bug',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'cat', to: [1700, 1100], speed: 260 }, { type: 'ACTOR_SET_STATE', actorId: 'cat', state: 'HAPPY' }] },
    { id: 'S1-E24', s: 'knob', t: 'mother', cat: 'TIMEOUT', title: 'ガス切れで鍋がひえひえ', say: 'あら……？ ガスが切れちゃったわ', anim: 'react.timeout', route: 'S1.route.end',
      fx: [{ type: 'FX', kind: 'smoke', at: 'hotpot' }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'つめたい鍋だ……', delayMs: 1800 }] },
    { id: 'S1-E25', s: 'knob', t: 'mother', cat: 'TERMINAL', title: '鍋、大噴火！', say: 'みんなそろったし、一気に強火で……あらあらあら！？', anim: 'react.terminal', route: 'S1.route.end',
      cond: [done('S1-E17'), done('S1-E07'), { anyEventDone: ['S1-E18', 'S1-E19'] }],
      fx: [{ type: 'FX', kind: 'eruption', at: 'hotpot', delayMs: 600 }, { type: 'PLAY_SOUND', soundId: 'boom', delayMs: 600 }, { type: 'ACTOR_SPEECH', actorId: 'father', text: 'うおお！ 天井まで湯気が！', delayMs: 1600 }, { type: 'ACTOR_SPEECH', actorId: 'daughter', text: 'あははは！ でもおいしそう！', delayMs: 2400 }, { type: 'ACTOR_SPEECH', actorId: 'grandpa', text: 'これじゃ、これがうちの鍋じゃ', delayMs: 3200 }, { type: 'WAIT', durationMs: 3600 }] },
  ],
  paths: {
    bugFly: { points: [[1700, 600], [1400, 700], [1100, 650], [800, 800], [1300, 820], [1650, 700], [1880, 560]], speed: 140, loop: true },
  },
};
