// ステージ2：ひだまり商店街（66 イベント）。登場人物・台詞はすべてオリジナル。
const done = id => ({ eventDone: id });
const notDone = id => ({ eventNotDone: id });
const anyDone = (...ids) => ({ anyEventDone: ids });

// ── 背景：上から「空と海 → 北の店並び＋公園 → 一番街 → 中の店並び → 二番街 → 南の店並び → 車道と川」の 1 枚地図 ──
const W = 6000;
const R1 = 720;    // 北の店並びの下端（一番街の北側）
const R2 = 1485;   // 中の店並びの下端（二番街の北側）
const R3 = 2225;   // 南の店並びの下端（車道の北側）
const B = (x, y, w, h, fill, roof, o = {}) => ({ t: 'building', x, y, w, h, fill, roof, ...o });
const PR = (kind, x, y, s, o = {}) => ({ t: 'prop', kind, x, y, s, ...o });
const EM = (e, x, y, s, o = {}) => ({ t: 'emoji', e, x, y, s, ...o });
const scenery = [
  // 空・遠景（山と海）
  { t: 'sky', x: 0, y: 0, w: W, h: 360, c1: '#56b2ec', c2: '#dff4ff' },
  PR('cloud', 650, 120, 70), PR('cloud', 1850, 80, 56), PR('cloud', 2950, 130, 80), PR('cloud', 3950, 70, 60), PR('cloud', 5150, 110, 70),
  PR('sun', 4620, 130, 170),
  PR('mountain', 330, 300, 250, { color: '#5f8fc0', snow: true, wide: 1.3 }), PR('mountain', 880, 300, 190, { color: '#6c9cca' }), PR('mountain', 1420, 300, 150, { color: '#7aaad2' }),
  PR('hill', 2150, 320, 80, { color: '#86c46e', wide: 4 }),
  { t: 'water', x: 3900, y: 95, w: 2100, h: 110, fill: '#4aa6de', shore: '#f0e2b8' },
  PR('boat', 4300, 275, 34, { color: '#fff' }), PR('boat', 5000, 300, 26, { color: '#e2463c' }),
  // 北の並びの裏手（店と店のすき間に見える路地）
  { t: 'rect', x: 0, y: 180, w: 2380, h: 420, fill: '#c9b38e' },
  { t: 'rect', x: 4110, y: 180, w: 1890, h: 420, fill: '#c9b38e' },
  // 一番街（歩道＋石だたみ）。中の並びの下までしいておく
  { t: 'rect', x: 0, y: R1, w: W, h: 70, fill: '#d6c6a8' },
  { t: 'stripes', x: 0, y: R1, w: W, h: 70, dir: 'v', n: 100, c1: 'rgba(0,0,0,0)', c2: 'rgba(110,90,60,.12)' },
  { t: 'rect', x: 0, y: 773, w: W, h: R2 - 773, fill: '#f2e5c8' },
  { t: 'stripes', x: 0, y: 653, w: W, h: 255, dir: 'h', n: 8, c1: 'rgba(0,0,0,0)', c2: 'rgba(170,130,80,.08)' },
  { t: 'rect', x: 0, y: 754, w: W, h: 33, fill: 'rgba(214,112,72,.2)' },
  // 二番街
  { t: 'rect', x: 0, y: R2, w: W, h: 60, fill: '#d6c6a8' },
  { t: 'stripes', x: 0, y: R2, w: W, h: 60, dir: 'v', n: 100, c1: 'rgba(0,0,0,0)', c2: 'rgba(110,90,60,.12)' },
  { t: 'rect', x: 0, y: 1530, w: W, h: R3 - 1780, fill: '#ead8b4' },
  { t: 'stripes', x: 0, y: 1295, w: W, h: 255, dir: 'h', n: 8, c1: 'rgba(0,0,0,0)', c2: 'rgba(170,130,80,.08)' },
  { t: 'rect', x: 0, y: 1419, w: W, h: 30, fill: 'rgba(90,140,200,.16)' },
  // 中の並び・南の並びの路地
  { t: 'rect', x: 130, y: 926, w: 5660, h: 370, fill: '#bfa985' },
  { t: 'rect', x: 0, y: 1601, w: W, h: 350, fill: '#bba682' },
  // 南の車道と川
  { t: 'rect', x: 0, y: R3, w: W, h: 70, fill: '#d6c6a8' },
  { t: 'stripes', x: 0, y: R3, w: W, h: 70, dir: 'v', n: 100, c1: 'rgba(0,0,0,0)', c2: 'rgba(110,90,60,.12)' },
  { t: 'road', x: 0, y: 1940, w: W, h: 230 },
  { t: 'water', x: 0, y: 2195, w: W, h: 95, fill: '#5ab4e6', shore: '#9ccc7a' },

  // ── ひだまり公園（北の並びの中ほど） ──
  { t: 'rect', x: 2380, y: 190, w: 1730, h: 463, fill: '#93cf6c' },
  { t: 'ellipse', x: 3250, y: 750, rx: 860, ry: 40, fill: '#a9db82' },
  PR('bush', 2440, 350, 70, { color: '#5aa845' }), PR('tree', 2620, 400, 190), PR('pine', 2780, 360, 170),
  PR('bush', 3020, 330, 60, { color: '#5aa845', flower: '#fff' }), PR('tree', 3330, 350, 170, { color: '#4aa040' }),
  PR('pine', 3640, 370, 200), PR('tree', 3990, 380, 210, { fruit: '#ff6f61' }), PR('bush', 3800, 350, 60, { color: '#5aa845', flower: '#ff8ab0' }),
  { t: 'sign', x: 2400, y: 400, w: 210, h: 56, text: 'ひだまり公園', fill: '#4a8a3a', color: '#fff', s: 24 },
  { t: 'rect', x: 2420, y: 456, w: 10, h: 120, fill: '#6a4a2a' }, { t: 'rect', x: 2580, y: 456, w: 10, h: 120, fill: '#6a4a2a' },
  // 野球のグラウンド（奥）
  { t: 'ellipse', x: 3070, y: 455, rx: 240, ry: 62, fill: '#e2c48e' },
  { t: 'rect', x: 3062, y: 280, w: 16, h: 16, fill: '#fff' }, { t: 'rect', x: 2900, y: 328, w: 16, h: 16, fill: '#fff' }, { t: 'rect', x: 3226, y: 328, w: 16, h: 16, fill: '#fff' },
  PR('fountain', 3480, 530, 110),
  // 大きな木（西：コソ泥がひそむ／東：チョロ吉が登る）
  { t: 'ellipse', x: 2500, y: 660, rx: 190, ry: 36, fill: 'rgba(30,70,30,.3)' },
  PR('tree', 2490, 665, 470, { color: '#4fa83a' }),
  PR('tree', 3880, 680, 520, { color: '#58b040' }),
  // ジャングルジム
  { t: 'line', pts: [2675, 680,2675, 490,2845, 490,2845, 680], stroke: '#e0453a', w: 9 },
  { t: 'line', pts: [2675, 553,2845, 553], stroke: '#e0453a', w: 7 }, { t: 'line', pts: [2675, 616,2845, 616], stroke: '#e0453a', w: 7 },
  { t: 'line', pts: [2732, 490,2732, 680], stroke: '#f2c14e', w: 7 }, { t: 'line', pts: [2788, 490,2788, 680], stroke: '#f2c14e', w: 7 },
  { t: 'ellipse', x: 2965, y: 718, rx: 75, ry: 22, fill: '#ead49c' },
  // 時計の柱
  { t: 'rect', x: 3260, y: 360, w: 10, h: 240, fill: '#666' },
  PR('flower', 2620, 728, 34, { color: '#ffe066' }), PR('tulip', 2650, 732, 34, { color: '#ff4d6d' }), PR('flower', 3180, 729, 32, { color: '#ffa8c8' }),
  PR('tulip', 3320, 734, 34, { color: '#ffcc22' }), PR('flower', 3690, 729, 32, { color: '#ffe066' }), PR('tulip', 3730, 734, 34, { color: '#ff4d6d' }),
  PR('bird', 2990, 744, 30, { color: '#c8ccd2' }), PR('bird', 3025, 750, 26, { color: '#c8ccd2', flip: true }), PR('bird', 3110, 747, 28, { color: '#b8bcc4' }),
  { t: 'fence', x: 2620, y: 649, w: 200, h: 25, fill: '#fff' }, { t: 'fence', x: 3640, y: 649, w: 150, h: 25, fill: '#fff' }, { t: 'fence', x: 4000, y: 649, w: 110, h: 25, fill: '#fff' },

  // ── 北の店並び（下端 R1） ──
  B(40, R1, 320, 430, '#f9dbe6', '#d0708f', { awning: '#ee8fb5', goods: ['#ff9fc8', '#fff', '#c76b8a', '#ffd23f'] }),
  B(380, R1, 260, 420, '#eef0f4', '#4a6a8a', { sign: '理容 さかば', signFill: '#fff', signColor: '#c33', signSize: 26, awning: '#3a5a8a' }),
  EM('💈', 372, 675, 50),
  B(660, R1, 300, 430, '#c8a27a', '#6b4426', { sign: '純喫茶 ポプラ', signFill: '#3a2414', signColor: '#f4d9a0', signSize: 26, awning: '#2f6b4a', goods: ['#7a4a2a', '#fff6e0', '#c8a27a'] }),
  PR('table', 900, 769, 70, { cloth: '#fff' }), PR('parasol', 900, 769, 150, { color: '#2f8a5a' }), PR('pot', 690, 769, 60),
  B(980, R1, 420, 440, '#e9edf2', '#2a4a8a', { roofStyle: 'flat', awning: '#f2c14e', goods: ['#333', '#555', '#3a8ad8', '#ddd'] }),
  { t: 'rect', x: 1296, y: 142, w: 8, h: 20, fill: '#555' },
  B(1420, R1, 320, 430, '#e4f3e8', '#2e8a5a', { awning: '#4caf7a', goods: ['#fff', '#5bb03b', '#ff6f61', '#3a8ad8'] }),
  B(1760, R1, 250, 500, '#f4f6f8', '#6aa0c8', { sign: 'しろくま歯科 2F', signFill: '#6aa0c8', signColor: '#fff', signSize: 24 }),
  B(2030, R1, 340, 430, '#d9c9a8', '#7a3a2a', { sign: '本の森書店', signFill: '#2a4a2a', signColor: '#f4f0d0', signSize: 28, awning: '#7a3a2a', goods: ['#c33', '#3a6ab0', '#5a8a3a', '#e8b52a', '#6a4a8a'] }),
  PR('table', 2300, 769, 60, { color: '#8a5a32' }),
  B(4120, R1, 300, 430, '#ffd8a8', '#c8641a', { awning: '#ff9a3a', goods: ['#ff9a3a', '#ffd23f', '#a0522d'] }),
  EM('🌞', 4270, 350, 54),
  B(4440, R1, 340, 440, '#fff4b8', '#3a8ac8', { sign: 'おもちゃのポッポ', signFill: '#e33', signColor: '#fff', signSize: 26, awning: '#e33' }),
  EM('🎰', 4805, 750, 50),
  B(4800, R1, 280, 420, '#f0fff0', '#4a9a5a', { awning: '#9ad07a', goods: ['#ff6fa8', '#ffd23f', '#ff4d6d', '#fff', '#c86ad8'] }),
  PR('bush', 5010, 769, 40, { color: '#4fa33a', flower: '#ff6fa8' }), PR('tulip', 4830, 769, 34, { color: '#ffcc22' }),
  // さくら湯（瓦屋根）と煙突・釜場
  { t: 'rect', x: 5730, y: -110, w: 60, h: 710, fill: '#8b4a3a' },
  { t: 'stripes', x: 5730, y: -110, w: 60, h: 710, dir: 'h', n: 16, c1: 'rgba(0,0,0,0)', c2: 'rgba(0,0,0,.14)' },
  B(5100, R1, 600, 470, '#f3ead8', '#3a3a5a', { roofStyle: 'tile', door: false, windowColor: '#ffe6b0' }),
  { t: 'rect', x: 5800, y: 500, w: 110, h: 100, fill: '#555', r: 8 }, EM('🔥', 5855, 685, 34),
  PR('logs', 5820, 773, 46),

  // ── 中の店並び（下端 R2）と店先の小物 ──
  B(130, R2, 290, 380, '#3a2050', '#1a0a2a', { sign: '占いの館', signFill: '#a07ad0', signColor: '#fff', windowColor: '#c8a0f0' }),
  { t: 'ellipse', x: 300, y: 1566, rx: 74, ry: 18, fill: '#4a2a6a' }, EM('🔮', 340, 1547, 38),
  B(440, R2, 320, 380, '#2a2a4a', '#111', { sign: 'ゲームセンター', signFill: '#f0f', signColor: '#fff', shop: true, goods: ['#f0f', '#0ff', '#ff0', '#f44'], windowColor: '#7a5ac8' }),
  B(780, R2, 290, 380, '#d6cbb4', '#3a2a1a', { awning: '#4a3a2a', goods: ['#c8a23a', '#8a3a6a', '#ddd'] }),
  B(1090, R2, 290, 380, '#d8e8ff', '#2a5aa8', { sign: 'スポーツ ダッシュ', signSize: 24, awning: '#2a5aa8' }),
  { t: 'rect', x: 1110, y: 1280, w: 240, h: 20, fill: '#8a6a4a', r: 4 },
  B(1460, R2, 290, 380, '#f6e6d6', '#6a3a2a', { sign: '和菓子 つきみ堂', signFill: '#fff', signColor: '#6a3a2a', signSize: 24, awning: '#b05a4a', goods: ['#ffb0c0', '#fff', '#8ac85a', '#6a3a2a'] }),
  B(1770, R2, 420, 380, '#dff0f7', '#1d5b8a', { door: false, windows: false, awning: '#3a8ac8', goods: ['#9ab', '#c8d8e8', '#e86a5a'] }),
  { t: 'rect', x: 1790, y: 1128, w: 92, h: 80, fill: '#8fd3f0', stroke: '#456', lw: 4 },
  { t: 'rect', x: 1900, y: 1220, w: 270, h: 32, fill: '#a8bccb', r: 4 }, EM('🧊', 2165, 1453, 26),
  B(2210, R2, 290, 380, '#f6e0d6', '#a33', { awning: '#d65a4a', goods: ['#e86a5a', '#c8642a', '#ffd8a8'] }),
  B(2520, R2, 320, 380, '#fff1c9', '#e2702a', { roofStyle: 'flat', awning: '#e8b52a', goods: ['#e2702a', '#ffd23f', '#a0522d', '#e2343c'] }),
  B(2860, R2, 270, 380, '#f3d2a0', '#8a3a1a', { awning: '#c84a1a', goods: ['#c84a1a', '#ffd23f', '#7a3a1a'] }),
  EM('🌶️', 2890, 1175, 40),
  B(3150, R2, 300, 380, '#f2e0b0', '#a33', { sign: 'ラーメン 大盛軒', signFill: '#a33', signColor: '#fff', signSize: 24, awning: '#d33' }),
  B(3470, R2, 270, 380, '#eef6ff', '#5a7a9a', { sign: 'クリーニング', signSize: 24, shop: true, goods: ['#fff', '#cde', '#9ab'] }),
  B(3760, R2, 520, 380, '#f6f0d8', '#3a7a2a', { sign: '八百屋 みどり', signFill: '#3a7a2a', signColor: '#fff', awning: '#5aa83a', door: false, goods: ['#5bb03b', '#ff8a2a', '#ffd23f', '#e2343c', '#8ac85a'] }),
  { t: 'rect', x: 3790, y: 1230, w: 470, h: 23, fill: '#a8703c', r: 4 },
  EM('🥬', 3940, 1459, 36), EM('🥕', 4010, 1459, 34), EM('🍌', 4080, 1459, 34), EM('🍊', 4140, 1461, 30),
  B(4300, R2, 260, 380, '#f4f4f4', '#2a3a6a', { roofStyle: 'flat', windows: false }),
  { t: 'ellipse', x: 4430, y: 1165, rx: 18, ry: 18, fill: '#e2343c' },
  B(4580, R2, 260, 380, '#fff8e0', '#c8a23a', { sign: '文具 えんぴつ', signSize: 24, shop: true }),
  B(4860, R2, 290, 380, '#f6dcb0', '#8a5a2a', { sign: 'パン こむぎ', signSize: 26, awning: '#c88a3a', goods: ['#d8a050', '#f0c070', '#a86a2a'] }),
  B(5170, R2, 300, 380, '#222', '#000', { sign: 'ライブハウス 轟', signFill: '#c00', signColor: '#fff', signSize: 24, windowColor: '#7a2a8a' }),
  EM('🎸', 5210, 1455, 44), EM('🥁', 5440, 1465, 40),
  B(5490, R2, 300, 380, '#e0f0f8', '#4a8ab0', { sign: 'コインランドリー', signSize: 24, shop: true, goods: ['#fff', '#ddd', '#bcd'] }),
  // 両はしの抜け道
  PR('tree', 60, 1265, 190), PR('bush', 70, 1465, 60, { color: '#4fa33a', flower: '#ffd23f' }),
  PR('tree', 5940, 1245, 200, { color: '#4fa83a' }), PR('vending', 5850, 1485, 120, { color: '#3a8ad8' }),

  // ── 南の店並び（下端 R3） ──
  B(20, R3, 340, 320, '#9aa8a8', '#566', { sign: '駐輪場', roofStyle: 'flat', windows: false, door: false }),
  PR('bike', 90, 2220, 70, { color: '#e2463c' }), PR('bike', 190, 2220, 70), PR('bike', 290, 2220, 70, { color: '#5bb03b' }),
  B(380, R3, 300, 350, '#d8c3e8', '#6a4a8a', { sign: '古着 ふるふる', signSize: 24, awning: '#9a6ac8' }),
  B(700, R3, 280, 340, '#e8d8a8', '#8a6a2a', { sign: 'たばこ・宝くじ', signSize: 22, awning: '#c8a23a' }),
  B(1000, R3, 300, 350, '#e8d6c0', '#7a5a3a', { sign: '酒の まるやま', signSize: 24, shop: true, goods: ['#3a6a3a', '#8a3a2a', '#ddd'] }),
  B(1320, R3, 340, 350, '#ffe8c8', '#c85a2a', { sign: '駄菓子 ちびっこ', signSize: 24, awning: '#f28a3a' }),
  // 小さな神社
  PR('pine', 1730, 2085, 190), PR('pine', 2060, 2095, 170),
  B(1820, 2145, 200, 220, '#f4e6d0', '#5a4a3a', { roofStyle: 'tile', windows: false }),
  { t: 'rect', x: 1700, y: 1744, w: 16, h: 160, fill: '#d8382a' }, { t: 'rect', x: 1800, y: 1744, w: 16, h: 160, fill: '#d8382a' },
  { t: 'rect', x: 1680, y: 1732, w: 156, h: 20, fill: '#d8382a', r: 4 }, { t: 'rect', x: 1692, y: 1759, w: 132, h: 12, fill: '#d8382a' },
  { t: 'rect', x: 1680, y: 1804, w: 420, h: 80, fill: '#d9ccb0' },
  // 駐車場
  { t: 'rect', x: 2120, y: 1714, w: 580, h: 200, fill: '#b4b6ba' },
  { t: 'stripes', x: 2120, y: 1714, w: 580, h: 200, dir: 'v', n: 6, c1: 'rgba(0,0,0,0)', c2: 'rgba(255,255,255,.25)' },
  PR('house', 2250, 2025, 160, { color: '#f2e2c4', roof: '#3a7ac8' }), PR('house', 2560, 2025, 150, { color: '#fff0d8', roof: '#c9503c' }),
  PR('car', 2230, 2205, 64, { color: '#3a7ad8' }), PR('car', 2420, 2205, 64, { color: '#f2c43a', flip: true }), PR('truck', 2610, 2205, 56),
  { t: 'sign', x: 2130, y: 1721, w: 54, h: 54, text: 'P', fill: '#2a5ab0', color: '#fff', s: 36 },
  B(2720, R3, 280, 340, '#fff0f0', '#e86a8a', { sign: 'たいやき', signSize: 26, awning: '#e86a8a' }),
  B(3020, R3, 300, 350, '#eef2f6', '#3a4a6a', { sign: 'メガネの光堂', signSize: 22, shop: true }),
  B(3340, R3, 320, 350, '#f2e6d0', '#3a3a3a', { sign: 'そば 更科', roofStyle: 'tile', awning: '#3a3a3a', signFill: '#3a2a1a', signColor: '#fff', signSize: 26 }),
  B(3680, R3, 320, 360, '#ffece0', '#c8342a', { sign: '〒 ゆうびん局', roofStyle: 'flat', signFill: '#c8342a', signColor: '#fff', signSize: 24 }),
  B(4020, R3, 280, 340, '#fff0f6', '#d86aa8', { sign: 'ケーキ ルル', signSize: 24, awning: '#f2a8c8', goods: ['#fff', '#ffb0c8', '#e2343c', '#f6dcb0'] }),
  B(4320, R3, 320, 360, '#2a3a6a', '#1a2a4a', { sign: 'カラオケ', roofStyle: 'flat', signFill: '#ffd23f', signColor: '#2a3a6a', signSize: 26, windowColor: '#ff9ad0' }),
  B(4660, R3, 300, 350, '#f8f4e8', '#5a8a5a', { sign: 'とうふ 白川', roofStyle: 'tile', shop: true, signSize: 24, goods: ['#fff', '#f4f0e0'] }),
  B(4980, R3, 380, 340, '#f4f8f4', '#3aa05a', { sign: 'コンビニ ひだまり', roofStyle: 'flat', signFill: '#3aa05a', signColor: '#fff', shop: true, signSize: 24 }),
  B(5380, R3, 300, 350, '#f0e8d8', '#7a5a3a', { sign: '自転車 くるくる', signSize: 22, awning: '#3a8ac8' }),
  B(5700, R3, 280, 340, '#e8f0d8', '#6a8a3a', { sign: 'お茶 みどり園', signSize: 22, awning: '#6a8a3a', goods: ['#6a8a3a', '#a8c86a', '#c8a23a'] }),

  // 車道の車（飾り）と川辺
  PR('car', 650, 2395, 66, { color: '#e2463c', flip: true }), PR('bus', 1700, 2515, 78, { color: '#3a9ad8' }),
  PR('car', 2950, 2395, 66, { color: '#5bb03b', flip: true }), PR('truck', 3900, 2515, 66, { color: '#f2a83a' }),
  PR('car', 4800, 2395, 66, { color: '#f2c43a', flip: true }), PR('car', 5600, 2515, 66, { color: '#fff' }),
  PR('boat', 2300, 2620, 40, { color: '#c8643c' }), PR('boat', 5000, 2630, 34),
];
// 街灯・のぼり・植えこみ（ループ）
for (const x of [20, 650, 1410, 2370, 4110, 4790, 5090]) scenery.push(PR('lamp', x, 774, 170));
for (const x of [430, 1380, 2200, 3000, 3780, 4600, 5300]) scenery.push(PR('lamp', x, 1535, 160));
for (const x of [380, 1700, 2900, 4320, 5370]) scenery.push(PR('lamp', x, 2293, 150));
[120, 900, 1500, 2600, 3300, 4100, 4900, 5700].forEach(x => scenery.push(PR('tree', x, 2297, 150, { color: '#5bb03b' })));

export default {
  id: 'S2', title: 'ひだまり商店街', subtitle: '商店街', theme: '商店街',
  intro: 'にぎやかな昼下がりの商店街。みんなそれぞれ、ちょっとした悩みをかかえているみたい。いちばん奥の銭湯は、今日はなぜか元気がない……',
  timeLimitMs: 300000,
  world: { width: W, height: 2650, minZoom: 0.75, maxZoom: 4, bg: '#ead8b4', spawnCamera: { x: 3000, y: 1265, zoom: 1 } },
  bgm: { tempo: 116, key: 2, mood: 'swing' },
  clearEventId: 'S2-E66', timeoutEventId: 'S2-E65',
  routes: {
    'S2.route.hair': 'ミツルの髪型さがし', 'S2.route.teruo': 'テルオの頭', 'S2.route.dinner': '今夜の献立', 'S2.route.fish': '魚屋さわぎ',
    'S2.route.yanagi': 'ヤナギの顔色', 'S2.route.sumo': '力士・大樽の休日', 'S2.route.sweets': 'アンズのがまん', 'S2.route.park': '公園の昼下がり',
    'S2.route.flower': '花屋のまわり', 'S2.route.climb': 'ノボルと高いところ', 'S2.route.kid': 'チョロ吉の木のぼり', 'S2.route.hungry': 'マンタの空腹',
    'S2.route.book': '本屋の三人', 'S2.route.baseball': '草野球', 'S2.route.minori': 'ミノリのおつかい', 'S2.route.runner': 'ハヤテの走り',
    'S2.route.ink': 'ガクとタコ', 'S2.route.pawn': 'キヌエの質入れ', 'S2.route.police': 'おまわりさんの一日', 'S2.route.kirari': 'キラリのイメチェン',
    'S2.route.end': 'さくら湯の釜',
  },
  scenery,
  actors: {
    // ── 西エリア ──
    mitsuru: {
      name: 'ミツル', x: 420, y: 848, wander: 110, speed: 55,
      look: { h: 170, hair: 'short', hairColor: '#3a2a1a', shirt: '#7ab0d8', pants: '#3a4a6a' },
      idle: [
        { text: '髪を切りたいんだけど……どんな髪型にするか決められない', when: [notDone('S2-E02'), notDone('S2-E03'), notDone('S2-E04'), notDone('S2-E05'), notDone('S2-E06')] },
        { text: '見本になるものがあればなあ。ポスターとか、看板とか', when: [notDone('S2-E02'), notDone('S2-E04')] },
        { text: 'かっこいい人を見ると、すぐマネしたくなるんだよね', when: [notDone('S2-E05'), notDone('S2-E06')] },
        { text: 'あのおじさんの頭、まぶしい……なんか神々しい……！', when: [done('S2-E08'), notDone('S2-E03')] },
        { text: 'どう？ この髪型。……やっぱ変かな', when: [anyDone('S2-E02', 'S2-E03', 'S2-E04', 'S2-E05', 'S2-E06', 'S2-E07')] },
      ],
    },
    teruo: {
      name: 'テルオ', x: 900, y: 915, path: [[150, 885], [1500, 915], [900, 983]], speed: 40,
      look: { h: 165, hair: 'short', hairColor: '#222', shirt: '#b8a07a', pants: '#5a4a3a', acc: ['mustache'], old: true },
      idle: [
        { text: '（しきりに頭をおさえている）……風の強い日は苦手でな', when: [notDone('S2-E01')] },
        { text: 'わしの髪？ ふさふさじゃろ？ ……さわるでないぞ', when: [notDone('S2-E01')] },
        { text: '頭がすーすーする……いっそピカッと開き直れたら楽なんじゃが', when: [done('S2-E01'), notDone('S2-E08'), notDone('S2-E09')] },
        { text: '海のものは髪にいいと聞いたことがあるが……', when: [done('S2-E01'), notDone('S2-E08'), notDone('S2-E09')] },
        { text: 'もう隠さん！ 明るく生きるんじゃ！', when: [done('S2-E08')] },
        { text: 'このうねうね、悪くないじゃろ？', when: [done('S2-E09')] },
      ],
    },
    kirari: {
      name: 'キラリ', x: 700, y: 968, path: [[300, 953], [2300, 983], [1300, 1005]], speed: 45,
      look: { h: 168, hair: 'long', hairColor: '#c8862a', skin: '#f2c9a0', shirt: '#ff7ac0', skirt: true, pants: '#fff', acc: ['earring', 'bag'] },
      idle: [
        { text: 'なーんか、イメチェンしたい気分〜', when: [notDone('S2-E60')] },
        { text: 'もっとこう、パッと明るい感じになりたいんだよね', when: [notDone('S2-E60')] },
        'あたしって、すぐ影響されちゃうタイプなの',
        { text: '真っ白すぎ……ちょっと焼いて色つけたいかも', when: [done('S2-E60'), notDone('S2-E61')] },
        { text: '黒すぎ！ ゴシゴシ洗ったら戻るかな……', when: [done('S2-E61'), notDone('S2-E62')] },
        { text: 'のぼせた〜。でも、なんか楽しかった', when: [done('S2-E62')] },
      ],
    },
    kinue: {
      name: 'キヌエ', x: 925, y: 1598, wander: 70, speed: 35,
      look: { h: 160, hair: 'bun', hairColor: '#6a3a6a', shirt: '#8a3a6a', skirt: true, pants: '#4a2a4a', acc: ['bag', 'earring', 'hat'], hatColor: '#c8a', old: true },
      idle: [
        { text: '家賃のしはらい、明日なのよ……どうしましょ', when: [notDone('S2-E55')] },
        { text: 'このバッグ、高かったのよねえ。手放すなんて……', when: [notDone('S2-E55')] },
        'お金って、どこに消えるのかしら',
        { text: 'ぜんぜん足りないわ……あとは首もとの、これくらいね', when: [done('S2-E55'), notDone('S2-E56')] },
        { text: 'ふう、身軽になったわ。家賃もなんとかなりそう', when: [done('S2-E56')] },
      ],
    },
    uranai: {
      name: '占い師', x: 300, y: 1545, wander: 0,
      look: { h: 165, hair: 'long', hairColor: '#222', shirt: '#4a2a6a', pants: '#2a1a3a', acc: ['scarf', 'earring'], sit: true },
      idle: ['迷える者よ、来たれ……', 'ほっほっ。水晶玉はなんでもお見通しじゃ', '今日の吉方位は……むむっ'],
    },
    // ── 電器店・薬局・本屋 ──
    yanagi: {
      name: 'ヤナギ', x: 1650, y: 833, wander: 60, speed: 30,
      look: { h: 176, hair: 'long', hairColor: '#2a1a12', skin: '#e4dfd2', shirt: '#2a2a2a', pants: '#2a2a2a', acc: ['scarf'] },
      idle: [
        { text: 'ゴホッ……最近どうも体がだるくてね', when: [notDone('S2-E16'), notDone('S2-E17')] },
        { text: '顔色が悪いってよく言われるんだ。栄養、足りてないのかな', when: [notDone('S2-E16'), notDone('S2-E17')] },
        { text: '髪型だけは毎朝きめてるんだ。見られてるからね', when: [notDone('S2-E17')] },
        { text: '体が軽い！ どこまでも歩けそうだ', when: [done('S2-E16')] },
        { text: 'ぼくの……自慢の髪が……', when: [done('S2-E17')] },
      ],
    },
    batter: {
      name: 'イワオ', x: 1120, y: 833, wander: 50, speed: 40,
      look: { h: 178, hair: 'short', hairColor: '#222', shirt: '#fff', pants: '#ddd', acc: ['cap'], hatColor: '#1d3a8a', wide: true },
      idle: [
        { text: 'ナイターまでヒマだなあ……', when: [notDone('S2-E38')] },
        { text: '電器屋のテレビ、いまなにやってるかな', when: [notDone('S2-E38')] },
        { text: '草野球の四番も、最近はバット振ってないや', when: [notDone('S2-E38')] },
        { text: 'ブン！ ブン！ ……だれか投げてくれないかなあ', when: [done('S2-E38'), notDone('S2-E36'), notDone('S2-E37')] },
        { text: 'いい汗かいた！', when: [anyDone('S2-E36', 'S2-E37')] },
      ],
    },
    gou: {
      name: 'ゴウ', x: 2180, y: 848, wander: 50, speed: 40,
      look: { h: 172, hair: 'spiky', hairColor: '#e8c040', shirt: '#222', pants: '#333', acc: ['sunglasses'] },
      idle: [
        { text: 'ヒマだなー。なんかおもしれーもんねーか', when: [notDone('S2-E32')] },
        { text: 'オレたち、アイドルにはうるさいんだぜ', when: [notDone('S2-E32')] },
        { text: 'へっへっ、この写真集は渡さねーぞ', when: [done('S2-E32'), notDone('S2-E34')] },
        { text: 'あ、あいつ、なんであんなにムキムキに……', when: [done('S2-E34'), notDone('S2-E35')] },
      ],
    },
    jin: {
      name: 'ジン', x: 2260, y: 863, wander: 50, speed: 40,
      look: { h: 160, hair: 'mohawk', hairColor: '#333', shirt: '#555', pants: '#333', acc: ['mask'] },
      idle: ['アニキ、どこまでもついてくっす！', 'アニキ、新刊のコーナー見たっすか？', { text: 'アニキ〜、こわいっす〜！', when: [done('S2-E34')] }],
    },
    nobu: {
      name: 'ノブ', x: 2320, y: 799, wander: 20, speed: 30,
      look: { h: 158, hair: 'bob', hairColor: '#3a2a1a', shirt: '#c8d8a8', pants: '#5a6a4a', acc: ['glasses', 'bag'] },
      idle: [
        { text: '静かに本を読みたいだけなのに……', when: [notDone('S2-E32')] },
        { text: 'ぼく、力じゃだれにも勝てないんだ', when: [notDone('S2-E33')] },
        { text: 'もっと体が強ければ、言い返せるのになあ', when: [done('S2-E32'), notDone('S2-E33')] },
        { text: 'みなぎる……！ さっきの二人、まだその辺にいるかな', when: [done('S2-E33'), notDone('S2-E34')] },
      ],
    },
    bookman: {
      name: '書店の店主', x: 2120, y: 774, wander: 30, speed: 25,
      look: { h: 165, hair: 'bald', hairColor: '#ccc', shirt: '#7a6a4a', pants: '#4a3a2a', acc: ['glasses', 'apron'], old: true },
      idle: ['立ち読みは、ほどほどにね', 'いらっしゃい。今日は写真集が入ったよ', { text: '店の前がさわがしいねえ……', when: [done('S2-E34'), notDone('S2-E35')] }],
    },
    anzu: {
      name: 'アンズ', x: 1605, y: 1583, wander: 60, speed: 35,
      look: { h: 125, hair: 'twin', hairColor: '#5a2a1a', shirt: '#ffb0c0', skirt: true, pants: '#fff', acc: ['ribbon'], kid: true },
      idle: [
        { text: 'あんみつ……どら焼き……ああ、食べたい', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'でも、最近ちょっと食べすぎかなあ……', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'だれか、あたしを止めてくれないかな', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'がまん、がまん……えらいでしょ？', when: [anyDone('S2-E20', 'S2-E21')] },
      ],
    },
    // ── 魚屋・肉屋・食べもの屋 ──
    fishman: {
      name: '魚屋の大将', x: 1990, y: 1541, wander: 40, speed: 30,
      look: { h: 175, hair: 'spiky', hairColor: '#222', shirt: '#fff', pants: '#2a4a8a', acc: ['apron', 'scarf'], muscle: true },
      idle: ['へいらっしゃい！ 今日はタコがいいよ！', 'ボウズ、生きものにはさわるなよ〜', { text: 'あのドロボウ猫め……', when: [done('S2-E15')] }],
    },
    tsurita: {
      name: 'ツリタ', x: 2120, y: 1575, wander: 50, speed: 35,
      look: { h: 168, hair: 'short', hairColor: '#555', shirt: '#6a8a5a', pants: '#4a4a3a', acc: ['hat', 'beard'], hatColor: '#c8b06a' },
      idle: [
        { text: '今日もボウズだ……一匹も釣れなかった', when: [notDone('S2-E13'), notDone('S2-E14')] },
        { text: '家族に「大漁だ」って言っちゃったんだよなあ', when: [notDone('S2-E13'), notDone('S2-E14')] },
        { text: 'これで家でも胸をはれるぞ！', when: [done('S2-E13')] },
        { text: '……竿、持ってくればよかった', when: [done('S2-E14')] },
      ],
    },
    gaku: {
      name: 'ガク', x: 2200, y: 1598, wander: 70, speed: 50,
      look: { h: 122, hair: 'spiky', hairColor: '#3a2a1a', skin: '#f2c9a0', shirt: '#f28a3a', pants: '#3a5a8a', acc: ['cap'], hatColor: '#d33', kid: true },
      idle: [
        { text: '魚屋さんって、へんな生きものがいっぱい！', when: [notDone('S2-E53')] },
        { text: 'さわってみたいなあ……ぐにゃぐにゃしたやつとか', when: [notDone('S2-E53'), notDone('S2-E52')] },
        { text: 'まっくろ……母ちゃんに怒られる。どこかで洗い流さないと', when: [done('S2-E53'), notDone('S2-E54')] },
        { text: 'ピッカピカ！ お風呂ってすごい！', when: [done('S2-E54')] },
      ],
    },
    goma: {
      name: '野良猫のゴマ', emoji: '🐈', size: 64, x: 2270, y: 1519, wander: 160, speed: 70,
      idle: ['ニャ〜（魚屋のほうをじっと見ている）', 'ゴロゴロ……', { text: 'ニャフ〜（満足そう）', when: [done('S2-E15')] }],
    },
    mama: {
      name: 'チョロ吉の母', x: 3700, y: 953, wander: 70, speed: 40,
      look: { h: 168, hair: 'pony', hairColor: '#4a2a1a', shirt: '#e8a86a', pants: '#5a5a7a', acc: ['bag'] },
      idle: [
        { text: 'チョロ吉ったら、どこ行ったのかしら', when: [notDone('S2-E45')] },
        { text: 'あの子、おもちゃばっかりほしがるんだから', when: [notDone('S2-E45')] },
        { text: 'あら？ どこからかチョロ吉の声がするわ……', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
      ],
    },
    harue: {
      name: 'ハルエ', x: 2500, y: 1605, path: [[1800, 1590], [3300, 1613], [2500, 1665]], speed: 35,
      look: { h: 168, hair: 'bob', hairColor: '#5a3a2a', shirt: '#a8c8e8', skirt: true, pants: '#6a7a9a', acc: ['apron', 'bag'] },
      idle: [
        { text: '今夜のごはん、なんにしようかしら……', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: '毎日考えるの、ほんと大変なのよ', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: 'お店の看板見てると、どれもおいしそうに見えるのよね', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: '献立が決まると、足どりも軽いわ♪', when: [anyDone('S2-E10', 'S2-E11', 'S2-E12')] },
      ],
    },
    manta: {
      name: 'マンタ', x: 2800, y: 1583, path: [[2500, 1575], [3200, 1590]], speed: 30,
      look: { h: 170, hair: 'short', hairColor: '#222', shirt: '#f2c14e', pants: '#6a4a2a', wide: true },
      idle: [
        'おなかすいた……',
        '看板を見てるだけで、よだれが……',
        { text: '辛いのは苦手だけど……だからこそ、あこがれるんだよね', when: [notDone('S2-E30')] },
        { text: 'ひーっ、まだ口が火事だ……', when: [done('S2-E30')] },
      ],
    },
    // ── 公園 ──
    thief: {
      name: 'コソ泥', x: 2545, y: 652, wander: 10, speed: 30, minZoom: 1.5,
      look: { h: 165, hair: 'short', hairColor: '#111', skin: '#d8b090', shirt: '#2a2a2a', pants: '#2a2a2a', acc: ['mask', 'bag'] },
      idle: ['しーっ……', 'ヒッヒッ、木陰ならだれも気づくまい'],
    },
    noboru: {
      name: 'ノボル', x: 2870, y: 769, wander: 120, speed: 60,
      look: { h: 122, hair: 'spiky', hairColor: '#222', shirt: '#5ac85a', pants: '#2a4a2a', acc: ['cap'], hatColor: '#2a7a2a', kid: true },
      idle: [
        { text: '高いところ、だーいすき！', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'この商店街で、いちばん高いところってどこだろう？', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'てっぺんから見る景色は、さいこうなんだ', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'やっほー！ ぜんぶ見えるぞー！', when: [anyDone('S2-E27', 'S2-E28')] },
      ],
    },
    grandma: {
      name: 'ベンチのおばあちゃん', x: 3040, y: 666, wander: 0,
      look: { h: 158, hair: 'bun', hairColor: '#ddd', shirt: '#a87ab0', pants: '#5a4a6a', acc: ['glasses'], old: true, sit: true },
      idle: ['ハトさん、お食べ', 'いい天気ねえ', { text: 'あら、となりのベンチ、空いたわねえ', when: [done('S2-E23'), notDone('S2-E19')] }],
    },
    nemuta: {
      name: '係長ネムタ', x: 3540, y: 666, wander: 0,
      look: { h: 170, hair: 'short', hairColor: '#333', shirt: '#fff', pants: '#3a3a4a', acc: ['tie'], sit: true },
      idle: [
        { text: 'ぐう……ぐう……', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'むにゃ……部長、あと五分……', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'ぐう……（腕時計はしていないようだ）', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'ちっ、犬のせいで目がさめた。……まあいいや、ゆっくりしよ', when: [done('S2-E22')] },
        { text: 'ハァハァ……会議、まにあった……？', when: [done('S2-E23')] },
      ],
    },
    dog: {
      name: '柴犬のポチ丸', emoji: '🐕', size: 72, x: 3350, y: 570, wander: 220, speed: 80,
      idle: ['ワン！', 'クゥーン（動くものを目で追っている）', 'ハッハッハッ', { text: 'フンフン（ベンチのほうをかいでいる）', when: [notDone('S2-E22'), notDone('S2-E23')] }],
    },
    rikishi: {
      name: '力士・大樽', x: 3200, y: 863, wander: 160, speed: 35,
      look: { h: 190, hair: 'topknot', hairColor: '#111', skin: '#f0c8a0', shirt: '#6a4a8a', pants: '#6a4a8a', wide: true },
      idle: [
        { text: '稽古のあとは、ひと休みしたいでごわす', when: [notDone('S2-E18'), notDone('S2-E19')] },
        { text: 'どこか腰をおろせる場所はないでごわすか', when: [notDone('S2-E18'), notDone('S2-E19')] },
        '体がでかいと、なにかと不便でごわす',
        { text: '汗と砂でどろどろでごわす。大きな湯船につかりたいでごわすなあ', when: [anyDone('S2-E18', 'S2-E19', 'S2-E47'), notDone('S2-E64')] },
        { text: 'いい湯でごわした！', when: [done('S2-E64')] },
      ],
    },
    sora: {
      name: 'ソラ', x: 2960, y: 480, wander: 80, speed: 50,
      look: { h: 122, hair: 'short', hairColor: '#222', shirt: '#e44', pants: '#fff', acc: ['cap'], hatColor: '#e44', kid: true },
      idle: ['ピッチャーなら、まかせて！', '投げるの、得意なんだ', { text: '四番のおじさん、来ないかなあ', when: [notDone('S2-E38')] }],
    },
    umi: {
      name: 'ウミ', x: 3190, y: 500, wander: 80, speed: 50,
      look: { h: 122, hair: 'short', hairColor: '#222', shirt: '#3a7ae8', pants: '#fff', acc: ['cap'], hatColor: '#3a7ae8', kid: true },
      idle: ['ソラより、ぼくのほうが球は速いよ！', 'ノーコンじゃないよ！ ……たぶん', 'キャッチボールしよー'],
    },
    minori: {
      name: 'ミノリ', x: 4000, y: 1613, wander: 30, speed: 40,
      look: { h: 125, hair: 'pony', hairColor: '#4a2a1a', shirt: '#ffd84a', skirt: true, pants: '#e88', acc: ['bag'], kid: true },
      idle: [
        { text: 'おつかい、たのまれたのに……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'あの犬がこわくて、お店に近づけないよ……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'なにか投げたら、追いかけていかないかな……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'えっと、なに買うんだっけ……赤いもの？ 白くて長いもの？', when: [anyDone('S2-E39', 'S2-E40'), notDone('S2-E41'), notDone('S2-E42'), notDone('S2-E43')] },
        { text: 'おつかい、できた！', when: [anyDone('S2-E41', 'S2-E42', 'S2-E43')] },
      ],
    },
    bulldog: {
      name: 'ブルドッグのドン', emoji: '🐶', size: 80, x: 4110, y: 1568, wander: 20, speed: 60,
      idle: [{ text: 'ウ〜……ガルル', when: [notDone('S2-E39'), notDone('S2-E40')] }, 'ブフッ', { text: 'ハッハッ（ボールに夢中だ）', when: [done('S2-E39'), notDone('S2-E44')] }],
    },
    police: {
      name: 'おまわりさん', x: 4430, y: 1560, wander: 40, speed: 40,
      look: { h: 175, hair: 'short', hairColor: '#222', shirt: '#2a3a6a', pants: '#2a3a6a', acc: ['hat'], hatColor: '#1a2a4a' },
      idle: [
        { text: '本日も異常なし！', when: [notDone('S2-E57')] },
        { text: 'この辺りに、ドロボウがひそんでいるらしい……', when: [notDone('S2-E57')] },
        'こまったことがあれば、交番へどうぞ',
        { text: 'お手がら、お手がら！', when: [done('S2-E57')] },
      ],
    },
    bikegirl: {
      name: 'コハル', emoji: '🚴‍♀️', size: 110, x: 3500, y: 1643, path: [[3300, 1643], [5700, 1643], [5700, 1703], [3300, 1703]], speed: 45,
      idle: [{ text: 'パパ、ぜったい離さないでね！', when: [notDone('S2-E44')] }, 'ほんとは、ひとりで乗れる気がするんだ', { text: 'ひとりで乗れたー！', when: [done('S2-E44')] }],
    },
    bikedad: {
      name: 'コハルの父', x: 3440, y: 1650, path: [[3240, 1650], [5640, 1650], [5640, 1710], [3240, 1710]], speed: 45,
      look: { h: 175, hair: 'short', hairColor: '#333', shirt: '#9ac87a', pants: '#4a4a4a', acc: ['glasses'] },
      idle: [
        { text: 'まだ手を離さないぞー！ パパがついてるからなー！', when: [notDone('S2-E44')] },
        { text: 'ひー、ひー……腰が……だれか、パパを走らせてくれ……', when: [notDone('S2-E44')] },
        { text: 'はあはあ……コハルが、ひとりで……！', when: [done('S2-E44')] },
      ],
    },
    // ── 東エリア ──
    choro: {
      name: 'チョロ吉', x: 4680, y: 791, wander: 40, speed: 60,
      look: { h: 115, hair: 'spiky', hairColor: '#3a2a1a', shirt: '#e8e84a', pants: '#3a6ab0', kid: true },
      idle: [
        { text: 'ガチャガチャ、まわしたい！', when: [notDone('S2-E45')] },
        { text: 'おこづかい、もうないんだよなあ……だれかくれないかな', when: [notDone('S2-E45')] },
        { text: 'たすけて〜！ 下を見るとこわい〜！', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
        { text: 'お母さ〜ん！ それか、大きくて力もちの人〜！', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
        { text: 'もう木には登らない……たぶん', when: [anyDone('S2-E46', 'S2-E47')] },
      ],
    },
    tsubomi: {
      name: '花屋のツボミ', x: 4990, y: 788, wander: 60, speed: 30,
      look: { h: 166, hair: 'long', hairColor: '#7a4a2a', shirt: '#f6f6e0', pants: '#7aa86a', skirt: true, acc: ['apron', 'flower'] },
      idle: [
        { text: '今日は日ざしが強いわね……', when: [notDone('S2-E25')] },
        { text: 'お店の前の子、元気がないの……', when: [notDone('S2-E25')] },
        'いらっしゃいませ〜',
      ],
    },
    takumi: {
      name: 'タクミ', x: 4600, y: 930, path: [[4200, 900], [5400, 938]], speed: 38,
      look: { h: 172, hair: 'short', hairColor: '#5a3a1a', shirt: '#e8e8f8', pants: '#3a3a5a', acc: ['tie'] },
      idle: [
        { text: 'あの子に、なにか贈りたいんだけど……', when: [notDone('S2-E26')] },
        { text: '言葉じゃなくて、形にできたらなあ', when: [notDone('S2-E26')] },
        '気持ちを伝えるって、むずかしいな',
        { text: 'いててて……顔がぱんぱんだ……', when: [done('S2-E26')] },
      ],
    },
    hayate: {
      name: 'ハヤテ', x: 1200, y: 938, path: [[60, 930], [3000, 953], [5900, 930], [5900, 1665], [3000, 1688], [60, 1665]], speed: 95,
      look: { h: 172, hair: 'short', hairColor: '#222', shirt: '#f84', pants: '#222', acc: ['headphones'] },
      idle: [
        { text: 'ハッ、ハッ……のどが、からからだ……', when: [notDone('S2-E48'), notDone('S2-E49')] },
        'もっと速く走りたいんだ！',
        { text: 'うるおった！ あとは足もとをなんとかしたいな', when: [anyDone('S2-E48', 'S2-E49'), notDone('S2-E50'), notDone('S2-E51')] },
        { text: 'シューズがすりへっちゃってさ', when: [notDone('S2-E50'), notDone('S2-E51')] },
      ],
    },
    gin: {
      name: 'ギン', x: 5320, y: 1560, wander: 80, speed: 40,
      look: { h: 175, hair: 'mohawk', hairColor: '#e0389a', shirt: '#111', pants: '#222', acc: ['earring', 'sunglasses'] },
      idle: ['ロックは魂だぜ', 'オレの髪型、イカしてるだろ？', '今夜のライブ、客が来るといいんだが'],
    },
    peddler: {
      name: '行商のおばあさん', x: 3600, y: 1740, path: [[2400, 1740], [5200, 1755]], speed: 22,
      look: { h: 150, hair: 'bun', hairColor: '#eee', shirt: '#6a7a5a', pants: '#4a4a3a', acc: ['scarf'], old: true },
      idle: ['だいこーん、だいこんはいらんかね〜', '畑でとれたての野菜だよ', '重たいねえ、だれか買っとくれ'],
    },
    magobe: {
      name: '観光客のマゴベエ', x: 5100, y: 1658, wander: 70, speed: 35,
      look: { h: 165, hair: 'short', hairColor: '#999', shirt: '#f6e86a', pants: '#a87a4a', acc: ['camera', 'cap'], old: true },
      idle: [
        { text: '地図がさかさまだ……ここ、どこだろう', when: [notDone('S2-E58')] },
        { text: 'こういうときは、だれに聞けばいいんだっけ', when: [notDone('S2-E58')] },
        '伝説のコロッケ、ひと口でいいから食べたいなあ',
        { text: '道はわかった。……でも、ほんとにこっちで運が開けるのかな', when: [done('S2-E58'), notDone('S2-E59')] },
      ],
    },
    hoshimi: {
      name: '銭湯の娘ホシミ', x: 5300, y: 791, wander: 50, speed: 30,
      look: { h: 166, hair: 'pony', hairColor: '#2a1a12', shirt: '#f6f0e6', pants: '#2b4a8a', acc: ['apron'] },
      idle: [
        { text: 'お母さんの形見のイヤリング……なくしちゃった', when: [notDone('S2-E63')] },
        { text: '朝、喫茶店でモーニングを食べて……そのあとは、どこを通ったっけ', when: [notDone('S2-E63')] },
        { text: '星のかたちの、小さいのなの。キラッて光るんだ', when: [notDone('S2-E63')] },
        { text: 'よーし！ 今日はとびきり熱いお風呂、わかすよ！', when: [done('S2-E63')] },
      ],
    },
    gonji: {
      name: '釜焚きのゴン爺', x: 5945, y: 769, wander: 0,
      look: { h: 155, hair: 'bald', hairColor: '#ddd', shirt: '#5a4a3a', pants: '#3a3a2a', acc: ['scarf', 'beard'], old: true, sit: true },
      idle: [
        { text: 'お嬢がしょげとると、釜の火も元気が出ん', when: [notDone('S2-E63')] },
        'マッチを切らしてしもうた……どこかにないかのう',
        '昔はのう、この煙突から火柱が上がったもんじゃ',
        { text: 'お嬢が笑うた。じゃが、今日の湯は大物の客が来んと焚きがいがないのう', when: [done('S2-E63'), notDone('S2-E64')] },
        { text: '湯船に横綱級の客が来とる……血がたぎるわい！ 火種はまだか！', when: [done('S2-E63'), done('S2-E64')] },
      ],
    },
  },
  objects: {
    // 北の並び・西（美容院・理容・喫茶・電器）
    salonSign: { name: '美容院の看板', sign: { text: 'ヘアサロン ふわり', fill: '#c76b8a', color: '#fff', s: 26 }, w: 290, h: 62, x: 200, y: 510 },
    hairPoster: { name: '髪型ポスター', sign: { text: '今月の おすすめ アフロ', fill: '#fff6d0', color: '#a33', s: 18 }, w: 90, h: 118, x: 98, y: 712 },
    chonmageSign: { name: '時代劇ポスター', sign: { text: 'まげ侍 参上', fill: '#2a1a12', color: '#f4d35e', s: 18 }, w: 90, h: 118, x: 598, y: 712 },
    match: { name: 'マッチ箱', sign: { text: 'MATCH', fill: '#c0392b', color: '#fff', s: 11 }, w: 44, h: 28, x: 905, y: 733, z: 772, minZoom: 1.2 },
    earring: { name: '星のイヤリング', emoji: '⭐', size: 22, x: 770, y: 848, minZoom: 1.6, rot: 0.4 },
    elecSign: { name: '電器店の看板', sign: { text: '⚡ 明るい未来の デンキのイナズマ', fill: '#f4d35e', color: '#2a4a8a', s: 22 }, w: 400, h: 66, x: 1190, y: 518 },
    tv: { name: '店頭のテレビ', sign: { text: 'プロ野球 まもなく中継', fill: '#222', color: '#fff', s: 16 }, w: 150, h: 100, x: 1075, y: 712 },
    vision: { name: '街頭ビジョン', sign: { text: '🌊 ワカメで フサフサ♪', fill: '#1d6b8a', color: '#fff', s: 16 }, w: 190, h: 112, x: 1300, y: 266 },
    // 薬局・歯科・本屋
    pharmSign: { name: '薬局の看板', sign: { text: 'まちの薬局 プロテイン特売中', fill: '#2e8a5a', color: '#fff', s: 20 }, w: 300, h: 66, x: 1580, y: 510 },
    goodMed: { name: 'ビタミン剤のポスター', sign: { text: '元気百倍 ビタミンZ', fill: '#e8ffd8', color: '#2a7a2a', s: 16 }, w: 90, h: 110, x: 1472, y: 712 },
    badMed: { name: 'あやしい薬の屋台', sign: { text: '毛がはえる？ 謎の薬 ¥100', fill: '#5a2a6a', color: '#f4d35e', s: 14 }, w: 120, h: 80, x: 1770, y: 799 },
    dentistPoster: { name: '歯医者のポスター', sign: { text: '🦷 ムシ歯は こわいぞ', fill: '#fff', color: '#2a5a8a', s: 16 }, w: 88, h: 100, x: 1806, y: 710 },
    photobook: { name: 'アイドル写真集', emoji: '📕', size: 40, x: 2300, y: 737, z: 772 },
    // 中の並び（魚屋・肉屋・食べもの）
    fishSign: { name: '魚屋の看板', sign: { text: '鮮魚 しおかぜ', fill: '#1d5b8a', color: '#fff', s: 26 }, w: 340, h: 66, x: 1980, y: 1287 },
    tankFish: { name: '水槽の魚', emoji: '🐠', size: 34, x: 1836, y: 1433 },
    fish: { name: '店先のサンマ', emoji: '🐟', size: 40, x: 1950, y: 1465, z: 1488 },
    crab: { name: 'カニ', emoji: '🦀', size: 36, x: 2040, y: 1467, z: 1488, minZoom: 1.1 },
    octopus: { name: 'タコ', emoji: '🐙', size: 40, x: 2115, y: 1465, z: 1488 },
    meatSign: { name: '肉屋の看板', sign: { text: '精肉 にくまる コロッケあり', fill: '#a33', color: '#fff', s: 20 }, w: 260, h: 66, x: 2355, y: 1287 },
    burgerSign: { name: 'ハンバーガー店の看板', sign: { text: '🍔 BIG BURGER', fill: '#e2702a', color: '#fff', s: 26 }, w: 300, h: 66, x: 2680, y: 1287 },
    currySign: { name: 'カレー屋の看板', sign: { text: '激辛カレー 地獄', fill: '#8a1a0a', color: '#ffd84a', s: 22 }, w: 240, h: 62, x: 2995, y: 1287 },
    // 公園
    jungleGym: { name: 'ジャングルジム', sign: { text: '', fill: 'rgba(255,255,255,0.05)', color: '#fff', s: 10 }, w: 170, h: 190, x: 2760, y: 680 },
    bench1: { name: 'ベンチ（使用中）', prop: 'bench', propOpts: { color: '#b77a3e' }, size: 95, w: 175, h: 86, x: 3060, y: 680 },
    clock: { name: '公園の時計', emoji: '🕒', size: 56, x: 3265, y: 488 },
    fountain: { name: '水飲み場', emoji: '🚰', size: 46, x: 3400, y: 698 },
    bench2: { name: 'ベンチ', prop: 'bench', propOpts: { color: '#b77a3e' }, size: 95, w: 175, h: 86, x: 3560, y: 680 },
    rccar: { name: 'ラジコンカー', emoji: '🏎️', size: 42, x: 4700, y: 773 },
    // 北の並び・東
    tanSign: { name: '日焼けサロンの看板', sign: { text: '日焼けサロン こんがり', fill: '#c8641a', color: '#fff', s: 22 }, w: 270, h: 62, x: 4270, y: 510 },
    babyDoll: { name: '赤ちゃん人形', emoji: '👶', size: 40, x: 4520, y: 702 },
    flowerSign: { name: '花屋の看板', sign: { text: '花のアトリエ', fill: '#4a9a5a', color: '#fff', s: 24 }, w: 230, h: 60, x: 4940, y: 516 },
    wiltedFlower: { name: 'しおれた花', emoji: '🥀', size: 40, x: 4880, y: 758 },
    sentoSign: { name: '銭湯の看板', sign: { text: '♨ さくら湯', fill: '#2b4a8a', color: '#fff', s: 30 }, w: 280, h: 80, x: 5400, y: 354 },
    noren: { name: '銭湯ののれん', sign: { text: 'ゆ', fill: '#2b4a8a', color: '#fff', s: 50 }, w: 160, h: 110, x: 5400, y: 722 },
    chimneyTop: { name: '銭湯の煙突', sign: { text: 'ゆ', fill: '#8b4a3a', color: '#fff', s: 34 }, w: 64, h: 110, x: 5760, y: 180 },
    // 中の並び（スポーツ店・八百屋・交番）
    skates: { name: 'ローラースケート', emoji: '🛼', size: 44, x: 1160, y: 1517 },
    ironGeta: { name: '鉄下駄', emoji: '🩴', size: 40, x: 1300, y: 1517, minZoom: 1.1 },
    vending: { name: '自販機', prop: 'vending', propOpts: { color: '#d33' }, size: 140, w: 84, h: 140, x: 1420, y: 1496 },
    apple: { name: 'リンゴ', emoji: '🍎', size: 40, x: 3850, y: 1467, z: 1490 },
    kakiPoster: { name: '柿のポスター', sign: { text: '🟠 甘い柿 入荷', fill: '#fff6e0', color: '#c8641a', s: 16 }, w: 150, h: 60, x: 4200, y: 1405 },
    koban: { name: '交番', sign: { text: '交番', fill: '#fff', color: '#2a3a6a', s: 28 }, w: 160, h: 64, x: 4430, y: 1293 },
    pawn: { name: '質屋の看板', sign: { text: '質 かめや', fill: '#fff', color: '#222', s: 26 }, w: 200, h: 66, x: 925, y: 1287 },
    // イベントのない、撮れる物（ダミー）
    umbrella: { name: '置き傘', emoji: '🌂', size: 40, x: 368, y: 769 },
    mailbox: { name: 'ポスト', emoji: '📮', size: 56, x: 2016, y: 773 },
    cone: { name: 'カラーコーン', emoji: '🚧', size: 46, x: 3140, y: 1703 },
    trash: { name: 'ごみ箱', emoji: '🗑️', size: 44, x: 2410, y: 774 },
    newspaper: { name: '新聞', emoji: '📰', size: 30, x: 3135, y: 715, minZoom: 1.2 },
    balloon: { name: '風船', emoji: '🎈', size: 40, x: 4790, y: 620 },
    bicycle: { name: '止めてある自転車', emoji: '🚲', size: 60, x: 5060, y: 776 },
    bucket: { name: '風呂おけ', emoji: '🪣', size: 34, x: 5520, y: 737 },
    // イベントで出てくる物
    toupee: { name: 'かつら', emoji: '🦱', size: 34, x: 670, y: 945, hidden: true },
    propeller: { name: '竹とんぼ', emoji: '🪁', size: 34, x: 3930, y: 350, hidden: true },
    bee: { name: 'ハチ', emoji: '🐝', size: 28, x: 4880, y: 735, hidden: true },
    ball: { name: '野球ボール', emoji: '⚾', size: 30, x: 3060, y: 440, hidden: true },
    pawnBag: { name: '質流れのバッグ', emoji: '👜', size: 36, x: 870, y: 1465, hidden: true },
    pawnNecklace: { name: '質流れのネックレス', emoji: '📿', size: 32, x: 985, y: 1465, hidden: true },
  },
  paths: {
    rcLoop: { points: [[4500, 840], [4100, 953], [3700, 840], [3400, 953], [3900, 998], [4300, 915], [4700, 773]], speed: 220, loop: false },
    dogChase: { points: [[4480, 848], [4080, 960], [3690, 848], [3410, 960], [3880, 1005], [4280, 923], [3600, 840]], speed: 200, loop: false },
    jog: { points: [[60, 930], [3000, 953], [5900, 930], [5900, 1665], [3000, 1688], [60, 1665]], speed: 95, loop: true },
  },
  reactions: [
    { s: 'match', t: 'gonji', say: 'お嬢があの調子じゃ、釜を焚く気になれんわい', when: [notDone('S2-E63')], anim: 'react.sad' },
    { s: 'match', t: 'gonji', say: '火種はある。じゃが、こんな日は大物の客が来てからじゃ', when: [done('S2-E63'), notDone('S2-E64')], anim: 'react.think' },
    { s: 'salonSign', t: 'teruo', say: 'わしには関係ない店じゃ……（帽子……いや、頭をおさえている）', anim: 'react.shrug' },
    { s: 'fish', t: 'fishman', say: 'それは売りもんだよ！', anim: 'react.angry' },
    { s: 'photobook', t: 'nobu', say: 'ぼ、ぼくはそういうのは……', anim: 'react.embarrassed' },
    { s: 'earring', t: 'kirari', say: 'かわいい〜。でも、あたしのじゃないな', anim: 'react.shrug' },
    { s: 'noren', t: 'hoshimi', say: 'うちのお風呂、今日はなんだか元気ないの', when: [notDone('S2-E63')], anim: 'react.sad' },
    { s: 'clock', t: 'batter', say: 'ナイターまで、まだまだだなあ', anim: 'react.shrug' },
  ],
  timeline: [
    { every: 60000, start: 40000, effects: [{ type: 'PLAY_SOUND', soundId: 'bell' }, { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'タイムセールだよー！ 安いよ安いよー！' }] },
    { at: 150000, effects: [{ type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'そろそろ釜の時間じゃが……' }] },
    { at: 240000, effects: [{ type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'もうすぐ夕方……お風呂、わかさなきゃ' }] },
  ],
  exclusiveGroups: [],
  events: [
    // ── ミツルの髪型（E01〜E07）・テルオ（E08〜E09） ──
    { id: 'S2-E01', s: 'salonSign', t: 'mitsuru', cat: 'CHAIN', title: 'ミツル、髪型の多さに目を回す', say: '髪型って、こんなに種類が……め、目が回る〜', anim: 'react.spin', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'teruo', to: [640, 930], speed: 200, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [600, 923], speed: 120, delayMs: 300 },
        { type: 'FX', kind: 'stars', at: 'teruo', delayMs: 2600 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { hair: 'bald' }, delayMs: 2700 },
        { type: 'SPAWN_OBJECT', objectId: 'toupee', delayMs: 2700 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'ああっ！ わしの……わしの毛が！', delayMs: 3000 },
        { type: 'ACTOR_SET_STATE', actorId: 'teruo', state: 'EMBARRASSED', delayMs: 3000 },
        { type: 'ACTOR_MOVE', actorId: 'teruo', to: [900, 930], speed: 50, wander: 120, delayMs: 7000 },
      ],
      after: [{ actor: 'teruo', text: 'みんな見とる……ええい、いっそ明るく開き直るか、海藻にでもすがるか……', delay: 5200 }] },
    { id: 'S2-E02', s: 'hairPoster', t: 'mitsuru', cat: 'BRANCH', group: 'S2-HAIR', title: 'ミツル、アフロになる', say: 'これだ！ 今月のおすすめにしよう！', anim: 'react.happy', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [200, 744], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2200 }, { type: 'FX', kind: 'smoke', x: 200, y: 600, delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'afro', hairColor: '#2b1a10' }, delayMs: 3000 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4600 }, { type: 'FX', kind: 'sparkle', at: 'mitsuru', delayMs: 4700 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'ボリューム満点！ 前が見えないけど！', delayMs: 5000 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [420, 893], speed: 60, wander: 100, delayMs: 6500 },
      ] },
    { id: 'S2-E03', s: 'teruo', t: 'mitsuru', cat: 'BRANCH', group: 'S2-HAIR', requires: ['S2-E08'], blocksIfCompleted: ['S2-E07'], title: 'ミツル、光の坊主頭になる', say: 'そのまぶしさ……ぼくも光りたい！ 全部そってください！', anim: 'react.sparkle', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [510, 746], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2000 }, { type: 'FX', kind: 'smoke', x: 510, y: 600, delayMs: 2400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'bald' }, delayMs: 2800 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4400 }, { type: 'FX', kind: 'flash', at: 'mitsuru', delayMs: 4500 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'おお、同志よ！', delayMs: 5200 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [560, 908], speed: 60, wander: 100, delayMs: 6000 },
      ] },
    { id: 'S2-E04', s: 'chonmageSign', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E07'], title: 'ミツル、ちょんまげになる', say: 'まげ……！ 武士の心意気、いただきます！', anim: 'react.happy', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [510, 746], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2000 }, { type: 'FX', kind: 'smoke', x: 510, y: 600, delayMs: 2400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'topknot', hairColor: '#111' }, delayMs: 2800 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4400 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'でござる！ ……ちょっと首がすーすーする', delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [560, 908], speed: 60, wander: 100, delayMs: 6000 },
      ] },
    { id: 'S2-E05', s: 'gin', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E07'], title: 'ミツル、パンクなトサカ頭に', say: 'うおお、ロックだ！ ぼくもあのトサカにする！', anim: 'react.transform', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'mohawk', hairColor: '#e0389a', acc: ['earring'] } },
        { type: 'PLAY_SOUND', soundId: 'roar', delayMs: 300 }, { type: 'FX', kind: 'notes', at: 'mitsuru', delayMs: 500 },
        { type: 'ACTOR_SPEECH', actorId: 'gin', text: 'へっ、わかってるじゃねえか', delayMs: 2400 },
      ] },
    { id: 'S2-E06', s: 'yanagi', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E17'], title: 'ミツル、大人の色気ヘアに', say: 'あの人みたいに、しっとり大人っぽく……！', anim: 'react.sparkle', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'long', hairColor: '#2a1a12', acc: ['sunglasses'] } },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: '……ふっ。（かっこつけている）', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'yanagi', text: 'ゴホッ……マネされると、悪い気はしないね', delayMs: 3200 },
      ] },
    { id: 'S2-E07', s: 'babyDoll', t: 'mitsuru', cat: 'FLAVOR', blocksIfCompleted: ['S2-E03', 'S2-E04', 'S2-E05'], title: 'ミツル、赤ちゃんヘアに', say: 'かわいい……！ このちょこんとした感じ、いいかも', anim: 'react.love', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'twin', hairColor: '#d8a860', acc: ['ribbon'] } },
        { type: 'FX', kind: 'hearts', at: 'mitsuru', delayMs: 300 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'え、あれ、かわいくない？', delayMs: 2400 },
      ] },
    { id: 'S2-E08', s: 'elecSign', t: 'teruo', cat: 'CHAIN', group: 'S2-TERUO', requires: ['S2-E01'], title: 'テルオの頭がピカッと光る', say: '「明るい未来」……そうじゃ、わしの頭も明るいんじゃ！', anim: 'react.sparkle', route: 'S2.route.teruo',
      fx: [
        { type: 'FX', kind: 'flash', at: 'teruo', delayMs: 200 }, { type: 'FX', kind: 'sparkle', at: 'teruo', delayMs: 700 },
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { skin: '#ffe9b8' } },
        { type: 'ACTOR_SET_STATE', actorId: 'teruo', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'teruo.shiny', value: true },
        { type: 'FX', kind: 'flash', at: 'teruo', delayMs: 2600 },
      ],
      after: [{ actor: 'mitsuru', text: 'な、なんだあのまぶしい人……かっこいい……', delay: 3600 }] },
    { id: 'S2-E09', s: 'vision', t: 'teruo', cat: 'FLAVOR', group: 'S2-TERUO', requires: ['S2-E01'], title: 'テルオ、ワカメヘアになる', say: 'ワカメ……ワカメ……おお！？ 生えてきた！ うねうねじゃ！', anim: 'react.transform', route: 'S2.route.teruo',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { hair: 'long', hairColor: '#2e5b34' }, delayMs: 400 },
        { type: 'FX', kind: 'bubbles', at: 'teruo', delayMs: 600 }, { type: 'PLAY_SOUND', soundId: 'tv' },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'あの人の髪……磯のかおりがする……', delayMs: 3000 },
      ] },
    // ── 献立（E10〜E12） ──
    { id: 'S2-E10', s: 'fishSign', t: 'harue', cat: 'BRANCH', group: 'S2-DINNER', title: 'ハルエ、今夜は魚の煮つけ', say: '決めた！ 今夜はお魚の煮つけにしましょ', anim: 'react.think', route: 'S2.route.dinner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'harue', to: [1900, 1560], speed: 120, wander: 30 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'へいらっしゃい！ 奥さん、今日のキンメはいいよ！', delayMs: 3000 },
        { type: 'SET_FLAG', id: 'dinner', value: 'fish' },
      ] },
    { id: 'S2-E11', s: 'meatSign', t: 'harue', cat: 'FLAVOR', group: 'S2-DINNER', title: 'ハルエ、揚げものに決める', say: 'コロッケ！ メンチ！ 今夜は揚げものパーティーよ！', anim: 'react.happy', route: 'S2.route.dinner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'harue', to: [2355, 1549], speed: 120, wander: 30 }, { type: 'SET_FLAG', id: 'dinner', value: 'fry' }, { type: 'FX', kind: 'steam', at: 'meatSign', delayMs: 1200 }] },
    { id: 'S2-E12', s: 'burgerSign', t: 'harue', cat: 'FLAVOR', group: 'S2-DINNER', decoy: true, title: 'ハルエ、料理を放棄する', say: '……もう作るのやめた！ 今夜はハンバーガー！', anim: 'react.laugh', route: 'S2.route.dinner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'harue', to: [2680, 1549], speed: 140, wander: 30 }, { type: 'SET_FLAG', id: 'dinner', value: 'burger' }, { type: 'ACTOR_SPEECH', actorId: 'manta', text: 'いいなあ……', delayMs: 3200 }] },
    // ── 魚屋（E13〜E15・E52〜E53） ──
    { id: 'S2-E13', s: 'fishSign', t: 'tsurita', cat: 'FLAVOR', group: 'S2-TSURITA', title: 'ツリタ、釣果を魚屋で買う', say: '釣れないなら……買えばいいじゃないか！', anim: 'react.think', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsurita', to: [1925, 1549], speed: 100, wander: 20 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'まいど！ 「釣りました」って顔して持って帰んな！', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'tsurita', look: { acc: ['hat', 'beard', 'bag'] }, delayMs: 3000 },
        { type: 'ACTOR_SET_STATE', actorId: 'tsurita', state: 'HAPPY', delayMs: 3000 },
      ] },
    { id: 'S2-E14', s: 'tankFish', t: 'tsurita', cat: 'FLAVOR', group: 'S2-TSURITA', title: 'ツリタ、水槽で釣りを始める', say: 'おっ、いい魚影……ここで釣ればボウズ脱出だ！', anim: 'react.happy', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsurita', to: [1840, 1524], speed: 100, wander: 0 },
        { type: 'FX', kind: 'splash', at: 'tankFish', delayMs: 2000 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'お客さん！ それは売りもんでも釣り堀でもないよ！', delayMs: 2600 },
        { type: 'ACTOR_SET_STATE', actorId: 'tsurita', state: 'EMBARRASSED', delayMs: 3600 },
      ] },
    { id: 'S2-E15', s: 'fish', t: 'goma', cat: 'FLAVOR', title: 'ゴマ、サンマをかっさらう', say: 'ニャッ！', anim: 'react.run', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'goma', to: [1960, 1502], speed: 260, wander: 0 },
        { type: 'HIDE_OBJECT', objectId: 'fish', delayMs: 1600 },
        { type: 'ACTOR_MOVE', actorId: 'goma', to: [3450, 640], speed: 300, wander: 140, delayMs: 1700 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'こらーっ！ ドロボウ猫ーっ！', delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'fishman', state: 'ANGRY', delayMs: 2000 },
      ] },
    // ── ヤナギ（E16〜E17） ──
    { id: 'S2-E16', s: 'goodMed', t: 'yanagi', cat: 'BRANCH', group: 'S2-YANAGI', title: 'ヤナギ、ビタミンで血色ばつぐん', say: 'ビタミン……そうか、栄養が足りてなかったんだ！ 力がみなぎる！', anim: 'react.sparkle', route: 'S2.route.yanagi',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'yanagi', look: { skin: '#f6c49a', acc: [] }, delayMs: 300 },
        { type: 'ACTOR_SET_STATE', actorId: 'yanagi', state: 'HAPPY' },
        { type: 'ACTOR_MOVE', actorId: 'yanagi', to: [2150, 945], speed: 180, wander: 200, delayMs: 1800 },
      ] },
    { id: 'S2-E17', s: 'badMed', t: 'yanagi', cat: 'FLAVOR', group: 'S2-YANAGI', decoy: true, title: 'ヤナギ、あやしい薬で髪が抜ける', say: 'もっと髪にツヤを……ゴクッ。……あれ？ 頭がかるい……', anim: 'react.transform', route: 'S2.route.yanagi',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'yanagi', look: { hair: 'bald' }, delayMs: 800 },
        { type: 'FX', kind: 'leaves', at: 'yanagi', delayMs: 800 },
        { type: 'ACTOR_SET_STATE', actorId: 'yanagi', state: 'SAD', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'ようこそ、こちら側へ……', delayMs: 3200 },
      ] },
    // ── 力士・ベンチ・公園（E18〜E24） ──
    { id: 'S2-E18', s: 'bench1', t: 'rikishi', cat: 'FLAVOR', title: '力士、満員のベンチに座りそこねる', say: 'ごっつぁんです、ちょっと失礼……おわっ！', anim: 'react.fall', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3080, 712], speed: 140, wander: 0 },
        { type: 'FX', kind: 'smoke', at: 'rikishi', delayMs: 1800 }, { type: 'PLAY_SOUND', soundId: 'crash', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'grandma', text: 'あらまあ、お相撲さん。ここは満員ですよ', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3150, 863], speed: 40, wander: 140, delayMs: 6000 },
      ],
      after: [{ actor: 'rikishi', text: 'いてて……砂まみれでごわす。ひとっ風呂あびたいでごわす', delay: 4200 }] },
    { id: 'S2-E19', s: 'bench2', t: 'rikishi', cat: 'CHAIN', requires: ['S2-E23'], title: '力士、ベンチをまっぷたつ', say: 'おお、空いてるでごわす！ どっこいしょ……', anim: 'react.fall', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3560, 712], speed: 140, wander: 0 },
        { type: 'OBJECT_SET_STATE', objectId: 'bench2', state: 'BROKEN', delayMs: 2400 },
        { type: 'OBJECT_APPEARANCE', objectId: 'bench2', look: { rot: 0.3 }, delayMs: 2400 },
        { type: 'FX', kind: 'stars', at: 'rikishi', delayMs: 2400 }, { type: 'PLAY_SOUND', soundId: 'crash', delayMs: 2400 },
        { type: 'ACTOR_SPEECH', actorId: 'grandma', text: 'あらあら、ベンチがまっぷたつ', delayMs: 3600 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3400, 863], speed: 40, wander: 140, delayMs: 6000 },
      ],
      after: [{ actor: 'rikishi', text: 'もうしわけないでごわす……汗と砂で、どろどろでごわす', delay: 4600 }] },
    { id: 'S2-E20', s: 'rikishi', t: 'anzu', cat: 'FLAVOR', group: 'S2-ANZU', title: 'アンズ、力士のお腹を見ておやつをがまん', say: 'あのお腹……！ あたし、やっぱりおやつはがまんする！', anim: 'react.surprised', route: 'S2.route.sweets',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'anzu', to: [1900, 1613], speed: 120, wander: 80 }, { type: 'ACTOR_SET_STATE', actorId: 'anzu', state: 'RESOLVED', delayMs: 1500 }] },
    { id: 'S2-E21', s: 'dentistPoster', t: 'anzu', cat: 'FLAVOR', group: 'S2-ANZU', title: 'アンズ、ムシ歯がこわくて和菓子をあきらめる', say: 'ムシ歯……！ ひいっ、今日はやめとく！', anim: 'react.scared', route: 'S2.route.sweets',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'anzu', to: [1300, 1613], speed: 160, wander: 80 }, { type: 'ACTOR_SET_STATE', actorId: 'anzu', state: 'RESOLVED', delayMs: 1500 }] },
    { id: 'S2-E22', s: 'nemuta', t: 'dog', cat: 'BRANCH', group: 'S2-NEMUTA', title: 'ポチ丸、昼寝の係長をほえて起こす', say: 'ワンワンワン！', anim: 'react.angry', route: 'S2.route.park',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [3615, 715], speed: 220, wander: 0 },
        { type: 'PLAY_SOUND', soundId: 'surprise', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'nemuta', text: 'うわっ！ ……な、なんだ犬か。おどかすなよ……', delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'nemuta', state: 'ANGRY', delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [3350, 570], speed: 80, wander: 220, delayMs: 5000 },
      ] },
    { id: 'S2-E23', s: 'clock', t: 'nemuta', cat: 'CHAIN', group: 'S2-NEMUTA', title: '係長、時計を見て飛び起きる', say: 'えっ、もうこんな時間！？ 会議、会議ーっ！', anim: 'react.wake', route: 'S2.route.park',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'nemuta', look: { sit: false } },
        { type: 'ACTOR_MOVE', actorId: 'nemuta', to: [5900, 1680], speed: 280, wander: 60, delayMs: 600 },
        { type: 'SET_FLAG', id: 'bench2.empty', value: true },
        { type: 'FX', kind: 'paper', at: 'nemuta', delayMs: 600 },
      ],
      after: [{ actor: 'grandma', text: 'あら、となりのベンチが空いたわねえ。大きい人でも座れそう', delay: 3200 }] },
    { id: 'S2-E24', s: 'rccar', t: 'dog', cat: 'FLAVOR', title: 'ポチ丸、ラジコンを追いかけまわす', say: 'ワンワン！ ワオーン！', anim: 'react.run', route: 'S2.route.park',
      fx: [
        { type: 'OBJECT_MOVE', objectId: 'rccar', pathId: 'rcLoop' }, { type: 'PLAY_SOUND', soundId: 'vehicle' },
        { type: 'ACTOR_MOVE', actorId: 'dog', pathId: 'dogChase', delayMs: 400 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'あーっ！ お店のラジコンが走ってる！', delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [3350, 570], speed: 80, wander: 220, delayMs: 14000 },
      ] },
    // ── 花屋（E25〜E26） ──
    { id: 'S2-E25', s: 'wiltedFlower', t: 'tsubomi', cat: 'FLAVOR', title: 'ツボミ、しおれた花に水をやる', say: 'あっ、この子しおれてる！ お水、お水！', anim: 'react.happy', route: 'S2.route.flower',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsubomi', to: [4910, 765], speed: 120, wander: 0 },
        { type: 'FX', kind: 'splash', at: 'wiltedFlower', delayMs: 1800 },
        { type: 'OBJECT_APPEARANCE', objectId: 'wiltedFlower', look: { emoji: '🌷' }, delayMs: 2600 },
        { type: 'FX', kind: 'sparkle', at: 'wiltedFlower', delayMs: 2600 },
        { type: 'ACTOR_MOVE', actorId: 'tsubomi', to: [4990, 788], speed: 40, wander: 60, delayMs: 5000 },
      ] },
    { id: 'S2-E26', s: 'flowerSign', t: 'takumi', cat: 'FLAVOR', title: 'タクミ、花束を買ってハチに刺される', say: '花……そうか、花をおくれば気持ちが伝わる！', anim: 'react.happy', route: 'S2.route.flower',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'takumi', to: [4960, 776], speed: 120, wander: 0 },
        { type: 'SPAWN_OBJECT', objectId: 'bee', delayMs: 2600 }, { type: 'OBJECT_MOVE', objectId: 'bee', to: [4960, 660], speed: 80, delayMs: 2700 },
        { type: 'FX', kind: 'stars', at: 'takumi', delayMs: 4000 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 4000 },
        { type: 'ACTOR_SPEECH', actorId: 'takumi', text: 'いてっ！ ハ、ハチ！？', delayMs: 4100 },
        { type: 'ACTOR_APPEARANCE', actorId: 'takumi', look: { skin: '#f4a6a0', wide: true }, delayMs: 4300 },
        { type: 'HIDE_OBJECT', objectId: 'bee', delayMs: 5500 },
        { type: 'ACTOR_SPEECH', actorId: 'tsubomi', text: 'だ、大丈夫ですか！？ 花束、おまけしときますね……', delayMs: 6000 },
        { type: 'ACTOR_MOVE', actorId: 'takumi', to: [4600, 945], speed: 30, wander: 150, delayMs: 8000 },
      ] },
    // ── ノボル（E27〜E29） ──
    { id: 'S2-E27', s: 'jungleGym', t: 'noboru', cat: 'FLAVOR', group: 'S2-CLIMB', title: 'ノボル、ジャングルジムのてっぺんへ', say: 'てっぺん、いっただきー！', anim: 'react.happy', route: 'S2.route.climb',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'noboru', to: [2760, 692], speed: 160, wander: 0 }, { type: 'ACTOR_MOVE', actorId: 'noboru', to: [2760, 494], speed: 70, wander: 0, delayMs: 2600 }, { type: 'FX', kind: 'confetti', at: 'noboru', delayMs: 5600 }] },
    { id: 'S2-E28', s: 'chimneyTop', t: 'noboru', cat: 'FLAVOR', group: 'S2-CLIMB', title: 'ノボル、銭湯の煙突によじ登る', say: 'あの煙突、商店街でいちばん高い！ 行ってくる！', anim: 'react.run', route: 'S2.route.climb',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [5760, 750], speed: 320, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [5760, 76], speed: 90, wander: 0, delayMs: 9000 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'こりゃーっ！ 煙突は遊び場じゃないわい！', delayMs: 10000 },
        { type: 'ACTOR_SPEECH', actorId: 'noboru', text: 'やっほー！ 海まで見えるー！', delayMs: 17000 },
      ] },
    { id: 'S2-E29', s: 'choro', t: 'noboru', cat: 'FLAVOR', requires: ['S2-E45'], blocksIfCompleted: ['S2-E27', 'S2-E28', 'S2-E46', 'S2-E47'], title: 'ノボル、木のぼり救出に失敗', say: 'まかせろ！ 木のぼりならオレが……うわあっ！', anim: 'react.fall', route: 'S2.route.climb',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [3860, 769], speed: 200, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [3860, 440], speed: 80, wander: 0, delayMs: 4500 },
        { type: 'FX', kind: 'leaves', at: 'noboru', delayMs: 8500 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [3850, 774], speed: 400, wander: 60, delayMs: 8600 },
        { type: 'FX', kind: 'stars', at: 'noboru', delayMs: 9600 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'ノボルにいちゃーん！ ……オレ、まだ降りられないよー！', delayMs: 10200 },
      ] },
    // ── マンタ（E30〜E31） ──
    { id: 'S2-E30', s: 'currySign', t: 'manta', cat: 'FLAVOR', title: 'マンタ、激辛カレーに挑んで火をふく', say: '辛いのダメだけど……挑戦する！ ……かっらーーーっ！！', anim: 'react.fire', route: 'S2.route.hungry',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [2995, 1541], speed: 100, wander: 0 },
        { type: 'FX', kind: 'fire', at: 'manta', delayMs: 1800 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { skin: '#e8645a' }, delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'あの人、口から火が出てる……', delayMs: 3200 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { skin: '#f2c9a0' }, delayMs: 9000 },
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [2850, 1605], speed: 40, wander: 200, delayMs: 9000 },
      ] },
    { id: 'S2-E31', s: 'burgerSign', t: 'manta', cat: 'FLAVOR', title: 'マンタ、ハンバーガーを十個たいらげる', say: 'ハンバーガー……おなかが、グゥ〜〜〜', anim: 'react.eat', route: 'S2.route.hungry',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [2680, 1541], speed: 100, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'manta', text: 'もぐもぐ……あと九個……', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { h: 182 }, delayMs: 4200 }, { type: 'FX', kind: 'big', at: 'manta', delayMs: 4200 },
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [2850, 1605], speed: 25, wander: 200, delayMs: 6000 },
      ] },
    // ── 本屋の三人（E32〜E35） ──
    { id: 'S2-E32', s: 'photobook', t: 'gou', cat: 'CHAIN', title: 'ツッパリ二人組、ノブを押しのける', say: 'おっ、アイドルの写真集じゃねーか！ どけどけ！', anim: 'react.love', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [2250, 788], speed: 160, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [2335, 804], speed: 160, wander: 0, delayMs: 300 },
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [2470, 893], speed: 220, wander: 20, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'nobu', text: 'わっ！ ……ぼくが先に見てたのに……', delayMs: 2200 },
        { type: 'ACTOR_SET_STATE', actorId: 'nobu', state: 'SAD', delayMs: 2200 },
      ],
      after: [{ actor: 'nobu', text: 'ぼくにも、もっと力があれば……', delay: 5000 }] },
    { id: 'S2-E33', s: 'pharmSign', t: 'nobu', cat: 'CHAIN', requires: ['S2-E32'], title: 'ノブ、プロテインでムキムキに', say: 'プロテイン……？ よし、ぼくだって！ ……ゴクゴク……うおおお！', anim: 'react.transform', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'nobu', look: { muscle: true, wide: true, h: 186 }, delayMs: 800 },
        { type: 'FX', kind: 'big', at: 'nobu', delayMs: 800 }, { type: 'PLAY_SOUND', soundId: 'roar', delayMs: 800 },
        { type: 'ACTOR_SET_STATE', actorId: 'nobu', state: 'HAPPY', delayMs: 1500 },
      ],
      after: [{ actor: 'nobu', text: 'みなぎる……！ さっきの二人に、ひとこと言ってやる', delay: 3400 }] },
    { id: 'S2-E34', s: 'gou', t: 'nobu', cat: 'CHAIN', requires: ['S2-E33'], title: 'ムキムキのノブ、仕返しを始める', say: 'さっきは、よくも押してくれたね……！', anim: 'react.angry', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [2330, 803], speed: 180, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'gou', text: 'ひいっ！ なんだそのムキムキ！', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [2130, 812], speed: 260, wander: 0, delayMs: 2200 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [2185, 834], speed: 260, wander: 0, delayMs: 2300 },
        { type: 'ACTOR_SET_STATE', actorId: 'gou', state: 'SCARED', delayMs: 2200 },
      ],
      after: [{ actor: 'gou', text: 'て、店主さーん！ こいつ、なんとかしてくれー！', delay: 3800 }] },
    { id: 'S2-E35', s: 'gou', t: 'bookman', cat: 'PROGRESSION', requires: ['S2-E34'], title: '店主のカミナリ、三人そろって出入り禁止', say: 'こらっ！ 店の前でケンカするんじゃない！ 全員、立ち読み禁止！', anim: 'react.angry', route: 'S2.route.book',
      fx: [
        { type: 'PLAY_SOUND', soundId: 'thunder' }, { type: 'FX', kind: 'lightning', at: 'bookman', delayMs: 200 },
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [250, 975], speed: 240, wander: 80, delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [335, 990], speed: 240, wander: 80, delayMs: 1900 },
        { type: 'ACTOR_SPEECH', actorId: 'nobu', text: 'ぼ、ぼくまで……！？', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [1500, 953], speed: 80, wander: 100, delayMs: 3200 },
      ] },
    // ── 草野球とミノリ（E36〜E44） ──
    { id: 'S2-E36', s: 'batter', t: 'sora', cat: 'CHAIN', group: 'S2-BAT', requires: ['S2-E38'], title: 'ソラの球をイワオが特大ホームラン', say: 'いくよー！ えいっ！', anim: 'react.happy', route: 'S2.route.baseball',
      fx: [
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'カッキーン！！', delayMs: 900 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 900 },
        { type: 'SPAWN_OBJECT', objectId: 'ball', delayMs: 1000 }, { type: 'FX', kind: 'stars', at: 'batter', delayMs: 1000 },
        { type: 'OBJECT_MOVE', objectId: 'ball', to: [3980, 1624], speed: 260, delayMs: 1100 },
        { type: 'ACTOR_SPEECH', actorId: 'sora', text: 'あーっ、ボールがあっちに転がってく！', delayMs: 2600 },
      ],
      after: [{ actor: 'minori', text: 'あ、ボールが転がってきた……', delay: 4200 }] },
    { id: 'S2-E37', s: 'batter', t: 'umi', cat: 'FLAVOR', group: 'S2-BAT', requires: ['S2-E38'], title: 'ウミのすっぽ抜けボール', say: 'それっ！ ……あっ、すっぽぬけた！', anim: 'react.embarrassed', route: 'S2.route.baseball',
      fx: [
        { type: 'FX', kind: 'stars', at: 'batter', delayMs: 900 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 900 },
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'いてっ！ デッドボール……今日はもう引退だ……', delayMs: 1400 },
        { type: 'ACTOR_SET_STATE', actorId: 'batter', state: 'SAD', delayMs: 1400 },
      ] },
    { id: 'S2-E38', s: 'tv', t: 'batter', cat: 'CHAIN', title: 'イワオ、中継を見て野球魂に火がつく', say: 'プレイボール……！ 血がさわぐ！ 公園で素振りだ！', anim: 'react.surprised', route: 'S2.route.baseball',
      fx: [
        { type: 'OBJECT_APPEARANCE', objectId: 'tv', look: { sign: { text: '⚾ プレイボール！', fill: '#2b6b3a', color: '#fff', s: 18 } } },
        { type: 'PLAY_SOUND', soundId: 'tv' },
        { type: 'ACTOR_MOVE', actorId: 'batter', to: [3060, 445], speed: 240, wander: 30, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'ブン！ ブン！ だれか投げてくれー！', delayMs: 15000 },
      ] },
    { id: 'S2-E39', s: 'ball', t: 'minori', cat: 'BRANCH', group: 'S2-DOG', requires: ['S2-E36'], title: 'ミノリ、ボールを投げてブルドッグを遠ざける', say: 'このボールを……えいっ！ ほら、取ってこーい！', anim: 'react.happy', route: 'S2.route.minori',
      fx: [
        { type: 'OBJECT_MOVE', objectId: 'ball', to: [3300, 1669], speed: 320 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [3335, 1676], speed: 200, wander: 90, delayMs: 300 },
        { type: 'HIDE_OBJECT', objectId: 'ball', delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'minori', to: [3980, 1605], speed: 80, wander: 40, delayMs: 2000 },
        { type: 'SET_FLAG', id: 'bulldog.away', value: 'ball' },
      ],
      after: [{ actor: 'minori', text: 'これでお店に行ける！ ……えっと、なに買うんだっけ', delay: 4200 }] },
    { id: 'S2-E40', s: 'koban', t: 'minori', cat: 'BRANCH', group: 'S2-DOG', title: 'ミノリ、交番に相談する', say: 'おまわりさんに、相談してみよう……', anim: 'react.think', route: 'S2.route.police',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4150, 1579], speed: 160, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'police', text: 'こらこら、ドン。おうちに帰ろうな', delayMs: 2800 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [5960, 1740], speed: 70, wander: 0, delayMs: 3600 },
        { type: 'ACTOR_HIDE', actorId: 'bulldog', delayMs: 40000 },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4430, 1560], speed: 60, wander: 40, delayMs: 5200 },
        { type: 'SET_FLAG', id: 'bulldog.away', value: 'police' },
      ],
      after: [{ actor: 'minori', text: 'ありがとう！ ……えっと、なに買うんだっけ', delay: 5600 }] },
    { id: 'S2-E41', s: 'apple', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、リンゴを買う', say: 'そうだ、リンゴ！ 赤くてツヤツヤのやつ！', anim: 'react.happy', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'minori', to: [3860, 1549], speed: 100, wander: 30 }, { type: 'HIDE_OBJECT', objectId: 'apple', delayMs: 2400 }, { type: 'ACTOR_SET_STATE', actorId: 'minori', state: 'HAPPY', delayMs: 2400 }] },
    { id: 'S2-E42', s: 'kakiPoster', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、柿を買う', say: '柿！ おばあちゃんの好物だった気がする！', anim: 'react.think', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'minori', to: [4200, 1549], speed: 100, wander: 30 }, { type: 'ACTOR_SET_STATE', actorId: 'minori', state: 'HAPPY', delayMs: 2400 }] },
    { id: 'S2-E43', s: 'peddler', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、行商の大根を買う', say: 'わあ、大根！ ……おつかいって、大根だった気がする！', anim: 'react.surprised', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_SPEECH', actorId: 'peddler', text: 'まいどあり。重たいから気をつけてね〜', delayMs: 1600 }, { type: 'ACTOR_APPEARANCE', actorId: 'minori', look: { acc: ['bag', 'scarf'] }, delayMs: 2000 }] },
    { id: 'S2-E44', s: 'bikedad', t: 'bulldog', cat: 'PROGRESSION', requires: ['S2-E39'], title: 'ドンがパパを追いかけ、コハルはひとりで走り出す', say: 'ガウッ！ ガウガウッ！', anim: 'react.run', route: 'S2.route.minori',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'bikedad', to: [5500, 1665], speed: 260, wander: 40, delayMs: 300 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [5420, 1680], speed: 240, wander: 60, delayMs: 600 },
        { type: 'ACTOR_SPEECH', actorId: 'bikedad', text: 'うわああ、こっち来るなーっ！', delayMs: 1000 },
        { type: 'ACTOR_SPEECH', actorId: 'bikegirl', text: 'パパ？ ……あれ、あたし、ひとりで走れてる！', delayMs: 2600 },
        { type: 'FX', kind: 'confetti', at: 'bikegirl', delayMs: 2800 }, { type: 'PLAY_SOUND', soundId: 'fanfare', delayMs: 2800 },
        { type: 'ACTOR_SET_STATE', actorId: 'bikegirl', state: 'HAPPY', delayMs: 2800 },
      ] },
    // ── チョロ吉と木（E45〜E47） ──
    { id: 'S2-E45', s: 'choro', t: 'mama', cat: 'CHAIN', title: 'チョロ吉、ガチャの竹とんぼで木に登る', say: 'もう、しょうがないわね。はい百円。一回だけよ', anim: 'react.think', route: 'S2.route.kid',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mama', to: [4650, 806], speed: 260, wander: 60 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [4790, 774], speed: 100, wander: 0, delayMs: 800 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'やった！ 竹とんぼ出た！ とばすぞー！', delayMs: 2400 },
        { type: 'SPAWN_OBJECT', objectId: 'propeller', delayMs: 3800 }, { type: 'FX', kind: 'leaves', x: 3900, y: 330, delayMs: 3900 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [3880, 769], speed: 240, wander: 0, delayMs: 3600 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'あっ、木に引っかかった！ 取ってくる！', delayMs: 6600 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [3880, 420], speed: 80, wander: 0, delayMs: 7400 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'と、取れた……けど、降りられない〜！', delayMs: 13000 },
        { type: 'ACTOR_SET_STATE', actorId: 'choro', state: 'SCARED', delayMs: 13000 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: true },
      ],
      after: [{ actor: 'mama', text: 'あら？ チョロ吉ったら、またどこかに……', delay: 9000 }] },
    { id: 'S2-E46', s: 'choro', t: 'mama', cat: 'PROGRESSION', group: 'S2-RESCUE', requires: ['S2-E45'], title: '母、肩車でチョロ吉を救出', say: 'チョロ吉！ ほら、お母さんの肩に足をかけて！', anim: 'react.angry', route: 'S2.route.kid',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mama', to: [3850, 774], speed: 240, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [3905, 779], speed: 110, wander: 40, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'ごめんなさーい……', delayMs: 7000 },
        { type: 'ACTOR_SET_STATE', actorId: 'choro', state: 'EMBARRASSED', delayMs: 7000 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: false, delayMs: 7000 },
        { type: 'HIDE_OBJECT', objectId: 'propeller', delayMs: 7000 },
      ] },
    { id: 'S2-E47', s: 'choro', t: 'rikishi', cat: 'PROGRESSION', group: 'S2-RESCUE', requires: ['S2-E45'], title: '力士の張り手で木をゆらし、チョロ吉をキャッチ', say: 'まかせるでごわす！ どすこーいっ！', anim: 'react.hit', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3840, 776], speed: 220, wander: 0 },
        { type: 'FX', kind: 'leaves', x: 3880, y: 350, delayMs: 3200 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 3200 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [3925, 780], speed: 500, wander: 40, delayMs: 3500 },
        { type: 'HIDE_OBJECT', objectId: 'propeller', delayMs: 3500 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'うわーい！ お相撲さん、ナイスキャッチ！', delayMs: 4800 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: false, delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [3700, 863], speed: 40, wander: 140, delayMs: 7000 },
      ],
      after: [{ actor: 'rikishi', text: 'ふう、汗だくでごわす。大きな湯船が恋しいでごわすなあ', delay: 6200 }] },
    // ── ハヤテ（E48〜E51） ──
    { id: 'S2-E48', s: 'fountain', t: 'hayate', cat: 'FLAVOR', group: 'S2-DRINK', title: 'ハヤテ、水飲み場でひと息', say: 'ぷはーっ！ やっぱり水がいちばん！', anim: 'react.drink', route: 'S2.route.runner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'hayate', to: [3400, 729], speed: 220, wander: 0 }, { type: 'FX', kind: 'splash', at: 'fountain', delayMs: 2400 }, { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', delayMs: 6000 }] },
    { id: 'S2-E49', s: 'vending', t: 'hayate', cat: 'FLAVOR', group: 'S2-DRINK', title: 'ハヤテ、スポーツドリンクを一気飲み', say: 'スポーツドリンク！ しみわたる〜！', anim: 'react.drink', route: 'S2.route.runner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'hayate', to: [1420, 1545], speed: 220, wander: 0 }, { type: 'PLAY_SOUND', soundId: 'pop', delayMs: 2000 }, { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', delayMs: 6000 }] },
    { id: 'S2-E50', s: 'skates', t: 'hayate', cat: 'BRANCH', group: 'S2-GEAR', requires: ['S2-E48'], title: 'ハヤテ、ローラースケートで爆走', say: 'ローラースケート！ これで速さ倍増だ！', anim: 'react.run', route: 'S2.route.runner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'hayate', to: [1150, 1553], speed: 220, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'hayate', look: { acc: ['headphones', 'helmet'] }, delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', speed: 300, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'ひゃっほーう！ 止まらなーい！', delayMs: 5000 },
      ] },
    { id: 'S2-E51', s: 'ironGeta', t: 'hayate', cat: 'BRANCH', group: 'S2-GEAR', cond: [anyDone('S2-E48', 'S2-E49')], title: 'ハヤテ、鉄下駄で修行を始める', say: '鉄下駄……！ 足腰をきたえるなら、これだ！', anim: 'react.think', route: 'S2.route.runner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'hayate', to: [1310, 1553], speed: 220, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'hayate', look: { muscle: true }, delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', speed: 22, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'ガッシャン……ガッシャン……お、重い……！', delayMs: 4500 },
      ] },
    // ── ガク（E52〜E54） ──
    { id: 'S2-E52', s: 'crab', t: 'gaku', cat: 'FLAVOR', blocksIfCompleted: ['S2-E53'], title: 'ガク、カニにはさまれる', say: 'カニだ！ ……いってええええ！ はさまれたー！', anim: 'react.hit', route: 'S2.route.ink',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'gaku', to: [2040, 1517], speed: 160, wander: 0 }, { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'だから、さわるなって言ったろ〜', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'gaku', to: [2200, 1605], speed: 60, wander: 70, delayMs: 5000 }] },
    { id: 'S2-E53', s: 'octopus', t: 'gaku', cat: 'CHAIN', title: 'ガク、タコ墨でまっくろ', say: 'タコだ〜！ つんつん……ぶわっ！？', anim: 'react.surprised', route: 'S2.route.ink',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [2120, 1517], speed: 160, wander: 0 },
        { type: 'FX', kind: 'ink', at: 'gaku', delayMs: 1600 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 1600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'gaku', look: { skin: '#2a2a2a', shirt: '#1a1a1a', pants: '#1a1a1a', hatColor: '#111' }, delayMs: 1700 },
        { type: 'ACTOR_SET_STATE', actorId: 'gaku', state: 'SAD', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [2200, 1605], speed: 60, wander: 70, delayMs: 5000 },
      ],
      after: [{ actor: 'gaku', text: 'まっくろ……母ちゃんに怒られる。どこかでゴシゴシ洗わないと', delay: 3800 }] },
    { id: 'S2-E54', s: 'noren', t: 'gaku', cat: 'PROGRESSION', requires: ['S2-E53'], title: 'ガク、銭湯でピカピカに', say: 'おふろ屋さん！ ひとっ走り行ってくる！', anim: 'react.run', route: 'S2.route.ink',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [5400, 750], speed: 340, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'gaku', delayMs: 11000 }, { type: 'FX', kind: 'bubbles', at: 'noren', delayMs: 11500 },
        { type: 'ACTOR_APPEARANCE', actorId: 'gaku', look: { skin: '#f2c9a0', shirt: '#f28a3a', pants: '#3a5a8a', hatColor: '#d33' }, delayMs: 12000 },
        { type: 'ACTOR_SHOW', actorId: 'gaku', delayMs: 15000 }, { type: 'FX', kind: 'sparkle', at: 'gaku', delayMs: 15100 },
        { type: 'ACTOR_SPEECH', actorId: 'gaku', text: 'ピッカピカ！ お風呂ってすごい！', delayMs: 15400 },
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [5200, 885], speed: 60, wander: 100, delayMs: 16500 },
      ] },
    // ── キヌエ（E55〜E56） ──
    { id: 'S2-E55', s: 'pawn', t: 'kinue', cat: 'CHAIN', title: 'キヌエ、ブランドバッグを質に入れる', say: 'このバッグ……ブランド品よ。いかほどになるかしら？', anim: 'react.think', route: 'S2.route.pawn',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'kinue', to: [925, 1538], speed: 90, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kinue', look: { acc: ['earring', 'hat'] }, delayMs: 2400 },
        { type: 'SPAWN_OBJECT', objectId: 'pawnBag', delayMs: 2400 },
      ],
      after: [{ actor: 'kinue', text: 'ぜんぜん足りないわ……あとは、首もとのこれくらい……', delay: 3800 }] },
    { id: 'S2-E56', s: 'pawn', t: 'kinue', cat: 'PROGRESSION', requires: ['S2-E55'], title: 'キヌエ、ネックレスも手放して家賃を工面', say: 'えーい、ネックレスも持ってって！ ……これで家賃が払えるわ', anim: 'react.happy', route: 'S2.route.pawn',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'kinue', look: { acc: ['hat'] }, delayMs: 1000 },
        { type: 'SPAWN_OBJECT', objectId: 'pawnNecklace', delayMs: 1000 },
        { type: 'ACTOR_SET_STATE', actorId: 'kinue', state: 'HAPPY', delayMs: 1600 },
        { type: 'ACTOR_MOVE', actorId: 'kinue', to: [760, 1620], speed: 50, wander: 80, delayMs: 3000 },
      ] },
    // ── おまわりさん・マゴベエ（E57〜E59） ──
    { id: 'S2-E57', s: 'thief', t: 'police', cat: 'PROGRESSION', title: 'おまわりさん、木陰のコソ泥を確保', say: 'ん！？ そこのあやしいやつ！ まてーい！', anim: 'react.run', route: 'S2.route.police',
      fx: [
        { type: 'PLAY_SOUND', soundId: 'whistle' },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [2640, 675], speed: 280, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'thief', text: 'げえっ、見つかった！', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'thief', to: [2720, 960], speed: 160, wander: 0, delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'thief', state: 'SCARED', delayMs: 6000 },
        { type: 'ACTOR_MOVE', actorId: 'thief', to: [4390, 1556], speed: 90, wander: 0, delayMs: 7000 },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4470, 1564], speed: 90, wander: 40, delayMs: 7000 },
        { type: 'ACTOR_SPEECH', actorId: 'thief', text: 'とほほ……木陰なら見つからないと思ったのに', delayMs: 9000 },
        { type: 'ACTOR_HIDE', actorId: 'thief', delayMs: 18000 },
        { type: 'SET_FLAG', id: 'thief.caught', value: true },
      ] },
    { id: 'S2-E58', s: 'koban', t: 'magobe', cat: 'CHAIN', title: 'マゴベエ、交番で道をたずねる', say: '伝説のコロッケ屋？ それなら西のほうの肉屋さんだよ、と……ありがとう！', anim: 'react.happy', route: 'S2.route.police',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'magobe', to: [2355, 1571], speed: 90, wander: 60, delayMs: 1500 }, { type: 'SET_FLAG', id: 'magobe.dir', value: 'west' }],
      after: [{ actor: 'magobe', text: '……でも、なんだか胸さわぎがする。運勢を見てもらおうかな', delay: 6000 }] },
    { id: 'S2-E59', s: 'uranai', t: 'magobe', cat: 'FLAVOR', requires: ['S2-E58'], title: 'マゴベエ、占いで逆方向へ', say: 'え？ 「東に吉」……？ さっき西って言われたのに……', anim: 'react.spin', route: 'S2.route.police',
      fx: [
        { type: 'ACTOR_SPEECH', actorId: 'uranai', text: 'ほっほっ、迷わず東へ進むがよい', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'magobe', to: [5700, 1684], speed: 90, wander: 60, delayMs: 3000 },
        { type: 'SET_FLAG', id: 'magobe.dir', value: 'east' },
      ] },
    // ── キラリ（E60〜E62） ──
    { id: 'S2-E60', s: 'salonSign', t: 'kirari', cat: 'CHAIN', title: 'キラリ、ブリーチで真っ白に', say: 'パッと明るく、ブリーチしちゃお！', anim: 'react.happy', route: 'S2.route.kirari',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'kirari', to: [200, 746], speed: 200, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'kirari', delayMs: 5000 }, { type: 'FX', kind: 'smoke', x: 200, y: 600, delayMs: 5400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { hairColor: '#f8f8f2', skin: '#fbfaf8' }, delayMs: 5600 },
        { type: 'ACTOR_SHOW', actorId: 'kirari', delayMs: 7400 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'え、肌まで白くなってない！？ おばけみたい……', delayMs: 7800 },
        { type: 'ACTOR_MOVE', actorId: 'kirari', to: [700, 960], speed: 50, wander: 150, delayMs: 9500 },
      ],
      after: [{ actor: 'kirari', text: 'ちょっと焼いて、健康的な色をつけたいかも', delay: 11000 }] },
    { id: 'S2-E61', s: 'tanSign', t: 'kirari', cat: 'CHAIN', requires: ['S2-E60'], title: 'キラリ、日焼けサロンで焼きすぎる', say: 'こんがり焼いて、健康的に……やりすぎたー！', anim: 'react.fire', route: 'S2.route.kirari',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { skin: '#5a321c', hairColor: '#f8f8f2' }, delayMs: 900 },
        { type: 'FX', kind: 'steam', at: 'kirari', delayMs: 900 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: '……だれ？', delayMs: 3200 },
      ],
      after: [{ actor: 'kirari', text: 'まっくろ……ゴシゴシ洗ったら、ちょっとは戻るかな', delay: 4600 }] },
    { id: 'S2-E62', s: 'sentoSign', t: 'kirari', cat: 'FLAVOR', requires: ['S2-E61'], title: 'キラリ、銭湯でのぼせて真っ赤', say: 'お風呂で洗いながそ！ ……のぼせて真っ赤になったー！', anim: 'react.embarrassed', route: 'S2.route.kirari',
      fx: [
        { type: 'FX', kind: 'steam', at: 'kirari', delayMs: 600 }, { type: 'FX', kind: 'bubbles', at: 'kirari', delayMs: 900 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { skin: '#f2897a', hairColor: '#c8862a' }, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'ゆでダコだよ〜。……まいっか、これはこれで！', delayMs: 3000 },
      ] },
    // ── さくら湯（E63〜E66） ──
    { id: 'S2-E63', s: 'earring', t: 'hoshimi', cat: 'PROGRESSION', title: 'ホシミ、星のイヤリングをとりもどす', say: 'あっ！ わたしの星のイヤリング！ どこにあったの！？', anim: 'react.love', route: 'S2.route.end', focus: true,
      fx: [
        { type: 'HIDE_OBJECT', objectId: 'earring' },
        { type: 'ACTOR_APPEARANCE', actorId: 'hoshimi', look: { acc: ['apron', 'earring'] }, delayMs: 600 },
        { type: 'FX', kind: 'sparkle', at: 'hoshimi', delayMs: 600 },
        { type: 'ACTOR_SET_STATE', actorId: 'hoshimi', state: 'HAPPY' },
        { type: 'SET_FLAG', id: 'sento.spirit', value: true },
        { type: 'FX', kind: 'steam', at: 'chimneyTop', delayMs: 2400 },
      ],
      after: [
        { actor: 'hoshimi', text: '元気出た！ 今日はとびきり熱いお風呂、わかすよ！', delay: 2800 },
        { actor: 'gonji', text: 'お嬢が笑うた……よし、釜の支度じゃ。大物の客と、火種さえあればのう', delay: 5200 },
      ] },
    { id: 'S2-E64', s: 'noren', t: 'rikishi', cat: 'PROGRESSION', cond: [anyDone('S2-E18', 'S2-E47', 'S2-E19')], title: '力士、さくら湯の湯船をあふれさせる', say: 'ひとっ風呂、浴びてくるでごわす！', anim: 'react.happy', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5400, 752], speed: 280, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'rikishi', delayMs: 9000 },
        { type: 'FX', kind: 'splash', at: 'noren', delayMs: 9600 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 9600 },
        { type: 'FX', kind: 'steam', at: 'noren', delayMs: 10000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'わっ、お湯が半分あふれた！', delayMs: 10400 },
        { type: 'ACTOR_SHOW', actorId: 'rikishi', delayMs: 16000 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5300, 885], speed: 40, wander: 100, delayMs: 16200 },
        { type: 'SET_FLAG', id: 'sento.bigGuest', value: true },
      ],
      after: [{ actor: 'gonji', text: 'ほう、横綱級の客か！ こりゃあ釜を本気で焚かにゃならん', delay: 11800 }] },
    { id: 'S2-E65', s: 'match', t: 'gonji', cat: 'TIMEOUT', title: 'ゴン爺の線香花火', say: 'もう日が暮れる……せめて、これくらいはのう', anim: 'react.timeout', route: 'S2.route.end',
      fx: [
        { type: 'FX', kind: 'sparkle', at: 'gonji', delayMs: 300 }, { type: 'PLAY_SOUND', soundId: 'pop', delayMs: 300 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'パチパチ……ちっちゃい花火みたいじゃのう', delayMs: 1400 },
        { type: 'FX', kind: 'smoke', at: 'chimneyTop', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: '今日はお店、閉めちゃおっか……', delayMs: 2600 },
      ] },
    { id: 'S2-E66', s: 'match', t: 'gonji', cat: 'TERMINAL', requires: ['S2-E63', 'S2-E64'], title: 'さくら湯、煙突から大火柱！', say: '火種じゃ！ お嬢の笑顔に横綱の湯……今日は特大でいくぞい！', anim: 'react.terminal', route: 'S2.route.end',
      fx: [
        { type: 'CAMERA_FOCUS', x: 5400, y: 580, zoom: 0.8 },
        { type: 'FX', kind: 'fire', at: 'gonji', delayMs: 400 }, { type: 'PLAY_SOUND', soundId: 'boom', delayMs: 900 },
        { type: 'FX', kind: 'eruption', at: 'chimneyTop', delayMs: 1200 },
        { type: 'FX', kind: 'fire', at: 'chimneyTop', delayMs: 1600 },
        { type: 'FX', kind: 'steam', at: 'noren', delayMs: 1800 },
        { type: 'ACTOR_SHOW', actorId: 'rikishi', delayMs: 1900 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5300, 960], speed: 320, wander: 0, delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'rikishi', text: 'あっちっちっちでごわすーー！！', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'きゃー！ 煙突が火をふいた！', delayMs: 2600 },
        { type: 'FX', kind: 'confetti', x: 5600, y: 130, delayMs: 2800 }, { type: 'PLAY_SOUND', soundId: 'fanfare', delayMs: 2800 },
        { type: 'ACTOR_SPEECH', actorId: 'police', text: 'しょ、消防車！ ……いや、花火か！？', delayMs: 3200 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'たーまやー！', delayMs: 3800 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'これじゃ！ これが、さくら湯の火柱じゃ！', delayMs: 4400 },
        { type: 'WAIT', durationMs: 4200 },
      ] },
  ],
};
