// ステージ2：ひだまり商店街（66 イベント）。登場人物・台詞はすべてオリジナル。
const done = id => ({ eventDone: id });
const notDone = id => ({ eventNotDone: id });
const anyDone = (...ids) => ({ anyEventDone: ids });

// ── 背景（くり返し要素はループで作る） ──
const NB = 1120;   // 北側の店の下端
const SB = 2400;   // 南側の店の下端
const scenery = [
  // 空・遠景
  { t: 'rect', x: 0, y: 0, w: 7200, h: NB, fill: '#bfe3f5' },
  { t: 'rect', x: 0, y: 260, w: 7200, h: 260, fill: '#d6eefa' },
  { t: 'emoji', e: '☁️', x: 900, y: 140, s: 120 }, { t: 'emoji', e: '☁️', x: 2600, y: 110, s: 90 },
  { t: 'emoji', e: '☁️', x: 4300, y: 160, s: 130 }, { t: 'emoji', e: '☁️', x: 5900, y: 90, s: 100 },
  { t: 'emoji', e: '☀️', x: 6500, y: 120, s: 110 },
  { t: 'rect', x: 150, y: 330, w: 260, h: 300, fill: '#c9d3dc' }, { t: 'rect', x: 1900, y: 280, w: 220, h: 350, fill: '#c3cdd6' },
  { t: 'rect', x: 3300, y: 340, w: 300, h: 300, fill: '#c9d3dc' }, { t: 'rect', x: 6100, y: 300, w: 200, h: 330, fill: '#c3cdd6' },
  // 歩道・通り
  { t: 'rect', x: 0, y: NB, w: 7200, h: 110, fill: '#cfc4b0' },
  { t: 'stripes', x: 0, y: NB, w: 7200, h: 110, dir: 'v', n: 72, c1: 'rgba(0,0,0,0)', c2: 'rgba(120,100,70,.12)' },
  { t: 'rect', x: 0, y: 1230, w: 7200, h: 800, fill: '#e3d3b4' },
  { t: 'stripes', x: 0, y: 1230, w: 7200, h: 800, dir: 'h', n: 16, c1: 'rgba(0,0,0,0)', c2: 'rgba(160,120,70,.08)' },
  { t: 'rect', x: 0, y: 1600, w: 7200, h: 60, fill: 'rgba(190,90,60,.18)' },
  { t: 'rect', x: 0, y: 2030, w: 7200, h: 50, fill: '#cfc4b0' },
  // 南側の店並び（下端 2400）
  { t: 'rect', x: 0, y: 2080, w: 7200, h: 320, fill: '#8f7a64' },
  // 入口ゲート（西・東）
  { t: 'rect', x: 40, y: 380, w: 34, h: 1650, fill: '#b23a2e' }, { t: 'rect', x: 230, y: 380, w: 34, h: 1650, fill: '#b23a2e' },
  { t: 'sign', x: 20, y: 300, w: 270, h: 90, text: 'ひだまり商店街', fill: '#f4d35e', color: '#7a2a1a', s: 30 },
  { t: 'rect', x: 6990, y: 380, w: 34, h: 1650, fill: '#b23a2e' }, { t: 'rect', x: 7150, y: 380, w: 34, h: 1650, fill: '#b23a2e' },
  { t: 'sign', x: 6970, y: 300, w: 230, h: 90, text: 'またおこしを', fill: '#f4d35e', color: '#7a2a1a', s: 26 },
  // ── 北側の店 ──
  { t: 'building', x: 290, y: NB, w: 330, h: 560, fill: '#f7d9e3', roof: '#c76b8a', door: true, windows: true, awning: '#e88fb0' },
  { t: 'emoji', e: '✂️', x: 560, y: 760, s: 50 }, { t: 'emoji', e: '💇', x: 360, y: 760, s: 50 },
  { t: 'building', x: 640, y: NB, w: 270, h: 520, fill: '#e8e4da', roof: '#5a6b7a', sign: '理容 さかば', signFill: '#fff', signColor: '#c33', door: true, awning: '#3a5a8a' },
  { t: 'emoji', e: '💈', x: 670, y: 1050, s: 70 },
  { t: 'building', x: 930, y: NB, w: 310, h: 540, fill: '#c8a27a', roof: '#6b4426', sign: '純喫茶 ポプラ', signFill: '#3a2414', signColor: '#f4d9a0', door: true, windows: true, awning: '#2f6b4a' },
  { t: 'ellipse', x: 1150, y: 1190, rx: 60, ry: 16, fill: '#7a5a3a' }, { t: 'rect', x: 1144, y: 1190, w: 12, h: 40, fill: '#5a4028' },
  { t: 'emoji', e: '☕', x: 1110, y: 1170, s: 30 }, { t: 'emoji', e: '🪴', x: 960, y: 1180, s: 60 },
  { t: 'building', x: 1260, y: NB, w: 440, h: 600, fill: '#e9edf2', roof: '#2a4a8a', door: true, windows: true, awning: '#f2c14e' },
  { t: 'emoji', e: '📻', x: 1560, y: 1060, s: 50 }, { t: 'emoji', e: '🔌', x: 1650, y: 1070, s: 40 }, { t: 'emoji', e: '💡', x: 1290, y: 800, s: 46 },
  { t: 'rect', x: 1505, y: 400, w: 190, h: 120, fill: '#333', r: 6 },
  { t: 'building', x: 1720, y: NB, w: 340, h: 560, fill: '#e4f3e8', roof: '#2e8a5a', door: true, windows: true, awning: '#4caf7a' },
  { t: 'emoji', e: '💊', x: 1960, y: 1050, s: 44 }, { t: 'emoji', e: '🧴', x: 2020, y: 1060, s: 40 },
  { t: 'building', x: 2080, y: NB, w: 260, h: 640, fill: '#f2f2f2', roof: '#6aa0c8', sign: 'しろくま歯科 2F', signFill: '#6aa0c8', signColor: '#fff', door: true, windows: true },
  { t: 'building', x: 2360, y: NB, w: 370, h: 560, fill: '#d9c9a8', roof: '#7a3a2a', sign: '本の森書店', signFill: '#2a4a2a', signColor: '#f4f0d0', door: true, windows: true, awning: '#7a3a2a' },
  { t: 'emoji', e: '📚', x: 2420, y: 1070, s: 56 }, { t: 'emoji', e: '📖', x: 2700, y: 1080, s: 40 },
  { t: 'building', x: 2750, y: NB, w: 410, h: 560, fill: '#dff0f7', roof: '#1d5b8a', door: false, windows: false, awning: '#3a8ac8' },
  { t: 'rect', x: 2770, y: 1030, w: 90, h: 70, fill: '#8fd3f0', stroke: '#456', lw: 4 },
  { t: 'rect', x: 2880, y: 1110, w: 260, h: 30, fill: '#9ab' }, { t: 'emoji', e: '🧊', x: 2960, y: 1110, s: 30 }, { t: 'emoji', e: '🦐', x: 3120, y: 1105, s: 30 },
  { t: 'building', x: 3180, y: NB, w: 280, h: 540, fill: '#f6e0d6', roof: '#a33', door: true, windows: true, awning: '#d65a4a' },
  { t: 'emoji', e: '🥩', x: 3250, y: 1060, s: 44 }, { t: 'emoji', e: '🍖', x: 3400, y: 1060, s: 44 },
  { t: 'building', x: 3480, y: NB, w: 340, h: 560, fill: '#fff1c9', roof: '#e2702a', door: true, windows: true, awning: '#e8b52a' },
  { t: 'emoji', e: '🍟', x: 3540, y: 1060, s: 40 }, { t: 'emoji', e: '🥤', x: 3780, y: 1060, s: 40 },
  { t: 'building', x: 3840, y: NB, w: 260, h: 520, fill: '#f3d2a0', roof: '#8a3a1a', door: true, windows: true, awning: '#c84a1a' },
  { t: 'emoji', e: '🌶️', x: 3880, y: 760, s: 44 }, { t: 'emoji', e: '🍛', x: 4060, y: 1060, s: 40 },
  // 公園（4120〜5280）
  { t: 'rect', x: 4120, y: 700, w: 1160, h: 420, fill: '#9ccc7a' },
  { t: 'fence', x: 4120, y: NB, w: 1160, h: 40, fill: '#fff' },
  { t: 'sign', x: 4130, y: 640, w: 200, h: 60, text: 'ひだまり公園', fill: '#5a8a3a', color: '#fff', s: 22 },
  { t: 'ellipse', x: 4210, y: 1150, rx: 150, ry: 40, fill: 'rgba(30,60,30,.35)' },
  { t: 'emoji', e: '🌳', x: 4210, y: 900, s: 330 },
  { t: 'emoji', e: '🌳', x: 5170, y: 870, s: 400 },
  { t: 'emoji', e: '🌲', x: 4700, y: 820, s: 160 }, { t: 'emoji', e: '🌳', x: 4950, y: 830, s: 170 },
  { t: 'line', pts: [4320, 1100, 4320, 920, 4480, 920, 4480, 1100], stroke: '#d33', w: 8 },
  { t: 'line', pts: [4320, 980, 4480, 980], stroke: '#d33', w: 6 }, { t: 'line', pts: [4320, 1040, 4480, 1040], stroke: '#d33', w: 6 },
  { t: 'line', pts: [4373, 920, 4373, 1100], stroke: '#f2c14e', w: 6 }, { t: 'line', pts: [4426, 920, 4426, 1100], stroke: '#f2c14e', w: 6 },
  { t: 'rect', x: 4776, y: 1000, w: 10, h: 120, fill: '#666' },
  { t: 'emoji', e: '🌼', x: 4640, y: 1100, s: 30 }, { t: 'emoji', e: '🌼', x: 4860, y: 1105, s: 28 }, { t: 'emoji', e: '🌷', x: 5000, y: 1100, s: 30 },
  { t: 'emoji', e: '🕊️', x: 4600, y: 1300, s: 30 }, { t: 'emoji', e: '🕊️', x: 4640, y: 1320, s: 26 }, { t: 'emoji', e: '🕊️', x: 4700, y: 1295, s: 28 },
  // 日焼けサロン・おもちゃ屋・花屋
  { t: 'building', x: 5300, y: NB, w: 300, h: 540, fill: '#ffd8a8', roof: '#c8641a', door: true, windows: true, awning: '#ff9a3a' },
  { t: 'emoji', e: '🌞', x: 5450, y: 780, s: 60 },
  { t: 'building', x: 5620, y: NB, w: 340, h: 560, fill: '#fff4b8', roof: '#3a8ac8', sign: 'おもちゃのポッポ', signFill: '#e33', signColor: '#fff', door: true, windows: true, awning: '#e33' },
  { t: 'emoji', e: '🧸', x: 5680, y: 1060, s: 44 }, { t: 'emoji', e: '🪀', x: 5940, y: 1070, s: 34 }, { t: 'emoji', e: '🎰', x: 5810, y: 1150, s: 54 },
  { t: 'building', x: 5980, y: NB, w: 270, h: 520, fill: '#f0fff0', roof: '#4a9a5a', door: true, windows: true, awning: '#9ad07a' },
  { t: 'emoji', e: '💐', x: 6000, y: 1130, s: 40 }, { t: 'emoji', e: '🌻', x: 6180, y: 1125, s: 44 }, { t: 'emoji', e: '🪻', x: 6220, y: 1130, s: 34 },
  // 銭湯（さくら湯）
  { t: 'rect', x: 6880, y: 220, w: 60, h: 900, fill: '#8b4a3a' },
  { t: 'stripes', x: 6880, y: 220, w: 60, h: 900, dir: 'h', n: 18, c1: 'rgba(0,0,0,0)', c2: 'rgba(0,0,0,.12)' },
  { t: 'building', x: 6280, y: NB, w: 580, h: 600, fill: '#f3ead8', roof: '#3a3a5a', door: false, windows: true },
  { t: 'poly', pts: [6260, 520, 6570, 380, 6880, 520], fill: '#3a3a5a' },
  { t: 'rect', x: 6880, y: 1000, w: 100, h: 120, fill: '#555', r: 8 }, { t: 'emoji', e: '🔥', x: 6930, y: 1060, s: 34 },
  { t: 'emoji', e: '🪵', x: 7050, y: 1110, s: 44 }, { t: 'emoji', e: '🪵', x: 7090, y: 1100, s: 40 },
  { t: 'emoji', e: '🧺', x: 6330, y: 1100, s: 40 },
  // ── 南側の店（看板だけの書き割り） ──
  { t: 'building', x: 10, y: SB, w: 370, h: 320, fill: '#9aa', roof: '#566', sign: '駐輪場' },
  { t: 'emoji', e: '🚲', x: 100, y: 2250, s: 60 }, { t: 'emoji', e: '🚲', x: 200, y: 2260, s: 60 }, { t: 'emoji', e: '🛵', x: 310, y: 2250, s: 60 },
  { t: 'building', x: 400, y: SB, w: 350, h: 320, fill: '#d8c3e8', roof: '#6a4a8a', sign: '古着 ふるふる', door: true, awning: '#9a6ac8' },
  { t: 'building', x: 770, y: SB, w: 320, h: 300, fill: '#e8d8a8', roof: '#8a6a2a', sign: 'たばこ・宝くじ', door: true, awning: '#c8a23a' },
  { t: 'building', x: 1110, y: SB, w: 370, h: 320, fill: '#2a2a4a', roof: '#111', sign: 'ゲームセンター', signFill: '#f0f', signColor: '#fff', door: true },
  { t: 'emoji', e: '👾', x: 1200, y: 2250, s: 44 }, { t: 'emoji', e: '🕹️', x: 1400, y: 2260, s: 44 },
  { t: 'building', x: 1500, y: SB, w: 340, h: 320, fill: '#d6cbb4', roof: '#3a2a1a', door: true },
  { t: 'building', x: 1860, y: SB, w: 340, h: 320, fill: '#3a2050', roof: '#1a0a2a', sign: '占いの館', signFill: '#a07ad0', signColor: '#fff', door: true },
  { t: 'ellipse', x: 2030, y: 2030, rx: 70, ry: 18, fill: '#4a2a6a' }, { t: 'emoji', e: '🔮', x: 2080, y: 2005, s: 40 },
  { t: 'building', x: 2220, y: SB, w: 340, h: 320, fill: '#f6e6d6', roof: '#6a3a2a', sign: '和菓子 つきみ堂', signFill: '#fff', signColor: '#6a3a2a', door: true, awning: '#b05a4a' },
  { t: 'emoji', e: '🍡', x: 2300, y: 2120, s: 40 }, { t: 'emoji', e: '🍘', x: 2480, y: 2120, s: 36 },
  { t: 'building', x: 2580, y: SB, w: 320, h: 320, fill: '#d8e8ff', roof: '#2a5aa8', sign: 'スポーツ ダッシュ', door: true, awning: '#2a5aa8' },
  { t: 'building', x: 2920, y: SB, w: 340, h: 300, fill: '#e8d6c0', roof: '#7a5a3a', sign: '酒・たばこ', door: true },
  { t: 'building', x: 3280, y: SB, w: 340, h: 320, fill: '#f2e0b0', roof: '#a33', sign: 'ラーメン 大盛軒', signFill: '#a33', signColor: '#fff', door: true, awning: '#d33' },
  { t: 'emoji', e: '🍜', x: 3450, y: 2240, s: 50 },
  { t: 'building', x: 3640, y: SB, w: 360, h: 300, fill: '#eef6ff', roof: '#5a7a9a', sign: 'クリーニング', door: true },
  { t: 'building', x: 4020, y: SB, w: 680, h: 320, fill: '#f6f0d8', roof: '#3a7a2a', sign: '八百屋 みどり', signFill: '#3a7a2a', signColor: '#fff', awning: '#5aa83a' },
  { t: 'emoji', e: '🥬', x: 4100, y: 2120, s: 40 }, { t: 'emoji', e: '🥕', x: 4300, y: 2120, s: 40 }, { t: 'emoji', e: '🍌', x: 4560, y: 2120, s: 40 }, { t: 'emoji', e: '🍊', x: 4640, y: 2125, s: 36 },
  { t: 'building', x: 4720, y: SB, w: 340, h: 300, fill: '#f2f2f2', roof: '#2a3a6a', door: true },
  { t: 'emoji', e: '🚨', x: 4800, y: 2120, s: 36 },
  { t: 'building', x: 5080, y: SB, w: 320, h: 300, fill: '#fff8e0', roof: '#c8a23a', sign: '文具 えんぴつ', door: true },
  { t: 'building', x: 5420, y: SB, w: 340, h: 320, fill: '#f6dcb0', roof: '#8a5a2a', sign: 'パン こむぎ', door: true, awning: '#c88a3a' },
  { t: 'emoji', e: '🥐', x: 5500, y: 2130, s: 40 }, { t: 'emoji', e: '🍞', x: 5680, y: 2130, s: 40 },
  { t: 'building', x: 5780, y: SB, w: 340, h: 320, fill: '#222', roof: '#000', sign: 'ライブハウス 轟', signFill: '#c00', signColor: '#fff', door: true },
  { t: 'emoji', e: '🎸', x: 5860, y: 2240, s: 50 }, { t: 'emoji', e: '🥁', x: 6050, y: 2250, s: 44 },
  { t: 'building', x: 6140, y: SB, w: 360, h: 300, fill: '#e0f0f8', roof: '#4a8ab0', sign: 'コインランドリー', door: true },
  { t: 'building', x: 6520, y: SB, w: 400, h: 320, fill: '#ffe8c8', roof: '#c85a2a', sign: '駄菓子 ちびっこ', door: true, awning: '#f28a3a' },
  { t: 'emoji', e: '🍬', x: 6600, y: 2130, s: 34 }, { t: 'emoji', e: '🍭', x: 6840, y: 2130, s: 36 },
  // 通りの小物
  { t: 'emoji', e: '🪴', x: 1250, y: 1250, s: 50 }, { t: 'emoji', e: '🪴', x: 3170, y: 1250, s: 50 }, { t: 'emoji', e: '🪴', x: 6270, y: 1250, s: 50 },
  { t: 'emoji', e: '🚏', x: 2200, y: 1980, s: 70 }, { t: 'emoji', e: '🚥', x: 3630, y: 1990, s: 54 },
  { t: 'emoji', e: '🎐', x: 1000, y: 920, s: 34 }, { t: 'emoji', e: '🎏', x: 5650, y: 600, s: 70 },
  { t: 'emoji', e: '🍃', x: 4500, y: 1500, s: 26, rot: 0.6 }, { t: 'emoji', e: '🍂', x: 2500, y: 1650, s: 24, rot: 1.2 }, { t: 'emoji', e: '🍃', x: 5900, y: 1420, s: 22 },
];
// アーケードの提灯と旗（ループ）
for (let x = 380; x < 7000; x += 380) {
  if (x > 4120 && x < 5280) continue;
  scenery.push({ t: 'line', pts: [x - 190, 250, x + 190, 250], stroke: '#7a5a3a', w: 3 });
  scenery.push({ t: 'emoji', e: '🏮', x, y: 290, s: 46 });
}
for (let x = 500; x < 7000; x += 760) scenery.push({ t: 'sign', x, y: 1240, w: 26, h: 90, text: '', fill: ['#e44', '#f2c14e', '#4a9ae8', '#5ac85a'][(x / 760 | 0) % 4], color: '#fff', s: 10 });

export default {
  id: 'S2', title: 'ひだまり商店街', subtitle: '商店街', theme: '商店街',
  intro: 'にぎやかな昼下がりの商店街。みんなそれぞれ、ちょっとした悩みをかかえているみたい。いちばん奥の銭湯は、今日はなぜか元気がない……',
  timeLimitMs: 300000,
  world: { width: 7200, height: 2400, minZoom: 0.75, maxZoom: 4, bg: '#e3d3b4', spawnCamera: { x: 1000, y: 1400, zoom: 1 } },
  bgm: { tempo: 116, key: 2, mood: 'swing' },
  clearEventId: 'S2-E66', timeoutEventId: 'S2-E65',
  routes: {
    'S2.route.hair': 'ミツルの髪型さがし', 'S2.route.teruo': 'テルオの頭', 'S2.route.dinner': '今夜の献立', 'S2.route.fish': '魚屋さわぎ',
    'S2.route.yanagi': 'ヤナギの顔色', 'S2.route.sumo': '力士・大樽の休日', 'S2.route.sweets': 'アンズのがまん', 'S2.route.park': '公園の昼下がり',
    'S2.route.flower': '花屋のまわり', 'S2.route.climb': 'ノボルと高いところ', 'S2.route.kid': 'チョロ吉の木のぼり', 'S2.route.hungry': 'マンタの空腹',
    'S2.route.book': '本屋の三人', 'S2.route.baseball': '草野球', 'S2.route.minori': 'ミノリのおつかい', 'S2.route.runner': 'ハヤテの走り',
    'S2.route.ink': 'ガクとタコ', 'S2.route.pawn': 'キヌエの質入れ', 'S2.route.police': 'おまわりさんの一日', 'S2.route.kirari': 'キラリのイメチェン',
    'S2.route.end': 'さくら湯の釜',
  },
  scenery,
  actors: {
    // ── 西エリア ──
    mitsuru: {
      name: 'ミツル', x: 470, y: 1330, wander: 110, speed: 55,
      look: { h: 150, hair: 'short', hairColor: '#3a2a1a', shirt: '#7ab0d8', pants: '#3a4a6a' },
      idle: [
        { text: '髪を切りたいんだけど……どんな髪型にするか決められない', when: [notDone('S2-E02'), notDone('S2-E03'), notDone('S2-E04'), notDone('S2-E05'), notDone('S2-E06')] },
        { text: '見本になるものがあればなあ。ポスターとか、看板とか', when: [notDone('S2-E02'), notDone('S2-E04')] },
        { text: 'かっこいい人を見ると、すぐマネしたくなるんだよね', when: [notDone('S2-E05'), notDone('S2-E06')] },
        { text: 'あのおじさんの頭、まぶしい……なんか神々しい……！', when: [done('S2-E08'), notDone('S2-E03')] },
        { text: 'どう？ この髪型。……やっぱ変かな', when: [anyDone('S2-E02', 'S2-E03', 'S2-E04', 'S2-E05', 'S2-E06', 'S2-E07')] },
      ],
    },
    teruo: {
      name: 'テルオ', x: 900, y: 1380, path: [[350, 1360], [1700, 1390], [1100, 1440]], speed: 40,
      look: { h: 150, hair: 'short', hairColor: '#222', shirt: '#b8a07a', pants: '#5a4a3a', acc: ['mustache'], old: true },
      idle: [
        { text: '（しきりに頭をおさえている）……風の強い日は苦手でな', when: [notDone('S2-E01')] },
        { text: 'わしの髪？ ふさふさじゃろ？ ……さわるでないぞ', when: [notDone('S2-E01')] },
        { text: '頭がすーすーする……いっそピカッと開き直れたら楽なんじゃが', when: [done('S2-E01'), notDone('S2-E08'), notDone('S2-E09')] },
        { text: '海のものは髪にいいと聞いたことがあるが……', when: [done('S2-E01'), notDone('S2-E08'), notDone('S2-E09')] },
        { text: 'もう隠さん！ 明るく生きるんじゃ！', when: [done('S2-E08')] },
        { text: 'このうねうね、悪くないじゃろ？', when: [done('S2-E09')] },
      ],
    },
    kirari: {
      name: 'キラリ', x: 700, y: 1720, path: [[600, 1720], [2500, 1760], [1500, 1820]], speed: 45,
      look: { h: 150, hair: 'long', hairColor: '#c8862a', skin: '#f2c9a0', shirt: '#ff7ac0', skirt: true, pants: '#fff', acc: ['earring', 'bag'] },
      idle: [
        { text: 'なーんか、イメチェンしたい気分〜', when: [notDone('S2-E60')] },
        { text: 'もっとこう、パッと明るい感じになりたいんだよね', when: [notDone('S2-E60')] },
        'あたしって、すぐ影響されちゃうタイプなの',
        { text: '真っ白すぎ……ちょっと焼いて色つけたいかも', when: [done('S2-E60'), notDone('S2-E61')] },
        { text: '黒すぎ！ ゴシゴシ洗ったら戻るかな……', when: [done('S2-E61'), notDone('S2-E62')] },
        { text: 'のぼせた〜。でも、なんか楽しかった', when: [done('S2-E62')] },
      ],
    },
    kinue: {
      name: 'キヌエ', x: 1650, y: 1960, wander: 70, speed: 35,
      look: { h: 150, hair: 'bun', hairColor: '#6a3a6a', shirt: '#8a3a6a', skirt: true, pants: '#4a2a4a', acc: ['bag', 'earring', 'hat'], hatColor: '#c8a', old: true },
      idle: [
        { text: '家賃のしはらい、明日なのよ……どうしましょ', when: [notDone('S2-E55')] },
        { text: 'このバッグ、高かったのよねえ。手放すなんて……', when: [notDone('S2-E55')] },
        'お金って、どこに消えるのかしら',
        { text: 'ぜんぜん足りないわ……あとは首もとの、これくらいね', when: [done('S2-E55'), notDone('S2-E56')] },
        { text: 'ふう、身軽になったわ。家賃もなんとかなりそう', when: [done('S2-E56')] },
      ],
    },
    uranai: {
      name: '占い師', x: 2030, y: 2010, wander: 0,
      look: { h: 150, hair: 'long', hairColor: '#222', shirt: '#4a2a6a', pants: '#2a1a3a', acc: ['scarf', 'earring'], sit: true },
      idle: ['迷える者よ、来たれ……', 'ほっほっ。水晶玉はなんでもお見通しじゃ', '今日の吉方位は……むむっ'],
    },
    // ── 電器店・薬局・本屋 ──
    yanagi: {
      name: 'ヤナギ', x: 1900, y: 1290, wander: 60, speed: 30,
      look: { h: 155, hair: 'long', hairColor: '#2a1a12', skin: '#e4dfd2', shirt: '#2a2a2a', pants: '#2a2a2a', acc: ['scarf'] },
      idle: [
        { text: 'ゴホッ……最近どうも体がだるくてね', when: [notDone('S2-E16'), notDone('S2-E17')] },
        { text: '顔色が悪いってよく言われるんだ。栄養、足りてないのかな', when: [notDone('S2-E16'), notDone('S2-E17')] },
        { text: '髪型だけは毎朝きめてるんだ。見られてるからね', when: [notDone('S2-E17')] },
        { text: '体が軽い！ どこまでも歩けそうだ', when: [done('S2-E16')] },
        { text: 'ぼくの……自慢の髪が……', when: [done('S2-E17')] },
      ],
    },
    batter: {
      name: 'イワオ', x: 1450, y: 1500, wander: 50, speed: 40,
      look: { h: 160, hair: 'short', hairColor: '#222', shirt: '#fff', pants: '#ddd', acc: ['cap'], hatColor: '#1d3a8a', wide: true },
      idle: [
        { text: 'ナイターまでヒマだなあ……', when: [notDone('S2-E38')] },
        { text: '電器屋のテレビ、いまなにやってるかな', when: [notDone('S2-E38')] },
        { text: '草野球の四番も、最近はバット振ってないや', when: [notDone('S2-E38')] },
        { text: 'ブン！ ブン！ ……だれか投げてくれないかなあ', when: [done('S2-E38'), notDone('S2-E36'), notDone('S2-E37')] },
        { text: 'いい汗かいた！', when: [anyDone('S2-E36', 'S2-E37')] },
      ],
    },
    gou: {
      name: 'ゴウ', x: 2480, y: 1300, wander: 50, speed: 40,
      look: { h: 158, hair: 'spiky', hairColor: '#e8c040', shirt: '#222', pants: '#333', acc: ['sunglasses'] },
      idle: [
        { text: 'ヒマだなー。なんかおもしれーもんねーか', when: [notDone('S2-E32')] },
        { text: 'オレたち、アイドルにはうるさいんだぜ', when: [notDone('S2-E32')] },
        { text: 'へっへっ、この写真集は渡さねーぞ', when: [done('S2-E32'), notDone('S2-E34')] },
        { text: 'あ、あいつ、なんであんなにムキムキに……', when: [done('S2-E34'), notDone('S2-E35')] },
      ],
    },
    jin: {
      name: 'ジン', x: 2560, y: 1320, wander: 50, speed: 40,
      look: { h: 140, hair: 'mohawk', hairColor: '#333', shirt: '#555', pants: '#333', acc: ['mask'] },
      idle: ['アニキ、どこまでもついてくっす！', 'アニキ、新刊のコーナー見たっすか？', { text: 'アニキ〜、こわいっす〜！', when: [done('S2-E34')] }],
    },
    nobu: {
      name: 'ノブ', x: 2650, y: 1240, wander: 20, speed: 30,
      look: { h: 145, hair: 'bob', hairColor: '#3a2a1a', shirt: '#c8d8a8', pants: '#5a6a4a', acc: ['glasses', 'bag'] },
      idle: [
        { text: '静かに本を読みたいだけなのに……', when: [notDone('S2-E32')] },
        { text: 'ぼく、力じゃだれにも勝てないんだ', when: [notDone('S2-E33')] },
        { text: 'もっと体が強ければ、言い返せるのになあ', when: [done('S2-E32'), notDone('S2-E33')] },
        { text: 'みなぎる……！ さっきの二人、まだその辺にいるかな', when: [done('S2-E33'), notDone('S2-E34')] },
      ],
    },
    bookman: {
      name: '書店の店主', x: 2420, y: 1200, wander: 30, speed: 25,
      look: { h: 150, hair: 'bald', hairColor: '#ccc', shirt: '#7a6a4a', pants: '#4a3a2a', acc: ['glasses', 'apron'], old: true },
      idle: ['立ち読みは、ほどほどにね', 'いらっしゃい。今日は写真集が入ったよ', { text: '店の前がさわがしいねえ……', when: [done('S2-E34'), notDone('S2-E35')] }],
    },
    anzu: {
      name: 'アンズ', x: 2390, y: 1960, wander: 60, speed: 35,
      look: { h: 125, hair: 'twin', hairColor: '#5a2a1a', shirt: '#ffb0c0', skirt: true, pants: '#fff', acc: ['ribbon'], kid: true },
      idle: [
        { text: 'あんみつ……どら焼き……ああ、食べたい', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'でも、最近ちょっと食べすぎかなあ……', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'だれか、あたしを止めてくれないかな', when: [notDone('S2-E20'), notDone('S2-E21')] },
        { text: 'がまん、がまん……えらいでしょ？', when: [anyDone('S2-E20', 'S2-E21')] },
      ],
    },
    // ── 魚屋・肉屋・食べもの屋 ──
    fishman: {
      name: '魚屋の大将', x: 2900, y: 1200, wander: 40, speed: 30,
      look: { h: 155, hair: 'spiky', hairColor: '#222', shirt: '#fff', pants: '#2a4a8a', acc: ['apron', 'scarf'], muscle: true },
      idle: ['へいらっしゃい！ 今日はタコがいいよ！', 'ボウズ、生きものにはさわるなよ〜', { text: 'あのドロボウ猫め……', when: [done('S2-E15')] }],
    },
    tsurita: {
      name: 'ツリタ', x: 3030, y: 1290, wander: 50, speed: 35,
      look: { h: 150, hair: 'short', hairColor: '#555', shirt: '#6a8a5a', pants: '#4a4a3a', acc: ['hat', 'beard'], hatColor: '#c8b06a' },
      idle: [
        { text: '今日もボウズだ……一匹も釣れなかった', when: [notDone('S2-E13'), notDone('S2-E14')] },
        { text: '家族に「大漁だ」って言っちゃったんだよなあ', when: [notDone('S2-E13'), notDone('S2-E14')] },
        { text: 'これで家でも胸をはれるぞ！', when: [done('S2-E13')] },
        { text: '……竿、持ってくればよかった', when: [done('S2-E14')] },
      ],
    },
    gaku: {
      name: 'ガク', x: 3080, y: 1330, wander: 70, speed: 50,
      look: { h: 120, hair: 'spiky', hairColor: '#3a2a1a', skin: '#f2c9a0', shirt: '#f28a3a', pants: '#3a5a8a', acc: ['cap'], hatColor: '#d33', kid: true },
      idle: [
        { text: '魚屋さんって、へんな生きものがいっぱい！', when: [notDone('S2-E53')] },
        { text: 'さわってみたいなあ……ぐにゃぐにゃしたやつとか', when: [notDone('S2-E53'), notDone('S2-E52')] },
        { text: 'まっくろ……母ちゃんに怒られる。どこかで洗い流さないと', when: [done('S2-E53'), notDone('S2-E54')] },
        { text: 'ピッカピカ！ お風呂ってすごい！', when: [done('S2-E54')] },
      ],
    },
    goma: {
      name: '野良猫のゴマ', emoji: '🐈', size: 60, x: 3200, y: 1240, wander: 160, speed: 70,
      idle: ['ニャ〜（魚屋のほうをじっと見ている）', 'ゴロゴロ……', { text: 'ニャフ〜（満足そう）', when: [done('S2-E15')] }],
    },
    mama: {
      name: 'チョロ吉の母', x: 3320, y: 1420, wander: 70, speed: 40,
      look: { h: 150, hair: 'pony', hairColor: '#4a2a1a', shirt: '#e8a86a', pants: '#5a5a7a', acc: ['bag'] },
      idle: [
        { text: 'チョロ吉ったら、どこ行ったのかしら', when: [notDone('S2-E45')] },
        { text: 'あの子、おもちゃばっかりほしがるんだから', when: [notDone('S2-E45')] },
        { text: 'あら？ どこからかチョロ吉の声がするわ……', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
      ],
    },
    harue: {
      name: 'ハルエ', x: 3000, y: 1420, path: [[2700, 1420], [4000, 1440], [3300, 1520]], speed: 35,
      look: { h: 150, hair: 'bob', hairColor: '#5a3a2a', shirt: '#a8c8e8', skirt: true, pants: '#6a7a9a', acc: ['apron', 'bag'] },
      idle: [
        { text: '今夜のごはん、なんにしようかしら……', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: '毎日考えるの、ほんと大変なのよ', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: 'お店の看板見てると、どれもおいしそうに見えるのよね', when: [notDone('S2-E10'), notDone('S2-E11'), notDone('S2-E12')] },
        { text: '献立が決まると、足どりも軽いわ♪', when: [anyDone('S2-E10', 'S2-E11', 'S2-E12')] },
      ],
    },
    manta: {
      name: 'マンタ', x: 3800, y: 1360, path: [[3550, 1350], [4060, 1360]], speed: 30,
      look: { h: 150, hair: 'short', hairColor: '#222', shirt: '#f2c14e', pants: '#6a4a2a', wide: true },
      idle: [
        'おなかすいた……',
        '看板を見てるだけで、よだれが……',
        { text: '辛いのは苦手だけど……だからこそ、あこがれるんだよね', when: [notDone('S2-E30')] },
        { text: 'ひーっ、まだ口が火事だ……', when: [done('S2-E30')] },
      ],
    },
    // ── 公園 ──
    thief: {
      name: 'コソ泥', x: 4230, y: 1180, wander: 10, speed: 30, minZoom: 1.5,
      look: { h: 145, hair: 'short', hairColor: '#111', skin: '#d8b090', shirt: '#2a2a2a', pants: '#2a2a2a', acc: ['mask', 'bag'] },
      idle: ['しーっ……', 'ヒッヒッ、木陰ならだれも気づくまい'],
    },
    noboru: {
      name: 'ノボル', x: 4420, y: 1300, wander: 120, speed: 60,
      look: { h: 118, hair: 'spiky', hairColor: '#222', shirt: '#5ac85a', pants: '#2a4a2a', acc: ['cap'], hatColor: '#2a7a2a', kid: true },
      idle: [
        { text: '高いところ、だーいすき！', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'この商店街で、いちばん高いところってどこだろう？', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'てっぺんから見る景色は、さいこうなんだ', when: [notDone('S2-E27'), notDone('S2-E28')] },
        { text: 'やっほー！ ぜんぶ見えるぞー！', when: [anyDone('S2-E27', 'S2-E28')] },
      ],
    },
    grandma: {
      name: 'ベンチのおばあちゃん', x: 4580, y: 1236, wander: 0,
      look: { h: 140, hair: 'bun', hairColor: '#ddd', shirt: '#a87ab0', pants: '#5a4a6a', acc: ['glasses'], old: true, sit: true },
      idle: ['ハトさん、お食べ', 'いい天気ねえ', { text: 'あら、となりのベンチ、空いたわねえ', when: [done('S2-E23'), notDone('S2-E19')] }],
    },
    nemuta: {
      name: '係長ネムタ', x: 5030, y: 1236, wander: 0,
      look: { h: 150, hair: 'short', hairColor: '#333', shirt: '#fff', pants: '#3a3a4a', acc: ['tie'], sit: true },
      idle: [
        { text: 'ぐう……ぐう……', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'むにゃ……部長、あと五分……', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'ぐう……（腕時計はしていないようだ）', when: [notDone('S2-E22'), notDone('S2-E23')] },
        { text: 'ちっ、犬のせいで目がさめた。……まあいいや、ゆっくりしよ', when: [done('S2-E22')] },
        { text: 'ハァハァ……会議、まにあった……？', when: [done('S2-E23')] },
      ],
    },
    dog: {
      name: '柴犬のポチ丸', emoji: '🐕', size: 66, x: 4800, y: 1500, wander: 220, speed: 80,
      idle: ['ワン！', 'クゥーン（動くものを目で追っている）', 'ハッハッハッ', { text: 'フンフン（ベンチのほうをかいでいる）', when: [notDone('S2-E22'), notDone('S2-E23')] }],
    },
    rikishi: {
      name: '力士・大樽', x: 4700, y: 1420, wander: 160, speed: 35,
      look: { h: 175, hair: 'topknot', hairColor: '#111', skin: '#f0c8a0', shirt: '#6a4a8a', pants: '#6a4a8a', wide: true },
      idle: [
        { text: '稽古のあとは、ひと休みしたいでごわす', when: [notDone('S2-E18'), notDone('S2-E19')] },
        { text: 'どこか腰をおろせる場所はないでごわすか', when: [notDone('S2-E18'), notDone('S2-E19')] },
        '体がでかいと、なにかと不便でごわす',
        { text: '汗と砂でどろどろでごわす。大きな湯船につかりたいでごわすなあ', when: [anyDone('S2-E18', 'S2-E19', 'S2-E47'), notDone('S2-E64')] },
        { text: 'いい湯でごわした！', when: [done('S2-E64')] },
      ],
    },
    sora: {
      name: 'ソラ', x: 4620, y: 1760, wander: 80, speed: 50,
      look: { h: 118, hair: 'short', hairColor: '#222', shirt: '#e44', pants: '#fff', acc: ['cap'], hatColor: '#e44', kid: true },
      idle: ['ピッチャーなら、まかせて！', '投げるの、得意なんだ', { text: '四番のおじさん、来ないかなあ', when: [notDone('S2-E38')] }],
    },
    umi: {
      name: 'ウミ', x: 4760, y: 1780, wander: 80, speed: 50,
      look: { h: 118, hair: 'short', hairColor: '#222', shirt: '#3a7ae8', pants: '#fff', acc: ['cap'], hatColor: '#3a7ae8', kid: true },
      idle: ['ソラより、ぼくのほうが球は速いよ！', 'ノーコンじゃないよ！ ……たぶん', 'キャッチボールしよー'],
    },
    minori: {
      name: 'ミノリ', x: 4330, y: 1900, wander: 30, speed: 40,
      look: { h: 122, hair: 'pony', hairColor: '#4a2a1a', shirt: '#ffd84a', skirt: true, pants: '#e88', acc: ['bag'], kid: true },
      idle: [
        { text: 'おつかい、たのまれたのに……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'あの犬がこわくて、お店に近づけないよ……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'なにか投げたら、追いかけていかないかな……', when: [notDone('S2-E39'), notDone('S2-E40')] },
        { text: 'えっと、なに買うんだっけ……赤いもの？ 白くて長いもの？', when: [anyDone('S2-E39', 'S2-E40'), notDone('S2-E41'), notDone('S2-E42'), notDone('S2-E43')] },
        { text: 'おつかい、できた！', when: [anyDone('S2-E41', 'S2-E42', 'S2-E43')] },
      ],
    },
    bulldog: {
      name: 'ブルドッグのドン', emoji: '🐶', size: 76, x: 4470, y: 1960, wander: 20, speed: 60,
      idle: [{ text: 'ウ〜……ガルル', when: [notDone('S2-E39'), notDone('S2-E40')] }, 'ブフッ', { text: 'ハッハッ（ボールに夢中だ）', when: [done('S2-E39'), notDone('S2-E44')] }],
    },
    police: {
      name: 'おまわりさん', x: 4890, y: 2010, wander: 40, speed: 40,
      look: { h: 160, hair: 'short', hairColor: '#222', shirt: '#2a3a6a', pants: '#2a3a6a', acc: ['hat'], hatColor: '#1a2a4a' },
      idle: [
        { text: '本日も異常なし！', when: [notDone('S2-E57')] },
        { text: 'この辺りに、ドロボウがひそんでいるらしい……', when: [notDone('S2-E57')] },
        'こまったことがあれば、交番へどうぞ',
        { text: 'お手がら、お手がら！', when: [done('S2-E57')] },
      ],
    },
    bikegirl: {
      name: 'コハル', emoji: '🚴‍♀️', size: 84, x: 3500, y: 1720, path: [[3300, 1720], [5600, 1720], [5600, 1790], [3300, 1790]], speed: 45,
      idle: [{ text: 'パパ、ぜったい離さないでね！', when: [notDone('S2-E44')] }, 'ほんとは、ひとりで乗れる気がするんだ', { text: 'ひとりで乗れたー！', when: [done('S2-E44')] }],
    },
    bikedad: {
      name: 'コハルの父', x: 3440, y: 1730, path: [[3300, 1730], [5600, 1730], [5600, 1800], [3300, 1800]], speed: 45,
      look: { h: 160, hair: 'short', hairColor: '#333', shirt: '#9ac87a', pants: '#4a4a4a', acc: ['glasses'] },
      idle: [
        { text: 'まだ手を離さないぞー！ パパがついてるからなー！', when: [notDone('S2-E44')] },
        { text: 'ひー、ひー……腰が……だれか、パパを走らせてくれ……', when: [notDone('S2-E44')] },
        { text: 'はあはあ……コハルが、ひとりで……！', when: [done('S2-E44')] },
      ],
    },
    // ── 東エリア ──
    choro: {
      name: 'チョロ吉', x: 5760, y: 1230, wander: 40, speed: 60,
      look: { h: 112, hair: 'spiky', hairColor: '#3a2a1a', shirt: '#e8e84a', pants: '#3a6ab0', kid: true },
      idle: [
        { text: 'ガチャガチャ、まわしたい！', when: [notDone('S2-E45')] },
        { text: 'おこづかい、もうないんだよなあ……だれかくれないかな', when: [notDone('S2-E45')] },
        { text: 'たすけて〜！ 下を見るとこわい〜！', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
        { text: 'お母さ〜ん！ それか、大きくて力もちの人〜！', when: [done('S2-E45'), notDone('S2-E46'), notDone('S2-E47')] },
        { text: 'もう木には登らない……たぶん', when: [anyDone('S2-E46', 'S2-E47')] },
      ],
    },
    tsubomi: {
      name: '花屋のツボミ', x: 6100, y: 1250, wander: 60, speed: 30,
      look: { h: 148, hair: 'long', hairColor: '#7a4a2a', shirt: '#f6f6e0', pants: '#7aa86a', skirt: true, acc: ['apron', 'flower'] },
      idle: [
        { text: '今日は日ざしが強いわね……', when: [notDone('S2-E25')] },
        { text: 'お店の前の子、元気がないの……', when: [notDone('S2-E25')] },
        'いらっしゃいませ〜',
      ],
    },
    takumi: {
      name: 'タクミ', x: 5600, y: 1520, path: [[5300, 1500], [6300, 1530]], speed: 38,
      look: { h: 155, hair: 'short', hairColor: '#5a3a1a', shirt: '#e8e8f8', pants: '#3a3a5a', acc: ['tie'] },
      idle: [
        { text: 'あの子に、なにか贈りたいんだけど……', when: [notDone('S2-E26')] },
        { text: '言葉じゃなくて、形にできたらなあ', when: [notDone('S2-E26')] },
        '気持ちを伝えるって、むずかしいな',
        { text: 'いててて……顔がぱんぱんだ……', when: [done('S2-E26')] },
      ],
    },
    hayate: {
      name: 'ハヤテ', x: 1200, y: 1620, path: [[300, 1620], [3000, 1660], [6800, 1620], [6800, 1840], [3000, 1880], [300, 1840]], speed: 95,
      look: { h: 155, hair: 'short', hairColor: '#222', shirt: '#f84', pants: '#222', acc: ['headphones'] },
      idle: [
        { text: 'ハッ、ハッ……のどが、からからだ……', when: [notDone('S2-E48'), notDone('S2-E49')] },
        'もっと速く走りたいんだ！',
        { text: 'うるおった！ あとは足もとをなんとかしたいな', when: [anyDone('S2-E48', 'S2-E49'), notDone('S2-E50'), notDone('S2-E51')] },
        { text: 'シューズがすりへっちゃってさ', when: [notDone('S2-E50'), notDone('S2-E51')] },
      ],
    },
    gin: {
      name: 'ギン', x: 5950, y: 1980, wander: 80, speed: 40,
      look: { h: 158, hair: 'mohawk', hairColor: '#e0389a', shirt: '#111', pants: '#222', acc: ['earring', 'sunglasses'] },
      idle: ['ロックは魂だぜ', 'オレの髪型、イカしてるだろ？', '今夜のライブ、客が来るといいんだが'],
    },
    peddler: {
      name: '行商のおばあさん', x: 3600, y: 1830, path: [[3000, 1830], [6000, 1850]], speed: 22,
      look: { h: 135, hair: 'bun', hairColor: '#eee', shirt: '#6a7a5a', pants: '#4a4a3a', acc: ['scarf'], old: true },
      idle: ['だいこーん、だいこんはいらんかね〜', '畑でとれたての野菜だよ', '重たいねえ、だれか買っとくれ'],
    },
    magobe: {
      name: '観光客のマゴベエ', x: 6700, y: 1600, wander: 70, speed: 35,
      look: { h: 150, hair: 'short', hairColor: '#999', shirt: '#f6e86a', pants: '#a87a4a', acc: ['camera', 'cap'], old: true },
      idle: [
        { text: '地図がさかさまだ……ここ、どこだろう', when: [notDone('S2-E58')] },
        { text: 'こういうときは、だれに聞けばいいんだっけ', when: [notDone('S2-E58')] },
        '伝説のコロッケ、ひと口でいいから食べたいなあ',
        { text: '道はわかった。……でも、ほんとにこっちで運が開けるのかな', when: [done('S2-E58'), notDone('S2-E59')] },
      ],
    },
    hoshimi: {
      name: '銭湯の娘ホシミ', x: 6500, y: 1260, wander: 50, speed: 30,
      look: { h: 148, hair: 'pony', hairColor: '#2a1a12', shirt: '#f6f0e6', pants: '#2b4a8a', acc: ['apron'] },
      idle: [
        { text: 'お母さんの形見のイヤリング……なくしちゃった', when: [notDone('S2-E63')] },
        { text: '朝、喫茶店でモーニングを食べて……そのあとは、どこを通ったっけ', when: [notDone('S2-E63')] },
        { text: '星のかたちの、小さいのなの。キラッて光るんだ', when: [notDone('S2-E63')] },
        { text: 'よーし！ 今日はとびきり熱いお風呂、わかすよ！', when: [done('S2-E63')] },
      ],
    },
    gonji: {
      name: '釜焚きのゴン爺', x: 7060, y: 1200, wander: 0,
      look: { h: 140, hair: 'bald', hairColor: '#ddd', shirt: '#5a4a3a', pants: '#3a3a2a', acc: ['scarf', 'beard'], old: true, sit: true },
      idle: [
        { text: 'お嬢がしょげとると、釜の火も元気が出ん', when: [notDone('S2-E63')] },
        'マッチを切らしてしもうた……どこかにないかのう',
        '昔はのう、この煙突から火柱が上がったもんじゃ',
        { text: 'お嬢が笑うた。じゃが、今日の湯は大物の客が来んと焚きがいがないのう', when: [done('S2-E63'), notDone('S2-E64')] },
        { text: '湯船に横綱級の客が来とる……血がたぎるわい！ 火種はまだか！', when: [done('S2-E63'), done('S2-E64')] },
      ],
    },
  },
  objects: {
    // 西
    salonSign: { name: '美容院の看板', sign: { text: 'ヘアサロン ふわり', fill: '#c76b8a', color: '#fff', s: 26 }, w: 300, h: 70, x: 455, y: 640 },
    hairPoster: { name: '髪型ポスター', sign: { text: '今月の おすすめ アフロ', fill: '#fff6d0', color: '#a33', s: 18 }, w: 90, h: 120, x: 330, y: 1010 },
    chonmageSign: { name: '時代劇ポスター', sign: { text: 'まげ侍 参上', fill: '#2a1a12', color: '#f4d35e', s: 18 }, w: 90, h: 120, x: 850, y: 1010 },
    match: { name: 'マッチ箱', sign: { text: 'MATCH', fill: '#c0392b', color: '#fff', s: 11 }, w: 44, h: 28, x: 1170, y: 1176, minZoom: 1.2 },
    earring: { name: '星のイヤリング', emoji: '⭐', size: 22, x: 1060, y: 1310, minZoom: 1.6, rot: 0.4 },
    elecSign: { name: '電器店の看板', sign: { text: '⚡ 明るい未来の デンキのイナズマ', fill: '#f4d35e', color: '#2a4a8a', s: 22 }, w: 420, h: 72, x: 1480, y: 600 },
    tv: { name: '店頭のテレビ', sign: { text: 'プロ野球 まもなく中継', fill: '#222', color: '#fff', s: 16 }, w: 160, h: 110, x: 1390, y: 1080 },
    vision: { name: '街頭ビジョン', sign: { text: '🌊 ワカメで フサフサ♪', fill: '#1d6b8a', color: '#fff', s: 16 }, w: 180, h: 110, x: 1600, y: 515 },
    pawn: { name: '質屋の看板', sign: { text: '質 かめや', fill: '#fff', color: '#222', s: 26 }, w: 200, h: 70, x: 1670, y: 2180 },
    // 薬局・歯科・本屋
    pharmSign: { name: '薬局の看板', sign: { text: 'まちの薬局 プロテイン特売中', fill: '#2e8a5a', color: '#fff', s: 20 }, w: 320, h: 70, x: 1890, y: 610 },
    goodMed: { name: 'ビタミン剤のポスター', sign: { text: '元気百倍 ビタミンZ', fill: '#e8ffd8', color: '#2a7a2a', s: 16 }, w: 100, h: 110, x: 1790, y: 1020 },
    badMed: { name: 'あやしい薬の屋台', sign: { text: '毛がはえる？ 謎の薬 ¥100', fill: '#5a2a6a', color: '#f4d35e', s: 14 }, w: 120, h: 80, x: 2010, y: 1200 },
    dentistPoster: { name: '歯医者のポスター', sign: { text: '🦷 ムシ歯は こわいぞ', fill: '#fff', color: '#2a5a8a', s: 16 }, w: 110, h: 110, x: 2210, y: 1020 },
    photobook: { name: 'アイドル写真集', emoji: '📕', size: 40, x: 2600, y: 1150 },
    // 魚屋・肉屋・食べもの
    fishSign: { name: '魚屋の看板', sign: { text: '鮮魚 しおかぜ', fill: '#1d5b8a', color: '#fff', s: 26 }, w: 340, h: 70, x: 2955, y: 610 },
    tankFish: { name: '水槽の魚', emoji: '🐠', size: 34, x: 2815, y: 1080 },
    fish: { name: '店先のサンマ', emoji: '🐟', size: 40, x: 2940, y: 1120 },
    crab: { name: 'カニ', emoji: '🦀', size: 36, x: 3020, y: 1125, minZoom: 1.1 },
    octopus: { name: 'タコ', emoji: '🐙', size: 40, x: 3080, y: 1122 },
    meatSign: { name: '肉屋の看板', sign: { text: '精肉 にくまる コロッケあり', fill: '#a33', color: '#fff', s: 20 }, w: 260, h: 70, x: 3320, y: 610 },
    burgerSign: { name: 'ハンバーガー店の看板', sign: { text: '🍔 BIG BURGER', fill: '#e2702a', color: '#fff', s: 26 }, w: 300, h: 70, x: 3650, y: 600 },
    currySign: { name: 'カレー屋の看板', sign: { text: '激辛カレー 地獄', fill: '#8a1a0a', color: '#ffd84a', s: 22 }, w: 240, h: 66, x: 3970, y: 620 },
    // 公園
    jungleGym: { name: 'ジャングルジム', sign: { text: '', fill: 'rgba(255,255,255,0.05)', color: '#fff', s: 10 }, w: 170, h: 190, x: 4400, y: 1105 },
    bench1: { name: 'ベンチ（使用中）', sign: { text: '', fill: '#8a5a33', color: '#fff', s: 10 }, w: 170, h: 30, x: 4590, y: 1250 },
    clock: { name: '公園の時計', emoji: '🕒', size: 56, x: 4781, y: 1010 },
    fountain: { name: '水飲み場', emoji: '🚰', size: 46, x: 4900, y: 1215 },
    bench2: { name: 'ベンチ', sign: { text: '', fill: '#8a5a33', color: '#fff', s: 10 }, w: 170, h: 30, x: 5040, y: 1250 },
    rccar: { name: 'ラジコンカー', emoji: '🏎️', size: 42, x: 5700, y: 1215 },
    // 東
    tanSign: { name: '日焼けサロンの看板', sign: { text: '日焼けサロン こんがり', fill: '#c8641a', color: '#fff', s: 22 }, w: 280, h: 66, x: 5450, y: 620 },
    babyDoll: { name: '赤ちゃん人形', emoji: '👶', size: 40, x: 5900, y: 1070 },
    flowerSign: { name: '花屋の看板', sign: { text: '花のアトリエ', fill: '#4a9a5a', color: '#fff', s: 24 }, w: 240, h: 64, x: 6115, y: 620 },
    wiltedFlower: { name: 'しおれた花', emoji: '🥀', size: 40, x: 6060, y: 1150 },
    sentoSign: { name: '銭湯の看板', sign: { text: '♨ さくら湯', fill: '#2b4a8a', color: '#fff', s: 30 }, w: 280, h: 80, x: 6570, y: 600 },
    noren: { name: '銭湯ののれん', sign: { text: 'ゆ', fill: '#2b4a8a', color: '#fff', s: 50 }, w: 160, h: 110, x: 6560, y: 1110 },
    chimneyTop: { name: '銭湯の煙突', sign: { text: 'ゆ', fill: '#8b4a3a', color: '#fff', s: 34 }, w: 64, h: 110, x: 6910, y: 560 },
    // 南側
    skates: { name: 'ローラースケート', emoji: '🛼', size: 44, x: 2660, y: 2075 },
    ironGeta: { name: '鉄下駄', emoji: '🩴', size: 40, x: 2820, y: 2075, minZoom: 1.1 },
    vending: { name: '自販機', sign: { text: 'のみもの', fill: '#d33', color: '#fff', s: 16 }, w: 80, h: 150, x: 3000, y: 2085 },
    apple: { name: 'リンゴ', emoji: '🍎', size: 40, x: 4200, y: 2090 },
    kakiPoster: { name: '柿のポスター', sign: { text: '🟠 甘い柿 入荷', fill: '#fff6e0', color: '#c8641a', s: 16 }, w: 150, h: 60, x: 4480, y: 2200 },
    koban: { name: '交番', sign: { text: '交番', fill: '#fff', color: '#2a3a6a', s: 28 }, w: 160, h: 64, x: 4890, y: 2180 },
    // イベントのない、撮れる物（ダミー）
    umbrella: { name: '置き傘', emoji: '🌂', size: 40, x: 1290, y: 1230 },
    mailbox: { name: 'ポスト', emoji: '📮', size: 56, x: 2340, y: 1230 },
    cone: { name: 'カラーコーン', emoji: '🚧', size: 46, x: 3460, y: 1890 },
    trash: { name: 'ごみ箱', emoji: '🗑️', size: 44, x: 4130, y: 1240 },
    newspaper: { name: '新聞', emoji: '📰', size: 30, x: 4520, y: 1230, minZoom: 1.2 },
    balloon: { name: '風船', emoji: '🎈', size: 40, x: 5640, y: 1020 },
    bicycle: { name: '止めてある自転車', emoji: '🚲', size: 60, x: 6260, y: 1240 },
    bucket: { name: '風呂おけ', emoji: '🪣', size: 34, x: 6440, y: 1220 },
    // イベントで出てくる物
    toupee: { name: 'かつら', emoji: '🦱', size: 34, x: 860, y: 1440, hidden: true },
    propeller: { name: '竹とんぼ', emoji: '🪁', size: 34, x: 5230, y: 760, hidden: true },
    bee: { name: 'ハチ', emoji: '🐝', size: 28, x: 6060, y: 1100, hidden: true },
    ball: { name: '野球ボール', emoji: '⚾', size: 30, x: 4700, y: 1720, hidden: true },
    pawnBag: { name: '質流れのバッグ', emoji: '👜', size: 36, x: 1600, y: 2240, hidden: true },
    pawnNecklace: { name: '質流れのネックレス', emoji: '📿', size: 32, x: 1740, y: 2240, hidden: true },
  },
  paths: {
    rcLoop: { points: [[5550, 1320], [5200, 1460], [4800, 1360], [4900, 1580], [5450, 1520], [5700, 1215]], speed: 220, loop: false },
    dogChase: { points: [[5530, 1330], [5180, 1470], [4790, 1370], [4890, 1590], [5430, 1530], [5000, 1500]], speed: 200, loop: false },
    jog: { points: [[300, 1620], [3000, 1660], [6800, 1620], [6800, 1840], [3000, 1880], [300, 1840]], speed: 95, loop: true },
  },
  reactions: [
    { s: 'match', t: 'gonji', say: 'お嬢があの調子じゃ、釜を焚く気になれんわい', when: [notDone('S2-E63')], anim: 'react.sad' },
    { s: 'match', t: 'gonji', say: '火種はある。じゃが、こんな日は大物の客が来てからじゃ', when: [done('S2-E63'), notDone('S2-E64')], anim: 'react.think' },
    { s: 'salonSign', t: 'teruo', say: 'わしには関係ない店じゃ……（帽子……いや、頭をおさえている）', anim: 'react.shrug' },
    { s: 'fish', t: 'fishman', say: 'それは売りもんだよ！', anim: 'react.angry' },
    { s: 'photobook', t: 'nobu', say: 'ぼ、ぼくはそういうのは……', anim: 'react.embarrassed' },
    { s: 'earring', t: 'kirari', say: 'かわいい〜。でも、あたしのじゃないな', anim: 'react.shrug' },
    { s: 'noren', t: 'hoshimi', say: 'うちのお風呂、今日はなんだか元気ないの', when: [notDone('S2-E63')], anim: 'react.sad' },
    { s: 'clock', t: 'batter', say: 'ナイターまで、まだまだだなあ', anim: 'react.shrug' },
  ],
  timeline: [
    { every: 60000, start: 40000, effects: [{ type: 'PLAY_SOUND', soundId: 'bell' }, { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'タイムセールだよー！ 安いよ安いよー！' }] },
    { at: 150000, effects: [{ type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'そろそろ釜の時間じゃが……' }] },
    { at: 240000, effects: [{ type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'もうすぐ夕方……お風呂、わかさなきゃ' }] },
  ],
  exclusiveGroups: [],
  events: [
    // ── ミツルの髪型（E01〜E07）・テルオ（E08〜E09） ──
    { id: 'S2-E01', s: 'salonSign', t: 'mitsuru', cat: 'CHAIN', title: 'ミツル、髪型の多さに目を回す', say: '髪型って、こんなに種類が……め、目が回る〜', anim: 'react.spin', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'teruo', to: [820, 1420], speed: 200, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [780, 1410], speed: 120, delayMs: 300 },
        { type: 'FX', kind: 'stars', at: 'teruo', delayMs: 2600 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { hair: 'bald' }, delayMs: 2700 },
        { type: 'SPAWN_OBJECT', objectId: 'toupee', delayMs: 2700 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'ああっ！ わしの……わしの毛が！', delayMs: 3000 },
        { type: 'ACTOR_SET_STATE', actorId: 'teruo', state: 'EMBARRASSED', delayMs: 3000 },
        { type: 'ACTOR_MOVE', actorId: 'teruo', to: [1100, 1420], speed: 50, wander: 120, delayMs: 7000 },
      ],
      after: [{ actor: 'teruo', text: 'みんな見とる……ええい、いっそ明るく開き直るか、海藻にでもすがるか……', delay: 5200 }] },
    { id: 'S2-E02', s: 'hairPoster', t: 'mitsuru', cat: 'BRANCH', group: 'S2-HAIR', title: 'ミツル、アフロになる', say: 'これだ！ 今月のおすすめにしよう！', anim: 'react.happy', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [440, 1180], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2200 }, { type: 'FX', kind: 'smoke', x: 450, y: 1050, delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'afro', hairColor: '#2b1a10' }, delayMs: 3000 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4600 }, { type: 'FX', kind: 'sparkle', at: 'mitsuru', delayMs: 4700 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'ボリューム満点！ 前が見えないけど！', delayMs: 5000 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [600, 1360], speed: 60, wander: 100, delayMs: 6500 },
      ] },
    { id: 'S2-E03', s: 'teruo', t: 'mitsuru', cat: 'BRANCH', group: 'S2-HAIR', requires: ['S2-E08'], blocksIfCompleted: ['S2-E07'], title: 'ミツル、光の坊主頭になる', say: 'そのまぶしさ……ぼくも光りたい！ 全部そってください！', anim: 'react.sparkle', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [770, 1180], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2000 }, { type: 'FX', kind: 'smoke', x: 775, y: 1050, delayMs: 2400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'bald' }, delayMs: 2800 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4400 }, { type: 'FX', kind: 'flash', at: 'mitsuru', delayMs: 4500 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'おお、同志よ！', delayMs: 5200 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [700, 1380], speed: 60, wander: 100, delayMs: 6000 },
      ] },
    { id: 'S2-E04', s: 'chonmageSign', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E07'], title: 'ミツル、ちょんまげになる', say: 'まげ……！ 武士の心意気、いただきます！', anim: 'react.happy', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [770, 1180], speed: 160, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'mitsuru', delayMs: 2000 }, { type: 'FX', kind: 'smoke', x: 775, y: 1050, delayMs: 2400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'topknot', hairColor: '#111' }, delayMs: 2800 },
        { type: 'ACTOR_SHOW', actorId: 'mitsuru', delayMs: 4400 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'でござる！ ……ちょっと首がすーすーする', delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'mitsuru', to: [700, 1380], speed: 60, wander: 100, delayMs: 6000 },
      ] },
    { id: 'S2-E05', s: 'gin', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E07'], title: 'ミツル、パンクなトサカ頭に', say: 'うおお、ロックだ！ ぼくもあのトサカにする！', anim: 'react.transform', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'mohawk', hairColor: '#e0389a', acc: ['earring'] } },
        { type: 'PLAY_SOUND', soundId: 'roar', delayMs: 300 }, { type: 'FX', kind: 'notes', at: 'mitsuru', delayMs: 500 },
        { type: 'ACTOR_SPEECH', actorId: 'gin', text: 'へっ、わかってるじゃねえか', delayMs: 2400 },
      ] },
    { id: 'S2-E06', s: 'yanagi', t: 'mitsuru', cat: 'FLAVOR', group: 'S2-HAIR', blocksIfCompleted: ['S2-E17'], title: 'ミツル、大人の色気ヘアに', say: 'あの人みたいに、しっとり大人っぽく……！', anim: 'react.sparkle', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'long', hairColor: '#2a1a12', acc: ['sunglasses'] } },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: '……ふっ。（かっこつけている）', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'yanagi', text: 'ゴホッ……マネされると、悪い気はしないね', delayMs: 3200 },
      ] },
    { id: 'S2-E07', s: 'babyDoll', t: 'mitsuru', cat: 'FLAVOR', blocksIfCompleted: ['S2-E03', 'S2-E04', 'S2-E05'], title: 'ミツル、赤ちゃんヘアに', say: 'かわいい……！ このちょこんとした感じ、いいかも', anim: 'react.love', route: 'S2.route.hair',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'mitsuru', look: { hair: 'twin', hairColor: '#d8a860', acc: ['ribbon'] } },
        { type: 'FX', kind: 'hearts', at: 'mitsuru', delayMs: 300 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'え、あれ、かわいくない？', delayMs: 2400 },
      ] },
    { id: 'S2-E08', s: 'elecSign', t: 'teruo', cat: 'CHAIN', group: 'S2-TERUO', requires: ['S2-E01'], title: 'テルオの頭がピカッと光る', say: '「明るい未来」……そうじゃ、わしの頭も明るいんじゃ！', anim: 'react.sparkle', route: 'S2.route.teruo',
      fx: [
        { type: 'FX', kind: 'flash', at: 'teruo', delayMs: 200 }, { type: 'FX', kind: 'sparkle', at: 'teruo', delayMs: 700 },
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { skin: '#ffe9b8' } },
        { type: 'ACTOR_SET_STATE', actorId: 'teruo', state: 'HAPPY' }, { type: 'SET_FLAG', id: 'teruo.shiny', value: true },
        { type: 'FX', kind: 'flash', at: 'teruo', delayMs: 2600 },
      ],
      after: [{ actor: 'mitsuru', text: 'な、なんだあのまぶしい人……かっこいい……', delay: 3600 }] },
    { id: 'S2-E09', s: 'vision', t: 'teruo', cat: 'FLAVOR', group: 'S2-TERUO', requires: ['S2-E01'], title: 'テルオ、ワカメヘアになる', say: 'ワカメ……ワカメ……おお！？ 生えてきた！ うねうねじゃ！', anim: 'react.transform', route: 'S2.route.teruo',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'teruo', look: { hair: 'long', hairColor: '#2e5b34' }, delayMs: 400 },
        { type: 'FX', kind: 'bubbles', at: 'teruo', delayMs: 600 }, { type: 'PLAY_SOUND', soundId: 'tv' },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: 'あの人の髪……磯のかおりがする……', delayMs: 3000 },
      ] },
    // ── 献立（E10〜E12） ──
    { id: 'S2-E10', s: 'fishSign', t: 'harue', cat: 'BRANCH', group: 'S2-DINNER', title: 'ハルエ、今夜は魚の煮つけ', say: '決めた！ 今夜はお魚の煮つけにしましょ', anim: 'react.think', route: 'S2.route.dinner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'harue', to: [2960, 1260], speed: 120, wander: 30 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'へいらっしゃい！ 奥さん、今日のキンメはいいよ！', delayMs: 3000 },
        { type: 'SET_FLAG', id: 'dinner', value: 'fish' },
      ] },
    { id: 'S2-E11', s: 'meatSign', t: 'harue', cat: 'FLAVOR', group: 'S2-DINNER', title: 'ハルエ、揚げものに決める', say: 'コロッケ！ メンチ！ 今夜は揚げものパーティーよ！', anim: 'react.happy', route: 'S2.route.dinner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'harue', to: [3320, 1260], speed: 120, wander: 30 }, { type: 'SET_FLAG', id: 'dinner', value: 'fry' }, { type: 'FX', kind: 'steam', at: 'meatSign', delayMs: 1200 }] },
    { id: 'S2-E12', s: 'burgerSign', t: 'harue', cat: 'FLAVOR', group: 'S2-DINNER', decoy: true, title: 'ハルエ、料理を放棄する', say: '……もう作るのやめた！ 今夜はハンバーガー！', anim: 'react.laugh', route: 'S2.route.dinner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'harue', to: [3650, 1260], speed: 140, wander: 30 }, { type: 'SET_FLAG', id: 'dinner', value: 'burger' }, { type: 'ACTOR_SPEECH', actorId: 'manta', text: 'いいなあ……', delayMs: 3200 }] },
    // ── 魚屋（E13〜E15・E52〜E53） ──
    { id: 'S2-E13', s: 'fishSign', t: 'tsurita', cat: 'FLAVOR', group: 'S2-TSURITA', title: 'ツリタ、釣果を魚屋で買う', say: '釣れないなら……買えばいいじゃないか！', anim: 'react.think', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsurita', to: [2900, 1250], speed: 100, wander: 20 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'まいど！ 「釣りました」って顔して持って帰んな！', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'tsurita', look: { acc: ['hat', 'beard', 'bag'] }, delayMs: 3000 },
        { type: 'ACTOR_SET_STATE', actorId: 'tsurita', state: 'HAPPY', delayMs: 3000 },
      ] },
    { id: 'S2-E14', s: 'tankFish', t: 'tsurita', cat: 'FLAVOR', group: 'S2-TSURITA', title: 'ツリタ、水槽で釣りを始める', say: 'おっ、いい魚影……ここで釣ればボウズ脱出だ！', anim: 'react.happy', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsurita', to: [2820, 1200], speed: 100, wander: 0 },
        { type: 'FX', kind: 'splash', at: 'tankFish', delayMs: 2000 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'お客さん！ それは売りもんでも釣り堀でもないよ！', delayMs: 2600 },
        { type: 'ACTOR_SET_STATE', actorId: 'tsurita', state: 'EMBARRASSED', delayMs: 3600 },
      ] },
    { id: 'S2-E15', s: 'fish', t: 'goma', cat: 'FLAVOR', title: 'ゴマ、サンマをかっさらう', say: 'ニャッ！', anim: 'react.run', route: 'S2.route.fish',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'goma', to: [2940, 1150], speed: 260, wander: 0 },
        { type: 'HIDE_OBJECT', objectId: 'fish', delayMs: 1600 },
        { type: 'ACTOR_MOVE', actorId: 'goma', to: [4600, 1340], speed: 300, wander: 140, delayMs: 1700 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'こらーっ！ ドロボウ猫ーっ！', delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'fishman', state: 'ANGRY', delayMs: 2000 },
      ] },
    // ── ヤナギ（E16〜E17） ──
    { id: 'S2-E16', s: 'goodMed', t: 'yanagi', cat: 'BRANCH', group: 'S2-YANAGI', title: 'ヤナギ、ビタミンで血色ばつぐん', say: 'ビタミン……そうか、栄養が足りてなかったんだ！ 力がみなぎる！', anim: 'react.sparkle', route: 'S2.route.yanagi',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'yanagi', look: { skin: '#f6c49a', acc: [] }, delayMs: 300 },
        { type: 'ACTOR_SET_STATE', actorId: 'yanagi', state: 'HAPPY' },
        { type: 'ACTOR_MOVE', actorId: 'yanagi', to: [2600, 1500], speed: 180, wander: 200, delayMs: 1800 },
      ] },
    { id: 'S2-E17', s: 'badMed', t: 'yanagi', cat: 'FLAVOR', group: 'S2-YANAGI', decoy: true, title: 'ヤナギ、あやしい薬で髪が抜ける', say: 'もっと髪にツヤを……ゴクッ。……あれ？ 頭がかるい……', anim: 'react.transform', route: 'S2.route.yanagi',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'yanagi', look: { hair: 'bald' }, delayMs: 800 },
        { type: 'FX', kind: 'leaves', at: 'yanagi', delayMs: 800 },
        { type: 'ACTOR_SET_STATE', actorId: 'yanagi', state: 'SAD', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'teruo', text: 'ようこそ、こちら側へ……', delayMs: 3200 },
      ] },
    // ── 力士・ベンチ・公園（E18〜E24） ──
    { id: 'S2-E18', s: 'bench1', t: 'rikishi', cat: 'FLAVOR', title: '力士、満員のベンチに座りそこねる', say: 'ごっつぁんです、ちょっと失礼……おわっ！', anim: 'react.fall', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [4640, 1270], speed: 140, wander: 0 },
        { type: 'FX', kind: 'smoke', at: 'rikishi', delayMs: 1800 }, { type: 'PLAY_SOUND', soundId: 'crash', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'grandma', text: 'あらまあ、お相撲さん。ここは満員ですよ', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [4700, 1420], speed: 40, wander: 140, delayMs: 6000 },
      ],
      after: [{ actor: 'rikishi', text: 'いてて……砂まみれでごわす。ひとっ風呂あびたいでごわす', delay: 4200 }] },
    { id: 'S2-E19', s: 'bench2', t: 'rikishi', cat: 'CHAIN', requires: ['S2-E23'], title: '力士、ベンチをまっぷたつ', say: 'おお、空いてるでごわす！ どっこいしょ……', anim: 'react.fall', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5040, 1265], speed: 140, wander: 0 },
        { type: 'OBJECT_SET_STATE', objectId: 'bench2', state: 'BROKEN', delayMs: 2400 },
        { type: 'OBJECT_APPEARANCE', objectId: 'bench2', look: { rot: 0.3 }, delayMs: 2400 },
        { type: 'FX', kind: 'stars', at: 'rikishi', delayMs: 2400 }, { type: 'PLAY_SOUND', soundId: 'crash', delayMs: 2400 },
        { type: 'ACTOR_SPEECH', actorId: 'grandma', text: 'あらあら、ベンチがまっぷたつ', delayMs: 3600 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [4900, 1420], speed: 40, wander: 140, delayMs: 6000 },
      ],
      after: [{ actor: 'rikishi', text: 'もうしわけないでごわす……汗と砂で、どろどろでごわす', delay: 4600 }] },
    { id: 'S2-E20', s: 'rikishi', t: 'anzu', cat: 'FLAVOR', group: 'S2-ANZU', title: 'アンズ、力士のお腹を見ておやつをがまん', say: 'あのお腹……！ あたし、やっぱりおやつはがまんする！', anim: 'react.surprised', route: 'S2.route.sweets',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'anzu', to: [2700, 1750], speed: 120, wander: 80 }, { type: 'ACTOR_SET_STATE', actorId: 'anzu', state: 'RESOLVED', delayMs: 1500 }] },
    { id: 'S2-E21', s: 'dentistPoster', t: 'anzu', cat: 'FLAVOR', group: 'S2-ANZU', title: 'アンズ、ムシ歯がこわくて和菓子をあきらめる', say: 'ムシ歯……！ ひいっ、今日はやめとく！', anim: 'react.scared', route: 'S2.route.sweets',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'anzu', to: [2100, 1760], speed: 160, wander: 80 }, { type: 'ACTOR_SET_STATE', actorId: 'anzu', state: 'RESOLVED', delayMs: 1500 }] },
    { id: 'S2-E22', s: 'nemuta', t: 'dog', cat: 'BRANCH', group: 'S2-NEMUTA', title: 'ポチ丸、昼寝の係長をほえて起こす', say: 'ワンワンワン！', anim: 'react.angry', route: 'S2.route.park',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [5080, 1290], speed: 220, wander: 0 },
        { type: 'PLAY_SOUND', soundId: 'surprise', delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'nemuta', text: 'うわっ！ ……な、なんだ犬か。おどかすなよ……', delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'nemuta', state: 'ANGRY', delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [4800, 1500], speed: 80, wander: 220, delayMs: 5000 },
      ] },
    { id: 'S2-E23', s: 'clock', t: 'nemuta', cat: 'CHAIN', group: 'S2-NEMUTA', title: '係長、時計を見て飛び起きる', say: 'えっ、もうこんな時間！？ 会議、会議ーっ！', anim: 'react.wake', route: 'S2.route.park',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'nemuta', look: { sit: false } },
        { type: 'ACTOR_MOVE', actorId: 'nemuta', to: [6750, 1700], speed: 280, wander: 60, delayMs: 600 },
        { type: 'SET_FLAG', id: 'bench2.empty', value: true },
        { type: 'FX', kind: 'paper', at: 'nemuta', delayMs: 600 },
      ],
      after: [{ actor: 'grandma', text: 'あら、となりのベンチが空いたわねえ。大きい人でも座れそう', delay: 3200 }] },
    { id: 'S2-E24', s: 'rccar', t: 'dog', cat: 'FLAVOR', title: 'ポチ丸、ラジコンを追いかけまわす', say: 'ワンワン！ ワオーン！', anim: 'react.run', route: 'S2.route.park',
      fx: [
        { type: 'OBJECT_MOVE', objectId: 'rccar', pathId: 'rcLoop' }, { type: 'PLAY_SOUND', soundId: 'vehicle' },
        { type: 'ACTOR_MOVE', actorId: 'dog', pathId: 'dogChase', delayMs: 400 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'あーっ！ お店のラジコンが走ってる！', delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'dog', to: [4800, 1500], speed: 80, wander: 220, delayMs: 14000 },
      ] },
    // ── 花屋（E25〜E26） ──
    { id: 'S2-E25', s: 'wiltedFlower', t: 'tsubomi', cat: 'FLAVOR', title: 'ツボミ、しおれた花に水をやる', say: 'あっ、この子しおれてる！ お水、お水！', anim: 'react.happy', route: 'S2.route.flower',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'tsubomi', to: [6020, 1170], speed: 120, wander: 0 },
        { type: 'FX', kind: 'splash', at: 'wiltedFlower', delayMs: 1800 },
        { type: 'OBJECT_APPEARANCE', objectId: 'wiltedFlower', look: { emoji: '🌷' }, delayMs: 2600 },
        { type: 'FX', kind: 'sparkle', at: 'wiltedFlower', delayMs: 2600 },
        { type: 'ACTOR_MOVE', actorId: 'tsubomi', to: [6100, 1250], speed: 40, wander: 60, delayMs: 5000 },
      ] },
    { id: 'S2-E26', s: 'flowerSign', t: 'takumi', cat: 'FLAVOR', title: 'タクミ、花束を買ってハチに刺される', say: '花……そうか、花をおくれば気持ちが伝わる！', anim: 'react.happy', route: 'S2.route.flower',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'takumi', to: [6080, 1240], speed: 120, wander: 0 },
        { type: 'SPAWN_OBJECT', objectId: 'bee', delayMs: 2600 }, { type: 'OBJECT_MOVE', objectId: 'bee', to: [6080, 1120], speed: 80, delayMs: 2700 },
        { type: 'FX', kind: 'stars', at: 'takumi', delayMs: 4000 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 4000 },
        { type: 'ACTOR_SPEECH', actorId: 'takumi', text: 'いてっ！ ハ、ハチ！？', delayMs: 4100 },
        { type: 'ACTOR_APPEARANCE', actorId: 'takumi', look: { skin: '#f4a6a0', wide: true }, delayMs: 4300 },
        { type: 'HIDE_OBJECT', objectId: 'bee', delayMs: 5500 },
        { type: 'ACTOR_SPEECH', actorId: 'tsubomi', text: 'だ、大丈夫ですか！？ 花束、おまけしときますね……', delayMs: 6000 },
        { type: 'ACTOR_MOVE', actorId: 'takumi', to: [5600, 1520], speed: 30, wander: 150, delayMs: 8000 },
      ] },
    // ── ノボル（E27〜E29） ──
    { id: 'S2-E27', s: 'jungleGym', t: 'noboru', cat: 'FLAVOR', group: 'S2-CLIMB', title: 'ノボル、ジャングルジムのてっぺんへ', say: 'てっぺん、いっただきー！', anim: 'react.happy', route: 'S2.route.climb',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'noboru', to: [4400, 1120], speed: 160, wander: 0 }, { type: 'ACTOR_MOVE', actorId: 'noboru', to: [4400, 925], speed: 70, wander: 0, delayMs: 2600 }, { type: 'FX', kind: 'confetti', at: 'noboru', delayMs: 5600 }] },
    { id: 'S2-E28', s: 'chimneyTop', t: 'noboru', cat: 'FLAVOR', group: 'S2-CLIMB', title: 'ノボル、銭湯の煙突によじ登る', say: 'あの煙突、商店街でいちばん高い！ 行ってくる！', anim: 'react.run', route: 'S2.route.climb',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [6960, 1130], speed: 320, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [6960, 460], speed: 90, wander: 0, delayMs: 9000 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'こりゃーっ！ 煙突は遊び場じゃないわい！', delayMs: 10000 },
        { type: 'ACTOR_SPEECH', actorId: 'noboru', text: 'やっほー！ 海まで見えるー！', delayMs: 17000 },
      ] },
    { id: 'S2-E29', s: 'choro', t: 'noboru', cat: 'FLAVOR', requires: ['S2-E45'], blocksIfCompleted: ['S2-E27', 'S2-E28', 'S2-E46', 'S2-E47'], title: 'ノボル、木のぼり救出に失敗', say: 'まかせろ！ 木のぼりならオレが……うわあっ！', anim: 'react.fall', route: 'S2.route.climb',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [5140, 1270], speed: 200, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [5140, 950], speed: 80, wander: 0, delayMs: 4500 },
        { type: 'FX', kind: 'leaves', at: 'noboru', delayMs: 8500 },
        { type: 'ACTOR_MOVE', actorId: 'noboru', to: [5140, 1280], speed: 400, wander: 60, delayMs: 8600 },
        { type: 'FX', kind: 'stars', at: 'noboru', delayMs: 9600 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'ノボルにいちゃーん！ ……オレ、まだ降りられないよー！', delayMs: 10200 },
      ] },
    // ── マンタ（E30〜E31） ──
    { id: 'S2-E30', s: 'currySign', t: 'manta', cat: 'FLAVOR', title: 'マンタ、激辛カレーに挑んで火をふく', say: '辛いのダメだけど……挑戦する！ ……かっらーーーっ！！', anim: 'react.fire', route: 'S2.route.hungry',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [3970, 1250], speed: 100, wander: 0 },
        { type: 'FX', kind: 'fire', at: 'manta', delayMs: 1800 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { skin: '#e8645a' }, delayMs: 1800 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'あの人、口から火が出てる……', delayMs: 3200 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { skin: '#f2c9a0' }, delayMs: 9000 },
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [3800, 1360], speed: 40, wander: 200, delayMs: 9000 },
      ] },
    { id: 'S2-E31', s: 'burgerSign', t: 'manta', cat: 'FLAVOR', title: 'マンタ、ハンバーガーを十個たいらげる', say: 'ハンバーガー……おなかが、グゥ〜〜〜', anim: 'react.eat', route: 'S2.route.hungry',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [3650, 1250], speed: 100, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'manta', text: 'もぐもぐ……あと九個……', delayMs: 2600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'manta', look: { h: 158 }, delayMs: 4200 }, { type: 'FX', kind: 'big', at: 'manta', delayMs: 4200 },
        { type: 'ACTOR_MOVE', actorId: 'manta', to: [3800, 1360], speed: 25, wander: 200, delayMs: 6000 },
      ] },
    // ── 本屋の三人（E32〜E35） ──
    { id: 'S2-E32', s: 'photobook', t: 'gou', cat: 'CHAIN', title: 'ツッパリ二人組、ノブを押しのける', say: 'おっ、アイドルの写真集じゃねーか！ どけどけ！', anim: 'react.love', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [2590, 1220], speed: 160, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [2640, 1240], speed: 160, wander: 0, delayMs: 300 },
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [2800, 1340], speed: 220, wander: 20, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'nobu', text: 'わっ！ ……ぼくが先に見てたのに……', delayMs: 2200 },
        { type: 'ACTOR_SET_STATE', actorId: 'nobu', state: 'SAD', delayMs: 2200 },
      ],
      after: [{ actor: 'nobu', text: 'ぼくにも、もっと力があれば……', delay: 5000 }] },
    { id: 'S2-E33', s: 'pharmSign', t: 'nobu', cat: 'CHAIN', requires: ['S2-E32'], title: 'ノブ、プロテインでムキムキに', say: 'プロテイン……？ よし、ぼくだって！ ……ゴクゴク……うおおお！', anim: 'react.transform', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'nobu', look: { muscle: true, wide: true, h: 165 }, delayMs: 800 },
        { type: 'FX', kind: 'big', at: 'nobu', delayMs: 800 }, { type: 'PLAY_SOUND', soundId: 'roar', delayMs: 800 },
        { type: 'ACTOR_SET_STATE', actorId: 'nobu', state: 'HAPPY', delayMs: 1500 },
      ],
      after: [{ actor: 'nobu', text: 'みなぎる……！ さっきの二人に、ひとこと言ってやる', delay: 3400 }] },
    { id: 'S2-E34', s: 'gou', t: 'nobu', cat: 'CHAIN', requires: ['S2-E33'], title: 'ムキムキのノブ、仕返しを始める', say: 'さっきは、よくも押してくれたね……！', anim: 'react.angry', route: 'S2.route.book',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [2660, 1250], speed: 180, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'gou', text: 'ひいっ！ なんだそのムキムキ！', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [2440, 1250], speed: 260, wander: 0, delayMs: 2200 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [2480, 1270], speed: 260, wander: 0, delayMs: 2300 },
        { type: 'ACTOR_SET_STATE', actorId: 'gou', state: 'SCARED', delayMs: 2200 },
      ],
      after: [{ actor: 'gou', text: 'て、店主さーん！ こいつ、なんとかしてくれー！', delay: 3800 }] },
    { id: 'S2-E35', s: 'gou', t: 'bookman', cat: 'PROGRESSION', requires: ['S2-E34'], title: '店主のカミナリ、三人そろって出入り禁止', say: 'こらっ！ 店の前でケンカするんじゃない！ 全員、立ち読み禁止！', anim: 'react.angry', route: 'S2.route.book',
      fx: [
        { type: 'PLAY_SOUND', soundId: 'thunder' }, { type: 'FX', kind: 'lightning', at: 'bookman', delayMs: 200 },
        { type: 'ACTOR_MOVE', actorId: 'gou', to: [600, 1880], speed: 240, wander: 80, delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'jin', to: [680, 1900], speed: 240, wander: 80, delayMs: 1900 },
        { type: 'ACTOR_SPEECH', actorId: 'nobu', text: 'ぼ、ぼくまで……！？', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'nobu', to: [2200, 1500], speed: 80, wander: 100, delayMs: 3200 },
      ] },
    // ── 草野球とミノリ（E36〜E44） ──
    { id: 'S2-E36', s: 'batter', t: 'sora', cat: 'CHAIN', group: 'S2-BAT', requires: ['S2-E38'], title: 'ソラの球をイワオが特大ホームラン', say: 'いくよー！ えいっ！', anim: 'react.happy', route: 'S2.route.baseball',
      fx: [
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'カッキーン！！', delayMs: 900 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 900 },
        { type: 'SPAWN_OBJECT', objectId: 'ball', delayMs: 1000 }, { type: 'FX', kind: 'stars', at: 'batter', delayMs: 1000 },
        { type: 'OBJECT_MOVE', objectId: 'ball', to: [4400, 1910], speed: 260, delayMs: 1100 },
        { type: 'ACTOR_SPEECH', actorId: 'sora', text: 'あーっ、ボールがあっちに転がってく！', delayMs: 2600 },
      ],
      after: [{ actor: 'minori', text: 'あ、ボールが転がってきた……', delay: 4200 }] },
    { id: 'S2-E37', s: 'batter', t: 'umi', cat: 'FLAVOR', group: 'S2-BAT', requires: ['S2-E38'], title: 'ウミのすっぽ抜けボール', say: 'それっ！ ……あっ、すっぽぬけた！', anim: 'react.embarrassed', route: 'S2.route.baseball',
      fx: [
        { type: 'FX', kind: 'stars', at: 'batter', delayMs: 900 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 900 },
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'いてっ！ デッドボール……今日はもう引退だ……', delayMs: 1400 },
        { type: 'ACTOR_SET_STATE', actorId: 'batter', state: 'SAD', delayMs: 1400 },
      ] },
    { id: 'S2-E38', s: 'tv', t: 'batter', cat: 'CHAIN', title: 'イワオ、中継を見て野球魂に火がつく', say: 'プレイボール……！ 血がさわぐ！ 公園で素振りだ！', anim: 'react.surprised', route: 'S2.route.baseball',
      fx: [
        { type: 'OBJECT_APPEARANCE', objectId: 'tv', look: { sign: { text: '⚾ プレイボール！', fill: '#2b6b3a', color: '#fff', s: 18 } } },
        { type: 'PLAY_SOUND', soundId: 'tv' },
        { type: 'ACTOR_MOVE', actorId: 'batter', to: [4690, 1700], speed: 240, wander: 30, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'batter', text: 'ブン！ ブン！ だれか投げてくれー！', delayMs: 15000 },
      ] },
    { id: 'S2-E39', s: 'ball', t: 'minori', cat: 'BRANCH', group: 'S2-DOG', requires: ['S2-E36'], title: 'ミノリ、ボールを投げてブルドッグを遠ざける', say: 'このボールを……えいっ！ ほら、取ってこーい！', anim: 'react.happy', route: 'S2.route.minori',
      fx: [
        { type: 'OBJECT_MOVE', objectId: 'ball', to: [3650, 1930], speed: 320 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [3680, 1940], speed: 200, wander: 90, delayMs: 300 },
        { type: 'HIDE_OBJECT', objectId: 'ball', delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'minori', to: [4300, 1980], speed: 80, wander: 40, delayMs: 2000 },
        { type: 'SET_FLAG', id: 'bulldog.away', value: 'ball' },
      ],
      after: [{ actor: 'minori', text: 'これでお店に行ける！ ……えっと、なに買うんだっけ', delay: 4200 }] },
    { id: 'S2-E40', s: 'koban', t: 'minori', cat: 'BRANCH', group: 'S2-DOG', title: 'ミノリ、交番に相談する', say: 'おまわりさんに、相談してみよう……', anim: 'react.think', route: 'S2.route.police',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4520, 1950], speed: 160, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'police', text: 'こらこら、ドン。おうちに帰ろうな', delayMs: 2800 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [6900, 1990], speed: 70, wander: 0, delayMs: 3600 },
        { type: 'ACTOR_HIDE', actorId: 'bulldog', delayMs: 40000 },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4890, 2010], speed: 60, wander: 40, delayMs: 5200 },
        { type: 'SET_FLAG', id: 'bulldog.away', value: 'police' },
      ],
      after: [{ actor: 'minori', text: 'ありがとう！ ……えっと、なに買うんだっけ', delay: 5600 }] },
    { id: 'S2-E41', s: 'apple', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、リンゴを買う', say: 'そうだ、リンゴ！ 赤くてツヤツヤのやつ！', anim: 'react.happy', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'minori', to: [4200, 2000], speed: 100, wander: 30 }, { type: 'HIDE_OBJECT', objectId: 'apple', delayMs: 2400 }, { type: 'ACTOR_SET_STATE', actorId: 'minori', state: 'HAPPY', delayMs: 2400 }] },
    { id: 'S2-E42', s: 'kakiPoster', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、柿を買う', say: '柿！ おばあちゃんの好物だった気がする！', anim: 'react.think', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'minori', to: [4480, 2000], speed: 100, wander: 30 }, { type: 'ACTOR_SET_STATE', actorId: 'minori', state: 'HAPPY', delayMs: 2400 }] },
    { id: 'S2-E43', s: 'peddler', t: 'minori', cat: 'FLAVOR', group: 'S2-FRUIT', cond: [anyDone('S2-E40', 'S2-E39')], title: 'ミノリ、行商の大根を買う', say: 'わあ、大根！ ……おつかいって、大根だった気がする！', anim: 'react.surprised', route: 'S2.route.minori',
      fx: [{ type: 'ACTOR_SPEECH', actorId: 'peddler', text: 'まいどあり。重たいから気をつけてね〜', delayMs: 1600 }, { type: 'ACTOR_APPEARANCE', actorId: 'minori', look: { acc: ['bag', 'scarf'] }, delayMs: 2000 }] },
    { id: 'S2-E44', s: 'bikedad', t: 'bulldog', cat: 'PROGRESSION', requires: ['S2-E39'], title: 'ドンがパパを追いかけ、コハルはひとりで走り出す', say: 'ガウッ！ ガウガウッ！', anim: 'react.run', route: 'S2.route.minori',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'bikedad', to: [6600, 1760], speed: 260, wander: 40, delayMs: 300 },
        { type: 'ACTOR_MOVE', actorId: 'bulldog', to: [6500, 1780], speed: 240, wander: 60, delayMs: 600 },
        { type: 'ACTOR_SPEECH', actorId: 'bikedad', text: 'うわああ、こっち来るなーっ！', delayMs: 1000 },
        { type: 'ACTOR_SPEECH', actorId: 'bikegirl', text: 'パパ？ ……あれ、あたし、ひとりで走れてる！', delayMs: 2600 },
        { type: 'FX', kind: 'confetti', at: 'bikegirl', delayMs: 2800 }, { type: 'PLAY_SOUND', soundId: 'fanfare', delayMs: 2800 },
        { type: 'ACTOR_SET_STATE', actorId: 'bikegirl', state: 'HAPPY', delayMs: 2800 },
      ] },
    // ── チョロ吉と木（E45〜E47） ──
    { id: 'S2-E45', s: 'choro', t: 'mama', cat: 'CHAIN', title: 'チョロ吉、ガチャの竹とんぼで木に登る', say: 'もう、しょうがないわね。はい百円。一回だけよ', anim: 'react.think', route: 'S2.route.kid',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mama', to: [5680, 1260], speed: 260, wander: 60 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [5810, 1200], speed: 100, wander: 0, delayMs: 800 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'やった！ 竹とんぼ出た！ とばすぞー！', delayMs: 2400 },
        { type: 'SPAWN_OBJECT', objectId: 'propeller', delayMs: 3800 }, { type: 'FX', kind: 'leaves', x: 5200, y: 760, delayMs: 3900 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [5180, 1260], speed: 240, wander: 0, delayMs: 3600 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'あっ、木に引っかかった！ 取ってくる！', delayMs: 6600 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [5180, 840], speed: 80, wander: 0, delayMs: 7400 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'と、取れた……けど、降りられない〜！', delayMs: 13000 },
        { type: 'ACTOR_SET_STATE', actorId: 'choro', state: 'SCARED', delayMs: 13000 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: true },
      ],
      after: [{ actor: 'mama', text: 'あら？ チョロ吉ったら、またどこかに……', delay: 9000 }] },
    { id: 'S2-E46', s: 'choro', t: 'mama', cat: 'PROGRESSION', group: 'S2-RESCUE', requires: ['S2-E45'], title: '母、肩車でチョロ吉を救出', say: 'チョロ吉！ ほら、お母さんの肩に足をかけて！', anim: 'react.angry', route: 'S2.route.kid',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'mama', to: [5170, 1275], speed: 240, wander: 0 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [5200, 1280], speed: 110, wander: 40, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'ごめんなさーい……', delayMs: 7000 },
        { type: 'ACTOR_SET_STATE', actorId: 'choro', state: 'EMBARRASSED', delayMs: 7000 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: false, delayMs: 7000 },
        { type: 'HIDE_OBJECT', objectId: 'propeller', delayMs: 7000 },
      ] },
    { id: 'S2-E47', s: 'choro', t: 'rikishi', cat: 'PROGRESSION', group: 'S2-RESCUE', requires: ['S2-E45'], title: '力士の張り手で木をゆらし、チョロ吉をキャッチ', say: 'まかせるでごわす！ どすこーいっ！', anim: 'react.hit', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5150, 1285], speed: 220, wander: 0 },
        { type: 'FX', kind: 'leaves', x: 5180, y: 800, delayMs: 3200 }, { type: 'PLAY_SOUND', soundId: 'hit', delayMs: 3200 },
        { type: 'ACTOR_MOVE', actorId: 'choro', to: [5210, 1280], speed: 500, wander: 40, delayMs: 3500 },
        { type: 'HIDE_OBJECT', objectId: 'propeller', delayMs: 3500 },
        { type: 'ACTOR_SPEECH', actorId: 'choro', text: 'うわーい！ お相撲さん、ナイスキャッチ！', delayMs: 4800 },
        { type: 'SET_FLAG', id: 'choro.inTree', value: false, delayMs: 4800 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [5000, 1420], speed: 40, wander: 140, delayMs: 7000 },
      ],
      after: [{ actor: 'rikishi', text: 'ふう、汗だくでごわす。大きな湯船が恋しいでごわすなあ', delay: 6200 }] },
    // ── ハヤテ（E48〜E51） ──
    { id: 'S2-E48', s: 'fountain', t: 'hayate', cat: 'FLAVOR', group: 'S2-DRINK', title: 'ハヤテ、水飲み場でひと息', say: 'ぷはーっ！ やっぱり水がいちばん！', anim: 'react.drink', route: 'S2.route.runner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'hayate', to: [4900, 1260], speed: 220, wander: 0 }, { type: 'FX', kind: 'splash', at: 'fountain', delayMs: 2400 }, { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', delayMs: 6000 }] },
    { id: 'S2-E49', s: 'vending', t: 'hayate', cat: 'FLAVOR', group: 'S2-DRINK', title: 'ハヤテ、スポーツドリンクを一気飲み', say: 'スポーツドリンク！ しみわたる〜！', anim: 'react.drink', route: 'S2.route.runner',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'hayate', to: [3000, 2020], speed: 220, wander: 0 }, { type: 'PLAY_SOUND', soundId: 'pop', delayMs: 2000 }, { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', delayMs: 6000 }] },
    { id: 'S2-E50', s: 'skates', t: 'hayate', cat: 'BRANCH', group: 'S2-GEAR', requires: ['S2-E48'], title: 'ハヤテ、ローラースケートで爆走', say: 'ローラースケート！ これで速さ倍増だ！', anim: 'react.run', route: 'S2.route.runner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'hayate', to: [2660, 2010], speed: 220, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'hayate', look: { acc: ['headphones', 'helmet'] }, delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', speed: 300, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'ひゃっほーう！ 止まらなーい！', delayMs: 5000 },
      ] },
    { id: 'S2-E51', s: 'ironGeta', t: 'hayate', cat: 'BRANCH', group: 'S2-GEAR', cond: [anyDone('S2-E48', 'S2-E49')], title: 'ハヤテ、鉄下駄で修行を始める', say: '鉄下駄……！ 足腰をきたえるなら、これだ！', anim: 'react.think', route: 'S2.route.runner',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'hayate', to: [2820, 2010], speed: 220, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'hayate', look: { muscle: true }, delayMs: 2000 },
        { type: 'ACTOR_MOVE', actorId: 'hayate', pathId: 'jog', speed: 22, delayMs: 3000 },
        { type: 'ACTOR_SPEECH', actorId: 'hayate', text: 'ガッシャン……ガッシャン……お、重い……！', delayMs: 4500 },
      ] },
    // ── ガク（E52〜E54） ──
    { id: 'S2-E52', s: 'crab', t: 'gaku', cat: 'FLAVOR', blocksIfCompleted: ['S2-E53'], title: 'ガク、カニにはさまれる', say: 'カニだ！ ……いってええええ！ はさまれたー！', anim: 'react.hit', route: 'S2.route.ink',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'gaku', to: [3020, 1200], speed: 160, wander: 0 }, { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'だから、さわるなって言ったろ〜', delayMs: 2600 }, { type: 'ACTOR_MOVE', actorId: 'gaku', to: [3100, 1340], speed: 60, wander: 70, delayMs: 5000 }] },
    { id: 'S2-E53', s: 'octopus', t: 'gaku', cat: 'CHAIN', title: 'ガク、タコ墨でまっくろ', say: 'タコだ〜！ つんつん……ぶわっ！？', anim: 'react.surprised', route: 'S2.route.ink',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [3080, 1200], speed: 160, wander: 0 },
        { type: 'FX', kind: 'ink', at: 'gaku', delayMs: 1600 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 1600 },
        { type: 'ACTOR_APPEARANCE', actorId: 'gaku', look: { skin: '#2a2a2a', shirt: '#1a1a1a', pants: '#1a1a1a', hatColor: '#111' }, delayMs: 1700 },
        { type: 'ACTOR_SET_STATE', actorId: 'gaku', state: 'SAD', delayMs: 2400 },
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [3100, 1340], speed: 60, wander: 70, delayMs: 5000 },
      ],
      after: [{ actor: 'gaku', text: 'まっくろ……母ちゃんに怒られる。どこかでゴシゴシ洗わないと', delay: 3800 }] },
    { id: 'S2-E54', s: 'noren', t: 'gaku', cat: 'PROGRESSION', requires: ['S2-E53'], title: 'ガク、銭湯でピカピカに', say: 'おふろ屋さん！ ひとっ走り行ってくる！', anim: 'react.run', route: 'S2.route.ink',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [6560, 1200], speed: 340, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'gaku', delayMs: 11000 }, { type: 'FX', kind: 'bubbles', at: 'noren', delayMs: 11500 },
        { type: 'ACTOR_APPEARANCE', actorId: 'gaku', look: { skin: '#f2c9a0', shirt: '#f28a3a', pants: '#3a5a8a', hatColor: '#d33' }, delayMs: 12000 },
        { type: 'ACTOR_SHOW', actorId: 'gaku', delayMs: 15000 }, { type: 'FX', kind: 'sparkle', at: 'gaku', delayMs: 15100 },
        { type: 'ACTOR_SPEECH', actorId: 'gaku', text: 'ピッカピカ！ お風呂ってすごい！', delayMs: 15400 },
        { type: 'ACTOR_MOVE', actorId: 'gaku', to: [6300, 1400], speed: 60, wander: 100, delayMs: 16500 },
      ] },
    // ── キヌエ（E55〜E56） ──
    { id: 'S2-E55', s: 'pawn', t: 'kinue', cat: 'CHAIN', title: 'キヌエ、ブランドバッグを質に入れる', say: 'このバッグ……ブランド品よ。いかほどになるかしら？', anim: 'react.think', route: 'S2.route.pawn',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'kinue', to: [1670, 2040], speed: 90, wander: 0 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kinue', look: { acc: ['earring', 'hat'] }, delayMs: 2400 },
        { type: 'SPAWN_OBJECT', objectId: 'pawnBag', delayMs: 2400 },
      ],
      after: [{ actor: 'kinue', text: 'ぜんぜん足りないわ……あとは、首もとのこれくらい……', delay: 3800 }] },
    { id: 'S2-E56', s: 'pawn', t: 'kinue', cat: 'PROGRESSION', requires: ['S2-E55'], title: 'キヌエ、ネックレスも手放して家賃を工面', say: 'えーい、ネックレスも持ってって！ ……これで家賃が払えるわ', anim: 'react.happy', route: 'S2.route.pawn',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'kinue', look: { acc: ['hat'] }, delayMs: 1000 },
        { type: 'SPAWN_OBJECT', objectId: 'pawnNecklace', delayMs: 1000 },
        { type: 'ACTOR_SET_STATE', actorId: 'kinue', state: 'HAPPY', delayMs: 1600 },
        { type: 'ACTOR_MOVE', actorId: 'kinue', to: [1500, 1900], speed: 50, wander: 80, delayMs: 3000 },
      ] },
    // ── おまわりさん・マゴベエ（E57〜E59） ──
    { id: 'S2-E57', s: 'thief', t: 'police', cat: 'PROGRESSION', title: 'おまわりさん、木陰のコソ泥を確保', say: 'ん！？ そこのあやしいやつ！ まてーい！', anim: 'react.run', route: 'S2.route.police',
      fx: [
        { type: 'PLAY_SOUND', soundId: 'whistle' },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4260, 1200], speed: 280, wander: 0 },
        { type: 'ACTOR_SPEECH', actorId: 'thief', text: 'げえっ、見つかった！', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'thief', to: [4080, 1450], speed: 160, wander: 0, delayMs: 2000 },
        { type: 'ACTOR_SET_STATE', actorId: 'thief', state: 'SCARED', delayMs: 6000 },
        { type: 'ACTOR_MOVE', actorId: 'thief', to: [4860, 2010], speed: 90, wander: 0, delayMs: 7000 },
        { type: 'ACTOR_MOVE', actorId: 'police', to: [4920, 2010], speed: 90, wander: 40, delayMs: 7000 },
        { type: 'ACTOR_SPEECH', actorId: 'thief', text: 'とほほ……木陰なら見つからないと思ったのに', delayMs: 9000 },
        { type: 'ACTOR_HIDE', actorId: 'thief', delayMs: 18000 },
        { type: 'SET_FLAG', id: 'thief.caught', value: true },
      ] },
    { id: 'S2-E58', s: 'koban', t: 'magobe', cat: 'CHAIN', title: 'マゴベエ、交番で道をたずねる', say: '伝説のコロッケ屋？ それなら西のほうの肉屋さんだよ、と……ありがとう！', anim: 'react.happy', route: 'S2.route.police',
      fx: [{ type: 'ACTOR_MOVE', actorId: 'magobe', to: [3320, 1320], speed: 90, wander: 60, delayMs: 1500 }, { type: 'SET_FLAG', id: 'magobe.dir', value: 'west' }],
      after: [{ actor: 'magobe', text: '……でも、なんだか胸さわぎがする。運勢を見てもらおうかな', delay: 6000 }] },
    { id: 'S2-E59', s: 'uranai', t: 'magobe', cat: 'FLAVOR', requires: ['S2-E58'], title: 'マゴベエ、占いで逆方向へ', say: 'え？ 「東に吉」……？ さっき西って言われたのに……', anim: 'react.spin', route: 'S2.route.police',
      fx: [
        { type: 'ACTOR_SPEECH', actorId: 'uranai', text: 'ほっほっ、迷わず東へ進むがよい', delayMs: 1800 },
        { type: 'ACTOR_MOVE', actorId: 'magobe', to: [6800, 1650], speed: 90, wander: 60, delayMs: 3000 },
        { type: 'SET_FLAG', id: 'magobe.dir', value: 'east' },
      ] },
    // ── キラリ（E60〜E62） ──
    { id: 'S2-E60', s: 'salonSign', t: 'kirari', cat: 'CHAIN', title: 'キラリ、ブリーチで真っ白に', say: 'パッと明るく、ブリーチしちゃお！', anim: 'react.happy', route: 'S2.route.kirari',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'kirari', to: [470, 1180], speed: 200, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'kirari', delayMs: 5000 }, { type: 'FX', kind: 'smoke', x: 455, y: 1050, delayMs: 5400 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { hairColor: '#f8f8f2', skin: '#fbfaf8' }, delayMs: 5600 },
        { type: 'ACTOR_SHOW', actorId: 'kirari', delayMs: 7400 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'え、肌まで白くなってない！？ おばけみたい……', delayMs: 7800 },
        { type: 'ACTOR_MOVE', actorId: 'kirari', to: [800, 1720], speed: 50, wander: 150, delayMs: 9500 },
      ],
      after: [{ actor: 'kirari', text: 'ちょっと焼いて、健康的な色をつけたいかも', delay: 11000 }] },
    { id: 'S2-E61', s: 'tanSign', t: 'kirari', cat: 'CHAIN', requires: ['S2-E60'], title: 'キラリ、日焼けサロンで焼きすぎる', say: 'こんがり焼いて、健康的に……やりすぎたー！', anim: 'react.fire', route: 'S2.route.kirari',
      fx: [
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { skin: '#5a321c', hairColor: '#f8f8f2' }, delayMs: 900 },
        { type: 'FX', kind: 'steam', at: 'kirari', delayMs: 900 },
        { type: 'ACTOR_SPEECH', actorId: 'mitsuru', text: '……だれ？', delayMs: 3200 },
      ],
      after: [{ actor: 'kirari', text: 'まっくろ……ゴシゴシ洗ったら、ちょっとは戻るかな', delay: 4600 }] },
    { id: 'S2-E62', s: 'sentoSign', t: 'kirari', cat: 'FLAVOR', requires: ['S2-E61'], title: 'キラリ、銭湯でのぼせて真っ赤', say: 'お風呂で洗いながそ！ ……のぼせて真っ赤になったー！', anim: 'react.embarrassed', route: 'S2.route.kirari',
      fx: [
        { type: 'FX', kind: 'steam', at: 'kirari', delayMs: 600 }, { type: 'FX', kind: 'bubbles', at: 'kirari', delayMs: 900 },
        { type: 'ACTOR_APPEARANCE', actorId: 'kirari', look: { skin: '#f2897a', hairColor: '#c8862a' }, delayMs: 1200 },
        { type: 'ACTOR_SPEECH', actorId: 'kirari', text: 'ゆでダコだよ〜。……まいっか、これはこれで！', delayMs: 3000 },
      ] },
    // ── さくら湯（E63〜E66） ──
    { id: 'S2-E63', s: 'earring', t: 'hoshimi', cat: 'PROGRESSION', title: 'ホシミ、星のイヤリングをとりもどす', say: 'あっ！ わたしの星のイヤリング！ どこにあったの！？', anim: 'react.love', route: 'S2.route.end', focus: true,
      fx: [
        { type: 'HIDE_OBJECT', objectId: 'earring' },
        { type: 'ACTOR_APPEARANCE', actorId: 'hoshimi', look: { acc: ['apron', 'earring'] }, delayMs: 600 },
        { type: 'FX', kind: 'sparkle', at: 'hoshimi', delayMs: 600 },
        { type: 'ACTOR_SET_STATE', actorId: 'hoshimi', state: 'HAPPY' },
        { type: 'SET_FLAG', id: 'sento.spirit', value: true },
        { type: 'FX', kind: 'steam', at: 'chimneyTop', delayMs: 2400 },
      ],
      after: [
        { actor: 'hoshimi', text: '元気出た！ 今日はとびきり熱いお風呂、わかすよ！', delay: 2800 },
        { actor: 'gonji', text: 'お嬢が笑うた……よし、釜の支度じゃ。大物の客と、火種さえあればのう', delay: 5200 },
      ] },
    { id: 'S2-E64', s: 'noren', t: 'rikishi', cat: 'PROGRESSION', cond: [anyDone('S2-E18', 'S2-E47', 'S2-E19')], title: '力士、さくら湯の湯船をあふれさせる', say: 'ひとっ風呂、浴びてくるでごわす！', anim: 'react.happy', route: 'S2.route.sumo',
      fx: [
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [6560, 1210], speed: 280, wander: 0 },
        { type: 'ACTOR_HIDE', actorId: 'rikishi', delayMs: 9000 },
        { type: 'FX', kind: 'splash', at: 'noren', delayMs: 9600 }, { type: 'PLAY_SOUND', soundId: 'splash', delayMs: 9600 },
        { type: 'FX', kind: 'steam', at: 'noren', delayMs: 10000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'わっ、お湯が半分あふれた！', delayMs: 10400 },
        { type: 'ACTOR_SHOW', actorId: 'rikishi', delayMs: 16000 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [6450, 1420], speed: 40, wander: 100, delayMs: 16200 },
        { type: 'SET_FLAG', id: 'sento.bigGuest', value: true },
      ],
      after: [{ actor: 'gonji', text: 'ほう、横綱級の客か！ こりゃあ釜を本気で焚かにゃならん', delay: 11800 }] },
    { id: 'S2-E65', s: 'match', t: 'gonji', cat: 'TIMEOUT', title: 'ゴン爺の線香花火', say: 'もう日が暮れる……せめて、これくらいはのう', anim: 'react.timeout', route: 'S2.route.end',
      fx: [
        { type: 'FX', kind: 'sparkle', at: 'gonji', delayMs: 300 }, { type: 'PLAY_SOUND', soundId: 'pop', delayMs: 300 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'パチパチ……ちっちゃい花火みたいじゃのう', delayMs: 1400 },
        { type: 'FX', kind: 'smoke', at: 'chimneyTop', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: '今日はお店、閉めちゃおっか……', delayMs: 2600 },
      ] },
    { id: 'S2-E66', s: 'match', t: 'gonji', cat: 'TERMINAL', requires: ['S2-E63', 'S2-E64'], title: 'さくら湯、煙突から大火柱！', say: '火種じゃ！ お嬢の笑顔に横綱の湯……今日は特大でいくぞい！', anim: 'react.terminal', route: 'S2.route.end',
      fx: [
        { type: 'CAMERA_FOCUS', x: 6700, y: 800, zoom: 0.8 },
        { type: 'FX', kind: 'fire', at: 'gonji', delayMs: 400 }, { type: 'PLAY_SOUND', soundId: 'boom', delayMs: 900 },
        { type: 'FX', kind: 'eruption', at: 'chimneyTop', delayMs: 1200 },
        { type: 'FX', kind: 'fire', at: 'chimneyTop', delayMs: 1600 },
        { type: 'FX', kind: 'steam', at: 'noren', delayMs: 1800 },
        { type: 'ACTOR_SHOW', actorId: 'rikishi', delayMs: 1900 },
        { type: 'ACTOR_MOVE', actorId: 'rikishi', to: [6450, 1500], speed: 320, wander: 0, delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'rikishi', text: 'あっちっちっちでごわすーー！！', delayMs: 2000 },
        { type: 'ACTOR_SPEECH', actorId: 'hoshimi', text: 'きゃー！ 煙突が火をふいた！', delayMs: 2600 },
        { type: 'FX', kind: 'confetti', x: 6700, y: 300, delayMs: 2800 }, { type: 'PLAY_SOUND', soundId: 'fanfare', delayMs: 2800 },
        { type: 'ACTOR_SPEECH', actorId: 'police', text: 'しょ、消防車！ ……いや、花火か！？', delayMs: 3200 },
        { type: 'ACTOR_SPEECH', actorId: 'fishman', text: 'たーまやー！', delayMs: 3800 },
        { type: 'ACTOR_SPEECH', actorId: 'gonji', text: 'これじゃ！ これが、さくら湯の火柱じゃ！', delayMs: 4400 },
        { type: 'WAIT', durationMs: 4200 },
      ] },
  ],
};
