// ================================================================ maps
const TR = (name, ch, party, money, pre, win, after, o = {}) => Object.assign({ name, ch, party, money, pre, win, after, flag: 'tr_' + name }, o);
const GRUNT = (n, party, pre, o = {}) => TR('カザンだんの したっぱ', o.ch || 'grunt', party, 400, pre, 'ぐぬぬ… こどもに まけるなんて！', 'カザンだんの じゃまを するなー！', Object.assign({ music: 'kazan', flag: 'tr_grunt' + n }, o));
function centerMap(id, back) {
  return {
    name: 'ふーモンセンター', bgm: 'center', benv: 'gym',
    grid: ['wwwwwwwwwwwpw', 'OOOOOOOOOOOOO', 'QOOOkkkkkOOOQ', 'OOOOOOOOOOOOO', 'OOOOOOOOOOOOO', 'QOOOOOOOOOOOQ', 'OOOOOOOOOOOOO', 'wwwwwwmwwwwww'],
    warps: [{ x: 6, y: 7, to: back[0], tx: back[1], ty: back[2], dir: 'D' }],
    npcs: [
      { id: 'nurse', ch: 'nurse', x: 6, y: 1, talk: centerHeal },
      { ch: pick(['lass', 'boy', 'oldlady']), x: 2, y: 5, dir: 'R', wander: true, talk: pick(['ふーモンが つかれたら ここで やすませて あげてね！', 'すみっこの パソコンで ふーモンを あずけたり ひきだしたり できるよ。', 'センターで かいふく すると、 まけちゃっても ここから やりなおせるんだって。']) },
    ],
  };
}
function martMap(id, back) {
  return {
    name: 'ショップ', bgm: 'center',
    grid: ['wwwwwwwww', 'OOOOOOOOO', 'KKKOOOOOO', 'OOOOOOOOO', 'QOObOObOQ', 'OOOOOOOOO', 'wwwwmwwww'],
    warps: [{ x: 4, y: 6, to: back[0], tx: back[1], ty: back[2], dir: 'D' }],
    npcs: [
      { ch: 'clerk', x: 1, y: 1, talk: martMenu },
      { ch: pick(['girl', 'fisher', 'oldman']), x: 6, y: 3, dir: 'L', wander: true, talk: pick(['ふーモンボールは たくさん もっておくと あんしん！', 'むしよけスプレーを つかうと よわい ふーモンが でてこなくなるよ。', 'なんでもなおしは まひも やけども なおせるんだよ。']) },
    ],
  };
}
function houseMap(back, npcs, grid) {
  return {
    name: 'いえ', bgm: 'town',
    grid: grid || ['wwbbwwvww', 'ooooooooo', 'oottooooo', 'oottooooo', 'PoooooooP', 'wwwwmwwww'],
    warps: [{ x: 4, y: 5, to: back[0], tx: back[1], ty: back[2], dir: 'D' }],
    npcs,
  };
}
const ENC1 = { grass: [[7, 2, 4, 35], [9, 2, 4, 30], [11, 2, 3, 25], [22, 3, 4, 10]] };
const ENC2 = { grass: [[9, 5, 8, 25], [11, 5, 7, 20], [13, 6, 8, 20], [22, 5, 8, 15], [7, 6, 8, 10], [17, 6, 8, 7], [18, 7, 8, 3]] };
const ENCCAVE = { cave: [[20, 8, 11, 45], [15, 8, 11, 35], [23, 9, 11, 20]] };
const ENC3 = { grass: [[21, 14, 18, 35], [20, 14, 18, 25], [15, 15, 18, 20], [23, 15, 18, 15], [18, 15, 17, 5]] };

MAPS = {
  // ------------------------------------------------------------ intro truck
  truck: {
    name: 'トラックの なか', bgm: null,
    grid: ['WWWWWWW', 'WqqjjqW', 'WqjjjjW', 'WqjjjqW', 'WWWmWWW'],
    warps: [{ x: 3, y: 4, to: 'town', tx: 4, ty: 12, dir: 'D', if: () => flag('truckStop') }],
    onEnter: () => introTruck(),
    trigs: [],
  },
  // ------------------------------------------------------------ どんぐりタウン
  town: {
    name: 'どんぐりタウン', bgm: 'town', out: true, border: 'T',
    grid: [
      'TTTTTTTTTT::TTTTTTTTTT',
      'TTTTTTTTTT::TTTTTTTTTT',
      'TT......;.::.;......TT',
      'TT.f......::......f.TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT...:....::....:...TT',
      'TT.n.::::::::::::.n.TT',
      'TT........::........TT',
      'TT.f......::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........:::::::...TT',
      'TT.FFFF.......f.....TT',
      'TT.ffff...........f.TT',
      'TTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    builds: [
      { k: 'house', x: 3, y: 4, to: 'home1', tx: 4, ty: 6 },
      { k: 'houseB', x: 14, y: 4, to: 'sotahome', tx: 4, ty: 5 },
      { k: 'lab', x: 13, y: 11, to: 'lab', tx: 5, ty: 9 },
      { k: 'truck', x: 5, y: 11, if: () => !flag('momHome') },
    ],
    onEnter: () => townEnter(),
    edges: { U: { to: 'route1', off: 0, if: () => flag('momHome'), block: async () => { await say('ママに あいさつ してから いこう！'); await walk(F.pl, 'D'); } } },
    signs: { '3,9': 'ここは どんぐりタウン。 ちいさな どんぐりが ころがる しずかな まち。', '18,9': 'キノミはかせの ふーモン けんきゅうじょ' },
    npcs: [
      { id: 'momOut', ch: 'mom', x: 4, y: 9, dir: 'D', if: () => !flag('momHome'), talk: 'ふーたん、 あたらしい おうちに はいりましょう！' },
      { ch: 'girl', x: 8, y: 13, wander: true, talk: 'くさむらには やせいの ふーモンが いるの。 ふーモンを もってないと あぶないよ！' },
      { ch: 'oldman', x: 16, y: 2, dir: 'D', talk: () => flag('starter') ? say('おお、 ふーモンを もらったのか！ くさむらで たくさん たたかうと つよく なるぞ。') : say('はかせは さっき きたの みちへ でかけて いったよ。') },
    ],
  },
  home1: {
    name: 'ふーたんの いえ', bgm: 'town', benv: 'gym',
    grid: ['wwwbbwvwwww', 'PooooooooSo', 'ooottoooooo', 'ooottoooooo', 'ooooooooooo', 'ooooooooooP', 'wwwwmwwwwww'],
    warps: [{ x: 4, y: 6, to: 'town', tx: 5, ty: 8, dir: 'D' }, { x: 9, y: 1, to: 'home2', tx: 7, ty: 1, dir: 'L', step: true }],
    onEnter: () => homeEnter(),
    npcs: [
      { id: 'mom', ch: 'mom', x: 6, y: 3, dir: 'D', talk: momTalk },
      { id: 'ricky', ch: 'ricky', x: 2, y: 4, wander: true, talk: () => say(pick(['リッキー「あうー！ ねえね！ ねえね！」', 'リッキー「だぁー！ ふーモン！ ふーモン！」', 'リッキーは にこにこ わらっている。']), { who: 'リッキー' }) },
    ],
  },
  home2: {
    name: 'ふーたんの へや', bgm: 'town', benv: 'gym',
    grid: ['wwwpwwwww', 'BoooooooS', 'Boooooooo', 'ooooootto', 'Poooooooo', 'wwwwwwwww'],
    warps: [{ x: 8, y: 1, to: 'home1', tx: 8, ty: 1, dir: 'L', step: true }],
    items: [{ x: 2, y: 3, item: 'potion' }],
    npcs: [],
  },
  sotahome: houseMap(['town', 16, 8], [
    { ch: 'lass', x: 6, y: 2, dir: 'L', talk: () => flag('starter') ? say('ソウタったら ふーたんちゃんと しょうぶ できて うれしそうだったわ。 なかよく してあげてね！', { who: 'ソウタの ママ' }) : say('あら！ となりに ひっこして きた ふーたんちゃんね！ うちの ソウタは けんきゅうじょで おてつだい してるのよ。', { who: 'ソウタの ママ' }) },
  ]),
  lab: {
    name: 'キノミはかせの けんきゅうじょ', bgm: 'town', benv: 'gym',
    grid: ['wbbbwpwbbbw', 'OOOOOOOOOOO', 'OOOOttOOOOO', 'OOOOOOOOOOO', 'QOOOOOOOOOQ', 'OOOOOOOOOOO', 'OOttOOOOttO', 'OOOOOOOOOOO', 'QOOOOOOOOOQ', 'wwwwwmwwwww'],
    warps: [{ x: 5, y: 9, to: 'town', tx: 16, ty: 15, dir: 'D' }],
    npcs: [
      { id: 'prof', ch: 'prof', x: 5, y: 3, dir: 'D', if: () => flag('starter'), talk: profTalk },
      { ch: 'scientist', x: 8, y: 5, dir: 'L', talk: () => flag('starter') ? say('ふーモンずかんは みつけた ふーモンを じどうで きろく してくれるんだ。 ぜんぶ うめて みてね！', { who: 'じょしゅ' }) : say('はかせなら きたの 1ばんどうろへ ふーモンの ちょうさに でかけたよ。', { who: 'じょしゅ' }) },
    ],
  },
  // ------------------------------------------------------------ 1ばんどうろ
  route1: {
    name: '1ばんどうろ', bgm: 'route', out: true, border: 'T', enc: ENC1,
    grid: [
      'TTTTTTTTTT::TTTTTTTTTT',
      'TT;.......::.......;TT',
      'TT.,,,,...::...,,,,.TT',
      'TT.,,,,...::...,,,,.TT',
      'TT.,,,,...::...,,,,.TT',
      'TT........::........TT',
      'TT____....::....____TT',
      'TT........::........TT',
      'TTTT..,,,,::,,,,..TTTT',
      'TTTT..,,,,::,,,,..TTTT',
      'TT....,,,,::,,,,....TT',
      'TT........::........TT',
      'TT..f.....::.....f..TT',
      'TTTTTT....::....TTTTTT',
      'TT,,,,,...::...,,,,,TT',
      'TT,,,,,...::...,,,,,TT',
      'TT,,,,,...::...,,,,,TT',
      'TT........::........TT',
      'TT..n.....::........TT',
      'TTTTTTTTTT::TTTTTTTTTT',
    ],
    edges: { D: { to: 'town', off: 0 }, U: { to: 'city1', off: 2, if: () => flag('starter'), block: async () => { await say('はかせ「まって まって！ ふーモンを もっていないと あぶないよ！」'); await walk(F.pl, 'D'); } } },
    onEnter: () => route1Enter(),
    signs: { '4,18': '1ばんどうろ  ↑ はなさきシティ  ↓ どんぐりタウン' },
    items: [{ x: 18, y: 17, item: 'potion' }, { x: 3, y: 1, item: 'ball', n: 2 }],
    trigs: [{ x: 2, y: 5, w: 18, h: 1, if: () => flag('starter') && !flag('rival1'), run: () => rivalBattle1() }],
    npcs: [
      { id: 'prof', ch: 'prof', x: 10, y: 14, dir: 'D', if: () => !flag('starter') },
      { id: 'wildpochi', mon: 7, x: 10, y: 13, dir: 'D', if: () => !flag('starter') },
      { id: 'sota', ch: 'sota', x: 11, y: 2, dir: 'L', if: () => flag('starter') && !flag('rival1') },
      { ch: 'boy', x: 14, y: 11, dir: 'L', tr: TR('げんきな こ タロウ', 'boy', [[7, 4], [9, 4]], 160, 'ふーモン もってるの？ しょうぶ しよう！', 'わー！ まけちゃった！', 'ぼくも もっと つよく なるぞー！', { sight: 3, music: 'trainer' }) },
    ],
  },
  // ------------------------------------------------------------ はなさきシティ
  city1: {
    name: 'はなさきシティ', bgm: 'town', out: true, border: 'T',
    grid: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TT..f...............f...TT',
      'TT......................TT',
      'TT......................TT',
      'TT......................TT',
      'TT......................TT',
      'TT......................TT',
      'TT....:......:......:...TT',
      'TT....:......:......:...TT',
      'TT::::::::::::::::::::::::',
      'TT::::::::::::::::::::::::',
      'TT..........::..........TT',
      'TT.n........::.......n..TT',
      'TT..........::..........TT',
      'TT..........::..........TT',
      'TT..........::..........TT',
      'TT..........::..........TT',
      'TT...:......::......:...TT',
      'TT...::::::::::::::::...TT',
      'TTff........::........ffTT',
      'TTTTTTTTTTTT::TTTTTTTTTTTT',
      'TTTTTTTTTTTT::TTTTTTTTTTTT',
    ],
    builds: [
      { k: 'center', x: 3, y: 3, to: 'c1', tx: 6, ty: 7 },
      { k: 'mart', x: 11, y: 3, to: 'm1', tx: 4, ty: 6 },
      { k: 'gymRock', x: 17, y: 2, to: 'gym1', tx: 5, ty: 13 },
      { k: 'houseG', x: 3, y: 13, to: 'h1a', tx: 4, ty: 5 },
      { k: 'house', x: 18, y: 13, to: 'h1b', tx: 4, ty: 5 },
    ],
    edges: { D: { to: 'route1', off: -2 }, R: { to: 'route2', off: -3, if: () => G.badges.length >= 1, block: async () => { await say('この さきは あぶない ふーモンが いっぱい。 ジムバッジを もっている ひとしか とおれないよ。 まずは ジムに ちょうせん してみて！', { who: 'おじいさん' }); await walk(F.pl, 'L'); } } },
    signs: { '3,12': 'はなさきシティ  おはなと いわの まち', '21,12': 'はなさきジム リーダー ゴロタ  「いわのように かたい ハート！」' },
    npcs: [
      { ch: 'oldman', x: 24, y: 8, dir: 'D', if: () => G.badges.length < 1, talk: 'この さきは 2ばんどうろ。 ジムバッジを もってないと あぶないぞ。' },
      { ch: 'girl', x: 9, y: 12, wander: true, talk: 'ジムリーダーの ゴロタさんは いわタイプ。 みずや くさの わざが よく きくんだって！' },
      { ch: 'boy', x: 16, y: 15, wander: true, talk: 'ふーモンセンターは あかい やねの たてもの！ ふーモンを ただで げんきに してくれるよ。' },
      { ch: 'lass', x: 7, y: 1, dir: 'D', talk: 'あかい やねの センターの となりの あおい やねは ショップよ。 ボールを かっておくと いいわ。' },
    ],
  },
  c1: centerMap('c1', ['city1', 6, 7]),
  m1: martMap('m1', ['city1', 13, 7]),
  h1a: houseMap(['city1', 5, 17], [
    { ch: 'oldlady', x: 2, y: 2, dir: 'R', talk: async () => { if (!flag('gift_h1a')) { await say('まあ かわいい トレーナーさん！ これを もっていきなさい。', { who: 'おばあちゃん' }); addItem('superpotion', 2); setFlag('gift_h1a'); AU.fanfare('item'); await say('ふーたんは いいきずぐすり ×2 を もらった！'); } else await say('ふーモンは あいじょうを こめて そだてると ぐんぐん そだつのよ。', { who: 'おばあちゃん' }); } },
  ]),
  h1b: houseMap(['city1', 20, 17], [
    { ch: 'boy', x: 6, y: 3, wander: true, talk: 'タイプの あいしょう だよ！ みずは ほのおに つよい。 ほのおは くさに つよい。 くさは みずに つよい！' },
    { ch: 'girl', x: 2, y: 4, dir: 'R', talk: 'でんきは みずと ひこうに つよいけど、 じめんには ぜんぜん きかないの。' },
  ]),
  gym1: {
    name: 'はなさきジム', bgm: 'route', benv: 'gym',
    grid: ['wwwwwwwwwww', 'ggggggggggg', 'gGGGgggGGGg', 'ggggggggggg', 'ggGGGgGGGgg', 'ggggggggggg', 'GGGgggggGGG', 'ggggggggggg', 'gGGgGGGgGGg', 'ggggggggggg', 'ggggggggggg', 'ggZgggggZgg', 'ggggggggggg', 'wwwwwmwwwww'],
    warps: [{ x: 5, y: 13, to: 'city1', tx: 20, ty: 7, dir: 'D' }],
    npcs: [
      { ch: 'scientist', x: 7, y: 12, dir: 'L', talk: 'やあ、 チャレンジャー！ ゴロタさんは いわタイプの つかいて。 いわは みずと くさに よわいよ！ がんばって！', who: 'ジムガイド' },
      { ch: 'miner', x: 1, y: 7, dir: 'R', tr: TR('こうふ テツ', 'miner', [[15, 8], [23, 8]], 320, 'いわの かたさを おしえて やる！', 'ほりすぎて つかれた〜', 'ゴロタさんは もっと かたいぞ！', { sight: 4 }) },
      { ch: 'hiker', x: 9, y: 3, dir: 'L', tr: TR('やまのぼり ガンさん', 'hiker', [[15, 9]], 360, 'ここを とおりたければ わしを たおしてみろ！', 'わっはっは！ まいった！', 'その ちょうしで リーダーに ちょうせんだ！', { sight: 4 }) },
      { id: 'leader', ch: 'gorota', x: 5, y: 1, dir: 'D', talk: () => gymLeader(0) },
    ],
  },
  // ------------------------------------------------------------ 2ばんどうろ
  route2: {
    name: '2ばんどうろ', bgm: 'route', out: true, border: 'T', enc: ENC2,
    grid: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#####TT',
      'TT,,,,,,TTTT.....,,,,,,,,,...TTTT#...#TT',
      'TT,,,,,,TTTT.....,,,,,,,,,...TTTT#...#TT',
      'TT,,,,,,.........,,,,,,,,,........:...TT',
      'TT.....f.................f........:...TT',
      '::::::::::::::::::::::::::::::::::::..TT',
      '::::::::::::::::::::::::::::::::::::..TT',
      'TT......,,,,,,,,......__________......TT',
      'TT......,,,,,,,,......................TT',
      'TT..n...,,,,,,,,.......,,,,,,,.....f..TT',
      'TT.....................,,,,,,,........TT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    builds: [{ k: 'cave', x: 34, y: 2, to: 'cave', tx: 2, ty: 14 }],
    edges: { L: { to: 'city1', off: 3 } },
    signs: { '4,10': '2ばんどうろ  ← はなさきシティ  → キラキラどうくつ' },
    items: [{ x: 3, y: 11, item: 'potion' }, { x: 37, y: 9, item: 'ball', n: 3 }, { x: 2, y: 2, item: 'repel' }],
    npcs: [
      { ch: 'bug', x: 12, y: 4, dir: 'D', tr: TR('むしとり しょうねん ユウ', 'bug', [[11, 6], [11, 6], [12, 7]], 200, 'むしむし ふーモンの ちからを みせて あげる！', 'むしが にげちゃった〜', 'むしは くさに つよいんだよ！', { sight: 3, music: 'trainer' }) },
      { ch: 'lass', x: 20, y: 9, dir: 'U', tr: TR('おねえさん ミカ', 'lass', [[22, 8], [9, 7]], 280, 'め が あったら しょうぶよ！', 'あら、 つよいのね！', 'わたしの ニャンタ、 かわいかったでしょ？', { sight: 3, music: 'trainer' }) },
      { ch: 'hiker', x: 30, y: 4, dir: 'L', tr: TR('やまおとこ ゴウ', 'hiker', [[15, 8], [23, 9]], 320, 'どうくつに いくのか？ そのまえに しょうぶだ！', 'がっはっは！ やるな！', 'どうくつの なかは くらいから きをつけてな。', { sight: 4, music: 'trainer' }) },
      { ch: 'fisher', x: 26, y: 10, dir: 'L', wander: true, talk: 'さいきん あかい フードの へんな ひとたちが どうくつに はいって いったんだ……' },
    ],
  },
  // ------------------------------------------------------------ キラキラどうくつ
  cave: {
    name: 'キラキラどうくつ', bgm: 'cave', benv: 'cave', weather: 'cave', enc: ENCCAVE,
    grid: [
      'CCCCCCCCCCCCCCCCCCCCCCCCCCeCCC',
      'CCcccccCCCCCCCcccccccCCCCcccCC',
      'CCcccccccCCCCCccccccccCCccccCC',
      'CCcc*ccccCCCCCcccCCccccccccc*C',
      'CCccccCCcCCCCCcccCCCCCccccccCC',
      'CCCcccCCcCCCCCccccccCCCcccccCC',
      'CCCccccccCCCCCC*cccccccccCCCCC',
      'CCcccccccccccccccccCCCcccccCCC',
      'CCcccCCCCCCCCCCCcccCCCcccccccC',
      'CCcccccccCCCCCCCcccccccc*ccccC',
      'CCCCcccccCCCCCCCCCCCCCCccccccC',
      'CCcccccccCCCCCCccccccCCCCcccCC',
      'CCcccCCCCCCCCCCcccccccccccccCC',
      'CCcccCCCCCCCCCCCCCCCCCCCCCCCCC',
      'CCcccCCCCCCCCCCCCCCCCCCCCCCCCC',
      'CCeCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    ],
    warps: [{ x: 2, y: 15, to: 'route2', tx: 35, ty: 4, dir: 'D' }, { x: 26, y: 0, to: 'city2', tx: 3, ty: 3, dir: 'D', step: true }],
    items: [{ x: 3, y: 3, item: 'superpotion' }, { x: 27, y: 1, item: 'great', n: 2 }, { x: 16, y: 12, item: 'fullheal' }],
    npcs: [
      { ch: 'miner', x: 4, y: 12, dir: 'U', talk: () => flag('tr_caveGrunt') ? say('ありがとう！ キラキラいしを とりかえして くれたんだね！ このさきは うみかぜシティだよ！', { who: 'こうふ' }) : say('たいへんだ！ あかい フードの カザンだんが どうくつの キラキラいしを もっていこうと してるんだ！', { who: 'こうふ' }) },
      { id: 'caveGrunt', ch: 'grunt', x: 11, y: 7, dir: 'L', if: () => !flag('tr_caveGrunt'), tr: Object.assign(GRUNT('', [[20, 9], [21, 10]], 'なんだ、 おまえ！ カザンだんの じゃまを するな！ この キラキラいしは ボスに とどけるんだ！', { sight: 5 }), { flag: 'tr_caveGrunt', post: async () => { await say('くそー！ キラキラいしは かえすよ！ でも ボスの けいかくは とめられないぞ！ だいちを もっと ひろげるんだ！', { who: 'したっぱ' }); const g = ent('caveGrunt'); await walk(g, 'RRR', 2); g.vis = false; } }) },
    ],
  },
  // ------------------------------------------------------------ うみかぜシティ
  city2: {
    name: 'うみかぜシティ', bgm: 'town', out: true, border: '~', benv: 'sea',
    grid: [
      'TTTTTTTTTTTTT::TTTTTTTTTTTTT',
      'TT...........::...........TT',
      'TT...........::...........TT',
      'TT.:.........::...........TT',
      'TT.:.........::...........TT',
      'TT.:.........::...........TT',
      'TT.:.........::...........TT',
      'TT.::::::::::::::::::::::.TT',
      'TT...........::...........TT',
      'TT...........::...........TT',
      'TT...........::...........TT',
      'TT...........::...........TT',
      'TT...........::...........TT',
      'TT......:....::....:......TT',
      'TT.n..::::::::::::::::....TT',
      'TTY==========::==========YTT',
      'TT========================TT',
      '~~~==========yy==========~~~',
      '~~~~~~~~~~~~~yy~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~yy~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~yy~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    ],
    builds: [
      { k: 'cave', x: 2, y: 1, to: 'cave', tx: 26, ty: 1 },
      { k: 'center', x: 5, y: 3, to: 'c2', tx: 6, ty: 7 },
      { k: 'mart', x: 16, y: 3, to: 'm2', tx: 4, ty: 6 },
      { k: 'gymElec', x: 5, y: 8, to: 'gym2', tx: 5, ty: 13 },
      { k: 'houseB', x: 17, y: 9, to: 'h2a', tx: 4, ty: 5 },
      { k: 'boat', x: 15, y: 18 },
    ],
    edges: { U: { to: 'route3', off: -3, if: () => G.badges.length >= 2, block: async () => { await say('この さきは えんとつやま。 あついし あぶない！ ジムバッジ 2こ もってる ひとしか とおれない きまりだよ。', { who: 'やまのぼり' }); await walk(F.pl, 'D'); } } },
    signs: { '3,14': 'うみかぜシティ  しおかぜ ふく みなとまち' },
    npcs: [
      { ch: 'hiker', x: 12, y: 1, dir: 'D', if: () => G.badges.length < 2, talk: 'えんとつやまへ いくなら ジムバッジ 2こが ひつようだよ。' },
      { ch: 'sailor', x: 14, y: 20, dir: 'R', talk: 'この ふねは いま おやすみちゅう。 また こんど のせて あげるよ！', who: 'ふなのり' },
      { ch: 'girl', x: 20, y: 15, wander: true, talk: 'うみの すなはまって きもちいい〜！ プカクラゲが ぷかぷか うかんでるよ。' },
      { ch: 'fisher', x: 9, y: 16, dir: 'D', talk: 'ジムリーダーの ピカリちゃんは でんきタイプ。 じめんタイプの ふーモンには でんきが きかないぞ！' },
      { ch: 'lass', x: 22, y: 8, wander: true, talk: 'うみかぜジムには ピカピカ ひかる でんきの ふーモンが いっぱい いるのよ。' },
    ],
  },
  c2: centerMap('c2', ['city2', 8, 7]),
  m2: martMap('m2', ['city2', 18, 7]),
  h2a: houseMap(['city2', 19, 13], [
    { ch: 'lass', x: 6, y: 2, dir: 'L', talk: giftYumeusa, who: 'おねえさん' },
    { ch: 'girl', x: 2, y: 4, wander: true, talk: 'ゆめうさは ながい みみで ゆめを きくんだって！' },
  ]),
  gym2: {
    name: 'うみかぜジム', bgm: 'route', benv: 'gym',
    grid: ['wwwwwwwwwww', 'ggggggggggg', 'gZgggggggZg', 'ggggGGGgggg', 'GGGgggggGGG', 'ggggggggggg', 'gggGGgGGggg', 'gZgggggggZg', 'ggggggggggg', 'GGGGgggGGGG', 'ggggggggggg', 'ggggggggggg', 'ggggggggggg', 'wwwwwmwwwww'],
    warps: [{ x: 5, y: 13, to: 'city2', tx: 8, ty: 13, dir: 'D' }],
    npcs: [
      { ch: 'scientist', x: 7, y: 12, dir: 'L', talk: 'ピカリちゃんは でんきタイプの つかいて！ でんきは じめんタイプに きかないよ。 いわや じめんの ふーモンが いると あんしん！', who: 'ジムガイド' },
      { ch: 'boy', x: 1, y: 8, dir: 'R', tr: TR('でんきこぞう ボルト', 'boy', [[13, 13], [13, 14]], 400, 'ビリビリ しびれさせて やる！', 'しびれた〜！', 'ピカリさんの ビリハリーは もっと はやいよ！', { sight: 5 }) },
      { ch: 'lass', x: 9, y: 5, dir: 'L', tr: TR('おどりこ ハナ', 'lass', [[9, 13], [17, 14]], 420, 'ピカピカ ダンスで しょうぶよ！', 'ステップが みだれちゃった！', 'ピカリちゃんは とっても げんきよ！', { sight: 4 }) },
      { id: 'leader', ch: 'pikari', x: 5, y: 1, dir: 'D', talk: () => gymLeader(1) },
    ],
  },
  // ------------------------------------------------------------ 3ばんどうろ（はいの みち）
  route3: {
    name: '3ばんどうろ', bgm: 'route', out: true, border: 'T', benv: 'ash', weather: 'ash', enc: ENC3,
    grid: [
      '######################',
      '#########...##########',
      '#########...##########',
      '##AAAAAAAA:AAAAAAAAA##',
      '##aaaaAAAA:AAAAaaaaa##',
      '##aaaaAAAA:AAAAaaaaa##',
      '##AAAAAAAA:AAAAAAAAA##',
      'TTTAAA____:____AAATTTT',
      'TTaaaAAAAA:AAAAAaaaaTT',
      'TTaaaAAAAA:AAAAAaaaaTT',
      'TTaaaAAAAA:AAAAAaaaaTT',
      'TTAAAAAAAA:AAAAAAAAATT',
      'TTTTTAAAAA:AAAAATTTTTT',
      'TTAAAAaaaa:aaaaAAAAATT',
      'TTAAAAaaaa:aaaaAAAAATT',
      'TTAnAAaaaa:aaaaAAAAATT',
      'TTAAAAAAAA:AAAAAAAAATT',
      'TTTTTTTTTT::TTTTTTTTTT',
      'TTTTTTTTTT::TTTTTTTTTT',
    ],
    builds: [{ k: 'cave', x: 9, y: 1, to: 'volcano', tx: 10, ty: 14 }],
    edges: { D: { to: 'city2', off: 3 } },
    signs: { '3,15': '3ばんどうろ  はいが ふる みち  ↑ えんとつやま' },
    items: [{ x: 18, y: 5, item: 'superpotion' }, { x: 3, y: 9, item: 'ultra' }, { x: 19, y: 14, item: 'revive' }],
    npcs: [
      { ch: 'hiker', x: 13, y: 9, dir: 'L', tr: TR('やまおとこ ダイ', 'hiker', [[16, 16], [23, 17]], 600, 'はいだらけの やまみちへ ようこそ！ しょうぶだ！', 'まいった まいった！', 'えんとつやまの うえで あかい フードの れんちゅうを みたぞ。', { sight: 3, music: 'trainer' }) },
      { ch: 'lass', x: 7, y: 14, dir: 'R', tr: TR('おねえさん サキ', 'lass', [[18, 17], [12, 16]], 560, 'はいが かかって ふくが まっしろ！ もう、 しょうぶよ！', 'きゃー！ まけちゃった！', 'ゆめうさって かわいいでしょ？', { sight: 3, music: 'trainer' }) },
      { ch: 'grunt', x: 12, y: 5, dir: 'L', tr: GRUNT('A', [[21, 18], [20, 18]], 'ここは カザンだんが みはってるんだ！ とおさないぞ！', { sight: 2 }) },
    ],
  },
  // ------------------------------------------------------------ えんとつやま
  volcano: {
    name: 'えんとつやま', bgm: 'kazan', benv: 'volcano', weather: 'heat',
    grid: [
      '####################',
      '##llllllllllllllll##',
      '##lllVVVVVVVVVllll##',
      '##llVVVVVVVVVVVVll##',
      '##lVVVVVVVVVVVVVVl##',
      '##VVVVVVVVVVVVVVVV##',
      '##VVVVllVVVVllVVVV##',
      '##VVVVllVVVVllVVVV##',
      '##VVVVVVVVVVVVVVVVVV',
      '##VVlVVVVVVVVVVlVV##',
      '##VVVVVVVVVVVVVVVV##',
      '##VVVVVVVVVVVVVVVV##',
      '###VVVVVVVVVVVVVV###',
      '####VVVVVVVVVVVV####',
      '#####VVVVVVVVVV#####',
      '##########e#########',
    ],
    warps: [{ x: 10, y: 15, to: 'route3', tx: 10, ty: 3, dir: 'D' }],
    edges: { R: { to: 'yukemuri', off: 0, if: () => flag('boss1'), block: async () => { await say('カザンだん「ここから さきは とおさないぞ！」'); await walk(F.pl, 'L'); } } },
    trigs: [{ x: 4, y: 6, w: 12, h: 1, if: () => !flag('boss1'), run: () => bossVolcano() }],
    npcs: [
      { id: 'boss', ch: 'boss', x: 10, y: 4, dir: 'D', if: () => !flag('boss1') },
      { id: 'vg1', ch: 'grunt', x: 9, y: 3, dir: 'D', if: () => !flag('boss1') },
      { id: 'vg2', ch: 'gruntF', x: 11, y: 3, dir: 'D', if: () => !flag('boss1') },
      { id: 'vgate', ch: 'grunt', x: 18, y: 8, dir: 'L', if: () => !flag('boss1'), talk: 'ボスの じゃまは させないぞ！' },
      { ch: 'gruntF', x: 4, y: 11, dir: 'R', tr: GRUNT('F', [[20, 19], [21, 19]], 'ボスは いま だいじな しごと ちゅう！ じゃまよ！', { sight: 4, ch: 'gruntF' }) },
      { ch: 'grunt', x: 15, y: 10, dir: 'L', tr: GRUNT('B', [[15, 19], [21, 20]], 'あかいたまの ちからで だいちを ひろげるんだ！ わっはっは！', { sight: 3 }) },
      { ch: 'oldman', x: 7, y: 12, dir: 'U', if: () => flag('boss1'), talk: 'えんとつやまの けむりが へったよ。 ありがとう、 ちいさな トレーナーさん。' },
    ],
  },
  // ------------------------------------------------------------ ゆけむりタウン
  yukemuri: {
    name: 'ゆけむりタウン', bgm: 'town', out: true, border: 'T', benv: 'grass',
    grid: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TT....................TT',
      'TT....................TT',
      'TT....................TT',
      'TT....................TT',
      'TT....................TT',
      'TT...:.....:......:...TT',
      'TT...:.....:......:...TT',
      '::::::::::::::::::::::::',
      'TT....................TT',
      'TT.hhhh.......n.......TT',
      'TT.hhhh...............TT',
      'TT.hhhh...............TT',
      'TT....................TT',
      'TT..f..........f......TT',
      'TTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    builds: [
      { k: 'center', x: 2, y: 2, to: 'c3', tx: 6, ty: 7 },
      { k: 'mart', x: 9, y: 2, to: 'm3', tx: 4, ty: 6 },
      { k: 'gymFire', x: 15, y: 1, to: 'gym3', tx: 5, ty: 13 },
    ],
    edges: { L: { to: 'volcano', off: 0 }, R: { to: 'ruinsOut', off: -1, if: () => G.badges.length >= 3, block: async () => { await say('ひがしの いせきは だいじな ばしょ。 ジムバッジ 3こ もってる ひとしか とおれないの。', { who: 'おばあちゃん' }); await walk(F.pl, 'L'); } } },
    signs: { '14,10': 'ゆけむりタウン  ぽかぽか おんせんの まち' },
    npcs: [
      { ch: 'oldlady', x: 22, y: 7, dir: 'L', if: () => G.badges.length < 3, talk: 'ジムバッジ 3こ あつめたら ひがしの いせきへ いけるよ。' },
      { ch: 'oldman', x: 7, y: 11, dir: 'L', talk: 'おんせんは いいのう〜。 ふーモンも ぽっかぽか じゃ。' },
      { ch: 'girl', x: 12, y: 13, wander: true, talk: 'ジムリーダーの ホムラさんは ほのおタイプ！ みずや いわの わざが よく きくよ！' },
      { ch: 'boy', x: 18, y: 10, wander: true, talk: () => flag('boss1') ? say('カザンだんが ひがしの ふるい いせきへ はしって いったよ！ なにを する きだろう？') : say('えんとつやまの ほうから ゴゴゴって おとが きこえたよ。') },
    ],
  },
  c3: centerMap('c3', ['yukemuri', 5, 6]),
  m3: martMap('m3', ['yukemuri', 11, 6]),
  gym3: {
    name: 'ゆけむりジム', bgm: 'route', benv: 'volcano',
    grid: ['wwwwwwwwwww', 'VVVVVVVVVVV', 'VlVVVVVVVlV', 'VVVVllVVVVV', 'llVVVVVVVll', 'VVVVVVVVVVV', 'VVVllVllVVV', 'VVVVVVVVVVV', 'lllVVVVVlll', 'VVVVVVVVVVV', 'VVVVVVVVVVV', 'VlVVVVVVVlV', 'VVVVVVVVVVV', 'wwwwwmwwwww'],
    warps: [{ x: 5, y: 13, to: 'yukemuri', tx: 18, ty: 6, dir: 'D' }],
    npcs: [
      { ch: 'scientist', x: 7, y: 12, dir: 'L', talk: 'ホムラさんは ほのおタイプ！ みず・いわ・じめんの わざが よく きくよ！ あつさに まけないで！', who: 'ジムガイド' },
      { ch: 'boy', x: 1, y: 9, dir: 'R', tr: TR('ほのおの こ ヒロ', 'boy', [[21, 21], [3, 22]], 600, 'ぼくの ほのおは あついぞー！', 'あちちっ！ まけた！', 'ホムラさんの ほのおは もっと あついよ！', { sight: 5 }) },
      { ch: 'lass', x: 9, y: 5, dir: 'L', tr: TR('おねえさん アカネ', 'lass', [[21, 22], [22, 21]], 620, 'あつい しょうぶ、 しましょ！', 'あら、 ほのおが きえちゃった。', 'がんばってね、 ちいさな チャレンジャー！', { sight: 4 }) },
      { id: 'leader', ch: 'homura', x: 5, y: 1, dir: 'D', talk: () => gymLeader(2) },
    ],
  },
  // ------------------------------------------------------------ いせき
  ruinsOut: {
    name: 'いせきの まえ', bgm: () => flag('rubidon') ? 'town' : 'legend', out: true, border: 'T', benv: 'ruin',
    grid: [
      'TTTTTTTT::TTTTTTTTTT',
      'TT======::========TT',
      'TT======::========TT',
      'TT================TT',
      'TT================TT',
      'TT================TT',
      'TT================TT',
      '::::::::::::::====TT',
      'TT================TT',
      'TT=====Y======Y===TT',
      'TT================TT',
      'TTTTTTTTTTTTTTTTTTTT',
    ],
    builds: [{ k: 'ruin', x: 11, y: 3, to: 'ruins', tx: 7, ty: 14 }],
    edges: { L: { to: 'yukemuri', off: 1 }, U: { to: 'leagueOut', off: -1, if: () => flag('rubidon'), block: async () => { await say('いせきの なかから ゴゴゴ…… と へんな おとが きこえる。 いまは さきに すすめない！'); await walk(F.pl, 'D'); } } },
    npcs: [{ ch: 'oldman', x: 4, y: 4, dir: 'R', talk: () => flag('rubidon') ? say('きたへ すすむと ふーモンリーグじゃ。 つよい トレーナーが まっておるぞ。') : say('この いせきには だいちの かみさま ルビドンが ねむって いるんじゃ。') }],
  },
  ruins: {
    name: 'ふるい いせき', bgm: () => flag('rubidon') ? 'cave' : 'legend', benv: 'ruin',
    grid: [
      'UUUUUUUUUUUUUUU',
      'UUUUUuuuuuUUUUU',
      'UUUUuuuuuuuUUUU',
      'UUUuuuuuuuuuUUU',
      'UUuuuuuuuuuuuUU',
      'UUuuuuuuuuuuuUU',
      'UUuuUuuuuuUuuUU',
      'UUuuUuuuuuUuuUU',
      'UUuuuuuuuuuuuUU',
      'UUuuUUUuUUUuuUU',
      'UUuuuuuuuuuuuUU',
      'UUuuuuuuuuuuuUU',
      'UUUUUUUuUUUUUUU',
      'UUuuuuuuuuuuuUU',
      'UUuuuuuuuuuuuUU',
      'UUUUUUUeUUUUUUU',
    ],
    warps: [{ x: 7, y: 15, to: 'ruinsOut', tx: 13, ty: 7, dir: 'D' }],
    trigs: [{ x: 3, y: 8, w: 9, h: 1, if: () => !flag('rubidon'), run: () => ruinsEvent() }],
    items: [{ x: 2, y: 13, item: 'hyperpotion' }, { x: 12, y: 10, item: 'ultra', n: 2 }],
    npcs: [
      { id: 'rubidon', mon: 24, big: true, x: 7, y: 2, dir: 'D', if: () => !flag('rubidonCaught'), talk: () => flag('rubidon') ? rubidonAgain() : null },
      { id: 'boss2', ch: 'boss', x: 7, y: 4, dir: 'U', if: () => !flag('rubidon') },
      { ch: 'grunt', x: 2, y: 11, dir: 'R', if: () => !flag('rubidon'), tr: GRUNT('C', [[21, 25], [20, 26]], 'ボスは ルビドンを めざめさせるんだ！ じゃまは させない！', { sight: 4 }) },
      { ch: 'gruntF', x: 12, y: 8, dir: 'L', if: () => !flag('rubidon'), tr: GRUNT('G', [[16, 26], [21, 26]], 'だいちを ひろげて カザンだんの くにを つくるのよ！', { sight: 3, ch: 'gruntF' }) },
    ],
  },
  // ------------------------------------------------------------ ふーモンリーグ
  leagueOut: {
    name: 'ふーモンリーグ', bgm: 'title', out: true, border: 'T', benv: 'league',
    grid: [
      'TTTTTTTTTTTTTTTT',
      'TTff........ffTT',
      'TT............TT',
      'TT............TT',
      'TT............TT',
      'TT............TT',
      'TT............TT',
      'TT............TT',
      'TT.....::.....TT',
      'TT.....::.....TT',
      'TTf....::....fTT',
      'TT.....::.....TT',
      'TTTTTTT::TTTTTTT',
      'TTTTTTT::TTTTTTT',
    ],
    builds: [{ k: 'league', x: 3, y: 2, to: 'leagueHall', tx: 6, ty: 9 }],
    edges: { D: { to: 'ruinsOut', off: 1 } },
    npcs: [{ ch: 'scientist', x: 10, y: 9, dir: 'L', talk: 'ここは ふーモンリーグ！ チャンピオンに かてば でんどういり だよ！' }],
  },
  leagueHall: {
    name: 'リーグ ロビー', bgm: 'center', benv: 'league',
    grid: ['wwwwwwrwwwwww', 'QOOOOOrOOOOOQ', 'OOOOOOrOOOOOO', 'OkkkOOrOOKKKO', 'OOOOOOrOOOOOO', 'OOOOOOrOOOOOO', 'QOOOOOrOOOOOQ', 'OOOOOOrOOOOOO', 'OOOOOOrOOOOOO', 'wwwwwwmwwwwww'],
    warps: [{ x: 6, y: 9, to: 'leagueOut', tx: 7, ty: 8, dir: 'D' }, { x: 6, y: 0, to: 'champ', tx: 5, ty: 10, dir: 'U', step: true }],
    npcs: [
      { ch: 'nurse', x: 2, y: 2, talk: centerHeal },
      { ch: 'clerk', x: 10, y: 2, talk: martMenu },
      { ch: 'sota', x: 7, y: 1, dir: 'L', if: () => flag('rival2'), talk: 'チャンピオンは この おくだよ。 がんばって、 ふーたん！', who: 'ソウタ' },
      { id: 'sota2', ch: 'sota', x: 6, y: 1, dir: 'D', if: () => !flag('rival2'), tr: { name: 'ライバルの ソウタ', ch: 'sota', partyFn: () => rivalParty(2), money: 3000, flag: 'rival2', sight: 6, music: 'boss', post: () => rivalLeaguePost(), pre: 'ふーたん！ やっぱり きたね！ ぼくも ジムバッジ あつめて ここまで きたんだ。 チャンピオンの まえに ぼくと しょうぶだ！', win: 'すごいや ふーたん…… ぼくの まけだ！', after: 'チャンピオンは この おくだよ。 がんばって、 ふーたん！' } },
    ],
  },
  champ: {
    name: 'チャンピオンの へや', bgm: 'legend', benv: 'league',
    grid: ['WWWWWWWWWWW', 'WRRRRrRRRRW', 'WRRRRrRRRRW', 'WRZRRrRRZRW', 'WRRRRrRRRRW', 'WRRRRrRRRRW', 'WRZRRrRRZRW', 'WRRRRrRRRRW', 'WRRRRrRRRRW', 'WRRRRrRRRRW', 'WRRRRrRRRRW', 'WWWWWWWWWWW'],
    trigs: [{ x: 1, y: 4, w: 9, h: 1, if: () => !flag('champion'), run: () => championBattle() }],
    npcs: [{ id: 'ruri', ch: 'ruri', x: 5, y: 2, dir: 'D', talk: () => say('おめでとう、 チャンピオン ふーたん！', { who: 'ルリ' }) }],
  },
};
