// ================= ice cream =================
const FLAV=[['#ffb3d6','いちご','strawberry'],['#fff6e0','バニラ','vanilla'],['#8a5a3a','チョコ','chocolate'],['#a8ecc8','メロン','melon'],['#b8a0ff','ぶどう','grape'],['#ffe07a','バナナ','banana']];
SCN.icecream={bg:'#e8f8ff',song:'fuwa',
  enter(){this.ci=0;this.fin=0;this.good=0;this.newCust();},
  newCust(){this.ph='cone';this.t=0;this.base=null;this.sc=[];this.spr=[];this.cherry=false;this.dr=null;this.lick=0;const n=2+(Math.random()<.5?1:0);this.cust={k:pick(['bear','rabbit','cat','panda','pig','chick']),want:shuffle(FLAV).slice(0,n).map(f=>f[0]),cone:pick(['cone','cup'])};
    say(`${WORDS[this.cust.k][0]}さんの ちゅうもん！ ${this.cust.cone==='cone'?'コーン':'カップ'}を えらんでね`);},
  C(){return{x:300,y:H*.62};},
  drawIce(c,x,y,s,base,sc,spr,cherry,lick){c.save();c.translate(x,y);c.scale(s,s);
    if(base==='cone'){c.fillStyle='#e8b060';c.beginPath();c.moveTo(-40,0);c.lineTo(40,0);c.lineTo(0,110);c.closePath();c.fill();c.strokeStyle='#c88a40';c.lineWidth=2;for(let i=-3;i<=3;i++){c.beginPath();c.moveTo(i*12-10,0);c.lineTo(i*6+6,70);c.stroke();c.beginPath();c.moveTo(i*12+10,0);c.lineTo(i*6-6,70);c.stroke();}}
    else if(base==='cup'){c.fillStyle='#ff9ac8';c.beginPath();c.moveTo(-50,0);c.lineTo(50,0);c.lineTo(38,70);c.lineTo(-38,70);c.closePath();c.fill();c.fillStyle='#fff';for(let i=0;i<4;i++)circ(c,-30+i*20,36,6);}
    sc.forEach((col,i)=>{const r=42*(i===sc.length-1?1-lick*.5:1);c.fillStyle=col;c.beginPath();c.arc(0,-24-i*54,r,0,TAU);c.fill();c.fillStyle=shade(col,-.08);for(let k=-2;k<=2;k++)circ(c,k*16,-2-i*54,11);c.fillStyle='rgba(255,255,255,.4)';ell(c,-14,-40-i*54,10,6);});
    for(const p of spr){c.fillStyle=p.col;c.save();c.translate(p.x,p.y);c.rotate(p.r);c.fillRect(-5,-1.5,10,3);c.restore();}
    if(cherry&&sc.length){c.fillStyle='#ff2a3a';circ(c,0,-24-(sc.length-1)*54-44,12);c.strokeStyle='#4a8a2a';c.lineWidth=3;c.beginPath();c.moveTo(0,-24-(sc.length-1)*54-54);c.quadraticCurveTo(8,-24-(sc.length-1)*54-70,14,-24-(sc.length-1)*54-74);c.stroke();}c.restore();},
  update(dt){this.t+=dt;if(this.fin>0){this.fin+=dt;if(this.fin>2.4&&this.fin<9){this.fin=9;celebrate('icecream',this.good>=2);}}},
  tubP(i){return{x:70+i*92,y:H-80};},
  draw(c){c.fillStyle='#e8f8ff';c.fillRect(-400,0,W+800,H);for(let x=-400;x<W+400;x+=60){c.fillStyle=(x/60)%2?'#ffd0e6':'#fff';c.beginPath();c.moveTo(x,0);c.lineTo(x+60,0);c.lineTo(x+60,50);c.quadraticCurveTo(x+30,70,x,50);c.fill();}
    c.fillStyle=vfill(c,H*.66,H,'#ffe0ee',.05,-.06);c.fillRect(-400,H*.66,W+800,H);const cu=this.cust,C=this.C(),ph=this.ph;
    drawAnimal(c,cu.k,80,H*.4,.62,{t:T,happy:ph==='serve',eat:this.lick>0});customerBubble(c,130,H*.4-200,(x,y)=>{this.drawIce(c,x,y+10,.26,cu.cone,cu.want,[],false,0);});
    for(let i=0;i<this.ci;i++){c.fillStyle='#ffd23a';star(c,W-60-i*40,150,16,7);c.fill();}
    if(ph==='cone'){for(const [b,x] of [['cone',200],['cup',400]]){c.fillStyle='#fff';circ(c,x,H*.5,90);c.strokeStyle='#ffb3d6';c.lineWidth=5;c.beginPath();c.arc(x,H*.5,90,0,TAU);c.stroke();this.drawIce(c,x,H*.5-20,.9,b,[],[],false,0);c.fillStyle='#8a5a8a';c.font=`800 22px ${FONT}`;c.textAlign='center';c.fillText(b==='cone'?'コーン':'カップ',x,H*.5+110);}}
    else{this.drawIce(c,C.x,C.y,1,this.base,this.sc,this.spr,this.cherry,this.lick);}
    if(ph==='scoop'){tray(c,H-80,120);FLAV.forEach((f,i)=>{const p=this.tubP(i);c.fillStyle='#d8e8f8';rr(c,p.x-38,p.y-20,76,50,10);c.fill();c.fillStyle=f[0];ell(c,p.x,p.y-18,34,16);c.fillStyle='#8a5a8a';c.font=`800 14px ${FONT}`;c.textAlign='center';c.fillText(f[1],p.x,p.y+18);});if(this.dr){c.fillStyle=this.dr.col;circ(c,this.dr.x,this.dr.y,40);c.strokeStyle='#a8b0c8';c.lineWidth=6;c.beginPath();c.moveTo(this.dr.x+20,this.dr.y+30);c.lineTo(this.dr.x+50,this.dr.y+80);c.stroke();}if(this.sc.length)drawBtn(c,W-70,H*.64,42,'#4cd08a','check',this.sc.length>=this.cust.want.length);}
    if(ph==='top'){c.fillStyle='#fff';rr(c,40,H-150,520,120,24);c.fill();SPECIAL_THING.sprinkles(c,150,H-90,1.6);c.fillStyle='#ff2a3a';circ(c,300,H-90,20);c.fillStyle='#8a5a8a';c.font=`800 16px ${FONT}`;c.textAlign='center';c.fillText('ふりかけ',150,H-40);c.fillText('さくらんぼ',300,H-40);drawBtn(c,470,H-90,40,'#4cd08a','check',this.spr.length>10);if(this.shaker){SPECIAL_THING.sprinkles(c,this.shaker.x,this.shaker.y,1.6);}}
    if(ph==='serve'){c.fillStyle='rgba(255,255,255,.9)';rr(c,W/2-150,H*.84,300,54,27);c.fill();c.fillStyle='#ff5fa2';c.font=`800 22px ${FONT}`;c.textAlign='center';c.textBaseline='middle';c.fillText('アイスを タッチして わたそう',W/2,H*.84+27);}
    drawFuka(c,530,H*.64,{outfit:outfit(),t:T,sc:2,point:1});stepDots(c,4,{cone:0,scoop:1,top:2,serve:3}[ph],128);},
  down(x,y){const ph=this.ph,C=this.C();
    if(ph==='cone'){for(const [b,bx] of [['cone',200],['cup',400]])if(hitC(x,y,bx,H*.5,95)){this.base=b;this.ph='scoop';sfx('pop');say(b===this.cust.cone?'ちゅうもん どおり！ アイスを すくって のせよう':'アイスを すくって のせよう');this.coneOk=b===this.cust.cone;return;}return;}
    if(ph==='scoop'){if(this.sc.length&&hitC(x,y,W-70,H*.64,52)){this.ph='top';sfx('spark');say('トッピング！ ふりかけを もって アイスの うえで ふりふり');return;}FLAV.forEach((f,i)=>{const p=this.tubP(i);if(Math.abs(x-p.x)<42&&Math.abs(y-p.y)<34&&this.sc.length<3){this.dr={col:f[0],x,y,n:f[1]};sfx('squish');sayPair(f[1],f[2]);}});return;}
    if(ph==='top'){if(hitC(x,y,150,H-90,50)){this.shaker={x,y};sfx('tap');return;}if(hitC(x,y,300,H-90,30)&&!this.cherry){this.cherry=true;sfx('pop');say('さくらんぼ ちょこん！');return;}if(hitC(x,y,470,H-90,48)){this.ph='serve';sfx('fanfare');return;}return;}
    if(ph==='serve'){if(Math.abs(x-C.x)<100&&y<C.y+120&&y>C.y-220){const cu=this.cust;const ok=this.coneOk&&cu.want.length===this.sc.length&&cu.want.every(w=>this.sc.includes(w));if(ok)this.good++;this.lick=.01;sfx('munch');say(ok?`${WORDS[cu.k][0]}さん「ちゅうもん ぴったり！ おいしい〜！」`:`${WORDS[cu.k][0]}さん「わあ、おいしそう！ ありがとう！」`);if(ok)confetti(40);this.ci++;setTimeout(()=>{if(scene!==this)return;if(this.ci>=3){this.fin=.01;sfx('fanfare');say('アイスやさん だいせいこう！');}else this.newCust();},2200);}}},
  move(x,y){if(this.dr){this.dr.x=x;this.dr.y=y;}if(this.shaker){const d=Math.hypot(x-this.shaker.x,y-this.shaker.y);this.shaker.x=x;this.shaker.y=y;const C=this.C();if(d>6&&Math.abs(x-C.x)<120&&y<C.y-20&&y>C.y-260){for(let k=0;k<2;k++)this.spr.push({x:rand(-40,40),y:-20-rand(0,this.sc.length*54),r:rand(0,6),col:pick(['#ff5f6f','#5aa8ff','#ffd23a','#6cd08a','#fff'])});if(Math.random()<.2)sfx('tick');}}},
  up(x,y){const C=this.C();if(this.dr){const d=this.dr;this.dr=null;if(Math.abs(x-C.x)<120&&y<C.y+40&&y>C.y-300){this.sc.push(d.col);sfx('boing');burst(C.x,C.y-24-(this.sc.length-1)*54,8,'star');if(this.sc.length>=3)say('3だん アイス！');}}this.shaker=null;},
  hint(){const ph=this.ph,C=this.C();if(ph==='cone')return{x:this.cust.cone==='cone'?200:400,y:H*.5};if(ph==='scoop'){if(this.sc.length>=this.cust.want.length)return{x:W-70,y:H*.64};const w=this.cust.want.find(w=>!this.sc.includes(w));const i=FLAV.findIndex(f=>f[0]===w);const p=this.tubP(Math.max(0,i));return{x:p.x,y:p.y,x2:C.x,y2:C.y-40};}if(ph==='top')return this.spr.length>10?{x:470,y:H-90}:{x:150,y:H-90,x2:C.x,y2:C.y-100};return{x:C.x,y:C.y-60};},
  hintText(){return{cone:'コーンか カップを えらんでね',scoop:'ちゅうもんの いろの アイスを のせよう',top:'ふりかけで かざろう',serve:'アイスを タッチして わたそう'}[this.ph]||'';}};
