// ================= hair salon (lion) =================
SCN.salon={bg:'#fff0f8',song:'fuwa',
  COLS:['#e8a040','#ff8cc0','#8ad0ff','#b48cff','#6cd08a','#ffd23a'],
  enter(){this.ph='wash';this.t=0;this.fin=0;this.L=[...Array(20)].map(()=>rand(70,140));this.wet=0;this.foam=0;this.rinse=0;this.fluff=0;this.col='#e8a040';this.acc=null;this.tool=null;this.photo=0;this.soaped=false;
    say('ヘアサロン！ らいおんさんの たてがみが ぼさぼさ。 シャンプーで あわあわ しよう！');},
  L0(){return{x:300,y:H*.46,s:1.25};},
  update(dt){this.t+=dt;if(this.photo>0){this.photo+=dt;if(this.photo>2.6&&!this.fin){this.fin=.01;}}if(this.fin>0){this.fin+=dt;if(this.fin>1&&this.fin<9){this.fin=9;celebrate('salon',this.L.every(l=>l<75)&&this.acc);}}},
  tools(){return{wash:[['shampoo','シャンプー'],['shower','シャワー']],cut:[['scissors','はさみ']],dry:[['dryer','ドライヤー']],style:[]}[this.ph]||[];},
  draw(c){c.fillStyle='#fff0f8';c.fillRect(-400,0,W+800,H);c.fillStyle='#ffe0ee';for(let x=0;x<W;x+=50)c.fillRect(x,0,25,H*.7);c.fillStyle='#fff';rr(c,120,H*.12,360,H*.52,180);c.fill();c.strokeStyle='#ffd23a';c.lineWidth=10;c.stroke();c.fillStyle='rgba(200,230,255,.4)';rr(c,130,H*.13,340,H*.5,170);c.fill();
    c.fillStyle=vfill(c,H*.7,H,'#e8c8d8',.05,-.08);c.fillRect(-400,H*.7,W+800,H);c.fillStyle='#b48cff';rr(c,190,H*.62,220,80,20);c.fill();
    const Lp=this.L0();drawLion(c,Lp.x,Lp.y,Lp.s,{L:this.L,col:this.col,wet:this.wet,fluff:this.fluff,acc:this.acc});
    if(this.foam>0){c.globalAlpha=Math.min(1,this.foam);c.fillStyle='#fff';for(let i=0;i<20;i++){const a=i/20*TAU,r=80+Math.sin(i*3)*20;circ(c,Lp.x+Math.cos(a)*r*Lp.s,Lp.y+Math.sin(a)*r*Lp.s,22);}c.globalAlpha=1;}
    if(this.ph==='cut'){c.strokeStyle='rgba(255,90,150,.35)';c.lineWidth=3;c.setLineDash([6,6]);c.beginPath();c.arc(Lp.x,Lp.y,(40+72)*Lp.s,0,TAU);c.stroke();c.setLineDash([]);const n=this.L.filter(l=>l<75).length;c.fillStyle='#fff';rr(c,W/2-110,H*.7+100,220,40,20);c.fill();c.fillStyle='#ff5fa2';c.font=`800 20px ${FONT}`;c.textAlign='center';c.textBaseline='middle';c.fillText(`カット ${n}/${this.L.length}`,W/2,H*.7+120);}
    if(this.ph==='style'){this.COLS.forEach((col,i)=>{const x=70+i*92;c.fillStyle=col;circ(c,x,H-150,30);c.strokeStyle=this.col===col?'#5a3a5a':'#fff';c.lineWidth=4;c.beginPath();c.arc(x,H-150,30,0,TAU);c.stroke();});
      [['bow','リボン'],['flower','はな'],['crown','かんむり']].forEach(([k,n],i)=>{const x=150+i*150;c.fillStyle=this.acc===k?'#fff0f7':'#fff';rr(c,x-56,H-100,112,60,20);c.fill();c.strokeStyle='#ff8cc0';c.lineWidth=3;c.stroke();c.fillStyle='#ff5fa2';c.font=`800 20px ${FONT}`;c.textAlign='center';c.textBaseline='middle';c.fillText(n,x,H-70);});drawBtn(c,W-60,H*.64,42,'#5aa8ff','camera',!!this.acc);}
    else{tray(c,H-80,120);this.tools().forEach(([k,n],i)=>{const x=W/2-(this.tools().length-1)*90+i*180;c.globalAlpha=this.tool&&this.tool.k===k?.3:1;if(k==='scissors'||k==='dryer')SPECIAL_THING[k](c,x,H-80,1.7);else drawItem(c,k,x,H-80,1.5);c.globalAlpha=1;});
      if(this.tool){const t=this.tool;if(t.k==='scissors')SPECIAL_THING.scissors(c,t.x,t.y,2+Math.sin(T*20)*.1);else if(t.k==='dryer'){SPECIAL_THING.dryer(c,t.x,t.y,2);c.strokeStyle='rgba(255,255,255,.7)';c.lineWidth=3;for(let i=0;i<4;i++){c.beginPath();c.moveTo(t.x+60,t.y-20+i*10);c.lineTo(t.x+100+Math.random()*20,t.y-24+i*12);c.stroke();}}else drawItem(c,t.k,t.x,t.y,1.8);}}
    if(this.photo>0){c.fillStyle=`rgba(255,255,255,${Math.max(0,1-this.photo*2)})`;c.fillRect(-400,0,W+800,H);c.font=`40px ${POP}`;c.textAlign='center';c.fillStyle='#ff5fa2';c.fillText('すてき〜！',W/2,H*.1);}
    drawFuka(c,70,H*.9,{outfit:outfit(),t:T,sc:2,point:1,cheer:this.photo>0});drawRikki(c,540,H*.9,{sc:1.5,t:T,clap:RK.clap});this.rkPos={x:540,y:H*.9,sc:1.5};stepDots(c,4,{wash:0,cut:1,dry:2,style:3}[this.ph],128);},
  down(x,y){const ph=this.ph;if(ph==='style'){this.COLS.forEach((col,i)=>{if(hitC(x,y,70+i*92,H-150,34)){this.col=col;sfx('spark');burst(300,H*.4,10,'star');say(['オレンジ','ピンク','みずいろ','むらさき','みどり','きいろ'][i]+'の たてがみ！');}});[['bow'],['flower'],['crown']].forEach(([k],i)=>{if(Math.abs(x-(150+i*150))<56&&Math.abs(y-(H-70))<30){this.acc=k;sfx('pop');burst(300,H*.3,10,'heart');}});if(this.acc&&hitC(x,y,W-60,H*.64,50)&&!this.photo){this.photo=.01;sfx('shutter');confetti(60);say('はい チーズ！ らいおんさん かっこいい〜！');}return;}
    const ts=this.tools();ts.forEach(([k],i)=>{const tx=W/2-(ts.length-1)*90+i*180;if(hitC(x,y,tx,H-80,56)){this.tool={k,x,y,lx:x,ly:y};sfx('tap');}});},
  move(x,y){const t=this.tool;if(!t)return;const d=Math.hypot(x-t.lx,y-t.ly);const Lp=this.L0();const dist=Math.hypot(x-Lp.x,y-Lp.y);
    if(t.k==='shampoo'&&dist<200*Lp.s&&!this.soaped){this.foam=Math.min(1.2,this.foam+d/1400);if(this.foam>=1)this.soaped=true;this.wet=Math.min(1,this.wet+d/2000);if(Math.random()<.2){bubbles(x,y,2);sfx('squish');}}
    if(t.k==='shower'&&dist<220*Lp.s&&this.soaped){this.rinse+=d/1600;this.foam=Math.max(.01,1.2-this.rinse);if(Math.random()<.5)parts.push({x:x+rand(-20,20),y,vx:0,vy:200,life:.6,t:0,kind:'drop',col:'#8ad0ff'});if(Math.random()<.1)sfx('water');if(this.rinse>=1.2){this.foam=0;this.ph='cut';this.tool=null;sfx('fanfare');say('きれいに なった！ はさみで ながい けを ちょきちょき しよう。 てんせんの ところ！');}}
    if(t.k==='scissors'){const n=this.L.length;for(let i=0;i<n;i++){const a=i/n*TAU-Math.PI/2;const ex=Lp.x+Math.cos(a)*(40+this.L[i])*Lp.s,ey=Lp.y+Math.sin(a)*(40+this.L[i])*Lp.s;if(this.L[i]>=75&&Math.hypot(x-ex,y-ey)<60){this.L[i]=rand(62,72);sfx('snap');parts.push({x:ex,y:ey,vx:rand(-40,40),vy:rand(40,120),life:1,t:0,kind:'dot',col:this.col,r:6});}}if(this.L.every(l=>l<75)){this.ph='dry';this.tool=null;sfx('fanfare');rkCheer();say('さっぱり！ ドライヤーで かわかそう');}}
    if(t.k==='dryer'&&dist<260*Lp.s){this.wet=Math.max(0,this.wet-d/1600);this.fluff=Math.min(1,this.fluff+d/2000);if(Math.random()<.1)sfx('whoosh');if(this.wet<=0&&this.fluff>=.8){this.ph='style';this.tool=null;sfx('fanfare');say('ふわふわ！ いろを えらんで、かざりを つけよう');}}
    t.x=x;t.y=y;t.lx=x;t.ly=y;},
  up(){if(this.tool&&this.tool.k==='shampoo'&&this.soaped)say('あわあわ！ つぎは シャワーで ながそう');this.tool=null;},
  hint(){const Lp=this.L0(),ph=this.ph;if(ph==='wash'){const x=this.soaped?W/2+90:W/2-90;return{x,y:H-80,x2:Lp.x,y2:Lp.y-60};}if(ph==='cut'){const n=this.L.length,i=this.L.findIndex(l=>l>=75);if(i<0)return null;const a=i/n*TAU-Math.PI/2;return{x:W/2,y:H-80,x2:Lp.x+Math.cos(a)*(40+this.L[i])*Lp.s,y2:Lp.y+Math.sin(a)*(40+this.L[i])*Lp.s};}if(ph==='dry')return{x:W/2,y:H-80,x2:Lp.x,y2:Lp.y};return this.acc?{x:W-60,y:H*.64}:{x:150,y:H-70};},
  hintText(){return{wash:'シャンプーで あわあわ、シャワーで ながそう',cut:'はさみを ながい けの さきに もっていこう',dry:'ドライヤーで かわかそう',style:'いろと かざりを えらんで カメラ'}[this.ph]||'';}};
