// ================= tidy up & recycling =================
const TIDY=[['bear','toy','くまの ぬいぐるみ'],['duck','toy','あひる'],['tennisball','toy','ボール'],['xylophone','toy','もっきん'],['book','book','えほん'],['book2','book','ずかん'],['dress','cloth','ふく'],['mitten','cloth','てぶくろ'],['paper','burn','かみくず'],['banana','burn','バナナの かわ'],['bottle','pet','ペットボトル'],['can','can','あきかん']];
SCN.tidy={bg:'#fff0e8',song:'play',
  DEST:{toy:['おもちゃばこ',110,'#ff9ac8'],book:['ほんだな',300,'#8ad0ff'],cloth:['タンス',490,'#c8a0ff'],burn:['もえるごみ',110,'#ff9a5a'],pet:['ペットボトル',300,'#5aa8ff'],can:['かん',490,'#a8b0c0']},
  enter(){this.ph='toys';this.t=0;this.fin=0;this.miss=0;this.dr=null;this.items=shuffle(TIDY.filter(q=>['toy','book','cloth'].includes(q[1]))).map((q,i)=>({k:q[0],cat:q[1],n:q[2],x:80+(i%4)*140+rand(-20,20),y:H*.52+Math.floor(i/4)*110+rand(-15,15),r:rand(-.5,.5),done:false,sh:0}));this.dust=[...Array(8)].map(()=>({x:rand(60,540),y:rand(H*.5,H*.78),on:true}));
    say('おへやが ぐちゃぐちゃ！ おもちゃは おもちゃばこ、ほんは ほんだな、ふくは タンスに かたづけよう');},
  drawK(c,k,x,y,s){if(k==='book2'){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#6cd08a';rr(c,-18,-24,36,48,4);c.fill();c.fillStyle='#fff';rr(c,-12,-16,24,14,3);c.fill();c.restore();}else if(k==='paper'){c.fillStyle='#f0f0f0';circ(c,x,y,16*s);c.strokeStyle='#c8c8d8';c.lineWidth=2;c.beginPath();c.moveTo(x-8*s,y-4*s);c.lineTo(x+6*s,y+6*s);c.moveTo(x+6*s,y-8*s);c.lineTo(x-4*s,y+8*s);c.stroke();}
    else if(k==='bottle'){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='rgba(180,220,255,.8)';rr(c,-10,-18,20,40,6);c.fill();c.fillStyle='#5aa8ff';rr(c,-6,-26,12,10,3);c.fill();c.fillStyle='#ff5f6f';c.fillRect(-10,-2,20,8);c.restore();}else if(k==='can'){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#c8c8d8';rr(c,-12,-18,24,36,4);c.fill();c.fillStyle='#ff5f6f';c.fillRect(-12,-8,24,14);c.restore();}
    else if(k==='banana'){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ffd23a';for(const r of[-.6,0,.6]){c.save();c.rotate(r);c.beginPath();c.ellipse(0,-10,5,16,0,0,TAU);c.fill();c.restore();}c.restore();}else drawThing(c,k,x,y,s);},
  update(dt){this.t+=dt;for(const it of this.items)if(it.sh>0)it.sh-=dt;if(this.fin>0){this.fin+=dt;if(this.fin>2.6&&this.fin<9){this.fin=9;celebrate('tidy',this.miss===0);}}},
  destY(){return H*.26;},
  draw(c){const ph=this.ph;c.fillStyle=ph==='trash'?'#e8f4e8':'#fff0e8';c.fillRect(-400,0,W+800,H);if(ph!=='trash'){c.fillStyle='#ffe0d0';for(let x=0;x<W;x+=40)c.fillRect(x,0,20,H*.4);}c.fillStyle=vfill(c,H*.4,H,ph==='trash'?'#b8d8a8':'#e8c090',.05,-.08);c.fillRect(-400,H*.4,W+800,H);
    const cats=ph==='trash'?['burn','pet','can']:['toy','book','cloth'];for(const cat of cats){const [n,x,col]=this.DEST[cat],y=this.destY();c.fillStyle=col;rr(c,x-80,y-60,160,140,16);c.fill();c.fillStyle='rgba(255,255,255,.3)';rr(c,x-70,y-50,140,40,10);c.fill();c.fillStyle='#fff';c.font=`800 20px ${FONT}`;c.textAlign='center';c.textBaseline='middle';c.fillText(n,x,y+50,150);
      const ic={toy:'toybox',book:'book2',cloth:'dress',burn:'paper',pet:'bottle',can:'can'}[cat];this.drawK(c,ic==='toybox'?'duck':ic,x,y-2,1.2);this.items.filter(i=>i.done&&i.cat===cat).forEach((it,j)=>this.drawK(c,it.k,x-50+j*30,y+20,.5));}
    if(ph==='vac'){for(const d of this.dust)if(d.on){c.fillStyle='rgba(160,150,150,.6)';for(let i=0;i<4;i++)circ(c,d.x+Math.cos(i*1.6)*8,d.y+Math.sin(i*1.6)*6,9);}if(this.vac)SPECIAL_THING.vacuum(c,this.vac.x,this.vac.y,2.2);else SPECIAL_THING.vacuum(c,W/2,H-90,1.8);c.fillStyle='#8a5a3a';c.font=`800 20px ${FONT}`;c.textAlign='center';c.fillText('そうじきで ほこりを すいとろう',W/2,H*.44);}
    for(const it of this.items){if(it.done||this.dr&&this.dr.it===it)continue;c.save();c.translate(it.x+(it.sh>0?Math.sin(it.sh*40)*6:0),it.y);c.rotate(it.r);this.drawK(c,it.k,0,0,1.3);c.restore();}
    if(this.dr)this.drawK(c,this.dr.it.k,this.dr.x,this.dr.y,1.5);
    if(ph==='done'){c.fillStyle='#fff';for(let i=0;i<8;i++)if(Math.sin(T*4+i)>.5){star(c,60+i*70,H*.5+(i%3)*60,10,4,4);c.fill();}}
    drawFuka(c,70,H*.95,{outfit:outfit(),t:T,sc:1.8,point:ph!=='done',cheer:ph==='done'});drawRikki(c,540,H*.95,{sc:1.4,t:T,clap:RK.clap});this.rkPos={x:540,y:H*.95,sc:1.4};stepDots(c,3,{toys:0,trash:1,vac:2,done:3}[ph],128);},
  down(x,y){if(this.ph==='vac'){this.vac={x,y};return;}for(let i=this.items.length-1;i>=0;i--){const it=this.items[i];if(!it.done&&hitC(x,y,it.x,it.y,50)){this.dr={it,x,y};sfx('tap');say(it.n);return;}}},
  move(x,y){if(this.dr){this.dr.x=x;this.dr.y=y;}if(this.vac){this.vac.x=x;this.vac.y=y;for(const d of this.dust)if(d.on&&Math.hypot(d.x-(x-30),d.y-(y+40))<60){d.on=false;sfx('whoosh');puff(d.x,d.y,3,'#ccc');}if(this.dust.every(d=>!d.on)&&this.ph==='vac'){this.ph='done';this.vac=null;this.fin=.01;sfx('fanfare');confetti(80);say('ピカピカの おへや！ おかたづけ めいじん！');}}},
  up(x,y){const d=this.dr;if(!d)return;this.dr=null;const it=d.it,cats=this.ph==='trash'?['burn','pet','can']:['toy','book','cloth'];const hit=cats.find(cat=>Math.abs(x-this.DEST[cat][1])<90&&Math.abs(y-this.destY())<90);
    if(!hit){it.x=x;it.y=y;return;}if(hit===it.cat){it.done=true;sfx('ding');burst(x,y,10,'star');rkCheer();
      if(this.items.every(q=>q.done)){if(this.ph==='toys'){this.ph='trash';sfx('fanfare');this.items=shuffle(TIDY.filter(q=>['burn','pet','can'].includes(q[1]))).map((q,i)=>({k:q[0],cat:q[1],n:q[2],x:110+i*130,y:H*.62+rand(-30,30),r:rand(-.4,.4),done:false,sh:0}));say('つぎは ごみの ぶんべつ！ もえるごみ、ペットボトル、かんに わけよう');}else{this.ph='vac';sfx('fanfare');say('さいごに そうじきで ほこりを すいとろう');}}}
    else{it.sh=.5;this.miss++;sfx('no');const n=this.DEST[it.cat][0];say(`${it.n}は 「${n}」だよ`);}},
  hint(){if(this.ph==='vac'){const d=this.dust.find(d=>d.on);return d?{x:W/2,y:H-90,x2:d.x+30,y2:d.y-40}:null;}const it=this.items.find(i=>!i.done);if(!it)return null;return{x:it.x,y:it.y,x2:this.DEST[it.cat][1],y2:this.destY()};},
  hintText(){return this.ph==='vac'?'そうじきを うごかそう':'ただしい ところに かたづけよう';}};
