// ================= learning attractions: shared art =================
const NUMJ=['ゼロ','いち','に','さん','よん','ご','ろく','なな','はち','きゅう','じゅう','じゅういち','じゅうに'],NUMEN=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve'];
const SHP={circle:['まる','circle','#ff6f8f'],tri:['さんかく','triangle','#ffd23a'],sq:['しかく','square','#5aa8ff'],star:['ほし','star','#b48cff'],heart:['ハート','heart','#ff8cc0'],rect:['ながしかく','rectangle','#6cd08a']};
function shapePath(c,k,x,y,s){c.beginPath();if(k==='circle')c.arc(x,y,s,0,TAU);else if(k==='tri'){c.moveTo(x,y-s);c.lineTo(x+s*1.1,y+s*.8);c.lineTo(x-s*1.1,y+s*.8);c.closePath();}
  else if(k==='sq')c.rect(x-s*.9,y-s*.9,s*1.8,s*1.8);else if(k==='rect')c.rect(x-s*.6,y-s*1.2,s*1.2,s*2.4);else if(k==='star'){for(let i=0;i<10;i++){const a=i/10*TAU-Math.PI/2,r=i%2?s*.45:s;c.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r);}c.closePath();}
  else if(k==='heart'){c.moveTo(x,y+s*.9);c.bezierCurveTo(x-s*1.3,y,x-s*.7,y-s*1.1,x,y-s*.45);c.bezierCurveTo(x+s*.7,y-s*1.1,x+s*1.3,y,x,y+s*.9);c.closePath();}}
function drawShape(c,k,x,y,s,col,mode){shapePath(c,k,x,y,s);if(mode==='hole'){c.fillStyle='rgba(60,40,80,.55)';c.fill();c.strokeStyle='rgba(255,255,255,.5)';c.lineWidth=3;c.stroke();return;}
  if(mode==='slot'){c.fillStyle='rgba(255,255,255,.45)';c.fill();c.setLineDash([10,8]);c.strokeStyle=col||'#8a7a9a';c.lineWidth=4;c.stroke();c.setLineDash([]);return;}
  c.fillStyle=gfill(c,x-s*.3,y-s*.3,s*1.4,col||SHP[k][2],.3,-.12);c.fill();c.strokeStyle=shade(col||SHP[k][2],-.25);c.lineWidth=Math.max(2,s*.07);c.stroke();c.fillStyle='rgba(255,255,255,.35)';ell(c,x-s*.3,y-s*.35,s*.25,s*.12);}
const SIL={};
function silhouette(k,col){const key=k+(col||'');if(SIL[key])return SIL[key];const cv2=document.createElement('canvas');cv2.width=cv2.height=220;const c=cv2.getContext('2d');drawThing(c,k,110,110,1.9);c.globalCompositeOperation='source-in';c.fillStyle=col||'#4a3a6a';c.fillRect(0,0,220,220);return SIL[key]=cv2;}
function numBadge(c,n,x,y,r,col){c.fillStyle=col||'#ff6fa8';circ(c,x,y,r);c.strokeStyle='#fff';c.lineWidth=r*.16;c.beginPath();c.arc(x,y,r,0,TAU);c.stroke();c.fillStyle='#fff';c.font=`${Math.round(r*1.2)}px ${POP}`;c.textAlign='center';c.textBaseline='middle';c.fillText(n,x,y+r*.06);}
function lfish(c,x,y,s,col,ch,dir,t){c.save();c.translate(x,y);c.scale(s*(dir<0?-1:1),s);const w=Math.sin((t||0)*8)*.2;c.fillStyle=shade(col,-.1);c.beginPath();c.moveTo(-40,0);c.lineTo(-66,-20+w*20);c.lineTo(-62,0);c.lineTo(-66,20-w*20);c.closePath();c.fill();
  c.fillStyle=gfill(c,-5,-10,50,col,.3,-.1);c.beginPath();c.ellipse(0,0,46,30,0,0,TAU);c.fill();c.fillStyle='#fff';circ(c,28,-8,8);c.fillStyle='#2a2040';circ(c,30,-8,4);c.restore();
  if(ch){c.fillStyle='#fff';circ(c,x-(dir<0?-1:1)*4*s,y+2*s,20*s);c.fillStyle='#4a3a5a';c.font=`800 ${Math.round(26*s)}px ${FONT}`;c.textAlign='center';c.textBaseline='middle';c.fillText(ch,x-(dir<0?-1:1)*4*s,y+3*s);}}
Object.assign(SPECIAL_THING,{
  hirafish:(c,x,y,s)=>lfish(c,x+4*s,y,s*.62,'#ff8a5a','あ',1,0),
  fishrod:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#b07a4a';c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(-26,30);c.lineTo(22,-30);c.stroke();c.strokeStyle='#8a8aa0';c.lineWidth=1.5;c.beginPath();c.moveTo(22,-30);c.lineTo(24,18);c.stroke();c.fillStyle='#ff5f6f';circ(c,24,18,6);c.fillStyle='#fff';circ(c,24,15,3);c.fillStyle='#8a8aa0';circ(c,-14,16,7);c.restore();},
  bucket:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#5aa8ff';c.beginPath();c.moveTo(-26,-14);c.lineTo(26,-14);c.lineTo(20,28);c.lineTo(-20,28);c.closePath();c.fill();c.fillStyle='#8fd8ff';ell(c,0,-14,26,8);c.strokeStyle='#3a7ad8';c.lineWidth=3;c.beginPath();c.arc(0,-14,24,Math.PI,TAU);c.stroke();c.fillStyle='#ff8a5a';ell(c,-4,-16,10,5);c.restore();},
  num123:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);[['1','#ff6f8f',-24,8],['2','#ffd23a',0,-8],['3','#5aa8ff',24,8]].forEach(([n,col,dx,dy])=>{c.fillStyle=col;rr(c,dx-14,dy-16,28,32,7);c.fill();c.fillStyle='#fff';c.font=`24px ${POP}`;c.textAlign='center';c.textBaseline='middle';c.fillText(n,dx,dy+1);});c.restore();},
  kazutrain:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ff6f6f';rr(c,-34,-18,40,32,6);c.fill();c.fillStyle='#5aa8ff';rr(c,10,-12,26,26,5);c.fill();c.fillStyle='#fff';c.font=`18px ${POP}`;c.textAlign='center';c.textBaseline='middle';c.fillText('3',-14,-2);c.fillStyle='#3a3050';for(const wx of[-24,-4,18,30])circ(c,wx,16,6);c.fillStyle='#ffd23a';rr(c,-30,-28,10,12,3);c.fill();c.restore();},
  abacus:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#b07a4a';c.lineWidth=5;rr(c,-30,-26,60,52,6);c.stroke();c.lineWidth=2;for(let r=0;r<3;r++){const yy=-12+r*12;c.beginPath();c.moveTo(-28,yy);c.lineTo(28,yy);c.stroke();for(let i=0;i<3;i++){c.fillStyle=PAST[(r*3+i)%8];ell(c,-18+i*10+r*6,yy,5,5);}}c.restore();},
  applebasket:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);for(const [ax,ay] of [[-12,-10],[10,-12],[0,-20]])drawItem(c,'apple',ax,ay,.55);c.fillStyle='#d8904a';c.beginPath();c.moveTo(-30,-4);c.lineTo(30,-4);c.lineTo(22,26);c.lineTo(-22,26);c.closePath();c.fill();c.strokeStyle='#b0703a';c.lineWidth=2;for(let i=0;i<3;i++){c.beginPath();c.moveTo(-28,4+i*8);c.lineTo(28,4+i*8);c.stroke();}c.restore();},
  applepie:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#e8a860';ell(c,0,6,34,18);c.fillStyle='#ffd08a';ell(c,0,0,32,15);c.strokeStyle='#d88a40';c.lineWidth=3;for(let i=-2;i<=2;i++){c.beginPath();c.moveTo(i*10-6,-12);c.lineTo(i*10+6,12);c.stroke();}c.restore();},
  plussign:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ff6fa8';circ(c,0,0,28);c.fillStyle='#fff';rr(c,-16,-5,32,10,5);c.fill();rr(c,-5,-16,10,32,5);c.fill();c.restore();},
  shapes:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);drawShape(c,'circle',-14,-10,13);drawShape(c,'tri',14,-10,13);drawShape(c,'sq',-12,14,11);drawShape(c,'star',14,14,14);c.restore();},
  shapehouse:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);drawShape(c,'sq',0,10,18);drawShape(c,'tri',0,-18,20);drawShape(c,'circle',24,-24,7);c.restore();},
  paintpot:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#e8e8f0';rr(c,-24,-12,48,38,8);c.fill();c.fillStyle='#ff6f8f';ell(c,0,-12,24,8);c.fillStyle='#ff6f8f';c.beginPath();c.moveTo(-10,-12);c.quadraticCurveTo(-12,8,-6,10);c.quadraticCurveTo(0,6,0,-12);c.fill();c.strokeStyle='#b07a4a';c.lineWidth=5;c.beginPath();c.moveTo(10,-12);c.lineTo(24,-34);c.stroke();c.fillStyle='#5aa8ff';rr(c,20,-44,10,12,3);c.fill();c.restore();},
  rainbow2:(c,x,y,s)=>{c.save();c.translate(x,y+14*s);c.scale(s,s);['#ff4d5a','#ff9a3a','#ffd23a','#4cc060','#3a8aff','#9a5ae8'].forEach((q,i)=>{c.strokeStyle=q;c.lineWidth=5;c.beginPath();c.arc(0,0,34-i*5,Math.PI,TAU);c.stroke();});cloud(c,-28,2,.18,false);cloud(c,28,2,.18,false);c.restore();},
  colorballoons:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);[['#ff4d5a',-16,-6],['#3a8aff',16,-8],['#ffd23a',0,-18]].forEach(([q,bx,by])=>{c.strokeStyle='#8a7a9a';c.lineWidth=1.5;c.beginPath();c.moveTo(bx,by+14);c.lineTo(0,30);c.stroke();c.fillStyle=gfill(c,bx-4,by-4,16,q);c.beginPath();c.ellipse(bx,by,12,15,0,0,TAU);c.fill();});c.restore();},
  clock2:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ff8cc0';circ(c,0,0,30);c.fillStyle='#fff';circ(c,0,0,24);c.fillStyle='#5a3a5a';for(let i=0;i<12;i++){const a=i/12*TAU;circ(c,Math.cos(a)*19,Math.sin(a)*19,i%3?1.5:3);}c.strokeStyle='#5a3a5a';c.lineWidth=4;c.lineCap='round';c.beginPath();c.moveTo(0,0);c.lineTo(0,-16);c.moveTo(0,0);c.lineTo(11,4);c.stroke();c.restore();},
  alarm:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ffd23a';circ(c,-18,-22,9);circ(c,18,-22,9);c.fillStyle='#ff5f6f';circ(c,0,2,26);c.fillStyle='#fff';circ(c,0,2,20);c.strokeStyle='#3a3050';c.lineWidth=3;c.beginPath();c.moveTo(0,2);c.lineTo(0,-12);c.moveTo(0,2);c.lineTo(10,6);c.stroke();c.strokeStyle='#ff5f6f';c.lineWidth=4;c.beginPath();c.moveTo(-14,24);c.lineTo(-20,32);c.moveTo(14,24);c.lineTo(20,32);c.stroke();c.restore();},
  sunmoon:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ffd23a';circ(c,-10,-6,18);for(let i=0;i<8;i++){const a=i/8*TAU;c.fillRect(-10+Math.cos(a)*24-2,-6+Math.sin(a)*24-2,4,4);}c.fillStyle='#5a5ab8';circ(c,14,10,16);c.fillStyle='#fff6c0';circ(c,20,6,14);c.fillStyle='#5a5ab8';circ(c,26,2,12);c.restore();},
  cards:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.rotate(-.2);c.fillStyle='#ff8cc0';rr(c,-26,-28,32,44,6);c.fill();c.fillStyle='#fff';c.font=`18px ${POP}`;c.textAlign='center';c.textBaseline='middle';c.fillText('?',-10,-6);c.rotate(.4);c.fillStyle='#fff';rr(c,-6,-24,32,44,6);c.fill();c.strokeStyle='#5aa8ff';c.lineWidth=3;c.stroke();drawItem(c,'apple',10,-2,.45);c.restore();},
  qcard:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle=gfill(c,-8,-10,40,'#b48cff');rr(c,-22,-30,44,60,8);c.fill();c.strokeStyle='#fff';c.lineWidth=3;rr(c,-16,-24,32,48,5);c.stroke();c.fillStyle='#fff';c.font=`30px ${POP}`;c.textAlign='center';c.textBaseline='middle';c.fillText('?',0,2);c.restore();},
  magnifier:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#b07a4a';c.lineWidth=8;c.lineCap='round';c.beginPath();c.moveTo(10,10);c.lineTo(28,28);c.stroke();c.fillStyle='rgba(180,230,255,.8)';circ(c,-6,-6,20);c.strokeStyle='#ffd23a';c.lineWidth=6;c.beginPath();c.arc(-6,-6,20,0,TAU);c.stroke();c.fillStyle='rgba(255,255,255,.7)';ell(c,-12,-14,6,4);c.restore();},
  dotstar:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#ffb03a';c.lineWidth=3;c.beginPath();for(let i=0;i<=10;i++){const a=i/10*TAU-Math.PI/2,r=i%2?12:28;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.stroke();for(let i=0;i<10;i++){const a=i/10*TAU-Math.PI/2,r=i%2?12:28;c.fillStyle='#ff5f9a';circ(c,Math.cos(a)*r,Math.sin(a)*r,3.5);}c.restore();},
  ruler:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.rotate(-.5);c.fillStyle='#ffd23a';rr(c,-36,-10,72,20,4);c.fill();c.fillStyle='#b07a4a';for(let i=0;i<9;i++)c.fillRect(-32+i*8,-10,2,i%2?6:10);c.restore();},
  maze:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#fff';rr(c,-30,-30,60,60,8);c.fill();c.strokeStyle='#5aa8ff';c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(-22,-22);c.lineTo(22,-22);c.lineTo(22,8);c.moveTo(-22,-8);c.lineTo(8,-8);c.lineTo(8,22);c.moveTo(-22,8);c.lineTo(-8,8);c.lineTo(-8,22);c.stroke();c.fillStyle='#ffd23a';star(c,-15,15,6,2.6);c.fill();c.fillStyle='#ff5f6f';circ(c,15,-14,4);c.restore();},
  compass:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ffd23a';circ(c,0,0,28);c.fillStyle='#fff';circ(c,0,0,22);c.fillStyle='#ff4d5a';c.beginPath();c.moveTo(0,-18);c.lineTo(6,0);c.lineTo(-6,0);c.fill();c.fillStyle='#5a6a8a';c.beginPath();c.moveTo(0,18);c.lineTo(6,0);c.lineTo(-6,0);c.fill();c.restore();},
  goalflag:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#8a6a4a';c.fillRect(-16,-30,5,60);for(let r=0;r<3;r++)for(let q=0;q<4;q++){c.fillStyle=(r+q)%2?'#3a3050':'#fff';c.fillRect(-11+q*9,-30+r*9,9,9);}c.fillStyle='#6cd08a';ell(c,-14,30,16,5);c.restore();},
  flashlight:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.rotate(-.6);c.fillStyle='rgba(255,240,160,.5)';c.beginPath();c.moveTo(18,-6);c.lineTo(40,-22);c.lineTo(40,22);c.lineTo(18,6);c.fill();c.fillStyle='#5aa8ff';rr(c,-30,-8,40,16,5);c.fill();c.fillStyle='#ffd23a';rr(c,8,-12,12,24,4);c.fill();c.restore();},
  shadowcat:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#fff6d8';rr(c,-30,-30,60,60,10);c.fill();c.drawImage(silhouette('cat'),-28,-28,56,56);c.restore();},
  shadowhand:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#4a3a6a';ell(c,0,6,18,14);c.beginPath();c.moveTo(-10,-4);c.lineTo(-18,-28);c.lineTo(-4,-8);c.moveTo(6,-6);c.lineTo(16,-28);c.lineTo(12,-4);c.fill();c.fillStyle='#fff';circ(c,6,2,3);c.restore();},
  bento:(c,x,y,s)=>{c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#ff6f8f';rr(c,-32,-20,64,44,8);c.fill();c.fillStyle='#fff';rr(c,-28,-16,30,36,5);c.fill();c.fillStyle='#3a3a3a';c.fillRect(-20,2,14,10);c.fillStyle='#ffd23a';rr(c,4,-16,24,16,4);c.fill();c.fillStyle='#6cd08a';circ(c,16,10,8);c.fillStyle='#ff4d5a';circ(c,-8,-6,4);c.restore();}});
Object.assign(WORDS,{hirafish:['もじの さかな','letter fish'],fishrod:['つりざお','fishing rod'],bucket:['バケツ','bucket'],num123:['すうじ','numbers'],kazutrain:['かずの でんしゃ','number train'],abacus:['そろばん','abacus'],applebasket:['りんごの かご','apple basket'],applepie:['アップルパイ','apple pie'],plussign:['たす','plus'],
  shapes:['かたち','shapes'],shapehouse:['かたちの いえ','shape house'],paintpot:['えのぐ','paint'],rainbow2:['にじ','rainbow'],colorballoons:['いろの ふうせん','balloons'],clock2:['とけい','clock'],alarm:['めざましどけい','alarm clock'],sunmoon:['あさと よる','day and night'],cards:['カード','cards'],qcard:['はてなカード','question card'],magnifier:['むしめがね','magnifier'],
  dotstar:['てんつなぎ','dot to dot'],ruler:['じょうぎ','ruler'],maze:['めいろ','maze'],compass:['コンパス','compass'],goalflag:['ゴール','goal'],flashlight:['かいちゅうでんとう','flashlight'],shadowcat:['ねこの かげ','cat shadow'],shadowhand:['かげえ','shadow puppet'],bento:['おべんとう','lunch box'],
  circle:['まる','circle'],triangle:['さんかく','triangle'],square:['しかく','square']});
