// ================= 3D しょうぼうし =================
reg3('fire',{bg:'#ffe0c8',song:'hero',
  build(){const S=this.S=stage3({sr:14,fov:50});const g=new THREE.Group();S.s.add(g);this.g=g;
    const gr=new THREE.Mesh(new THREE.PlaneGeometry(80,80),m3('#b8e890'));gr.rotation.x=-Math.PI/2;gr.receiveShadow=true;g.add(gr);B3(g,40,.04,8,'#8a8aa0',0,0,8,0);for(let x=-18;x<18;x+=4)B3(g,2,.05,.25,'#ffffff',x,0,8,0);B3(g,12,.1,3,'#e8e0d0',0,0,2.6,.02);
    const bd=new THREE.Group();g.add(bd);const BC=pick([['#ffe6c8','#c86a4a','#e8704a'],['#e0f0ff','#5a7ab8','#4a8ae8'],['#fff0f6','#c85a8a','#ff7aa8'],['#f0ffe0','#6a9a4a','#5cbe5a']]);B3(bd,11,9.4,5,BC[0],0,0,-2.5,.3);B3(bd,11.6,.6,5.6,BC[1],0,9.4,-2.5,.15);prism3(bd,11.4,2.2,5.6,BC[2],0,10,-2.5);this.rescK=pick([['cat','ねこちゃん'],['dog','わんちゃん'],['rabbit','うさぎさん'],['chick','ひよこちゃん'],['panda','パンダさん']]);
    this.wins=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++){const x=(c-1)*3.2,y=1.7+r*2.9;if(r===0&&c===1){B3(bd,1.8,2.6,.2,'#b07a4a',0,0,.02,.1);continue;}B3(bd,2.1,1.9,.15,'#ffffff',x,y-.95,.02,.06);const gl=B3(bd,1.8,1.6,.18,m3('#9ad0f0',{roughness:.2}),x,y-.8,.04,.03);B3(bd,2.3,.18,.4,'#c86a4a',x,y-1.05,.2,.04);this.wins.push({x,y,r,c,gl});}
    for(let i=0;i<5;i++)flower3(g,-5+i*2.5,0,.4,PAST[i],1.3);tree3(g,-8.5,-1,1.5);tree3(g,8.5,-1.5,1.4);
    const hy=this.hyd=new THREE.Group();hy.position.set(6.5,0,4.6);g.add(hy);C3(hy,.35,.4,1.1,'#ff4d5a',0,0,0,16);S3(hy,.36,'#ff4d5a',0,1.1,0);for(const s of[-1,1]){const n=C3(hy,.14,.14,.4,'#ffd23a',s*.4,.6,0,10);n.rotation.z=Math.PI/2;}tagPk(hy,{hyd:1});
    const tk=this.truck=new THREE.Group();g.add(tk);B3(tk,5.4,1.8,2.3,'#ff4d5a',0,.5,0,.25);B3(tk,1.8,1.6,2.2,'#ff4d5a',3.3,.5,0,.25);B3(tk,1.3,.9,2.25,m3('#bfe8ff',{roughness:.2}),3.6,1.2,0,.08);B3(tk,5.4,.14,2.35,'#ffffff',0,1.2,0,.02);
    for(const x of[-1.8,1.6,3.2])for(const z of[-1.1,1.1]){const w=C3(tk,.55,.55,.35,'#3a3050',x,0,z,18);w.rotation.x=Math.PI/2;w.position.y=.55;}this.lamps=[S3(tk,.2,'#ff3050',3,2.25,-.5),S3(tk,.2,'#3080ff',3,2.25,.5)];B3(tk,.9,.5,.9,'#dcdce8',-1.8,2.3,0,.1);
    this.lad=new THREE.Group();this.lad.position.set(-1.8,2.8,0);tk.add(this.lad);this.ladM=new THREE.Group();this.lad.add(this.ladM);for(const s of[-1,1])B3(this.ladM,.1,.1,1,'#e8e8f0',s*.35,-.05,.5,0);for(let i=0;i<10;i++)B3(this.ladM,.7,.06,.06,'#ffffff',0,-.03,.05+i*.1,0);
    tk.position.set(-26,0,8);tk.rotation.y=0;
    this.fu=charAdd(S,charSpr('fu',2.6,{outfit:outfit({acc:'cap'})}));this.fu.x=2.4;this.fu.z=6.4;this.fu.face=3;this.rk=charAdd(S,charSpr('rk',1.8));this.rk.x=-7.5;this.rk.z=10;
    this.flames=[];this.drops=[];for(let i=0;i<70;i++){const d=S3(g,.12,m3('#6ac8ff',{transparent:true,opacity:.8,roughness:.1}),0,-5,0);d.castShadow=false;this.drops.push({m:d,v:new THREE.Vector3(),live:0});}this.smk=[];
    this.ph='drive';this.pt=0;this.water=1;this.aim=null;this.spray=false;this.time=0;this.spreadT=0;this.tries=0;this.fin=0;this.refill=0;this.lvl=Math.min(3,lvOf('fire'));
    setTimeout(()=>{if(scene===this){sfx('honk');say('ウーウー！ かじだ！ しょうぼうしゃ しゅつどう！');}},300);},
  addFire(w){if(w.fire)return;const f=new THREE.Group();f.position.set(w.x,w.y-.9,.4);this.g.add(f);const cs=[['#ff5a2a',.7,1.6],['#ffa030',.5,1.2],['#ffe06a',.3,.8]];cs.forEach(([col,r,h],i)=>{const m=mesh3(f,geo3('fl'+i,()=>new THREE.ConeGeometry(r,h,10)),m3(col,{emissive:new THREE.Color(col),emissiveIntensity:.9,transparent:true,opacity:.92}),0,h/2,.05*i);m.castShadow=false;});
    const o={w,g:f,hp:1};w.fire=o;this.flames.push(o);w.gl.material=m3('#ffb070',{emissive:new THREE.Color('#ff7a30'),emissiveIntensity:.6});},
  startSpray(){this.ph='spray';const n=3+this.lvl;const cand=shuffle(this.wins.slice());for(let i=0;i<n;i++)this.addFire(cand[i]);say('ゆびで ほのおを ねらって おみずを かけよう！');},
  update(dt){const S=this.S,fu=this.fu,tk=this.truck;this.pt+=dt;const on=Math.floor(T*6)%2;this.lamps[0].material=m3(on?'#ff3050':'#802030',{emissive:new THREE.Color(on?'#ff3050':'#000000'),emissiveIntensity:.8});this.lamps[1].material=m3(on?'#203080':'#3080ff',{emissive:new THREE.Color(on?'#000000':'#3080ff'),emissiveIntensity:.8});
    if(this.ph==='drive'){tk.position.x=Math.min(-5,tk.position.x+dt*14);if(tk.position.x>=-5&&this.pt>2){this.startSpray();}}
    if(this.ph==='spray'||this.ph==='rescue'){this.time+=dt;}
    if(this.ph==='spray'){const act=this.spray&&this.water>0&&this.aim&&!this.refill;if(act){this.water=Math.max(0,this.water-dt*.09);if(this.water<=0){this.spray=false;sfx('no');say('おみずが なくなった！ しょうかせんを タッチして ホースを つなごう');}}
      if(this.refill>0){this.refill-=dt;this.water=Math.min(1,this.water+dt*.6);if(this.refill<=0)say('まんたん！ もう いちど ねらおう');}
      const noz=new THREE.Vector3(fu.x+.5,1.5,fu.z-.3);if(act){for(let k=0;k<2;k++){const d=this.drops.find(q=>!q.live);if(!d)break;const tg=this.aim.clone().add(new THREE.Vector3(rand(-.25,.25),rand(-.25,.25),0));const t=.55;d.live=t+.2;d.m.position.copy(noz);d.v.set((tg.x-noz.x)/t,(tg.y-noz.y)/t+4.9*t,(tg.z-noz.z)/t);}
        for(const f of this.flames){if(f.hp<=0)continue;const c=new THREE.Vector3(f.w.x,f.w.y-.3,.4);if(c.distanceTo(this.aim)<1.4){f.hp-=dt*(.55-this.lvl*.05);if(Math.random()<dt*8)this.puff(c,'#e0e4ea');if(f.hp<=0)this.out(f);}}if(Math.random()<dt*6)sfx('water');}
      this.spreadT+=dt;if(this.spreadT>7-this.lvl){this.spreadT=0;const burning=this.flames.filter(f=>f.hp>0);if(burning.length&&burning.length<5){const f=pick(burning);const nb=this.wins.find(w=>!w.fire&&Math.abs(w.r-f.w.r)+Math.abs(w.c-f.w.c)===1);if(nb){this.addFire(nb);sfx('boom');say('たいへん！ ほのおが ひろがった！');}}}
      if(this.flames.length&&this.flames.every(f=>f.hp<=0)){this.ph='rescue0';this.pt=0;sfx('fanfare');confetti(40);say('ぜんぶ きえた！ あれ？ うえに '+this.rescK[1]+'が いるよ！');}}
    if(this.ph==='rescue0'&&this.pt>1.6){this.ph='rescue';const top=this.wins.filter(w=>w.r===2);this.cw=pick(top);this.cat=charAdd(S,charSpr(this.rescK[0],1.2,{k:this.rescK[0]}));this.cat.x=this.cw.x;this.cat.y=this.cw.y-1.6;this.cat.z=.5;this.len=0;this.hold=0;this.lab=null;say('はしごを のばして たすけよう！ ボタンを おしている あいだ のびるよ');}
    if(this.ph==='rescue'||this.ph==='climb'){const base=new THREE.Vector3(tk.position.x-1.8,2.8,tk.position.z),tg=new THREE.Vector3(this.cw.x,this.cw.y-1.4,.6);this.lad.lookAt(tg);this.lad.rotation.x=this.lad.rotation.x;
      this.need=base.distanceTo(tg);if(this.hold)this.len=Math.min(this.need+3,this.len+dt*3.2);else if(this.ph==='rescue'&&this.retract){this.len=Math.max(0,this.len-dt*6);if(this.len<=0)this.retract=0;}this.ladM.scale.z=Math.max(.01,this.len);if(this.cat)this.cat.cheer=this.ph==='climb'?1:0;
      if(this.ph==='climb'){this.ct+=dt;const k=this.ct<2?this.ct/2:this.ct<2.6?1:Math.max(0,1-(this.ct-2.6)/2);const p=base.clone().lerp(tg,k);fu.x=p.x;fu.y=p.y-.2;fu.z=p.z+.3;fu.mv=true;if(this.ct>2&&this.cat&&!this.caught){this.caught=1;sfx('heart');hush();speak('にゃ〜ん！ ありがとう！');}if(this.caught&&this.cat){this.cat.x=fu.x+.6;this.cat.y=fu.y+.8;this.cat.z=fu.z;}if(this.ct>4.6){fu.y=0;fu.mv=false;fu.cheer=3;this.ph='end';this.fin=.01;sfx('fanfare');confetti(90);say(this.rescK[1]+'を たすけた！ ヒーローだね！');}}}
    for(const d of this.drops){if(d.live<=0){d.m.visible=false;continue;}d.live-=dt;d.v.y-=9.8*dt;d.m.position.addScaledVector(d.v,dt);d.m.visible=true;if(d.m.position.z<.3){d.live=0;}}
    for(const f of this.flames){if(f.hp>0){const k=.6+.4*f.hp;f.g.children.forEach((m,i)=>{m.scale.set(k*(1+Math.sin(T*14+i)*.1),k*(1+Math.sin(T*11+i*2)*.18),k);});if(Math.random()<dt*2)this.puff(new THREE.Vector3(f.w.x,f.w.y+.6,.3),'#9a9aa8');}}
    for(const s of this.smk){s.t+=dt;s.m.position.y+=dt*1.4;s.m.scale.setScalar(.4+s.t*1.2);s.m.material.opacity=Math.max(0,.55-s.t*.4);}this.smk=this.smk.filter(s=>{if(s.t>1.4){this.g.remove(s.m);return false;}return true;});
    if(this.ph!=='climb'&&this.ph!=='end'){fu.x=2.4;fu.z=6.4;fu.mv=false;}
    S.cam.position.set(0,this.ph==='drive'?5:7,32);S.cam.lookAt(0,this.ph==='rescue'||this.ph==='climb'?5.4:4.6,0);lightAt(S,0,2);charUpd(fu,dt);charUpd(this.rk,dt);if(this.cat)charUpd(this.cat,dt);
    if(this.fin>0){this.fin+=dt;if(this.fin>2.2&&this.fin<9){this.fin=9;const st=this.time<30+this.lvl*8&&this.tries<=1?3:this.time<55?2:1;celebrate('fire',st===3,st);}}},
  puff(v,col){const m=S3(this.g,.4,new THREE.MeshStandardMaterial({color:new THREE.Color(col),transparent:true,opacity:.55,roughness:1}),v.x+rand(-.3,.3),v.y,v.z+.2);m.castShadow=false;this.smk.push({m,t:0});},
  out(f){f.hp=0;this.g.remove(f.g);f.w.gl.material=m3('#6a6a78',{roughness:.6});sfx('splash');const p=toScr(this.S,new THREE.Vector3(f.w.x,f.w.y,.4));burst(p.x,p.y,12,'star');for(let i=0;i<5;i++)this.puff(new THREE.Vector3(f.w.x,f.w.y-.3,.4),'#ffffff');hush();speak(pick(['きえた！','やったね！','ジュー！']));},
  draw(c){sky3(c,this.ph==='spray'?'#ffd0b0':'#9ad8ff','#fff0e0',true);render3(c,this.S);
    if(this.ph==='spray'){c.fillStyle='rgba(255,255,255,.92)';rr(c,20,112,W-40,56,28);c.fill();c.fillStyle='#3a8ad8';c.font=`800 18px ${FONT}`;c.textAlign='left';c.textBaseline='middle';c.fillText('おみず',40,140);c.fillStyle='#dde8f4';rr(c,110,128,W-300,24,12);c.fill();c.fillStyle=this.water<.25?'#ff6f6f':'#4aa8ff';rr(c,110,128,(W-300)*this.water,24,12);c.fill();
      const n=this.flames.filter(f=>f.hp>0).length;c.fillStyle='#ff5a2a';c.textAlign='center';c.font=`800 20px ${FONT}`;c.fillText(`🔥 ${n}`,W-110,141);
      if(this.aim&&this.spray){const p=toScr(this.S,this.aim);c.strokeStyle='rgba(255,255,255,.9)';c.lineWidth=4;c.beginPath();c.arc(p.x,p.y,34,0,TAU);c.stroke();c.beginPath();c.moveTo(p.x-44,p.y);c.lineTo(p.x+44,p.y);c.moveTo(p.x,p.y-44);c.lineTo(p.x,p.y+44);c.stroke();}
      if(this.water<.3||this.refill>0){const p=toScr(this.S,new THREE.Vector3(6.5,2,4.6));c.fillStyle='#fff';rr(c,p.x-70,p.y-60,140,36,18);c.fill();c.fillStyle='#ff4d5a';c.font=`800 16px ${FONT}`;c.fillText(this.refill>0?'ちゅうすい ちゅう…':'ここを タッチ！',p.x,p.y-42);}}
    if(this.ph==='rescue'){const by=H-110;const pr=this.hold?.9:1;c.save();c.translate(W/2,by);c.scale(pr,pr);drawBtn(c,0,0,56,'#ff4d5a','plus',!this.hold);c.restore();c.fillStyle='#ff4d5a';c.font=`800 20px ${FONT}`;c.textAlign='center';c.fillText('はしごを のばす',W/2,by+76);
      const p=toScr(this.S,new THREE.Vector3(this.cw.x,this.cw.y-.4,.6));c.strokeStyle='#ffd23a';c.lineWidth=4;c.setLineDash([8,6]);c.beginPath();c.arc(p.x,p.y+30,44,0,TAU);c.stroke();c.setLineDash([]);
      const k=clamp(this.len/this.need,0,1.5);c.fillStyle='rgba(255,255,255,.92)';rr(c,30,H*.3,26,H*.34,13);c.fill();c.fillStyle='#6cd08a';c.fillRect(30,H*.3+H*.34*(1-1/1.5)-6,26,12);c.fillStyle=k>1.15?'#ff6f6f':'#ffb03a';rr(c,30,H*.3+H*.34*(1-k/1.5),26,H*.34*k/1.5,13);c.fill();}},
  down(x,y){if(this.ph==='spray'){const h=pick3(this.S,x,y,[this.hyd]);if(h&&this.water<1){this.refill=1.5;sfx('pour');say('しょうかせんに つないだ！ おみずを ためるよ');return;}this.spray=true;this.setAim(x,y);return;}
    if(this.ph==='rescue'&&hitC(x,y,W/2,H-110,70)&&!this.retract){this.hold=1;sfx('pop');}},
  setAim(x,y){const v=new THREE.Vector3();const ok=ray3(this.S,x,y).ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-.4),v);if(ok){v.y=clamp(v.y,.3,9.5);v.x=clamp(v.x,-6,6);this.aim=v;}},
  move(x,y){if(this.ph==='spray'&&this.spray)this.setAim(x,y);},
  up(){if(this.ph==='spray'){this.spray=false;return;}if(this.ph==='rescue'&&this.hold){this.hold=0;this.tries++;const r=this.len/this.need;if(r>=.9&&r<=1.18){this.len=this.need;this.ph='climb';this.ct=0;sfx('ding');say('ぴったり！ のぼるよ！');}else if(r<.9){sfx('tick');say('もう すこし！ もう いちど おしてね');}else{sfx('no');say('ながすぎた！ いちど もどすよ');this.retract=1;}}},
  hint(){if(this.ph==='spray'){if(this.water<.15&&!this.refill){const p=toScr(this.S,new THREE.Vector3(6.5,1,4.6));return{x:p.x,y:p.y};}const f=this.flames.find(f=>f.hp>0);if(!f)return null;const p=toScr(this.S,new THREE.Vector3(f.w.x,f.w.y-.3,.4));return{x:p.x,y:p.y};}if(this.ph==='rescue')return{x:W/2,y:H-110};return null;},
  hintText(){return this.ph==='spray'?'ほのおを ゆびで おさえて おみずを かけよう':'ボタンを おして はしごを のばそう。 きいろい まるに とどいたら はなしてね';}});
