// ================= 3D ケーキやさん =================
const CK_SH=[['round','まる','round'],['heart','ハート','heart'],['square','しかく','square']];
const CK_CR=[['#ffb3d0','ピンク','pink'],['#fffaf2','しろ','white'],['#8a5a3a','チョコ','chocolate']];
const CK_TP=[['strawberry','いちご','strawberry'],['cherry','さくらんぼ','cherry'],['candle','ろうそく','candle'],['starcandy','ほし','star'],['blueberry','ブルーベリー','blueberry'],['choco','チョコ','chocolate']];
function topping3(g,k){const t=new THREE.Group();g.add(t);if(k==='strawberry'){const m=mesh3(t,geo3('stb',()=>new THREE.ConeGeometry(.2,.36,12)),'#ff3d5a',0,.16,0);m.rotation.x=Math.PI;S3(t,.1,'#4cbe6a',0,.34,0,1.4,.4,1.4);}
  else if(k==='cherry'){S3(t,.17,'#e8102a',0,.17,0);C3(t,.015,.015,.3,'#4c8a3a',.03,.3,0,4).rotation.z=-.3;}else if(k==='candle'){C3(t,.07,.07,.55,PAST[Math.floor(Math.random()*8)],0,0,0,10);const f=mesh3(t,geo3('flame',()=>new THREE.ConeGeometry(.07,.2,8)),m3('#ffb030',{emissive:new THREE.Color('#ff9a00'),emissiveIntensity:1}),0,.66,0);f.userData.fl=1;f.castShadow=false;}
  else if(k==='starcandy'){const m=mesh3(t,starGeo(.18,.06),'#ffd23a',0,.2,0);m.rotation.x=-.3;}else if(k==='blueberry'){for(let i=0;i<3;i++)S3(t,.09,'#3a4aa8',Math.cos(i*2.1)*.1,.09,Math.sin(i*2.1)*.1);}else{B3(t,.4,.06,.3,'#6a3a2a',0,.02,0,.02).rotation.x=-.4;}return t;}
reg3('cake',{bg:'#ffe6f0',song:'play',
  build(){const S=this.S=stage3({sr:9,fov:48,hi:.8});const g=new THREE.Group();S.s.add(g);this.g=g;
    const fl=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({map:(()=>{const t=decorTex('f_check');return t;})(),roughness:.8}));fl.rotation.x=-Math.PI/2;fl.receiveShadow=true;g.add(fl);
    B3(g,9,2.2,3,'#fff0f6',0,0,-.2,.2);B3(g,9.4,.25,3.4,'#ff8cc0',0,2.2,-.2,.08);B3(g,40,10,.3,'#ffe4ef',0,0,-6,0);for(let i=0;i<3;i++){B3(g,2.2,.1,.8,'#ffffff',-5+i*5,4.5,-5.6,.03);C3(g,.5,.5,.6,PAST[i*2],-5+i*5,4.6,-5.6,16);}
    this.tt=new THREE.Group();this.tt.position.set(0,2.35,0);g.add(this.tt);C3(this.tt,1.9,2,.12,'#e8e8f4',0,0,0,40);C3(this.tt,1.95,1.95,.03,'#ffffff',0,.12,0,40);this.cakeG=new THREE.Group();this.cakeG.position.y=.15;this.tt.add(this.cakeG);
    this.fu=charAdd(S,charSpr('fu',2.8,{outfit:outfit({acc:'none'})}));this.fu.x=3.4;this.fu.z=-2.6;this.fu.y=0;this.cust=null;
    this.served=0;this.perfect=0;this.fin=0;this.newOrder();},
  newOrder(){const lv=Math.min(3,lvOf('cake'));while(this.cakeG.children.length)this.cakeG.remove(this.cakeG.children[0]);this.layers=[];this.cream=null;this.tops=[];this.shape=null;this.crc=null;this.cov=0;this.sel=null;this.ph='shape';this.rot=0;
    const nk=1+Math.min(2,Math.floor(Math.random()*(1+lv*.7)));const ks=shuffle(CK_TP.map(q=>q[0])).slice(0,nk);this.order={sh:pick(CK_SH)[0],ly:Math.random()<.4+lv*.1?2:1,cr:Math.floor(Math.random()*3),tp:ks.map(k=>[k,1+Math.floor(Math.random()*(k==='candle'?5:3+lv*.4))])};
    const ak=pick(['bear','rabbit','cat','dog','panda','pig','chick','hippo']);if(this.cust){this.S.s.remove(this.cust.sp);this.S.s.remove(this.cust.sh);}this.cust=charAdd(this.S,charSpr(ak,2.4,{k:ak}));this.cust.x=-9;this.cust.z=2.4;this.cust.walk=1;this.ak=ak;
    setTimeout(()=>{if(scene!==this)return;const o=this.order,sh=CK_SH.find(q=>q[0]===o.sh);hush();speak(`${WORDS[ak]?WORDS[ak][0]:''}さんの ちゅうもん！`);speak(`${sh[1]}の ケーキ、 ${o.ly}だん。 ${CK_CR[o.cr][1]}の クリーム。`);speak(o.tp.map(([k,n])=>`${CK_TP.find(q=>q[0]===k)[1]} ${n}こ`).join('、 '));},900);},
  addLayer(){const n=this.layers.length;if(n>=3)return;const sh=this.shape,y=n*.62,s=1-n*.16;let m;const col='#ffe0a8';
    if(sh==='round')m=C3(this.cakeG,1.3*s,1.3*s,.6,col,0,y,0,40);else if(sh==='square')m=B3(this.cakeG,2.2*s,.6,2.2*s,col,0,y,0,.08);else{m=mesh3(this.cakeG,heartGeo(1.25*s,.5),col,0,y+.3,0);m.rotation.x=-Math.PI/2;}
    m.userData.s=s;m.userData.y=y;this.layers.push(m);sfx('boing');},
  addCream(){const col=CK_CR[this.crc][0];this.cream=[];for(const L of this.layers){const s=L.userData.s,y=L.userData.y;let m;if(this.shape==='round')m=C3(this.cakeG,1.36*s,1.36*s,.66,col,0,y,0,40);else if(this.shape==='square')m=B3(this.cakeG,2.3*s,.66,2.3*s,col,0,y,0,.14);else{m=mesh3(this.cakeG,heartGeo(1.32*s,.56),col,0,y+.33,0);m.rotation.x=-Math.PI/2;}m.scale.set(.2,.2,.2);tagPk(m,{top:1});this.cream.push(m);}},
  topY(){return this.layers.length*.62+.08;},
  update(dt){const S=this.S,c=this.cust;if(c.walk){const tx=this.ph==='gone'?-10:-3.3;c.x+=(tx-c.x)*Math.min(1,dt*2.2);c.mv=Math.abs(tx-c.x)>.1;if(this.ph==='gone'&&c.x<-9.5){c.walk=0;this.served++;if(this.served>=3){this.fin=.01;}else this.newOrder();}}
    if(this.cream&&this.ph==='cream'){const k=Math.min(1,this.cov);for(const m of this.cream){const e=.2+.8*k;m.scale.set(this.shape==='heart'?e:e,this.shape==='heart'?e:e*1,e);}if(this.cov>=1){this.ph='top';sfx('fanfare');say('クリーム かんせい！ トッピングを えらんで ケーキの うえを タッチしてね');}}
    this.tt.rotation.y=this.rot;this.rot+=(this.ph==='serve'||this.ph==='gone'?dt*1.2:0);for(const t of this.tops)t.children.forEach(ch=>{if(ch.userData.fl)ch.scale.y=1+Math.sin(T*20+t.userData.ph)*.2;});
    S.cam.position.set(0,11.5,15.5);S.cam.lookAt(0,2.3,-.3);charUpd(this.fu,dt);charUpd(c,dt);if(this.hearts>0)this.hearts-=dt;
    if(this.fin>0){this.fin+=dt;if(this.fin>.6&&this.fin<9){this.fin=9;celebrate('cake',this.perfect===3,this.perfect>=3?3:this.perfect>=2?2:1);}}},
  count(k){return this.tops.filter(t=>t.userData.k===k).length;},
  check(){const o=this.order;let ok=this.shape===o.sh&&this.layers.length===o.ly&&this.crc===o.cr;for(const [k,n] of o.tp)if(this.count(k)!==n)ok=false;const extra=this.tops.filter(t=>!o.tp.some(q=>q[0]===t.userData.k)).length;return ok&&extra===0;},
  draw(c){sky3(c,'#ffe0ee','#fff6ea',false);render3(c,this.S);const o=this.order;
    c.fillStyle='rgba(255,255,255,.96)';rr(c,16,110,W-32,118,24);c.fill();c.strokeStyle='#ff8cc0';c.lineWidth=4;c.stroke();drawAnimal(c,this.ak,58,212,.4,{t:T,happy:1});c.fillStyle='#c0508a';c.font=`800 16px ${FONT}`;c.textAlign='left';c.textBaseline='middle';c.fillText('ちゅうもん',100,128);
    let x=110;const chip=(ok,draw,lab)=>{c.fillStyle=ok?'#e8fbe8':'#fff6fa';rr(c,x-6,142,88,74,14);c.fill();c.strokeStyle=ok?'#6cd08a':'#ffd0e4';c.lineWidth=3;c.stroke();draw(x+38,172);c.fillStyle='#6a4a5a';c.font=`800 15px ${FONT}`;c.textAlign='center';c.fillText(lab,x+38,204);x+=94;};
    chip(this.shape===o.sh&&this.layers.length===o.ly,(cx,cy)=>{const col='#ffe0a8';for(let i=0;i<o.ly;i++){if(o.sh==='round'){c.fillStyle=col;rr(c,cx-22+i*4,cy+6-i*14,44-i*8,14,6);c.fill();}else if(o.sh==='square'){c.fillStyle=col;c.fillRect(cx-20+i*4,cy+6-i*14,40-i*8,14);}else{c.fillStyle=col;heartP(c,cx,cy+2-i*12,14-i*3);c.fill();}}},`${CK_SH.find(q=>q[0]===o.sh)[1]}${o.ly}だん`);
    chip(this.crc===o.cr,(cx,cy)=>{c.fillStyle=CK_CR[o.cr][0];circ(c,cx,cy,18);c.strokeStyle='#d8c0c8';c.lineWidth=2;c.beginPath();c.arc(cx,cy,18,0,TAU);c.stroke();},CK_CR[o.cr][1]);
    for(const [k,n] of o.tp){const have=this.count(k);chip(have===n,(cx,cy)=>{drawThing(c,k,cx-10,cy,.55);c.fillStyle=have>n?'#ff5f6f':'#ff4d8d';c.font=`22px ${POP}`;c.fillText('×'+n,cx+22,cy+2);},`${have}/${n}`);}
    const by=H-150;c.fillStyle='rgba(255,255,255,.94)';rr(c,10,by-70,W-20,210,28);c.fill();c.strokeStyle='#ffc0da';c.lineWidth=4;c.stroke();c.textAlign='center';
    if(this.ph==='shape'){CK_SH.forEach(([k,ja],i)=>{const bx=110+i*150;c.fillStyle=this.shape===k?'#fff0d0':'#fff6fa';rr(c,bx-60,by-50,120,90,20);c.fill();c.strokeStyle=this.shape===k?'#ffb03a':'#ffd0e4';c.lineWidth=4;c.stroke();c.fillStyle='#ffe0a8';if(k==='round'){ell(c,bx,by-6,36,18);}else if(k==='square'){c.fillRect(bx-30,by-24,60,36);}else{heartP(c,bx,by-6,24);c.fill();}c.fillStyle='#8a5a6a';c.font=`800 16px ${FONT}`;c.fillText(ja,bx,by+28);});
      hud3Btn(c,W-90,by+90,30,'#ff8cc0','plus','だんを ふやす');if(this.layers.length)hud3Btn(c,90,by+90,30,'#6cd08a','check','つぎへ');}
    if(this.ph==='crc'){CK_CR.forEach(([col,ja],i)=>{const bx=110+i*150;c.fillStyle=col;circ(c,bx,by,40);c.strokeStyle='#e8c8d8';c.lineWidth=4;c.beginPath();c.arc(bx,by,40,0,TAU);c.stroke();c.fillStyle='#8a5a6a';c.font=`800 17px ${FONT}`;c.fillText(ja,bx,by+60);});}
    if(this.ph==='cream'){c.fillStyle='#c0508a';c.font=`800 22px ${FONT}`;c.fillText('← → よこに スワイプして くるくる',W/2,by-20);c.fillStyle='#f0e0e8';rr(c,70,by+20,W-140,26,13);c.fill();c.fillStyle=CK_CR[this.crc][0];rr(c,70,by+20,(W-140)*Math.min(1,this.cov),26,13);c.fill();c.strokeStyle='#e0c0d0';c.lineWidth=2;c.stroke();}
    if(this.ph==='top'){CK_TP.forEach(([k,ja],i)=>{const bx=62+i*95,on=this.sel===k;c.fillStyle=on?'#fff0d0':'#fff6fa';rr(c,bx-42,by-52,84,84,18);c.fill();c.strokeStyle=on?'#ffb03a':'#ffd0e4';c.lineWidth=on?5:3;c.stroke();drawThing(c,k,bx,by-12,.75);c.fillStyle='#8a5a6a';c.font=`800 12px ${FONT}`;c.fillText(ja,bx,by+22,80);});
      hud3Btn(c,W-90,by+92,32,'#6cd08a','check','できた！');hud3Btn(c,90,by+92,30,'#b0a0c0','retry','とる');}
    if(this.hearts>0){for(let i=0;i<5;i++){c.fillStyle='#ff5f9a';heartP(c,120+i*20,250-(1.5-this.hearts)*60-i*8,10);c.fill();}}},
  down(x,y){this.sw={x,y,lx:x};const by=H-150;
    if(this.ph==='shape'){CK_SH.forEach(([k,ja,en],i)=>{if(Math.abs(x-(110+i*150))<60&&Math.abs(y-by)<50){if(this.shape!==k){while(this.cakeG.children.length)this.cakeG.remove(this.cakeG.children[0]);this.layers=[];}this.shape=k;if(!this.layers.length)this.addLayer();sayPair(ja,en);}});
      if(hitC(x,y,W-90,by+90,40)&&this.shape){this.addLayer();hush();speak(this.layers.length+'だん');}if(hitC(x,y,90,by+90,40)&&this.layers.length){this.ph='crc';sfx('ding');say('クリームの いろを えらんでね');}return;}
    if(this.ph==='crc'){CK_CR.forEach(([col,ja,en],i)=>{if(hitC(x,y,110+i*150,by,46)){this.crc=i;this.addCream();this.ph='cream';this.cov=0;sayPair(ja,en);setTimeout(()=>{if(scene===this&&this.ph==='cream')say('よこに スワイプして ターンテーブルを まわそう！');},900);}});return;}
    if(this.ph==='top'){for(let i=0;i<CK_TP.length;i++)if(Math.abs(x-(62+i*95))<44&&Math.abs(y-(by-12))<44){this.sel=CK_TP[i][0];sfx('tap');sayPair(CK_TP[i][1],CK_TP[i][2]);return;}
      if(hitC(x,y,W-90,by+92,42)){this.serve();return;}if(hitC(x,y,90,by+92,40)){const t=this.tops.pop();if(t){this.cakeG.remove(t);sfx('pop');}return;}
      if(!this.sel){say('したから トッピングを えらんでね');return;}const top=this.cream[this.cream.length-1];const h=pick3(this.S,x,y,[top]);if(!h)return;const lp=this.cakeG.worldToLocal(h.pt.clone());const t=topping3(this.cakeG,this.sel);t.position.set(lp.x,this.topY(),lp.z);t.userData.k=this.sel;t.userData.ph=Math.random()*9;this.tops.push(t);sfx('pop');hush();speak(NUMJ[this.count(this.sel)]||String(this.count(this.sel)));}},
  move(x,y){const s=this.sw;if(!s)return;if(this.ph==='cream'){const d=x-s.lx;s.lx=x;this.rot+=d*.012;this.cov+=Math.abs(d)/900;if(Math.random()<.05)sfx('squish');}},
  up(){this.sw=null;},
  serve(){if(!this.tops.length){say('トッピングを のせてね');return;}this.ph='serve';const ok=this.check();if(ok){this.perfect++;sfx('fanfare');confetti(60);this.hearts=1.5;this.cust.cheer=2.5;say(pick(['ちゅうもん どおり！ おいしそう〜！','わあ！ ぴったり！ ありがとう！']));}else{sfx('ding');this.cust.cheer=1;say('ちょっと ちがうけど… かわいい ケーキ！ ありがとう');}
    setTimeout(()=>{if(scene===this){this.ph='gone';this.cakeG.visible=true;}},2600);},
  hint(){const by=H-150,o=this.order;if(this.ph==='shape'){if(this.shape!==o.sh)return{x:110+CK_SH.findIndex(q=>q[0]===o.sh)*150,y:by};if(this.layers.length<o.ly)return{x:W-90,y:by+90};return{x:90,y:by+90};}if(this.ph==='crc')return{x:110+o.cr*150,y:by};if(this.ph==='cream')return{x:W/2-120,y:by-100,x2:W/2+120,y2:by-100};
    if(this.ph==='top'){const need=o.tp.find(([k,n])=>this.count(k)<n);if(!need)return{x:W-90,y:by+92};if(this.sel!==need[0])return{x:62+CK_TP.findIndex(q=>q[0]===need[0])*95,y:by-12};const p=toScr(this.S,new THREE.Vector3(rand(-.5,.5),2.5+this.topY(),rand(-.5,.5)));return{x:p.x,y:p.y};}return null;},
  hintText(){return{shape:'ちゅうもんの かたちを えらんでね',crc:'クリームの いろを えらんでね',cream:'よこに スワイプして まわそう',top:'トッピングを えらんで ケーキの うえを タッチ'}[this.ph]||'';}});
