// ================= 3D のうじょう =================
const FVEG=[['carrot','にんじん','carrot','#ff8a2a'],['corn','とうもろこし','corn','#ffd23a'],['tomato','トマト','tomato','#ff3d3d'],['pumpkin','かぼちゃ','pumpkin','#ff9a3a']];
function veg3(g,k){const v=new THREE.Group();g.add(v);if(k==='carrot'){const c=mesh3(v,geo3('car3',()=>new THREE.ConeGeometry(.28,1,14)),'#ff8a2a',0,.1,0);c.rotation.x=Math.PI;for(let i=0;i<3;i++){const l=B3(v,.12,.8,.05,'#4cbe6a',(i-1)*.12,.55,0,.03);l.rotation.z=(i-1)*.3;}}
  else if(k==='corn'){S3(v,.3,'#ffd23a',0,.8,0,1,2.2,1);for(let s of[-1,1]){const l=S3(v,.25,'#6cd08a',s*.18,.6,0,.5,2.4,.3);l.rotation.z=s*.2;}C3(v,.05,.05,.5,'#6cd08a',0,0,0,6);}
  else if(k==='tomato'){C3(v,.05,.05,1.1,'#4cae4a',0,0,0,6);for(let i=0;i<3;i++)S3(v,.24,'#ff3d3d',Math.cos(i*2.1)*.25,.55+i*.15,Math.sin(i*2.1)*.25);S3(v,.4,'#5cbe5a',0,1.1,0,1,.6,1);}
  else{S3(v,.55,'#ff9a3a',0,.45,0,1.2,.8,1.2);C3(v,.07,.07,.3,'#6a8a3a',0,.85,0,6);S3(v,.3,'#5cbe5a',.5,.2,.3,1.4,.3,1);}return v;}
function hen3(g){const h=new THREE.Group();g.add(h);S3(h,.45,'#ffffff',0,.5,0,1.1,.9,1.3);S3(h,.28,'#ffffff',0,.95,.4);S3(h,.1,'#ff3d3d',0,1.25,.4,.6,1.2,1.4);mesh3(h,geo3('beak',()=>new THREE.ConeGeometry(.08,.2,8)),'#ffb03a',0,.95,.72).rotation.x=Math.PI/2;S3(h,.05,'#2a2a3a',-.12,1.02,.6);S3(h,.05,'#2a2a3a',.12,1.02,.6);S3(h,.25,'#f0f0f0',0,.6,-.55,.6,1,.8);return h;}
function cow3(g){const c=new THREE.Group();g.add(c);S3(c,1,'#ffffff',0,1.3,0,1.5,.85,.9);for(const [x,z,r] of [[-.5,.3,.35],[.4,-.4,.3],[.8,.5,.25]])S3(c,r,'#2a2a3a',x,1.6,z+(z>0?.45:-.45),1,.8,.4);S3(c,.5,'#ffffff',1.55,1.6,0,1.1,.9,.9);S3(c,.3,'#ffc0d0',1.95,1.45,0,.8,.7,1.1);for(const s of[-1,1]){S3(c,.1,'#2a2a3a',1.75,1.8,s*.25);mesh3(c,geo3('horn',()=>new THREE.ConeGeometry(.06,.3,8)),'#f0e0c0',1.5,2.1,s*.3);}
  for(const [x,z] of [[-.8,.4],[-.8,-.4],[.8,.4],[.8,-.4]])C3(c,.14,.14,.9,'#ffffff',x,0,z,8);S3(c,.22,'#ffc0d0',-.1,.55,0,1,.8,1);return c;}
reg3('farm',{bg:'#bfe8ff',song:'town',
  build(){const S=this.S=stage3({sr:16,fov:50});const g=new THREE.Group();S.s.add(g);this.g=g;const gr=new THREE.Mesh(new THREE.PlaneGeometry(120,120),m3('#9ee07a'));gr.rotation.x=-Math.PI/2;gr.receiveShadow=true;g.add(gr);
    const barn=new THREE.Group();barn.position.set(-7,0,-9);g.add(barn);B3(barn,6,4,5,'#e84a4a',0,0,0,.2);prism3(barn,6.6,2.6,5.6,'#ffffff',0,4,0);B3(barn,2,2.8,.2,'#ffffff',0,0,2.52,.08);C3(g,1.4,1.4,6,'#c8c8d8',-2.8,0,-9,16);S3(g,1.4,'#e84a4a',-2.8,6,-9,1,.6,1);
    for(let i=0;i<12;i++){B3(g,.2,1,.2,'#ffffff',-12+i*2,0,-3.5,.04);}B3(g,24,.15,.1,'#ffffff',-1,.7,-3.5,.03);SEEDR=8;for(let i=0;i<16;i++)tree3(g,(srand()<.5?-1:1)*(14+srand()*6),-20+srand()*28,1.4+srand()*.6);
    this.plots=[];for(let i=0;i<6;i++){const x=-3.2+(i%3)*3.2,z=2+Math.floor(i/3)*3.2;const pg=new THREE.Group();pg.position.set(x,0,z);g.add(tagPk(pg,{plot:i}));const soil=B3(pg,2.6,.25,2.6,'#8ad06a',0,0,0,.1);this.plots.push({g:pg,soil,x,z,st:'grass',veg:FVEG[i%4],grow:0,w:0,v:null});}
    const tr=this.tractor=new THREE.Group();g.add(tr);tr.position.set(-7,0,3.6);B3(tr,1.6,1,2.4,'#ff5f5f',0,.6,0,.2);B3(tr,1.3,1.1,1.1,'#ff5f5f',0,1.5,-.4,.15);B3(tr,1.2,.8,1,m3('#bfe8ff',{roughness:.2}),0,1.7,-.4,.05);C3(tr,.1,.1,.8,'#3a3a4a',0,1.5,.8,8);
    for(const s of[-1,1]){const bw=C3(tr,.75,.75,.4,'#3a3050',s*.95,0,-.5,16);bw.rotation.z=Math.PI/2;bw.position.y=.75;const fw=C3(tr,.45,.45,.3,'#3a3050',s*.85,0,.8,14);fw.rotation.z=Math.PI/2;fw.position.y=.45;}
    this.cloud=new THREE.Group();this.cloud.visible=false;g.add(this.cloud);for(let k=0;k<4;k++)S3(this.cloud,.9+k%2*.3,'#ffffff',k*.8-1.2,Math.sin(k)*.3,0);this.cloud.position.set(0,5,2);this.rain=[];for(let i=0;i<30;i++){const d=C3(g,.03,.03,.4,m3('#6ac8ff',{transparent:true,opacity:.8}),0,-5,0,4);d.castShadow=false;this.rain.push(d);}
    this.hens=[];for(let i=0;i<3;i++){const h=hen3(g);h.position.set(4+i*1.8,0,-7.5+(i%2)*1.2);tagPk(h,{hen:i});this.hens.push(h);}this.cow=cow3(g);this.cow.position.set(5,0,-11.5);tagPk(this.cow,{cow:1});this.eggs=[];this.milk=0;
    this.basket=new THREE.Group();this.basket.position.set(6,0,4.5);g.add(this.basket);C3(this.basket,.9,.7,.8,'#d8904a',0,0,0,16);
    this.fu=charAdd(S,charSpr('fu',2.4,{outfit:outfit({acc:'cap'})}));this.fu.x=6.8;this.fu.z=6.5;this.rk=charAdd(S,charSpr('rk',1.7));this.rk.x=8.4;this.rk.z=6.8;
    this.ph='plow';this.got=[];this.fin=0;this.pt=0;S.cam.position.set(0,13,17);this.ctv=new THREE.Vector3(0,0,3);say('のうじょう！ トラクターを ゆびで うごかして、 はたけを たがやそう');},
  update(dt){const S=this.S,tr=this.tractor;this.pt+=dt;
    if(this.ph==='plow'&&this.tt){const dx=this.tt.x-tr.position.x,dz=this.tt.z-tr.position.z,d=Math.hypot(dx,dz);if(d>.1){const st=Math.min(d,dt*6);tr.position.x+=dx/d*st;tr.position.z+=dz/d*st;tr.rotation.y=Math.atan2(dx,dz)+Math.PI;if(Math.random()<dt*4)sfx('squish');}
      for(const p of this.plots){if(p.st==='grass'&&Math.abs(tr.position.x-p.x)<1.5&&Math.abs(tr.position.z-p.z)<1.5){p.st='soil';p.soil.material=m3('#8a5a3a');sfx('pop');const q=toScr(S,new THREE.Vector3(p.x,.5,p.z));burst(q.x,q.y,6,'dot');}}
      if(this.plots.every(p=>p.st!=='grass')){this.ph='seed';this.tt=null;this.parkT=1;sfx('fanfare');say('ふかふかの はたけ！ はたけを タッチして たねを まこう');}}
    if(this.parkT){tr.position.x+=(-8.5-tr.position.x)*Math.min(1,dt*2);tr.position.z+=(1-tr.position.z)*Math.min(1,dt*2);tr.rotation.y=Math.PI/2;}
    if(this.ph==='water'){const c=this.cloud;if(this.ct2){c.position.x+=(this.ct2.x-c.position.x)*Math.min(1,dt*5);c.position.z+=(this.ct2.z-c.position.z)*Math.min(1,dt*5);}
      this.rain.forEach((d,i)=>{d.position.y-=dt*9;if(d.position.y<0){d.position.set(c.position.x+rand(-1.3,1.3),c.position.y-.3,c.position.z+rand(-.8,.8));}});
      for(const p of this.plots){if(p.grow>=3)continue;if(Math.abs(c.position.x-p.x)<1.3&&Math.abs(c.position.z-p.z)<1.3){p.w+=dt;if(p.w>1){p.w=0;p.grow++;this.setGrow(p);sfx('spark');}}}
      if(this.plots.every(p=>p.grow>=3)){this.ph='harvest';this.cloud.visible=false;this.rain.forEach(d=>d.position.y=-5);sfx('fanfare');say('やさいが できた！ タッチして しゅうかく しよう');}}
    for(const p of this.plots){if(p.fly){p.fly.t+=dt*1.5;const k=Math.min(1,p.fly.t);p.v.position.set(lerp(p.x,6,k),.3+Math.sin(k*Math.PI)*4+(1-k)*.2,lerp(p.z,4.5,k));if(k>=1){this.g.remove(p.v);p.fly=null;const n=this.got.length;const m=veg3(this.basket,p.veg[0]);m.scale.setScalar(.45);m.position.set((n%3-1)*.35,.6+Math.floor(n/3)*.3,0);}}}
    if(this.ph==='animals'){for(const e of this.eggs){if(e.fall){e.vy-=dt*10;e.m.position.y=Math.max(.15,e.m.position.y+e.vy*dt);}}this.hens.forEach((h,i)=>{h.rotation.y=Math.sin(T*.8+i)*.5;h.position.y=Math.abs(Math.sin(T*3+i))*.05;});
      if(this.eggs.filter(e=>e.got).length>=3&&this.milk>=1&&!this.adone){this.adone=1;sfx('fanfare');confetti(80);say('たまごも ぎゅうにゅうも いっぱい！ のうじょう だいせいこう！');this.fin=.01;this.fu.cheer=3;}}
    let cp,ct;if(this.ph==='animals'){cp=new THREE.Vector3(4,8,3);ct=new THREE.Vector3(5,1,-9);}else{cp=new THREE.Vector3(0,13,17);ct=new THREE.Vector3(0,0,3);}S.cam.position.lerp(cp,Math.min(1,dt*2.5));this.ctv=(this.ctv||ct.clone()).lerp(ct,Math.min(1,dt*2.5));S.cam.lookAt(this.ctv);lightAt(S,this.ctv.x,this.ctv.z);charUpd(this.fu,dt);charUpd(this.rk,dt);
    if(this.fin>0){this.fin+=dt;if(this.fin>2.2&&this.fin<9){this.fin=9;celebrate('farm',true,3);}}},
  setGrow(p){if(p.v)p.g.remove(p.v);if(p.grow===1){p.v=new THREE.Group();p.g.add(p.v);C3(p.v,.04,.04,.4,'#4cae4a',0,.25,0,6);S3(p.v,.15,'#6cd08a',.1,.65,0,1,.4,.6);}else if(p.grow===2){p.v=new THREE.Group();p.g.add(p.v);C3(p.v,.05,.05,.8,'#4cae4a',0,.25,0,6);for(const s of[-1,1])S3(p.v,.25,'#6cd08a',s*.2,.8,0,1,.4,.6);}else{p.v=veg3(p.g,p.veg[0]);p.v.position.y=.25;p.v.scale.setScalar(p.veg[0]==='pumpkin'?1:1.1);}},
  draw(c){sky3(c,'#8fd8ff','#e6f8ff',true);render3(c,this.S);c.textAlign='center';c.textBaseline='middle';const lab={plow:'はたけを たがやそう',seed:'たねを まこう',water:'あめくもで おみずを あげよう',harvest:'しゅうかく しよう',animals:'どうぶつの おせわ'}[this.ph];
    c.fillStyle='rgba(255,255,255,.93)';rr(c,W/2-170,112,340,50,25);c.fill();c.strokeStyle='#8ad08a';c.lineWidth=4;c.stroke();c.fillStyle='#3a8a4a';c.font=`800 22px ${FONT}`;c.fillText(lab||'',W/2,138);stepDots(c,5,['plow','seed','water','harvest','animals'].indexOf(this.ph),184);
    if(this.ph==='water')for(const p of this.plots){const q=toScr(this.S,new THREE.Vector3(p.x,1.6,p.z));for(let i=0;i<3;i++){c.fillStyle=i<p.grow?'#5aa8ff':'rgba(255,255,255,.7)';circ(c,q.x-16+i*16,q.y,6);}}
    if(this.ph==='animals'){c.fillStyle='rgba(255,255,255,.92)';rr(c,W/2-150,H-110,300,60,30);c.fill();c.fillStyle='#6a5a3a';c.font=`800 22px ${FONT}`;c.fillText(`🥚 ${this.eggs.filter(e=>e.got).length}/3   🥛 ${Math.min(1,this.milk)>=1?'OK':Math.round(this.milk*100)+'%'}`,W/2,H-80);}},
  down(x,y){const S=this.S;if(this.ph==='plow'){const h=hitPlane(S,x,y,0);if(h)this.tt={x:h.x,z:h.z};return;}
    if(this.ph==='seed'){const h=pick3(S,x,y,this.plots.map(p=>p.g));if(!h)return;const p=this.plots[h.o.userData.pk.plot];if(p.grow>0)return;p.grow=.5;p.v=new THREE.Group();p.g.add(p.v);for(let i=0;i<3;i++)S3(p.v,.07,'#5a3a2a',(i-1)*.25,.28,0);sfx('pop');sayPair(p.veg[1]+'の たね',p.veg[2]);
      if(this.plots.every(q=>q.grow>0)){this.ph='water';this.plots.forEach(q=>q.grow=0);this.cloud.visible=true;setTimeout(()=>{if(scene===this)say('あめくもを ゆびで うごかして はたけに あめを ふらせよう');},900);}return;}
    if(this.ph==='water'){const h=hitPlane(S,x,y,0);if(h)this.ct2={x:h.x,z:h.z};return;}
    if(this.ph==='harvest'){const h=pick3(S,x,y,this.plots.map(p=>p.g));if(!h)return;const p=this.plots[h.o.userData.pk.plot];if(p.done)return;p.done=1;this.got.push(p.veg[0]);const wp=new THREE.Vector3();p.v.getWorldPosition(wp);p.g.remove(p.v);this.g.add(p.v);p.v.position.copy(wp);p.fly={t:0};sfx('pop');sayPair(p.veg[1],p.veg[2]);
      if(this.plots.every(q=>q.done)){setTimeout(()=>{if(scene===this){this.ph='animals';say('どうぶつの おせわ！ にわとりを タッチして たまご、 うしを タッチして ぎゅうにゅう！');}},1800);}return;}
    if(this.ph==='animals'){const eh=pick3(S,x,y,this.eggs.filter(e=>!e.got).map(e=>e.m));if(eh){const e=this.eggs.find(q=>q.m===eh.o);e.got=true;this.g.remove(e.m);sfx('coin');hush();speak(`たまご ${NUMJ[this.eggs.filter(q=>q.got).length]}こ`);return;}
      const h=pick3(S,x,y,this.hens.concat([this.cow]));if(!h)return;const d=h.o.userData.pk;if(d.hen!=null&&this.eggs.length<5){const hn=this.hens[d.hen];const m=S3(this.g,.2,'#fff6e8',hn.position.x+rand(-.3,.3),.8,hn.position.z+.8,1,1.25,1);tagPk(m,{egg:1});this.eggs.push({m,got:false,fall:1,vy:0});sfx('pop');hush();speak('コケコッコー！');}
      else if(d.cow){this.milk=Math.min(1,this.milk+.34);sfx('pour');hush();speak(this.milk>=1?'ぎゅうにゅう いっぱい！':'モーモー！');}}},
  move(x,y){if(this.ph==='plow'){const h=hitPlane(this.S,x,y,0);if(h)this.tt={x:h.x,z:h.z};}if(this.ph==='water'){const h=hitPlane(this.S,x,y,0);if(h)this.ct2={x:h.x,z:h.z};}},
  up(){},
  hint(){const S=this.S;const sc=v=>{const q=toScr(S,v);return{x:q.x,y:q.y};};if(this.ph==='plow'){const p=this.plots.find(p=>p.st==='grass');if(!p)return null;const a=sc(this.tractor.position),b=sc(new THREE.Vector3(p.x,0,p.z));return{x:a.x,y:a.y,x2:b.x,y2:b.y};}
    if(this.ph==='seed'){const p=this.plots.find(p=>!p.grow);return p?sc(new THREE.Vector3(p.x,.3,p.z)):null;}if(this.ph==='water'){const p=this.plots.find(p=>p.grow<3);if(!p)return null;const a=sc(this.cloud.position),b=sc(new THREE.Vector3(p.x,0,p.z));return{x:a.x,y:a.y,x2:b.x,y2:b.y};}
    if(this.ph==='harvest'){const p=this.plots.find(p=>!p.done);return p?sc(new THREE.Vector3(p.x,.8,p.z)):null;}if(this.ph==='animals'){const e=this.eggs.find(e=>!e.got);if(e)return sc(e.m.position);if(this.eggs.length<3)return sc(this.hens[0].position.clone().add(new THREE.Vector3(0,.6,0)));return sc(this.cow.position.clone().add(new THREE.Vector3(0,1.3,0)));}return null;},
  hintText(){return{plow:'トラクターを ゆびで はたけの うえに はしらせよう',seed:'はたけを タッチ',water:'くもを はたけの うえに うごかそう',harvest:'やさいを タッチ',animals:'にわとりと うしを タッチ'}[this.ph]||'';}});
