// ================================================================ ingredients / recipes
const ING = {
  tomato: { n: 'トマト', e: '🍅', chop: 1 },
  lettuce: { n: 'レタス', e: '🥬', chop: 1 },
  onion: { n: 'タマネギ', e: '🧅', chop: 1 },
  mushroom: { n: 'キノコ', e: '🍄', chop: 1 },
  rice: { n: 'お米', e: '🌾' },
  nori: { n: '海苔', e: 'nori' },
  meat: { n: '肉', e: '🥩', chop: 1 },
  bun: { n: 'バンズ', e: 'bun' },
  fish: { n: '魚', e: '🐟', chop: 1 },
  carrot: { n: 'ニンジン', e: '🥕', chop: 1 },
  potato: { n: 'ジャガイモ', e: '🥔', chop: 1 },
};
const CRATE_CH = { t: 'tomato', l: 'lettuce', o: 'onion', m: 'mushroom', r: 'rice', n: 'nori', k: 'meat', b: 'bun', f: 'fish', c: 'carrot', j: 'potato' };
// component keys (what sits on a plate) -> icon + how it's made
const COMP = {
  lettuce_c: { ic: '🥬', how: ['🥬', 'knife'] },
  tomato_c: { ic: '🍅', how: ['🍅', 'knife'] },
  fish_c: { ic: '🐟', how: ['🐟', 'knife'] },
  nori: { ic: 'nori', how: ['nori'] },
  bun: { ic: 'bun', how: ['bun'] },
  soup_t: { ic: 'soupT', how: ['🍅', 'knife', '×3', 'pot'] },
  soup_o: { ic: 'soupO', how: ['🧅', 'knife', '×3', 'pot'] },
  soup_m: { ic: 'soupM', how: ['🍄', 'knife', '×3', 'pot'] },
  gohan: { ic: 'gohan', how: ['🌾', 'pot'] },
  patty: { ic: 'patty', how: ['🥩', 'knife', 'pan'] },
  curry: { ic: 'curry', how: ['🥕', '🥔', '🧅', 'knife', 'pot'] },
  ffish: { ic: 'ffish', how: ['🐟', 'knife', 'fry'] },
  chips: { ic: '🍟', how: ['🥔', 'knife', 'fry'] },
};
const POT_RECIPES = [
  { items: ['rice'], out: 'gohan', t: 12 },
  { items: ['tomato_c', 'tomato_c', 'tomato_c'], out: 'soup_t', t: 18 },
  { items: ['onion_c', 'onion_c', 'onion_c'], out: 'soup_o', t: 18 },
  { items: ['mushroom_c', 'mushroom_c', 'mushroom_c'], out: 'soup_m', t: 18 },
  { items: ['carrot_c', 'onion_c', 'potato_c'], out: 'curry', t: 20 },
];
const PAN_RECIPES = [{ items: ['meat_c'], out: 'patty', t: 9 }];
const FRY_RECIPES = [{ items: ['fish_c'], out: 'ffish', t: 9 }, { items: ['potato_c'], out: 'chips', t: 9 }];
const RECS_OF = { pot: POT_RECIPES, pan: PAN_RECIPES, fry: FRY_RECIPES };
const ALL_COOK = POT_RECIPES.concat(PAN_RECIPES, FRY_RECIPES);
const sortK = a => a.slice().sort();
const sameSet = (a, b) => a.length === b.length && sortK(a).join() === sortK(b).join();
function isSub(a, b) { const c = {}; for (const k of b) c[k] = (c[k] || 0) + 1; for (const k of a) { if (!c[k]) return false; c[k]--; } return true; }
function potOut(items) { for (const r of ALL_COOK) if (sameSet(items, r.items)) return r.out; return null; }

const RECIPES = {
  salad_l: { n: 'レタスサラダ', ic: 'saladL', items: ['lettuce_c'], pts: 20, time: 60 },
  salad: { n: 'ミックスサラダ', ic: '🥗', items: ['lettuce_c', 'tomato_c'], pts: 30, time: 70 },
  soup_t: { n: 'トマトスープ', ic: 'soupT', items: ['soup_t'], pts: 30, time: 90 },
  soup_o: { n: 'オニオンスープ', ic: 'soupO', items: ['soup_o'], pts: 30, time: 90 },
  soup_m: { n: 'キノコスープ', ic: 'soupM', items: ['soup_m'], pts: 30, time: 90 },
  onigiri: { n: 'おにぎり', ic: '🍙', items: ['gohan', 'nori'], pts: 30, time: 85 },
  sushi: { n: '巻き寿司', ic: '🍣', items: ['gohan', 'nori', 'fish_c'], pts: 40, time: 95 },
  burger: { n: 'ハンバーガー', ic: '🍔', items: ['bun', 'patty'], pts: 30, time: 80 },
  burger_l: { n: 'レタスバーガー', ic: 'burgerL', items: ['bun', 'patty', 'lettuce_c'], pts: 40, time: 90 },
  burger_lt: { n: 'デラックスバーガー', ic: 'burgerLT', items: ['bun', 'patty', 'lettuce_c', 'tomato_c'], pts: 50, time: 100 },
  fishchips: { n: 'フィッシュ＆チップス', ic: 'fishchips', items: ['ffish', 'chips'], pts: 40, time: 90 },
  curry: { n: 'カレーライス', ic: '🍛', items: ['gohan', 'curry'], pts: 50, time: 110 },
};

// ================================================================ themes
const THEMES = {
  school: { bg: 0x9fd8ff, f1: '#f4e7c8', f2: '#e6d3a8', body: 0x6fb6d8, top: 'wood', slab: 0xb8744a, ground: 0x7fc85a, music: 'school' },
  night: { bg: 0x241a3c, f1: '#d8c8e8', f2: '#c4b0da', body: 0x5a5a9a, top: 'wood', slab: 0x4a3a6a, ground: 0x2a3a2a, music: 'boss' },
  park: { bg: 0x9fe0ff, f1: '#cfe6a8', f2: '#bcd890', body: 0xc8844a, top: 'wood', slab: 0x7a5232, ground: 0x6cc24a, music: 'park' },
  truck: { bg: 0xa8d8ff, f1: '#c8ccd2', f2: '#b4b8c0', body: 0xe8a028, top: 'steel', slab: 0x3a3e46, ground: 0x6a6e76, music: 'school' },
  street: { bg: 0xffd8a8, f1: '#e8d8c0', f2: '#d8c4a6', body: 0xd8483a, top: 'steel', slab: 0x5a4a40, ground: 0x7a7a80, music: 'park' },
  ship: { bg: 0x8fd4ff, f1: '#c89660', f2: '#b88450', body: 0x2f6aa8, top: 'wood', slab: 0x7a4426, ground: 0x2a8ad8, music: 'ship' },
  sushi: { bg: 0x2a1c3a, f1: '#e2d2a0', f2: '#d2c088', body: 0x7a3e22, top: 'wood', slab: 0x4a2a1a, ground: 0x3a2a4a, music: 'sushi' },
  beach: { bg: 0x8ad8ff, f1: '#f2deb0', f2: '#e6cf98', body: 0x2ab0a8, top: 'wood', slab: 0xc8a060, ground: 0xf0d89a, music: 'ship' },
  raft: { bg: 0x8ad8ff, f1: '#b88a58', f2: '#a87a48', body: 0x8a5a32, top: 'wood', slab: 0x6a4224, ground: 0x2a8ad8, music: 'camp' },
  snow: { bg: 0xcfe8ff, f1: '#e4f4ff', f2: '#cce6f8', body: 0x8a5a3a, top: 'wood', slab: 0x7aa0c0, ground: 0xf4fbff, music: 'snow' },
  camp: { bg: 0xffd6a0, f1: '#c4d890', f2: '#b2ca7a', body: 0xa0682e, top: 'wood', slab: 0x6a4a2a, ground: 0x7ab84a, music: 'camp' },
  lake: { bg: 0xbfe0ff, f1: '#d4ecfa', f2: '#bcdcf2', body: 0x5a7aa8, top: 'steel', slab: 0x6a8ab0, ground: 0xe8f4ff, music: 'snow' },
  wizard: { bg: 0x1e1438, f1: '#8a7ab8', f2: '#7a6aa8', body: 0x4a2e7a, top: 'stone', slab: 0x2a1e4a, ground: 0x1a1430, music: 'sushi' },
  volcano: { bg: 0x3a1a1a, f1: '#6e5e5a', f2: '#5e4e4a', body: 0x8a3a2a, top: 'stone', slab: 0x2a1a1a, ground: 0x2a1212, music: 'volcano' },
  quake: { bg: 0x4a2a2a, f1: '#a89a8a', f2: '#988a7a', body: 0x6a5a4a, top: 'stone', slab: 0x3a2a22, ground: 0x2a1a14, music: 'volcano' },
  castle: { bg: 0x241838, f1: '#b8a8c8', f2: '#a898b8', body: 0x5a3a8a, top: 'stone', slab: 0x2a2040, ground: 0x2a2040, music: 'boss' },
  boss: { bg: 0x2a1840, f1: '#dcc4f4', f2: '#caaeea', body: 0x6a4ab0, top: 'steel', slab: 0x3a2a6a, ground: 0x3a2a5a, music: 'boss' },
};

// ================================================================ levels
// . floor  # counter  C board  S stove+pot  P stove+pan  F fryer  D plates  W window  K sink  R dirty return
// T trash  E counter+extinguisher  % moving counter  ~ water  L lava  (space) gap  = / - opening floor (A / B phase)
// @ portal  >< ^v conveyor   crates: t l o m r n k b f c j
const LEVELS = [
  {
    id: '0', name: 'ハラペコン襲来', world: 0, theme: 'night', recipes: ['salad_l', 'soup_o'], time: 100, stars: [0, 0, 0], plates: 4, prologue: 1, boss: 1, need: 100,
    map: ['##C#S#W#S#C##',
      '#...........#',
      'l..#T###D#..o',
      '#...........#',
      '#...........#',
      '####C###C####'],
    start: [[4, 3], [8, 3]],
  },
  {
    id: '1-1', name: 'ようちえんの給食室', world: 1, theme: 'school', recipes: ['salad_l', 'salad'], time: 150, stars: [60, 140, 200], plates: 4, tut: 1,
    map: ['##C##W##C##',
      '#.........#',
      'l..#D#T#..t',
      '#.........#',
      '#.........#',
      '#####C#####'],
    start: [[3, 3], [7, 3]],
    talk: 'まずは基本じゃ！ 野菜を切って皿に盛り、受け取り口へ。注文は左から順番に出すとチップが増えるぞ！',
  },
  {
    id: '1-2', name: '公園のピクニック', world: 1, theme: 'park', recipes: ['soup_t', 'soup_o'], time: 180, stars: [80, 180, 260], plates: 4,
    map: ['##S###W###S#',
      '#..........#',
      't...#CTC#..o',
      '#..........#',
      '#..........#',
      '###D####C###'],
    start: [[3, 3], [8, 3]],
    talk: '鍋に切った材料を3つ入れるとスープになる。完成したら放っておくと焦げて…火事になるぞ！',
  },
  {
    id: '1-3', name: '引っ越しトラック', world: 1, theme: 'truck', recipes: ['soup_o', 'salad'], time: 180, stars: [80, 180, 260], plates: 4, gaps: { open: 7, close: 13 },
    map: ['#o#C#C #S#SW#',
      '#.....=.....#',
      'l..C..=..D..#',
      '#.....=.....#',
      't.....=.....#',
      '##C#T# #T####'],
    start: [[3, 3], [9, 3]],
    talk: '2台のトラックが離れたりくっついたり！ 落ちたら復活まで5秒かかる。離れている間は材料を投げて渡すのじゃ！',
  },
  {
    id: '1-4', name: '交差点の屋台', world: 1, theme: 'street', recipes: ['burger', 'burger_l'], time: 180, stars: [100, 200, 300], plates: 4, peds: { rows: [3], every: 3.5 },
    map: ['##P#P##W##D##',
      '#...........#',
      '#..#T###C#..#',
      '.............',
      '#...........#',
      'k...C...C...b',
      '##l##T###E###'],
    start: [[3, 1], [6, 4]],
    talk: '屋台の真ん中を通行人が横切る！ ぶつかると押し流されるから気をつけるのじゃ。',
  },
  {
    id: '2-1', name: 'ゆらゆら海賊船', world: 2, theme: 'ship', recipes: ['onigiri', 'sushi'], time: 180, stars: [80, 180, 280], plates: 3, dirty: 1, tilt: 1,
    map: ['#S#S##W#R#K#',
      '#..........#',
      'r...#CnC#..f',
      '#..........#',
      '#..........#',
      '##D#C##T##E#'],
    start: [[3, 3], [8, 3]],
    talk: '船が揺れて体が流される！ 汚れた皿は返却口から取って、シンクで洗うのじゃ。',
  },
  {
    id: '2-2', name: 'ねこ寿司', world: 2, theme: 'sushi', recipes: ['sushi', 'onigiri'], time: 200, stars: [100, 220, 320], plates: 3, dirty: 1,
    map: ['#f#C##S#S#Cn#',
      '#...........r',
      '#...........#',
      '>>>>>>>>>>>>#',
      '#...........#',
      '#...........#',
      '##D#K#W#R#T##'],
    start: [[3, 1], [6, 4]],
    talk: '厨房はベルトコンベアで真っ二つ。シェフを切り替えて、上下で連携するのじゃ！',
  },
  {
    id: '2-3', name: '浜辺の海の家', world: 2, theme: 'beach', recipes: ['fishchips', 'salad_l'], time: 200, stars: [100, 220, 320], plates: 4,
    map: ['#f#C#~~~#F#F#',
      '#....~~~....W',
      'j..C.~~~.D..#',
      '#....~~~....#',
      'l..C.....T...',
      '##C#T#~#####E'],
    start: [[2, 3], [10, 3]],
    talk: 'フライヤーで魚とポテトを揚げるのじゃ。海に落ちたら一回休み！',
  },
  {
    id: '2-4', name: 'いかだキッチン', world: 2, theme: 'raft', recipes: ['fishchips', 'burger'], time: 210, stars: [100, 220, 320], plates: 4, gaps: { open: 6, close: 9 },
    map: ['#f#C#~#P#~#F#F#',
      '#....~...~....W',
      'j....=...-....#',
      'k..C.~.D.~.C..#',
      '#....~...~....E',
      '##C#T~#b#~#####'],
    start: [[2, 3], [11, 3]],
    talk: '3つのいかだを渡し板がつないでいる。板は交互に外れるぞ！',
  },
  {
    id: '3-1', name: 'つるつる雪山ロッジ', world: 3, theme: 'snow', recipes: ['burger', 'burger_l', 'burger_lt'], time: 210, stars: [100, 240, 340], plates: 3, dirty: 1, ice: 1,
    map: ['#k#C#P#P#W##',
      '#..........#',
      'b...#C#D#..l',
      '#..........#',
      't..........#',
      '###T##K#R#E#'],
    start: [[3, 3], [8, 3]],
    talk: '床が凍っていてよく滑る！ 止まりたい場所の少し手前で手を離すのがコツじゃ。',
  },
  {
    id: '3-2', name: '川辺のキャンプ', world: 3, theme: 'camp', recipes: ['burger_l', 'salad'], time: 200, stars: [100, 220, 320], plates: 4,
    map: ['#k#C#l~#P#P##',
      '#.....~.....W',
      't..C..~..#..#',
      '#.....~..D..#',
      'b.....~.....#',
      '##C#T#~#T##E#'],
    start: [[2, 3], [9, 1]],
    talk: '川の向こうへは材料を投げるしかない。受け取る側は手を空けておくのじゃ！',
  },
  {
    id: '3-3', name: '氷の湖', world: 3, theme: 'lake', recipes: ['soup_m', 'soup_o'], time: 200, stars: [100, 220, 320], plates: 3, dirty: 1, ice: 1, gaps: { open: 6, close: 12 },
    map: ['#m#C#S#S#S#W#',
      '#...........#',
      'o..=..#..=..#',
      '#..C..D..C..#',
      '#...=...=...R',
      '###T###K#E###'],
    start: [[2, 1], [10, 1]],
    talk: '氷にヒビが入って穴が開く！ 滑って落ちないように気をつけるのじゃ。',
  },
  {
    id: '3-4', name: '魔法使いの台所', world: 3, theme: 'wizard', recipes: ['soup_t', 'soup_o', 'soup_m'], time: 210, stars: [100, 240, 340], plates: 3, dirty: 1,
    map: ['#t#C#o##S#S#W##',
      '#.....@#......#',
      'm..C...#..D...#',
      '#......#.....@#',
      '#.C...T#.C....#',
      '###C####T#K#RE#'],
    start: [[3, 3], [10, 3]],
    talk: '魔法の床に乗ると反対側へワープする！ 真ん中の壁のカウンターでも受け渡しできるぞ。',
  },
  {
    id: '4-1', name: 'どっかん火山カレー', world: 4, theme: 'volcano', recipes: ['curry', 'onigiri'], time: 220, stars: [120, 260, 360], plates: 3, dirty: 1, erupt: 1,
    map: ['#c#j#o#S#S#S#',
      '#...........W',
      'r..#C#C#C#..#',
      '#...........#',
      'n...........E',
      '##D#T##K#R###'],
    start: [[3, 3], [9, 3]],
    talk: '火山が噴火すると火の玉が降ってくる！ 消火器はすぐ手に取れる場所に置いておくのじゃ。',
  },
  {
    id: '4-2', name: '溶岩の吊り橋', world: 4, theme: 'volcano', recipes: ['curry', 'burger'], time: 220, stars: [120, 260, 360], plates: 4, gaps: { open: 6, close: 10 }, erupt: 1,
    map: ['#c#j#o#L#S#P#W#',
      '#.....#L#...b.#',
      'r..C...=...D..#',
      '#.....#L#.....#',
      'k..C...-...C...',
      '##C#T#LLL#S#T#E'],
    start: [[3, 3], [11, 3]],
    talk: '溶岩の上の橋は交互に崩れる。材料を投げ渡して、橋を待つ時間を減らすのじゃ！',
  },
  {
    id: '4-3', name: '大地震の厨房', world: 4, theme: 'quake', recipes: ['soup_o', 'burger_l', 'salad'], time: 220, stars: [120, 260, 380], plates: 3, dirty: 1, mover: { d: [2, 0], period: 14 },
    map: ['#o#C#S#S#W#P#k#',
      '#.............#',
      'l..%%%...%%%..b',
      '#.............#',
      't..C..D.T..C..#',
      '#.............#',
      '###C##K#R##E###'],
    start: [[3, 3], [11, 3]],
    talk: '地震でカウンターが動く！ 通れる道が変わるから、揺れたらすぐに確認じゃ。',
  },
  {
    id: '4-4', name: 'ハラペコン城の厨房', world: 4, theme: 'castle', recipes: ['soup_t', 'onigiri', 'burger_l'], time: 230, stars: [140, 280, 400], plates: 3, dirty: 1,
    map: ['#t#C#S#S#W#P#k#',
      '#@............#',
      'l..>>>>v...C..b',
      '#..^###v......#',
      'r..^<<<<..C...n',
      '#...........@.#',
      '###T#C#K#R#E#D#'],
    start: [[2, 3], [10, 3]],
    talk: 'いよいよハラペコンの城じゃ。コンベアとワープを使いこなせ！',
  },
  {
    id: 'FINAL', name: '最終決戦 ハラペコン', world: 5, theme: 'boss', recipes: ['soup_o', 'burger_lt', 'sushi'], time: 240, stars: [200, 350, 500], plates: 4, boss: 1, need: 16, mover: { d: [0, 2], period: 15 },
    map: ['#o#S#S#W#P#k#',
      '#.....%.....#',
      'l..C..%..C..b',
      'f.....%.....t',
      'r..D.....D..n',
      '#...........E',
      '###T#C#C#T###'],
    start: [[3, 3], [9, 3]],
    talk: '7日間の修行の成果を見せるときじゃ！ ハラペコンの腹を満たせ！',
  },
];
